### ISSUE TITLE
Filter doesn't work

### ISSUE THREAD

**Issue by djcaesar9114** [apidoc/apidoc#1000]
# Describe the bug
I installed the basic example and generated the documentation correctly. I can see everything, navigate through the different APIs, but typing anything in the "filter" input doesn't change anything. It doesn't filter the APIs as I expect it to.

# Steps to reproduce
Follow the steps in the README:
```
$ git clone https://github.com/apidoc/apidoc && cd apidoc
$ npm install --prod
$ ./bin/apidoc -i example -o /tmp/doc
```

I open the `index.html` file and type somthing in the "filter" input.

# Information

- Version of apidoc: 0.50.0
- Operating system (e.g. GNU+Linux/MacOS/Windows): Ubuntu 20.04
- Browser (e.g. firefox, chrome): Firefox 92.0 (64 bits)

**Comment by NicolasCARPi** [comment]
Hello,

Yes I can confirm this bug, thanks for trying out the unreleased 0.50.0 :)

When I read the code I don't even understand how it was working in the first place :p So I have scraped old code (also this removes a dependency) and wrote a good old jquery show/hide function instead.

Can you try the latest from `dev` branch please? And tell me if it works as expected.

PS: issue number 1000 :tada:

**Comment by djcaesar9114** [comment]
Hello,
I confirm it works fine on the latest dev branch!
I'm happy the 1000th issue is a quick fixed one :)
Thanks a lot :)

**Comment by NicolasCARPi** [comment]
Ok cool, let me know if you find other issues! :)
