### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by vishalg-flexiloans** [apidoc/apidoc#1045]
# Describe the bug

Unable to generate the API documents.

# Steps to reproduce

```sh
apidoc -i controllers/  -o public/
```
# Information
![Screenshot 2021-10-18 at 10 29 32 AM](https://user-images.githubusercontent.com/83216045/137671738-1b45fd29-02dd-4688-b790-31cbbe29e610.png)

- Version of apidoc: apidoc@0.50.0
- Operating system (e.g. GNU+Linux/MacOS/Windows): MacOS Big Sur 11.3
- Browser (e.g. firefox, chrome): Chrome
- NodeJS Version: v12.22.1
- NPM Version: 6.14.12

**Comment by NicolasCARPi** [comment]
Exactly, use a more recent Node version. Added it to the BREAKING changes part of the changelog.
