### ISSUE TITLE
api_data.json and api_project.json no longer generated

### ISSUE THREAD

**Issue by ManciuStefan** [apidoc/apidoc#1046]
# Describe the bug

The last version of apidoc (0.50.0) seems to not generate the JSON files anymore, which breaks the apidoc-markdown plugin (for example). I know this is more an issue for that project, but I don't see how they could fix it without those files. I tried searching through the commits to see where it was removed and [this](https://github.com/apidoc/apidoc/commit/aa05d6aa7416207572c170e29a6e3117dbeab0e6#diff-0d4a8db044ab1e69251470c5867c96087ba2629d39de216ab9d2a59c74afbff5) is the commit where it seems to have been removed. Judging by the commit description, it doesn't seem to be intentional. I didn't spend too much time on this, so I might be wrong. The bottom line is that those files were really useful and it would be a shame to remove them.
# Steps to reproduce

apidoc -i src -o ./apidoc

# Information

- Version of apidoc: v0.50.0
- Operating system (e.g. GNU+Linux/MacOS/Windows): Manjaro
- Browser (e.g. firefox, chrome): Chrome

**Comment by NicolasCARPi** [comment]
Closing this as you can get the parsed data from programmatic usage and save it as you wish.
