### ISSUE TITLE
Gulp build bug 

### ISSUE THREAD

**Issue by ddeabreu** [apidoc/apidoc#1047]
# Describe the bug
With the last version, i'm using gulp on my project and when i trigger a the 'gulp' command, i have this error:
![image](https://user-images.githubusercontent.com/10730772/137817695-a8f74d15-9c72-46aa-9c0d-173bab3522da.png)

When i trigger the command gulp, i ve an error:

/src/formation-services/node_modules/apidoc/lib/writer.js:136
    const title = projectInfo.title ?? projectInfo.name ?? 'Loading...';
                                     ^
SyntaxError: Unexpected token ?

# Steps to reproduce
gulp on a projet wich have a composer.json with apidoc
    "gulp-apidoc": "^0.2.4",
then gulp

# Information

- Version of apidoc:"^0.2.4", 
- Operating system (e.g. GNU+Linux/MacOS/Windows): Linux ( Docker system on a gitlabrunner)

**Comment by NicolasCARPi** [comment]
Node v14 minimum needed.
