### ISSUE TITLE
I18N support

### ISSUE THREAD

**Issue by itsmanishagarwal** [apidoc/apidoc#105]
First of all thanks for this tool. It is very helpful.
My question is, does APIdoc has I18N support? I want to generate my docs in multiple languages.
I saw that the doc template itself support multiple languages (German is available by default), but is there any way to generate the doc in multiple langauges?

Thanks,
Manish

**Comment by 2naive** [comment]
@rottmann indeed native multilingual support would be nice!
I use documentation block inside Express API routes. So it's much more beautiful approach to leave them close to code itself instead of moving doc blocks to separate different files and language folders as it proposed in #48
