### ISSUE TITLE
The generated apidoc is incorrect

### ISSUE THREAD

**Issue by indrodev** [apidoc/apidoc#1067]
In package.json
```
...
"apidoc": {
    "name": "demo",
    "description": "test project",
    "title": "demo",
    "url": "https://example/api/v1"
},
...
```

![image](https://user-images.githubusercontent.com/33631711/138923124-43a1789d-8a62-4e66-a20c-73444302f38d.png)

Please if possible, give option to select the default version (an option in apidoc config json) for preview

Thank you

**Comment by NicolasCARPi** [comment]
You can set the version apidoc.json.
