### ISSUE TITLE
Add links to example comments on the website

### ISSUE THREAD

**Issue by jeremybradbury** [apidoc/apidoc#1087]
# Feature request

The problem: It's hard to go back and forth between the examples and the output and view the parity.

The ideal solution: vertical frame-split, api docs left, foldable source right, scrolling together.

The easy solution: place relevant links with line number range hashes to the example source, inside the comments themselves, so they render clickable links inside the descriptions.

**Comment by NicolasCARPi** [comment]
This is more or less #162. Maybe once the parser knows what line is the docblock coming from we can have links to it from the doc (or have an additional key to the parsed block which is "source"). Closing as duplicate.
