### ISSUE TITLE
Exclude Folder Command Issue

### ISSUE THREAD

**Issue by deerawan** [apidoc/apidoc#109]
I have three folders
- business
- user
- doc => for apidoc output

When I read how to exclude folder on https://github.com/apidoc/apidoc/issues/6, I tried with this command

``` JavaScript
apidoc -i ./ -e business/ -o doc/
```

but the api still generate doc for codes inside business, but when I tried with

``` JavaScript
apidoc -i ./ -e business -o doc/
```

It works. See the business now without /.

My environment
- windows 8
- apidoc 0.7.0
- node 0.10.26

I don't know whether it is bug or not. Just want to let you know.

**Comment by lomby92** [comment]
Using / and \ still not work on: Ubuntu 16.04 x64, Node 6.4.0 and apidoc 0.16.1

The complete command is:
apidoc -i myfolder/ -e myfolder/node_modules/ -o myfolder-doc/

**Comment by lomby92** [comment]
Solved,
now i use `apidoc` in `myfolder` and using command:
`apidoc -e node_modules -o ../myfolder-doc`

Maybe the `-i` command is stronger than `-e`
