### ISSUE TITLE
Add option to remove `required` flag

### ISSUE THREAD

**Issue by vlebourl** [apidoc/apidoc#1095]
# Feature request

Although having parameters as required as default option is IMO a good idea, showing the `required` flag in the rendering is sometimes a bit too much... For instance, the following block as a `required` or `optional` showing up in response and errors areas, which doesn't make much sens to me...

I may have missed how to disable that. But if not, adding an option to not show those would be great!

Cheers and thanks for the great work!

```java
/**
 * @api {post} /api/login Retrieve user's password salted hash.
 * @apiName Login
 * @apiGroup API
 *
 * @apiBody {String} userId    The user's id.
 * @apiBody {String} password  The user's password.
 * @apiParamExample {json} Request-Example:
 *   {
 *     "userId": "user1",
 *     "password": "password"
 *   }
 * 
 * @apiSuccess {String} loginHash Salted hash of the user's password.
 *
 * @apiSuccessExample {json} Success-Response:
 *  HTTP/1.1 200 OK
 *  {
 *    "loginHash": "9LfzEggSuUPj4DKGkyxm5vSk7fBaUgKKUvwDQeJoVF3MkEbxhr6JG2czF3gPb3r6N2sq8wxry5pePfYRUwKXEG"
 *  }
 * 
 * @apiError (500 Internal Server Error) [InternalServerError] Server Out of Memory.
 * @apiError (Error 4xx)                 BadRequest          <code>userId</code> is either unknown or does not have access to this StarQube Server.
 * @apiError (Error 4xx)                 BadRequest          <code>userId</code> requires kerberos authentication.
 * @apiError (Error 4xx)                 Unauthorized        Invalid password.
 */
 ```
 
![image](https://user-images.githubusercontent.com/5701372/142184059-078e2c41-bedb-402f-989e-a2d6c47bc735.png)
![image](https://user-images.githubusercontent.com/5701372/142184075-f6f6c4ae-aa44-41d2-8c5b-6a2538a91a3b.png)

**Comment by TheJaysH** [comment]
+1 for this.. I'm sure it never used to do this. But i could be wrong.

**Comment by NicolasCARPi** [comment]
I think I will add an option `showRequiredLabels`, so the default won't show it.

**Comment by TheJaysH** [comment]
Maybe prefix the value with a `!` or something to dictate its required? just an idea? Love the project btw. thanks :)

**Comment by NicolasCARPi** [comment]
> Maybe prefix the value with a ! or something to dictate its required?

No it needs to be the same as the `optional` label. I think the big issue here is mainly aesthetic, with too many red labels.

> Love the project btw. thanks :)

Cheers :)

**Comment by NicolasCARPi** [comment]
The option `showRequiredLabels` has been added (default: `false`) and will be available in next release.
