### ISSUE TITLE
Order `Request Body` above `Success`

### ISSUE THREAD

**Issue by AlvinStefanus** [apidoc/apidoc#1100]
# Feature request

Hello,
I want to set the order for `Request Body` to be above `Success` part. Currently `Success` comes first before `Request Body`.

Thanks.

**Comment by NicolasCARPi** [comment]
Hello,

The blocks appear in the order in which you add them in your source code comments.

**Comment by AlvinStefanus** [comment]
I put the `Request Body` block above the `Success` block, but in the documentation it appears differently. `Request Body` block comes after `Success` block.

**Comment by NicolasCARPi** [comment]
Indeed. Fixed it.
