### ISSUE TITLE
Add support for Yarn v2.x

### ISSUE THREAD

**Issue by 2hoyeong** [apidoc/apidoc#1118]
# Describe the bug

Yarn berry no longer create node_modules. but apidoc find assets in node_modules
```
error: Could not find where dependencies of apidoc live!
error: The "path" argument must be of type string. Received undefined
[error] apidoc encountered an error during documentation generation!
```

# Steps to reproduce
1. Create yarn berry project
2. Install apidoc >= 0.50
3. Build

# Information

- Version of apidoc: ^0.50.2
- Operating system (e.g. GNU+Linux/MacOS/Windows): MacOS
- Node version: v16.4.1
- Browser (e.g. firefox, chrome):
- Yarn: 3.1.1

**Comment by NicolasCARPi** [comment]
Note to future self (or another contributor wanting to address this shortcoming): this should be used: https://yarnpkg.com/advanced/pnpapi/#accessing-the-files
