### ISSUE TITLE
when use multer to upload file

### ISSUE THREAD

**Issue by FxPixels** [apidoc/apidoc#1122]
# Describe the bug
apidoc: 0.50.2

I try to use @apiParam  or @apiBody  to  mark upload file

![image](https://user-images.githubusercontent.com/25996313/146663135-4a3b1037-d712-456c-897f-fb5fad4f08c6.png)
 but it show that 
![image](https://user-images.githubusercontent.com/25996313/146663146-1825dfae-a934-4fc6-ace5-4dd8f1395c43.png)
Error: Multipart: Boundary not found

my ejs page is work:
![image](https://user-images.githubusercontent.com/25996313/146663181-b035e6bf-bba7-45a1-8e75-ccd099cce513.png)

# Steps to reproduce

# Information

- Version of apidoc:0.50.2
- Operating system (e.g. GNU+Linux/MacOS/Windows): Windows
- Node version: 14.17.3
- Browser (e.g. firefox, chrome): chrome 96

**Comment by FxPixels** [comment]
I use apidoc in my express project

**Comment by NicolasCARPi** [comment]
Can you try with `@apiBody` instead of `@apiParam`?

**Comment by anjan-saal** [comment]
@NicolasCARPi I am facing same issue even with @apiBody

**Comment by KujoMiva** [comment]
> Can you try with `@apiBody` instead of `@apiParam`?

Because there is a problem with nodejs' support for 'multipart/form-data'.

**Comment by thenewvu** [comment]
there're 2 more duplicated issues: #1309 #1234 

@NicolasCARPi  @KujoMiva: it's not a NodeJS issue, multipart/* content type actually requires the boundary parameter. The spec does say about this, please take a look below:

> The only mandatory parameter for the multipart Content-Type is the boundary parameter
> https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html

I believe this commit causes the issue:
https://github.com/apidoc/apidoc/commit/b937c6e63baa005db80059830d0fcd8b87c408a1

With no content-type header (or with false value in this case), browser will know it need to generate a proper content type for the form data when sending it. (ref: https://stackoverflow.com/questions/23960036/error-no-multipart-boundary-is-found-when-passing-form-data-via-ajax)

Could I make a PR for this?
