### ISSUE TITLE
Upgrade to 0.50.x fails to build main.bundle.js

### ISSUE THREAD

**Issue by kevinbull** [apidoc/apidoc#1125]
# Describe the bug

Our project has been using apidoc for a while now but when we upgrade the package from 0.29.0 to 0.50.x the `assets/main.bundle.js` file never gets built.  It doesn't appear to output any errors either.  

# Steps to reproduce
A repo with a minimal reproducible case, https://github.com/kevinbull/apidoc-bug, the default branch is master where the problem will occur, then

- clone the repo
- npm install
- npm run build-docs

The output from the script will log the options object and the config object and will say that the docs were built without an error.  But if you open `./docs/dist/index.html` it will never fully load.  Looking at the network inspector will show the `assets/main.bundle.js` file failed load.  This is because that file never got created.  Go back to the repo and inspect the `./docs/dist/assets` folder to verify `main.bundle.js` does not exist.

To see apidoc build correctly with version 0.29.0 you can
- git checkout version-0.29.0
- npm install
- npm run build-docs

Open `./docs/dist/index.html` in a browser to see a minimal API doc.

# Information

- Version of apidoc: 0.50.x
- Operating system (e.g. GNU+Linux/MacOS/Windows): MacOS and Alpine
- Node version: 14.18.2
- Browser (e.g. firefox, chrome): Chrome, Firefox

**Comment by kevinbull** [comment]
@NicolasCARPi thanks for the quick response but something is still out of whack.  Your command didn't include the `/docs/src/` where the `@apiUse` is defined.  However when I run apidoc similar to the method you mentioned `./node_modules/apidoc/bin/apidoc -i docs/src -i src/routes/ -o docs2 -d -c apidoc.config.js` it does work correctly.  So it got me thinking maybe I need to have the `docs/src` defined first in the input array.  Sadly that didn't make any difference.

I am also wondering what changed internally because our regular method of building docs using the script in the repo and doing `npm run build-docs` would display errors like the `@apiUse` not being defined.  It would also indicate if invalid json was detected.

Despite running apidoc on the command line successfully the way we have always run it, and still works using apidoc 0.29.0, still doesn't work.  Any ideas on that one?

**Comment by NicolasCARPi** [comment]
> I am also wondering what changed internally

Well, many things. A lot of the code has been rewritten.

> Any ideas on that one?

No, this will need in-depth analysis of the behavior.

**Comment by dorukgunes** [comment]
Hi @NicolasCARPi, we are facing with the same issue `main.bundle.js` is not being created with 0.50.x versions. Is there any update or planning for this issue?

**Comment by NicolasCARPi** [comment]
@dorukgunes You need to:

1. Use the latest version
2. Run with debug flag (`-d`)
3. Figure out where is the issue in YOUR code.

I'm considering this issue as fixed. If someone finds a **reproducible** bug, please open a new issue with ALL information.
