### ISSUE TITLE
apidoc -v

### ISSUE THREAD

**Issue by meipeng** [apidoc/apidoc#1129]
# Describe the bug

~~~
verbose: apidoc-generator name: apidoc
verbose: apidoc-generator version: 0.50.3
verbose: apidoc version: 0.50.3
verbose: apidoc-spec version: 0.3.0
verbose: run parser
error: ENOENT: no such file or directory, scandir 'C:\Users\11480\src'
error: Error during source code parsing!
[error] apidoc encountered an error during documentation generation!
~~~

**Comment by meipeng** [comment]
Run command error  The resulting document is also incorrect

**Comment by NicolasCARPi** [comment]
Hello,

You need to show which command you run, and add the `-d` flag. Use correct markdown to show results, too.

**Comment by meipeng** [comment]
![image](https://user-images.githubusercontent.com/15810837/147662171-2e17ecaa-f154-4f3d-894d-72883a169edf.png)

**Comment by NicolasCARPi** [comment]
Use the `-i` flag to specify an input directory.
