### ISSUE TITLE
Apidocjs Website Preview Doc Feature

### ISSUE THREAD

**Issue by andrewpolemeni** [apidoc/apidoc#1130]
# Feature request
Would like to be able to copy the docs from my project and copy paste them to the [apidocjs website](https://apidocjs.com/) just to preview without having to generate the project. Basically like the swagger online editor.

**Comment by NicolasCARPi** [comment]
Hello,

Thank you for your suggestion. However, this is not planned at the moment.

**Comment by andrewpolemeni** [comment]
@NicolasCARPi Could this be planned in the future? It's low priority, just think it's a cool feature and should help with wider adoption.
