### ISSUE TITLE
Doc generation not working with apidoc key in package.json

### ISSUE THREAD

**Issue by jualoppaz** [apidoc/apidoc#1137]
# Describe the bug
After upgrading to 0.50.3 version I noticed that using **apidoc** key in **package.json** is not generating rightly the docs. The result is an empty screen with **Acme project** title at top.

![Captura](https://user-images.githubusercontent.com/5088244/148697438-26fdcfc8-a360-4073-b11a-9218452efe62.JPG)

# Steps to reproduce

- Add apidoc config to package.json:

```javascript
{
  "name": "pronostigol-v2",
  "version": "2.0.0",
  "apidoc": {
    "title": "Documentación de la API Rest de Pronostigol",
    "url": "https://www.pronostigol.es/api"
  },...
```

- Generate docs with the command `apidoc -i api/ -o static/docs/ -d` (it is a nuxt project)

# Information

- Version of apidoc: 0.50.3
- Operating system (e.g. GNU+Linux/MacOS/Windows): Windows 10
- Node version: 16.13.1
- Browser (e.g. firefox, chrome): Chrome

I discovered that adding the **version** parameter in **apidoc** key produces a right generation of docs. I suppose the error consist of the recollection of all parameters from the **package.json** when they are in different levels.

With the following **apidoc** key in **package.json** the docs are generated successfully.

```javascript
{
  "name": "pronostigol-v2",
  "version": "2.0.0",
  "apidoc": {
    "version": "2.0.1",
    "title": "Documentación de la API Rest de Pronostigol",
    "url": "https://www.pronostigol.es/api"
  },...
```

![Captura 2](https://user-images.githubusercontent.com/5088244/148697448-6a443702-cb44-4aa3-b7b5-6c2b8d8ba8df.JPG)

**Comment by gnickm** [comment]
Same here. Opened PR #1163 with a fix to use version root of package.json if it's not in apidoc block.

**Comment by gnickm** [comment]
I missed `name` and `description` in the original PR. Fixed in #1164

**Comment by ManshuSengar** [comment]
any other solution?

**Comment by NicolasCARPi** [comment]
@ManshuSengar this issue should be fixed, what version are you using?
