### ISSUE TITLE
error: ENOENT: no such file or directory, open './template/src/css/main.css'

### ISSUE THREAD

**Issue by Mohammad-Alavi** [apidoc/apidoc#1142]
# Describe the bug

I upgraded from `0.27.1` to `0.50.3` and i got this error while using `--single`.

**error: ENOENT: no such file or directory, open './template/src/css/main.css'**

# Steps to reproduce

Try to generate docs using `--single`

# Information
I am using a Docker Node container.

- Version of apidoc: `0.50.3`
- Operating system: `Windows 10`
- Node version: `14`
- Browser: `chrome`

# Fix that i found
In line 153 of [writer.js](https://github.com/apidoc/apidoc/blob/625bc861b1ac26cbdb98ea76ca28311d7060bb4a/lib/writer.js#L153) file
change `'./template/src/css/main.css'` to `'node_modules/apidoc/template/src/css/main.css'`

debug info with `-d` can be found [here](https://gist.github.com/Mohammad-Alavi/6b3cddcffc92701ca5136e13d0366c1e).

**Comment by NicolasCARPi** [comment]
How did you install the lib? Is it global or not?

I think a good fix would be to use the `findAsset()` function like the other assets.

**Comment by Mohammad-Alavi** [comment]
@NicolasCARPi Thanks for the fast replay. 👍 
Not Global.
It might be an stupid question but i there any other docs beside [this](https://apidocjs.com/index.html) which explains things like `--single` parameters and `findAsset()` function? Or i should just dig up the source code to learn about the features of apidoc?

Ill test `findAsset()` function and come back to you. First i need to findout how it works and where should i use it because i cannot find it anywhere in the mentioned docs.

**Comment by NicolasCARPi** [comment]
> It might be an stupid question but i there any other docs

`apidoc --help`

> Ill test findAsset() function and come back to you. First i need to find out how it works and where should i use it because i cannot find it anywhere in the mentioned docs.

No this was more of a comment to my future self, it is not a user facing function, just something that I need to change in the code. I'm talking about this function: https://github.com/apidoc/apidoc/blob/master/lib/writer.js#L41-L55

**Comment by NicolasCARPi** [comment]
Can you try the latest code from the `dev` branch please? (`npm i apidoc#dev`).

**Comment by Mohammad-Alavi** [comment]
Yea, it is fixed. Thank you 😄

**Comment by NicolasCARPi** [comment]
Ok great, I'll make a new release soon then!

**Comment by Mohammad-Alavi** [comment]
So when can we expect a release? 😄 Just so i dont forgot to switch to the master 😄

**Comment by NicolasCARPi** [comment]
Just use the watch feature of github and select "Releases" so you'll get an email for new versions.

**Comment by Facj** [comment]
I have found the same issue when running "apidoc -i src/ -o apidoc/public/api/ -t apiDoc/templateDoc/ -v" after updating from 0.28.1 to 0.52.0.

**Comment by SerGem811** [comment]
I am still facing this error
When this one can be fixed or which version will be fine with this?
