### ISSUE TITLE
Wrong parameters in send example request

### ISSUE THREAD

**Issue by canonex** [apidoc/apidoc#1149]
# Describe the bug

When a parameter is set, in the generated query url, the param is not substituted by the value of the search param but by the param name.
That means that, using ex. search=agri instead of 
`/search/autocomplete?s=agri`
you get
`/search/autocomplete?s=:search`

In previous version was working fine as expected and there was no problem (I think the version of October... I'll see if I can check).

![ApiDoc-ParamsError](https://user-images.githubusercontent.com/1444378/150782404-059d6002-8402-4c90-8e49-7076f285c308.png)

# Steps to reproduce

Try using this simple annotation:
```
/**
 * @api {get} /search/autocomplete?s=:search Autocomplete search
 * @apiVersion 1.0.0
 * @apiName SearchAutocomplete
 * @apiGroup Search
 *
 * @apiDescription Search for tag similar to the term searched for in the search bar.
 *
 * @apiParam {String} search	Found tag starting with search input
 *
 */
```

# Information

- Version of apidoc: 0.50.3
- Operating system: Linux Debian 10
- Node version: 8.3.2
- Browser (e.g. firefox, chrome): tested in Firefox Dev 97 and Chromium 90

**Comment by NicolasCARPi** [comment]
Try with apiQuery instead of apiParam.

**Comment by canonex** [comment]
Thank you, you are right, I thought it was simply a substitution.
Using apiQuery is working smooth!

**Comment by NicolasCARPi** [comment]
See also: https://github.com/apidoc/apidoc/discussions/1078
