### ISSUE TITLE
npm install -g apidoc return error 

### ISSUE THREAD

**Issue by JamesKid** [apidoc/apidoc#1150]
# Describe the bug
use `npm install -g apidoc` to  install    return error 

```sh
changed 302 packages in 9s

2 packages are looking for funding
  run `npm fund` for details
```

# Steps to reproduce
npm install -g apidoc

# Information

changed 302 packages in 9s

2 packages are looking for funding
  run `npm fund` for details

- Version of apidoc:
- Operating system (e.g. GNU+Linux/MacOS/Windows):
- Node version:  v16.13.1
- Browser (e.g. firefox, chrome):
- Npm version : 8.3.2

**Comment by NicolasCARPi** [comment]
I see no errors here.
