### ISSUE TITLE
@apiGroup doesn't work on other language

### ISSUE THREAD

**Issue by exdj158** [apidoc/apidoc#1180]
i read the source code，found that @apiGroup must be in English

the code line
![image](https://user-images.githubusercontent.com/85820498/156115156-08839e29-bf86-4bde-bd0b-452a0a5e8856.png)

- Version of apidoc:0.50.4

**Comment by NicolasCARPi** [comment]
can you make a PR?

**Comment by exdj158** [comment]
> can you make a PR?

yes,i had make a PR,and i found a bug,when write by chinese，the apigroup are not sorted correctly

**Comment by exdj158** [comment]
> can you make a PR?

Can you lift this restriction？
