### ISSUE TITLE
Allow XML and Plain Text as valid testable return types.

### ISSUE THREAD

**Issue by cjbarth** [apidoc/apidoc#120]
My API can return not only JSON objects, but also well-formed XML and plain text lists. It would be nice if the sample generator code in the template would properly handle such return types and also display them in the results box.

**Comment by xIscateLx** [comment]
Indeed, I would like to see the ability to display the query results in XML format. These issues are highly relevant.

**Comment by NicolasCARPi** [comment]
Now XML works.
