### ISSUE TITLE
Getting issue while install Apidocjs Library

### ISSUE THREAD

**Issue by prakashmuvi** [apidoc/apidoc#1203]
# Describe the bug

oot@ip-172-31-39-75:~# apidoc -v
/usr/lib/node_modules/apidoc/node_modules/chokidar/index.js:162
  async remove(item) {
        ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/apidoc/node_modules/nodemon/lib/monitor/watch.js:6:16)

# Steps to reproduce
While installing APidocJs library in server.

# Information

- Version of apidoc: Just use the command not specifying any version
- Operating system (e.g. GNU+Linux/MacOS/Windows):
- Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
- Node version:v6.16.0
- Browser (e.g. firefox, chrome):

**Comment by NicolasCARPi** [comment]
Use at least node v14.

**Comment by prakashmuvi** [comment]
Hi Support,
We have installed the below version:-
Version of apidoc:1.4.0
Operating system (e.g. GNU+Linux/MacOS/Windows): Ubuntu 18.47
Node version: v17.9.0

While Using the command to generate the APIDOC HTML:-
We are getting the parser Error.
**2022-04-11 04:54:37,115 - ERROR - Failed to parse sources**

**Comment by prakashmuvi** [comment]
Hi Support,
Could you please find the bug details?
[https://docs.google.com/document/d/19FCgVvP2kH42JzbhM4VtLw3MqKk7nEsDPjjJGl9dRbQ/edit?usp=sharing](url)

**Please find the details of our dev server where it is working fine:-**

OS VERSION: "Amazon Linux AMI 2018.03"

node -v  (Details): Node: v6.17.1

apidoc -v (Details)
{"message":"Please create an apidoc.json configuration file.","level":"warn"}
{"message":"apidoc-generator name: apidoc","level":"verbose"}
{"message":"apidoc-generator version: 0.17.7","level":"verbose"}
{"message":"apidoc-core version: 0.8.3","level":"verbose"}
{"message":"apidoc-spec version: 0.3.0","level":"verbose"}
{"message":"run parser","level":"verbose"}

**Our Staging Server info where not working:-**
Version of apidoc:1.4.0
Operating system (e.g. GNU+Linux/MacOS/Windows): Ubuntu 18.47
Node version: v17.9.0

**Comment by NicolasCARPi** [comment]
You cannot have apidoc version 1.4.0, as the latest version is 0.51.0.
