### ISSUE TITLE
Getting issue "589 - ERROR - Failed to parse sources"

### ISSUE THREAD

**Issue by prakashmuvi** [apidoc/apidoc#1204]
# Describe the bug

While executing the command getting the issues"589 - ERROR - Failed to parse sources"

# Steps to reproduce

# Information

- Version of apidoc:
- Operating system (e.g. GNU+Linux/MacOS/Windows):
- Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
- Node version:v6.16.0
- Browser (e.g. firefox, chrome):

**Comment by NicolasCARPi** [comment]
Use the debug flag and provide the source that make it fail. How do you expect to get any help if you don't provide anything in the "Steps to reproduce" section.....

**Comment by prakashmuvi** [comment]
Hi Support,
Thanks for your support. Now we are able to install the latest version 0.51.0.
Now it is working fine and the UI is totally different.
Could you please help to get some warning while generating the  API document?
[33mwarn[39m: @apiParam 'authToken' was defined but does not appear in URL of @api 'IsRegistrationEnabled' in file:
[33mwarn[39m: @apiParam 'lang_code' was defined but does not appear in URL of @api 'IsRegistrationEnabled' in file:

**Comment by VaibhavPoliwal** [comment]
hey @NicolasCARPi ,
Actually I'm working in python and I have written simple script python with proper @api formats in comment when I run apidoc then it says 

`798 - ERROR - Failed to parse sources`

**Comment by VaibhavPoliwal** [comment]
This is the python code
```

# below example: doc string is for GET API 
"""
@api {get} api/v1/user/:id/ Get user
@apiName Get User
@apiGroup User 
@apiDescription API will return response
@apiParam {String} uid  uid 
@apiSuccessParam {String} message message will be display
@apiHeader (MyHeaderGroup) {String} authorization Authorization value

@apiSuccessExample Success-Response:
HTTP/1.1 200 OK
{
["name": "xyz",
"name": "yyy"]
}
@apiErrorExample Error-Response:
HTTP/1.1 403 Bad Data
{
"status": "Bad Data"
}
"""

def hello():
    return "hello world"
```

**Comment by NicolasCARPi** [comment]
Please provide enough information for a **reproducible** issue.

**Comment by VaibhavPoliwal** [comment]
@NicolasCARPi 
This is the python code

`# This is a example 

"""
@api {get} /user/:id Request User information
@apiName GetUser
@apiGroup User

@apiParam {Number} id Users unique ID.

@apiSuccess {String} firstname Firstname of the User.
@apiSuccess {String} lastname  Lastname of the User.
"""

def hello():
    # 
    return "hello world"`

**Comment by NicolasCARPi** [comment]
This works fine for me. No issues with that code.

**Comment by VaibhavPoliwal** [comment]
I'm working in Ubuntu ec2, and I have installed apidoc by pip. Do I need to import something in python program or I have missed something... 
And can you please help me in this, if I'm using yml config file in apiDoc, so what parameters would be in yaml file so that I can run my api from docs itself...

**Comment by VaibhavPoliwal** [comment]
So bro can you please help me this, 
I have made some api's with python and I want to document python methods(api methods) using apidoc. In which I able to run the api from docs itself.

**Comment by VaibhavPoliwal** [comment]
How should I use apiDoc for this? If you are on slack we can connect on slack...

**Comment by VaibhavPoliwal** [comment]
We can connect on another platform for further communication...
