### ISSUE TITLE
Only node14 and above can use latest apidoc?

### ISSUE THREAD

**Issue by iori2882** [apidoc/apidoc#1218]
![image](https://user-images.githubusercontent.com/1480587/164887726-a1bb81e1-e80a-45a5-bfd4-bc7d0c4072a6.png)

![image](https://user-images.githubusercontent.com/1480587/164887754-a43f693e-23e4-4b4a-9e2d-5afe6a17d14a.png)

# Information

- Version of apidoc:
- Operating system (e.g. GNU+Linux/MacOS/Windows):Windows10
- Node version: node12.16.1
- Browser (e.g. firefox, chrome):

**Comment by NicolasCARPi** [comment]
Yes.

**Comment by iori2882** [comment]
> Yes.

Thank you very much
