### ISSUE TITLE
Sample Request Defaults

### ISSUE THREAD

**Issue by cjbarth** [apidoc/apidoc#123]
It would be nice to be able to specify a default parameter that only applied to a sample. Some API's that I'm working with have more than 5 parameters, but none of them are default. So it would be nice if I could give some generic values that are valid for use in sending sample/test request, perhaps having them only appear in association with the block to send sample/test requests.

**Comment by mypark** [comment]
it would be nice to also be able to set sample request headers as well - for instance a use case where a client key or auth token is sent in the header to the example server

**Comment by NicolasCARPi** [comment]
You can do that now.
