### ISSUE TITLE
no parameter at url warning on POST method

### ISSUE THREAD

**Issue by wesolydexter** [apidoc/apidoc#1240]
# Describe the bug
After update apidoc from 0.50.2 to last version 0.51.1 is returned warrning:
`warn: @apiParam 'name' was defined but does not appear in URL of @api 'Create user profile' in file: 'documentation/doc.php'`
after all, the POST method does not send parameters in the url.
# Steps to reproduce
doc.php file:
```<?php
/**
 * @api {post} /users Create user profile
 * @apiParam (Request) {String} name Name of user.
 */
```
# Information
- Version of apidoc: 0.51.1
- Operating system (e.g. GNU+Linux/MacOS/Windows): Ubuntu 20.04.4 LTS
- Node version: v16.15.1

**Comment by NicolasCARPi** [comment]
Yes, use `apiBody` here. An `apiParam` would be for `/users/:name`.

**Comment by wesolydexter** [comment]
Ok, thanks.
Than please add this feature https://github.com/apidoc/apidoc/issues/1196
