### ISSUE TITLE
main.bundle.js not exported in 0.51.1

### ISSUE THREAD

**Issue by alexanderweiss** [apidoc/apidoc#1246]
# Describe the bug

When upgrading from 0.51.0 to 0.51.1, the `main.bundle.js` file is no longer exported when I run apidoc in our project. It is when reverting apidoc to 0.51.0 and running it again. There's warnings about undocumented parameters in URLs, but otherwise the command runs fine: no errors, etc.

# Steps to reproduce

# Information

- Version of apidoc: 0.51.1
- Operating system (e.g. GNU+Linux/MacOS/Windows): macOS
- Node version: 16.15.1
- Browser (e.g. firefox, chrome): any

**Comment by NicolasCARPi** [comment]
Hello,

It is. What you describe is unreproducible.

**Comment by alexanderweiss** [comment]
Hey!

Yeah I get that it's little to go on, but there isn't much more I'm doing. Do you have any ideas of what I could provide to help with figuring out what's going on here? Or pointers on how to debug this further? I took a look at the diff before creating the issue, but didn't really see anything that I thought could be the cause here. Though I'm obviously not very familiar with the codebase.

**Comment by NicolasCARPi** [comment]
You have to take a scientific approach: remove/change one component at the time to try and figure out where the issue might be. Is it in your codebase? Is it your computer? Is it your node version?

I'm closing this issue but feel free to comment here if you can demonstrate a reproducible bug in apidoc, I'll re-open. Given that this version has been out for some time and that no-one else reported this, I'd go with "the error is on your side". A missing main.bundle.js would be hard to miss for any other users.
