### ISSUE TITLE
white page with js error when forceLanguage is set in config file

### ISSUE THREAD

**Issue by astalavist** [apidoc/apidoc#1248]
# Describe the bug
Got a white page if apidoc.json config file includes following block
  "template": {
    "forceLanguage": "zh_cn"
  }

It works after I remove this block

# Steps to reproduce

# Information

- Version of apidoc: 0.51.1 (0.29.0 is ok, 0.50.0 has the same issue)
- Operating system (e.g. GNU+Linux/MacOS/Windows):
- Node version: 14/16
- Browser (e.g. firefox, chrome):

**Comment by NicolasCARPi** [comment]
Any error in the browser's log? Which browser are you using and which version?

**Comment by astalavist** [comment]
I'm using chrome 103.0.5060.114.
I don't think it's browser related issue.
In your doc tempalte/forceLanguage, there's a link https://github.com/apidoc/apidoc/tree/master/template/locales
which is 404 now, maybe because you've moved the locales package. 
And I think this might be the reason of the issue.
see error below

main.bundle.js:98 Uncaught TypeError: Cannot read properties of undefined (reading 'Filter...')
    at Ae (main.bundle.js:98:12230)
    at Object.<anonymous> (main.bundle.js:98:14337)
    at Object.l (main.bundle.js:34:4558)
    at Object.eval [as main] (eval at createFunctionContext (main.bundle.js:41:1515), <anonymous>:11:137)
    at z (main.bundle.js:34:155)

**Comment by NicolasCARPi** [comment]
Use `zh`, not `zh_cn`. See: https://github.com/apidoc/apidoc/blob/3d3025e7c96adf0d5926cfd7388dbbec5b900fbd/template/src/locales/locale.mjs#L41

> And I think this might be the reason of the issue.

No the doc is completely separate and a dead link has nothing to do with the app.

The dead link has been fixed in the doc.

Now it would be best to have a check of the config and show a useful error message if some value is wrong (like unsupported lang).

**Comment by NicolasCARPi** [comment]
I've pushed a change allowing you to use `zh_cn`, too.

**Comment by astalavist** [comment]
A useful error message is great. I'm wondering if the locale checking can be done in building?

**Comment by NicolasCARPi** [comment]
>  I'm wondering if the locale checking can be done in building?

That was my first thought, too. Validating the config options once it's loaded, but it is more involved so I went with an easier/faster fix.
