### ISSUE TITLE
GEO coördinates as parameters

### ISSUE THREAD

**Issue by Dadinos** [apidoc/apidoc#1252]
Is there a possibility to give geo coordinates as a parameter withh an output like so:

    "zaakgeometrie": {
        "within": {
          "type": "Point",
          "coordinates": [ 0, 0 ]
        }
    },

Sofar I got this:
     * @apiBody {Object} [zaakgeometrie] object (GeoJSONGeometry) 
     * @apiBody {Object} zaakgeometrie.within object  
     * @apiBody {String = Point,MultiPoint,LineString,MultiLineString,Polygon,MultiPolygon,GeometryCollection} zaakgeometrie.within.type = Point
	 * @apiBody {Number} zaakgeometrie.within.coordinates

But gives me:

    "zaakgeometrie": {
        "within": {
            "type": "Point",
            "coordinates": 0
        }
    },
 

Can't get the Point notation in the coordinates correct like the sample: [0,0] , tried it also with type object but no luck, is there a way to do this?

**Comment by NicolasCARPi** [comment]
I don't think so no.
