### ISSUE TITLE
Nested fields are not processed correctly.

### ISSUE THREAD

**Issue by kosala-almeda** [apidoc/apidoc#1255]
# Describe the bug
Nested fields are not processed correctly.

# Steps to reproduce

```
 * @apiBody {String} [data[stack[version]]] Release version
```
Above will extract field name as `data` and description as `[stack[version]]] Release version`

# Information

- Version of apidoc: v0.52.0
- Operating system (e.g. GNU+Linux/MacOS/Windows): MacOS
- Node version: v16.15.1
- Browser (e.g. firefox, chrome):

**Comment by NicolasCARPi** [comment]
Try with a dot. See https://github.com/apidoc/apidoc/issues/975
