### ISSUE TITLE
Links to other APIs not work in the default template

### ISSUE THREAD

**Issue by nianxy** [apidoc/apidoc#1261]
# Describe the bug
I have a link in the @apiParam description, which looks like `<a href="#api-User-login">Login</a>`
But nothing happens when I click the link in the generated document, although the hash is changed in the browser's address bar. If I refresh the page after the hash changes, the document is navigated to the right API definition, so I'm sure the link is right.

# Steps to reproduce

- write two API definitions
- link to one API from another through the HTML A markup
- generate the document and click the link
- the document is not navigated to the right position

# Information

- Version of apidoc: 0.52.0
- Operating system (e.g. GNU+Linux/MacOS/Windows): Ubuntu
- Node version: v16.14.2
- Browser (e.g. firefox, chrome): Chrome

**Comment by NicolasCARPi** [comment]
Works fine for me with Chromium and Firefox.
