### ISSUE TITLE
Warning for param not defined in URL when generating document

### ISSUE THREAD

**Issue by nianxy** [apidoc/apidoc#1262]
# Describe the bug
After upgrading to 0.52.0, a lot of warnings displayed for param is not defined in URL, but the params defined by @apiParam may be in the URL queries or in the Forms or in the request json, these params are not defined in the URL pattern.

# Information

- Version of apidoc: 0.52.0
- Operating system (e.g. GNU+Linux/MacOS/Windows): Ubuntu
- Node version: v16.14.2
- Browser (e.g. firefox, chrome): Chrome

**Comment by NicolasCARPi** [comment]
Then use `@apiQuery`?
