### ISSUE TITLE
What is the reason for this mistake？

### ISSUE THREAD

**Issue by c-c-j** [apidoc/apidoc#1265]
![image](https://user-images.githubusercontent.com/47840230/185530111-2bdfc124-e174-4973-91c3-00f6e32e8877.png)

![image](https://user-images.githubusercontent.com/47840230/185530061-10b4d514-aaf2-4c2f-a33c-3cd47262785a.png)

**Comment by NicolasCARPi** [comment]
Might want to use `@apiBody` for this.
