### ISSUE TITLE
When {type} is missing in @apiBody, there's no build error or warning info, however the apidoc fails to display with js error

### ISSUE THREAD

**Issue by astalavist** [apidoc/apidoc#1291]
# Describe the bug

Someone missing {String} type in @apiBody, like: @apiBody lastname User lastname.
After upgrade apidoc from v0.24.0  to v0.53.1, the whole apidoc fails to display.
I don't see a build error, also I don't expect this impact the whole apidoc.

In browser console:
Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at jsonifier.mjs:40:1

# Steps to reproduce

# Information

- Version of apidoc: v0.53.1
- Operating system (e.g. GNU+Linux/MacOS/Windows): win10/linux
- Node version: node 16
- Browser (e.g. firefox, chrome): chrome

**Comment by NicolasCARPi** [comment]
Isn't it an issue with the doc comment rather than apidoc? Even if I agree that a proper error should be thrown.

**Comment by astalavist** [comment]
> Isn't it an issue with the doc comment rather than apidoc? Even if I agree that a proper error should be thrown.

But v0.24 works. I upgrade one of my projects, it took me some time to figure out what was wrong. I don't think it's OK to break what works before.

**Comment by NicolasCARPi** [comment]
> I don't think it's OK to break what works before.

The first number of the version is a 0, that means anything can break anytime. Also there was a major code rewrite, so things might change yes.

**Comment by Wayde2014** [comment]
The same happened when I upgraded apidoc from 0.11.1 to 1.10.

Thanks to @astalavist reminder, otherwise I don't know how to locate this problem.
