### ISSUE TITLE
apidoc ignores documentation blocks with same @api path. Why we can't have multiple endpoints with same path in apidoc?

### ISSUE THREAD

**Issue by IVoyt** [apidoc/apidoc#1292]
# Feature request

Option to have multiple endpoints with same path. E.g.

```
/**
 * @api {get} / Endpoint 1
 * @apiParamExample {json} Request-Example:
 *  {
 *      "method_id": 123
 *  }
 */

```
```
/**
 * @api {get} / Endpoint 2
 * @apiParamExample {json} Request-Example:
 *  {
 *      "method_id": 135
 *  }
 */
```

**Comment by NicolasCARPi** [comment]
If it's the same path and same method, it's the same endpoint. So you need to merge the different examples in the same codeblock.

**Comment by IVoyt** [comment]
I'm pretty sure this solution will be very uncomfortable since apiParamExample may become too large, as well as apiSuccessExample and apiErrorExample for each example. It will be unreadable
