### ISSUE TITLE
Improve current default template or create a new one

### ISSUE THREAD

**Issue by amarcadet** [apidoc/apidoc#13]
Hi, 

This issue is related to https://github.com/apidoc/apidoc/issues/12.

In the default template every api is displayed in the same page, for really long REST API it becomes hard to read the documentation.

It would be great to split the different types of information in several tabs below the `@api` definition:
- Request: parameters definition + sample
- Response: objects definition + sample
- Errors: errors definition + sample

Also it would be nice to add a test feature for the API like https://developers.helloreverb.com/swagger/ does.

Thank you,
Antoine

**Comment by johannlaqua** [comment]
+1
