### ISSUE TITLE
Obsolete warning @apiParam and @apiDefine

### ISSUE THREAD

**Issue by psychonetic** [apidoc/apidoc#1301]
# Describe the bug
Using the following example:

```
AssetController.ts

 /**
   * @api {Get} /assets/temporary/:id Returns a temporary url to a file by id.
   * @apiName temporaryUrlById
   * @apiGroup Assets
   * @apiUse GetSignedAssetUrlQuery
   *
   */
   
```

```

doc/asset.ts
/**
 * @apiDefine GetSignedAssetUrlQuery
 *
 * @apiParam {id} id The id of the asset to download.
 *
*/
```

will produce the warning "URL contains a parameter ':id' that is not documented as @apiParam in [...]", even though it is defined in the apiDefine. If I copy the line @apiParam to the AssetController the warning won't be displayed.

So my question is: is this intended? Because I like to define all the arguments (query, param, body) for requests/responses within an extra file. 

In the old versions 0.29.* this didn't create a warning. But if I am not mistaken the check is new in the 0.5X releases. 

# Information

- Version of apidoc: 0.53.1
- Operating system (e.g. GNU+Linux/MacOS/Windows): MacOS
- Node version: 16.10.0
- Browser (e.g. firefox, chrome): *

**Comment by NicolasCARPi** [comment]
Probably because the code is not taking into account things defined externally. See https://github.com/apidoc/apidoc/pull/1189.

@Lucas-C care to have a look if you can improve this to include `@apiDefine`?

**Comment by Lucas-C** [comment]
I opened #1305 to fix this
