### ISSUE TITLE
Error when POST file multipart/form-data

### ISSUE THREAD

**Issue by dungla2011** [apidoc/apidoc#1309]
My note when you have this error:
Error when POST file multipart/form-data
(Missing boundary in multipart/form-data POST data in ...)

I modified this like, so error is resolved:

In:
main.bundle.js

Change "multipart/form-data;"
To: "multipart/form-data;boundary=something"
So everything work fine!

![image](https://user-images.githubusercontent.com/7878963/202412893-1865019e-2908-48ea-934b-4d617de5a406.png)

![image](https://user-images.githubusercontent.com/7878963/202414233-8aa81ca7-edcc-499f-a6d9-e0634b6c594b.png)

**OR you can repaire in core:**

![image](https://user-images.githubusercontent.com/7878963/202416945-f1253fef-0dc3-4bdb-911c-ca9bf96eaa4e.png)

Find where send_sample_request.js : 
c:\Users\pc1\AppData\Roaming\npm\node_modules\apidoc\template\src\send_sample_request.js
Replace 2 position: 'multipart/form-data' =>  'multipart/form-data;boundary=abc123'

So when we generate docs, it automatically generates string ...boundary=abc123 ...

**Comment by j-o-r** [comment]
I ran into the same issue, however my fix would be different (above's @dungla2011 fix did not work for me):

apidoc\template\src\send_sample_request.js
Line: 141

```
requestParams.data = formData;
requestParams.processData = false;
requestParams.encType = 'multipart/form-data';
requestParams.contentType = false;
requestParams.cache = false,
// remove the Content-Type header anyway (for every method)
// it will be added automatically by the browser
delete requestParams.headers['Content-Type'];

```
[send_sample_request.zip](https://github.com/apidoc/apidoc/files/10123394/send_sample_request.zip)


![apidoc_fix](https://user-images.githubusercontent.com/52747632/204801493-df0bd436-daa9-4970-8d5a-0d9d0a9393bd.png)
