### ISSUE TITLE
Submenus when using header.md and footer.md

### ISSUE THREAD

**Issue by everdevFR** [apidoc/apidoc#1324]
# Feature request

Hi !

I would like to know if there is a way to add submenus in the nav when using header.md or footer.md files?

If it is not available, is it possible to add it for the next versions ^^?

Best regards,
Yann

**Comment by NicolasCARPi** [comment]
Hello,

Please take into account that there is nobody available to maintain this library. See https://github.com/apidoc/apidoc/issues/1436.
