### ISSUE TITLE
 ENOENT: no such file or directory, lstat 'template/src/css/main.css'

### ISSUE THREAD

**Issue by ksbhaskar15** [apidoc/apidoc#1326]
After installing latest version 0.53.1 I can't able to generate collection. Getting error

error: ENOENT: no such file or directory, lstat '/template/src/css/main.css'
[error] apidoc encountered an error during documentation generation!

**Comment by SerGem811** [comment]
This is still happening on 0.54.0
Please check and confirm!!!
