### ISSUE TITLE
@apiGroup can't support Korean.

### ISSUE THREAD

**Issue by mihilt** [apidoc/apidoc#1331]
# Describe the bug

`@apiGroup` can't support Korean.

# Steps to reproduce

In general, groups with the same name will be grouped together. 
I grouped my APIs into several groups, as shown in the picture below.

<kbd>![image](https://user-images.githubusercontent.com/50368758/216797734-075c2d6d-be87-4f50-a3f2-5848ef513cc3.png)</kbd>

However, groups in Korean recognize only one group, even if their group names are different.
I only changed all the groups to Korean in the picture above, but my APIs became one group.

<kbd>![image](https://user-images.githubusercontent.com/50368758/216798018-ae3f2842-db01-4388-9c9d-1a26cf06f72b.png)</kbd>

As the question mark shows, I didn't write the group with the same name.

# Information

- Version of apidoc: 0.53.1
- Operating system (e.g. GNU+Linux/MacOS/Windows): MacOS
- Node version: 14.19.3
- Browser (e.g. firefox, chrome): chrome

**Comment by NicolasCARPi** [comment]
Hello,

I have just pushed a commit that should fix this issue. Could you please try the `dev` branch and let me know if that works for you?

**Comment by mihilt** [comment]
@NicolasCARPi 

![image](https://user-images.githubusercontent.com/50368758/233873065-c9eb12a9-aeb8-46d9-a11c-d3a283be5af9.png)

Yup it works well.

I've tried creating two groups in Korean, and now it doesn't merge into one group.
It looks code for security has been filtered out of Korean.

**Comment by NicolasCARPi** [comment]
> It looks code for security has been filtered out of Korean.

What do you mean by that. I think something was lost in translation.

**Comment by mihilt** [comment]
@NicolasCARPi 
Just ignore it. I was talking about the situation before you committed.
