### ISSUE TITLE
Add a `cacheBustingQueryParam` option for a cache busting system

### ISSUE THREAD

**Issue by ghost** [apidoc/apidoc#1332]
Hi,

# Introduction

Currently, URLs generated in template files are static. This implies that if the website caches the files, it is not possible to empty this cache, we have to wait for the expiration. That's why I suggest implementing a `cacheBustingQueryParam` option: a query paramater added to all URLs that acts as a cache busting system.

# Examples

## Example 1

```js
createDoc({
  // We don't write the question mark at the beginning: it would be better to add it automatically.
  cacheBustingQueryParam: 'v=1',
  // Options...
})
```
All URLs will have `v=1` added as a query paremeter. For example, `<link href="assets/bootstrap.min.css" rel="stylesheet" media="screen">` will become `<link href="assets/bootstrap.min.css?v=1" rel="stylesheet" media="screen">`

## Example 2

```js
createDoc({
  // `null` or `undefined` don't change URLs.
  cacheBustingQueryParam: null,
  // Options...
})
```
All URLs will remain as is. For example, `<link href="assets/bootstrap.min.css" rel="stylesheet" media="screen">` will not be changed.

# Conclusion

I hope this option will suit you, because I think it can be very useful in many cases. Other libraries already use this kind of options, e.g. TinyMCE (see https://www.tiny.cloud/docs/configure/integration-and-setup/#cache_suffix). If ever the Apidoc maintainers accept this enhancement, I will offer to develop it myself in a pull request!

**Comment by NicolasCARPi** [comment]
Hello, I'm also using this strategy in [eLabFTW](https://github.com/elabftw/elabftw/). It is the next best thing after having all assets built with a random name.

Previously in eLabFTW I was using the version as parameter, but now I'm using the Docker build id (a random string generated at each build). For apidoc, the version string will be enough though.

You can start working on a PR :+1: 

On the implementation, I would not make it an option or a parameter, but simply something substituted at build time of the doc in the template.

**Comment by NicolasCARPi** [comment]
> Maybe in some cases some developers would like to avoid cache busting, I don't know.

I don't see a reason to ever do that, if the assets have been modified on the server, that's what should be served to the client. Every time. I've never heard of someone wanting a broken web page because the html doesn't fit with the JS and they like to tell users to empty their browser's cache ;)

If someone really doesn't like it, they can fork it.
