### ISSUE TITLE
apidoc search not working 

### ISSUE THREAD

**Issue by mominrazashahid** [apidoc/apidoc#1335]
search is not working using
nodeJS version : v16.14.0
apidoc version: 0.53.1

**Comment by NicolasCARPi** [comment]
Did you look into the browser's console for errors?

**Comment by mominrazashahid** [comment]
The issue has been resolved there was a syntax error I was using `/` in the API Name which caused a syntax error. Just remove `/` from the API name which fixes the issue by the way how can I use `/` in the API name?

**Comment by NicolasCARPi** [comment]
You don't.
