### ISSUE TITLE
filter input not work,The input is stuck

### ISSUE THREAD

**Issue by liumingsongning** [apidoc/apidoc#1337]
# Describe the bug

# Steps to reproduce

# Information

- Version of apidoc: apidoc@0.53.1 
- Operating system (e.g. GNU+Linux/MacOS/Windows):macos
- Node version:v14.15.0
- Browser (e.g. firefox, chrome):chrome
filter input not work,The input is stuck

**Comment by liumingsongning** [comment]
I start a new project is ok，Is there too much code in my old project?

**Comment by liumingsongning** [comment]
The apidoc directory is 2.2 MB in size

**Comment by NicolasCARPi** [comment]
Do you see an error in the console?

**Comment by liumingsongning** [comment]
no

**Comment by NicolasCARPi** [comment]
Well, you have to give more information. If the issue is your computer that is not fast enough or your doc that is too big there is not much to do...

**Comment by liumingsongning** [comment]
can I give you my doc url，you test？

**Comment by NicolasCARPi** [comment]
@liumingsongning You should try the change in #1343.

**Comment by NicolasCARPi** [comment]
Also, after trying the URL you sent me privately, I did not find any issue (with firefox). It works fine.
