### ISSUE TITLE
Getting error, no such file or directory when using -t template

### ISSUE THREAD

**Issue by SerGem811** [apidoc/apidoc#1348]
After installing latest version 0.54.0 I can't able to generate collection. Getting error

error: ENOENT: no such file or directory, lstat '/template/src/css/main.css'
[error] apidoc encountered an error during documentation generation!

**Comment by NicolasCARPi** [comment]
There is an issue template. It is not for decoration. It saves me from having to ask always the same things. Why did you decide to ignore it?

**Comment by SerGem811** [comment]
It means, we can't use template feature?

**Comment by NicolasCARPi** [comment]
No, I'm talking about this:

https://github.com/apidoc/apidoc/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by SerGem811** [comment]
1. node version: 18.12.0
2. apidoc version 0.54.0
3. used template
    https://github.com/ahmed-dinar/apidoc-template/template
4. operating system: windows 10
--------------
with your example folder
i did 
`apidoc -i src -o docs -t template`
and then i received error.
`error: ENOENT: no such file or directory, lstat '/template/src/css/main.css'
[error] apidoc encountered an error during documentation generation!`

**Comment by SerGem811** [comment]
can you recommend one template that i can test please?

Thank you.

**Comment by NicolasCARPi** [comment]
The one in this repository is known to work.
