### ISSUE TITLE
grunt-apidoc not generating the document currently from the repo it self

### ISSUE THREAD

**Issue by KartikSuthar** [apidoc/apidoc#1358]
# Describe the bug
I have clone the repo into: https://github.com/apidoc/grunt-apidoc
Install the npm
Run a command `grunt test`
It will generate few files on tmp directory but when render the index.html file
It was showing me an error on frontend: https://prnt.sc/GkwOuwHvoiuc

Checked the code and found that it was loading form the assets directory: https://prnt.sc/o-6VcOA-rBGo
Here is the screenshot from the directory: https://prnt.sc/xU5WixArzo0h

there was no any JS file was generated into the assets.

# Steps to reproduce

- download the repo: https://github.com/apidoc/grunt-apidoc
- run command `npm install`
- tun command `grunt test`
- check the output generated into the `tmp` directory.

# Information

- Version of apidoc: "0.54.0"
- Operating system (e.g. GNU+Linux/MacOS/Windows): MacOS
- Node version: tried into 19.7.0, 14.19.0 and 14.16.0
- Browser (e.g. firefox, chrome): chrome

**Comment by NicolasCARPi** [comment]
Hello,

`grunt-apidoc` is unmaintained.

@rottmann Can you give me write access to this repo please?

**Comment by rottmann** [comment]
@NicolasCARPi Done. OMG ive created this 9 years ago, i am old ;-)

**Comment by NicolasCARPi** [comment]
@KartikSuthar `grunt-apidoc` has been archived, see: https://github.com/apidoc/apidoc/issues/1393#issuecomment-1586283684
