### ISSUE TITLE
Optional fields not mapped properly in request body

### ISSUE THREAD

**Issue by Nadeem-Riaz** [apidoc/apidoc#1364]
# Bug
In the latest version, optional fields are not properly mapped to our json request body. Previously (in v0.54.0) it was perfectly fine.

### Code
`@apiBody {String} [FilterInfo.Keyword]`
`@apiBody {String} [FilterInfo.SearchType]`

### Expected Result
`{
        "FilterInfo" : {
           "Keyword" : "",
           "SearchType" : ""
       }
}`
###  Actual Result
`{
    "FilterInfo.Keyword": "",
    "FilterInfo.SearchType": "",
}
`

# Information

Version of apidoc: v1.0.1
Operating system (e.g. GNU+Linux/MacOS/Windows): Windows
Node version: v20.0.0
Browser (e.g. firefox, chrome): chrome

**Comment by NicolasCARPi** [comment]
It works if you add:

~~~javascript
@apiBody {Object} [FilterInfo]
~~~

This change is I think linked to the merge of #774 and should be communicated as breaking change. I didn't realize that having a parent `Object` was necessary now.

**Comment by Nadeem-Riaz** [comment]
Thanks. It Worked!
