### ISSUE TITLE
apidoc warnings

### ISSUE THREAD

**Issue by mihailsin** [apidoc/apidoc#1378]
# Describe the bug

While generating apidoc (npm run apidoc)
multiple warnings in console appears:
warn: The use of square brackets for object properties is deprecated. Please use dot notation instead: "@apiSuccessExample {json} Success-Response

however dot notation is being used already

# Information

- Version of apidoc: v 1.0.2
- Operating system (e.g. GNU+Linux/MacOS/Windows): Ubuntu 22.04
- Node version:v16.20.0
- Browser (e.g. firefox, chrome): both

**Comment by NicolasCARPi** [comment]
Please provide reproducible code snippet.

**Comment by yanlong-li** [comment]
``` json
@apiSuccessExample {json} Success-Response
        {"data":{"list":[1]}}
```

**Comment by mihailsin** [comment]
issue already mentioned https://github.com/apidoc/apidoc/issues/1365
sorry for inconvenience
should just add spaces between semicolons and opening brackets in @apiSuccessExample sections
