### ISSUE TITLE
@apiParamExample - problem with parsing PHP source code

### ISSUE THREAD

**Issue by rkaktus** [apidoc/apidoc#1384]
# Describe the bug
If in @apiParamExample I give source code in PHP where there is an array inside, I get an error about unauthorized use of square brackets.
Is there any nice way to get around this error?

Example:
```
/**
 * @api {get} /utils/countdown/?token=:token Countdown timer
 * @apiVersion 1.0.0
 *
 * @apiParamExample {php} PHP-Example:
 *	$ch = curl_init();
 *	curl_setopt($ch, CURLOPT_URL, 'https://api.example.com/utils/countdown/?token=xyz');
 *	curl_setopt($ch, CURLOPT_USERAGENT, $_SERVER['HTTP_USER_AGENT']);
 *	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
 *	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
 *
 *	$result = curl_exec($ch);
 *	$result = json_decode($result, true);
 *
 *	if (empty($result['data']) or curl_getinfo($ch, CURLINFO_HTTP_CODE) != 200) {
 *		//tutaj obsługa błędu
 *	}
 *
 *	curl_close($ch);
 *
 */
```

Response:
warn: The use of square brackets for object properties is deprecated. Please use dot notation instead: "@apiParamExample {php} PHP-Example: ...

# Information

- Version of apidoc: 1.0.2
- Operating system (e.g. GNU+Linux/MacOS/Windows): Debian
- Node version: v12.22.12

**Comment by NicolasCARPi** [comment]
I would classify this as a bug, it shouldn't warn for stuff found in examples.

**Comment by rkaktus** [comment]
Than you.

The same problem occurs in @apiSuccessExample

It seems that it is enough to exclude these two elements from checking the condition in the parser.js file on line 205 and everything returns to normal.

**Comment by NicolasCARPi** [comment]
Feel free to submit a PR then!

**Comment by sl-ffx** [comment]
Just upgraded to version 1.0.3 but still get warnings when square brackets in @apiQuery or @apiDeprecated. I'm using the [json:api specification](https://jsonapi.org/)

/**
 * @api {get} /articles
 * @apiVersion 1.0.0
 *
 * @apiQuery {Number} page[limit]
 * @apiQuery {Number} page[offset]
 * @apiQuery {String} filter[title]
 * 
 * @apiDeprecated {String} filter[author]
 **/

**Comment by esaracco** [comment]
So why not just following the advice and using dot notation?

**Comment by sl-ffx** [comment]
Because there is a big difference between `/articles?page[limit]=10` and `/articles?page.limit=10`.

**Comment by rkaktus** [comment]
It should also be remembered that errors occur in other sections, such as @apiParamExample or @apiSuccessExample where you can't just skip square brackets.

I skipped this error by adding a condition `!["apiparamexample", "apisuccessexample"].includes(element.name) &&` but it's not a perfect solution.

```
(...)
else if (!["apiparamexample", "apisuccessexample"].includes(element.name) && element.source.match(/[^\s]\[[^\]]/)) {
   app.log.warn(`The use of square brackets for object properties is deprecated. Please use dot notation instead: "${element.source}"`);
} else {
(...)
```
