### ISSUE TITLE
apidoc square brackets warning

### ISSUE THREAD

**Issue by sl-ffx** [apidoc/apidoc#1385]
# Describe the bug
While generating apidoc (npm run apidoc)
a warning in console appears even if the brackets are in the value part of the json:
`warn: The use of square brackets for object properties is deprecated. Please use dot notation instead: "@apiSuccessExample {json} Success-Response:`

# Steps to reproduce
1. create a new file
```
/**
 * @apiSuccessExample {json} Success-Response:
 * {
 *   "data": {
 *     "url": "http://test.app/items?page[limit]=10"
 *   }
 * }
**/
```

2. run apidoc
`npx apidoc -i apidoctest`

# Information

- Version of apidoc: 1.0.2
- Operating system (e.g. GNU+Linux/MacOS/Windows): MacOS
- Node version: 18.13.0
- replacing "page[limit]" with "page.limit" prevents the warning but the value is no longer correct/the same
- I expect no warnings for using brackets in the value parts of a JSON

**Comment by NicolasCARPi** [comment]
#1384

**Comment by gayathma** [comment]
@NicolasCARPi any update on this?
I get the same warning for query parameters as well.

`warn: The use of square brackets for object properties is deprecated. Please use dot notation instead: "@apiQuery {String} [filter[code]] Filter by code"`

**Comment by NicolasCARPi** [comment]
@gayathma 1.0.3 just released with a fix.

**Comment by gayathma** [comment]
@NicolasCARPi [the issue](https://github.com/apidoc/apidoc/issues/1385#issuecomment-1571665830) still exists with  `@apiQuery` parameter

**Comment by iamnena** [comment]
@gayathma just discovered how to solve this, just add a space before [.
```
@apiBody {String {8...32}= [a-zA-Z0-9-_]} bizId
@apiBody {Number} [threshold] range [0,100]
@apiDescription see [detail](#api-detail)
```

**Comment by jgxvx** [comment]
Still seeing this behaviour in `1.2.0` and using the workaround of adding a whitespace before the opening bracket.
