### ISSUE TITLE
Issue generating js bundle with grunt

### ISSUE THREAD

**Issue by NicolasCARPi** [apidoc/apidoc#1393]
@NicolasCARPi I installed `apidoc` from NPM globally (v1.0.2). When running `apidoc -i src/routes/ -o docs/api/` it works!??

So the issue is definitely from the grunt package, you forgot about... I'm using `"grunt-apidoc": "^0.11.0"`.... Which is the latest version: https://www.npmjs.com/package/grunt-apidoc?activeTab=versions (7 years old!).

My gruntfile config for `apidoc`:

```js
    apidoc: {
      myapp: {
        src: './src/routes/',
        dest: 'docs/api',
        options: {
          debug: true
        }
      }
    }
```

That being said, I do think yarn installed the latest apidoc command:

![image](https://github.com/apidoc/apidoc/assets/628926/b7ca1b89-ab0e-4ca2-b32e-4dbe9fb982d6)

_Originally posted by @melroy89 in https://github.com/apidoc/apidoc/issues/1043#issuecomment-1570972828_

**Comment by NicolasCARPi** [comment]
So I can reproduce the issue. It seems webpack is not generating the js files, but there are no error messages.

This line: https://github.com/apidoc/apidoc/blob/c7905d2b27d70142f5f3e1239779719f79705dd8/lib/writer.js#L117 seems like it's not running. Doing a console.log of err or stats objects produces nothing.

It might be an easy fix once we get an error message, but I didn't manage to get one so far, so any help would be appreciated.

**Comment by melroy89** [comment]
Maybe first try to upgrade to the latest webpack npm package (v5.86 instead of v5.64.2). And also upgrade webpack-cli to v5.1.1.

**Comment by melroy89** [comment]
After that, I would implement the following for catching errors: https://webpack.js.org/api/node/#run

Currently you are missing `compiler.close()` error catching for sure..

```js
const compiler = webpack({
  // ...
});

compiler.run((err, stats) => {
  // ...

  compiler.close((closeErr) => {
    // ...
  });
});
```

The docs also mention:

> Don't forget to close the compiler, so that low-priority work (like persistent caching) have the opportunity to complete.

Maybe grunt exists too soon now??

**Comment by NicolasCARPi** [comment]
> Maybe first try to upgrade to the latest webpack npm package (v5.86 instead of v5.64.2). And also upgrade webpack-cli to v5.1.1.

I did my test after a complete npm upgrade, to get the latest apidoc, and webpack-cli is not used in this case. Also, the grunt-apidoc only has one dependency which is apidoc, and we know it's working with the current locked dependencies.

> Currently you are missing compiler.close() error catching for sure..

Yeah, tried that too, no diff.

> using the toString() method on the Stats object?

Tried it too, but adding a log just after the run call doesn't output anything! (see previous message).

**Comment by melroy89** [comment]
In which branch? I can't see the changes at all..

**Comment by melroy89** [comment]
You also don't catch errors here: https://github.com/apidoc/apidoc/blob/c7905d2b27d70142f5f3e1239779719f79705dd8/lib/index.js#L93. 

Also since you are using try / catch code in your [`createDoc()`](https://github.com/apidoc/apidoc/blob/c7905d2b27d70142f5f3e1239779719f79705dd8/lib/index.js#LL36C10-L36C19) you are basically executing code from top to bottom (thus synchronous code, line by line). Where as you methods are running promises. 

So you are creating and returning a new Promise in JS (`new Promise`) for some reason.. But you execute them in a synchronous way, most likely causing the `createDoc` method to finish, while the promises isn't finished yet.

The easier way is I think to use `await` either in when calling `runWebpack`. Or when looking at your current code, you might want to add `await` before the [`writer.write()` call in index.js](https://github.com/apidoc/apidoc/blob/c7905d2b27d70142f5f3e1239779719f79705dd8/lib/index.js#LL93C5-L93C19). 

so your code would be like:

`await writer.write();`

Or if you want to get the resolve object you can use:

`const result = await writer.write();`

Errors are then automatically catched then when using `await` with your existing try/catch code. The `app.log.verbose('All done :)')` can be added to the end of the `try {}` block.

**Comment by NicolasCARPi** [comment]
I tried a few more things, but still don't manage to make webpack run. Tried without compiler stuff, it seems it doesn't even go in the "build" step:

~~~javascript
webpack(webpackConfig, (err, stats) => {
  // it doesn't seems to go in there
  if (err || stats.hasErrors()) {
  }
~~~

So feel free to propose a PR if you manage to fix this.

**Comment by melroy89** [comment]
Well, too bad. I think I will migrate away from grunt. It seems to get used less and less.

**Comment by NicolasCARPi** [comment]
It does. In fact, I hardly see the point of it anymore, you can have scripts an packages.json, and `grunt-apidoc` doesn't really add value. Maybe the repo should be archived...

Grunt seems to be a relic of a time where bundlers didn't exist.

from [this reddit post](https://www.reddit.com/r/webdev/comments/kz2ew2/can_someone_please_explain_the_differences/)

> When gulp and grunt were created NPM wasn’t the standard way to install JS packages. There was also bower, and it was still common to just copy paste things in as well. Gulp and Grunt provided some structure in a more chaotic front end ecosystem. Things have changed a bit since then.

> Simple task running can often be handled by defining npm tasks in your package.json. You can run tests and other scripts that way without routing them through gulp and grunt. While you could still use these old taskrunners for building/bundling, some of the paradigms have changed. Typically these old taskrunners were global installs. These days our bundler scripts are NPM dependencies which helps keep things consistent across environments.

**Comment by NicolasCARPi** [comment]
@rottmann I suggest archiving the grunt-apidoc repository, what do you think? Life's too short to maintain outdated tools.

**Comment by melroy89** [comment]
Indeed. I would personally also archive this repo. Rip grunt.

**Comment by rottmann** [comment]
@NicolasCARPi @melroy89 Yes we can archive it, i think the time for grunt is over. Personally i used it last time around 6 years.
For smaller projects i use [scripty](https://www.npmjs.com/package/scripty9) which is easer than grunt and simple scripts.

**Comment by melroy89** [comment]
Yea indeed, I was using npm anyways now. So I migrated towards npm scripts. No grunt required anymore.
