### ISSUE TITLE
General questions: non-REST documentation & embed apidoc in existing documentation

### ISSUE THREAD

**Issue by orionseye** [apidoc/apidoc#1399]
I love this approach you have here :)
Two questions i haven't found here, because i am looking for a solution to document a quite old API

a) can apidoc be used for API documentation other than OpenAPI specs and/or non-REST formats, like HTTPS-POST request (key/value pairs)? e.g. mid=12345&aid=12345&portalid=1234567&key=a116ca816e9a312f27c57c2b96ddd319&request=authorization&mode=test

b) can apidoc be embedded in existing documentation pages?

**Comment by NicolasCARPi** [comment]
Hello,

a) I guess... POST is REST!

b) Nothing is stopping you from doing this.
