### ISSUE TITLE
apidocs recognizes apidoc.json, but doesn't parse it properly

### ISSUE THREAD

**Issue by Donvickins** [apidoc/apidoc#1424]
# Describe the bug

`apidocs` recognizes `apidoc.json` on my project root directory, but doesn't return the desired output.

# Steps to reproduce
This is my `apidoc.json` file

```
{
  "name": "backend Docs",
  "version": "0.1.0",
  "title": "backend API",
  "description": "Documentation of endpoints for backend API",
  "sampleuUrl": "http://localhost:4000"
}
```

This is my api
```
   /**
    @api {POST} /api/admin/auth/login Admin login
    @apiName adminLogin
    @apiGroup Admin Endpoints
    @apiVersion 0.1.0
   
    @apiSampleRequest
   
    @apiBody {String} phone=+12345678901 User's phone number.
    @apiBody {String} email=johndoe@abc.com User's email address.
    @apiBody {String} password=Johndoe123 User's password.
   
    @apiSuccess {Json} Object This returns a HTTP success status
    @apiSuccessExample Success-Response:
    HTTP/1.1 200 OK
    {
      "statusCode": 200,
      "statusText": "LOGIN_SUCCESSFUL",
     }
   */
```

This produced this error:

```
error: Empty parser result. {"Block":1,"Element":"@apiSampleRequest","File":"./controllers/admin/authentication/login.controller.js","Source":"@apiSampleRequest\n"}
error: Error during source code parsing!
[error] apidoc encountered an error during documentation generation!
```

# Information

- Version of apidoc: 1.0.3
- Operating system (e.g. GNU+Linux/MacOS/Windows): Linux
- Node version: 16.20
- Browser (e.g. firefox, chrome): chrome

Note: I have used the -c flag, didn't work.

**Comment by NicolasCARPi** [comment]
Hello.

First you have a typo in `sampleUrl` of your apidoc.json. Second you should remove the `@apiSampleRequest` with no value in the code.

**Comment by Donvickins** [comment]
Thank you so much @NicolasCARPi, I corrected the typo and deleted  `@apiSampleRequest`. I thought I had to specify `@apiSampleRequest`. Thanks once again.
