### ISSUE TITLE
Unexpected token '<' for Ubuntu

### ISSUE THREAD

**Issue by Vubni** [apidoc/apidoc#1437]
Hello, I have a problem - I was working with the library on windows and everything was fine, but when I switched to a vps with an ubuntu system, an error appears at startup: `Uncaught SyntaxError: Unexpected token '<' (at main.bundle.js?v=1699460831378:1:1)`. Maybe it's not a mistake, but I stepped somewhere, I'm new to web programming

**Comment by NicolasCARPi** [comment]
You're probably not loading the bundle correctly, and the webserver is sending HTML back (such as a 404 default page), which contains HTML, and thus cannot be interpreted as JS.
