### ISSUE TITLE
Change order of functions in generated api doc

### ISSUE THREAD

**Issue by dsc8x** [apidoc/apidoc#15]
Would it be possible, to display the api functions in the same order as they appear in the source code? That would be neat! :-)

**Comment by dvdnhm** [comment]
Cant we have a numeric "position in the group" parameter?

ie: 
* @apiName eventSearchFields
* @apiGroup Events
* @apiPosition 1
..
..
..
* @apiName eventSearch
* @apiGroup Events
* @apiPosition 2
..
..
..

**Comment by rcrooks** [comment]
Personally, I'd rather "order" in json package allowed you to order both groups and apis - I think that's less prone to breakage than hardcoding numerical positions. But either would be welcome.

**Comment by heisian** [comment]
This is what it says in the docs:

> order	A list of api-names / group-names for ordering the output. Not defined names are automatically displayed last.

But ordering by group name doesn't work.

**Comment by jomy-joseph** [comment]
I made this by changing main.js

line
 // sort by name ASC
        titles.sort();

replace with

	var collator = new Intl.Collator(undefined, {numeric: true, sensitivity: 'base'});
        titles.sort(collator.compare);

So ordering is working inside groups

**Comment by fedecaccia** [comment]
It seems that the fix only orders groups... how to order the enpoints inside a group?
