### ISSUE TITLE
@apiGroup sorting

### ISSUE THREAD

**Issue by david-ts** [apidoc/apidoc#158]
Hi,

As an enhancement, can @apiGroup take one additional parameter use for internal sorting on the navigation menu?  For example, I would like to have the option to display the APIs related to "User" group show on top of the navigation menu without renaming the "User" group to something else.

So I was thinking maybe @apiGroup name groupPriority where groupPriority is a number.
Then for navigation menu, we can sort first by groupPriority then by name?

**Comment by xuanskyer** [comment]
This feature isn't implemented yet?
