### ISSUE TITLE
@apiDescription not correctly parsed

### ISSUE THREAD

**Issue by butsjoh** [apidoc/apidoc#160]
Hey,

Discovered an issue with parsing the @apiDescription when you include a code block in it. The following:

###
@api {post} /resources Create resource(s)
@apiGroup Resources
@apiVersion 0.1.0
@apiDescription

Some text before

```json
{
   "meta":{
      "story":{
         "story_text":"Look at the picture i uploaded"
      }
   }
}
 ```

Some text after

###

Generates:

![screen shot 2014-11-26 at 15 56 16](https://cloud.githubusercontent.com/assets/96848/5203278/8e5322ca-7585-11e4-9d35-699d79ec069e.png)

As you can see the code is all put on one line. If you look at the generated api_data.json file it does not contain any newlines. I think the parsing somehow goes wrong.

**Comment by rajesh-smartwebtech** [comment]
@rottmann  Can i use new line using <br> in apiDescription

**Comment by rottmann** [comment]
Yes: https://apidocjs.com/#param-api-description
