### ISSUE TITLE
Special char doesn't show in @apiGroup

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [apidoc/apidoc#163]
Hi, I'm using apidoc.js to write an api documentation in brazilian portuguese language, but when I use chars like "ç", "ã", "é" in a @apiGroup name, the layout hide this chars.

For example, if I set "@apiGroup Autenticação", the layout will show "AUTENTICA O" instead "AUTENTICAÇÃO".

**Comment by neko2891** [comment]
vi /usr/local/lib/node_modules/apidoc/node_modules/apidoc-core/lib/workers/api_group.js 

Found about this string on line 83
`group = group.replace(/[^\w]/g, '_');`
change into
`//group = group.replace(/[^\w]/g, '_');`
`group = group;`
rebuild api_data.js

then you can use special chars 

Forgive me, my English is very bad
