### ISSUE TITLE
Custom order not working

### ISSUE THREAD

**Issue by saitheexplorer** [apidoc/apidoc#174]
package.json:

```
"apidoc": {
  "order": [
    "GetUser",
    "GetEmail",
    "GetWidget"
  ]
}
```

Documentation shows up in alphabetical order of `@apiDescription` field. Is the reordering supposed to be happening in `lib/apidoc.js` `#createOutputFiles`?

**Comment by heisian** [comment]
why does it say this in the docs?

> order	A list of api-names / group-names for ordering the output. Not defined names are automatically displayed last.
