### ISSUE TITLE
Ability to link to another @api

### ISSUE THREAD

**Issue by simplenotezy** [apidoc/apidoc#178]
I miss a feature to hyperlink to another API in the documentation. 

Something like:
@apiDescription A link to [link gotoapi="GetUserInfo" text="another api request"] or similar.

**Comment by goosefraba** [comment]
Hello - We definitely need this feature as we can use it to document return types (DTOs).

Even more, it would be great to "link" DTO models in the resulting HTML-page.
This, probably requires to document a DTO class (e.g. java) and link it somehow to the apidoc part of the method.
Is there any chance to get this feature? :)

**Comment by vlapo** [comment]
+1

**Comment by vherilier** [comment]
+1

**Comment by samherrmann** [comment]
+1

**Comment by Benew** [comment]
+1 Must have

**Comment by iolo** [comment]
i'm using:
`@apiDescription see <a href="#api-GroupName-ApiName">....blah blah...</a>`
and it works well with default template. ;)

**Comment by Benew** [comment]
Hey I was just about to post the same comment. Awesome!

**Comment by huseyinkozan** [comment]
How about this:
`[GetProperty](#api-Group-GetProperty)`

**Comment by Tinixi** [comment]
+1

**Comment by ishan28mkip** [comment]
+1

**Comment by TheDeathStreaker** [comment]
+1

**Comment by amertis** [comment]
+1

**Comment by jscubida** [comment]
+1

**Comment by amertis** [comment]
+1

**Comment by alexandruirimiea** [comment]
+1

**Comment by mikec** [comment]
+1

**Comment by iszlailorand** [comment]
+1

**Comment by oafifi** [comment]
+1

**Comment by mindojo-victor** [comment]
+1

**Comment by LukaszEnegive** [comment]
Hello there. 
What's the status of this request?
It was posted over 3 years ago.

**Comment by nitan84** [comment]
+1

**Comment by Lopo** [comment]
+1

**Comment by gopal-augment** [comment]
hi.. I want link to external url.. Cause I have same api doc for two project.. How can i use same apidoc for both

**Comment by geoshar** [comment]
+

**Comment by gsteimer** [comment]
Seems like (#GroupName:ApiName) works with `@apiDeprecated`.  Is there a reason it can't work with `@apiDescription` and `@apiParam` as well?

**Comment by 8zler** [comment]
Just put `<a href="#IdYouWantToGoLookAtTheUrlBarToFindIt">go here instead</a>` inside a `@apiDescription` tag and it will works !

Hope this help

**Comment by NicolasCARPi** [comment]
Add an html link works and nobody has proposed any code for that feature so => close.

**Comment by Ajuriaa** [comment]
Is there a way to link the Type in @apiSuccess to another api??

something like:
`@apiSuccess {[Driver](#api-Interfaces-ObjectDriver)} driver The requested driver.`
Driver
that used to work it seems (#278 in [here](https://github.com/apidoc/apidoc/issues/278#issuecomment-266364448)), but now it returns `The use of square brackets for object properties is deprecated. Please use dot notation instead` and it does not render out.
