### ISSUE TITLE
Raw JSON request-body support

### ISSUE THREAD

**Issue by iameugenejo** [apidoc/apidoc#179]
Current template doesn't allow sending Boolean, multi-depth Object, Arrays or even Numbers. These types are all converted to String when sent as a JSON.

Either those should be supported through dynamic UI, or sending Raw JSON request-body should be supported.

The clients in the template are useless for more than half of my API endpoints that takes schema with property types other than String.

**Comment by fedefarina** [comment]
+1

**Comment by hussaintamboli** [comment]
+1

**Comment by leoliaolei** [comment]
+1

**Comment by areguig** [comment]
+1

**Comment by hirako2000** [comment]
+1

**Comment by fabiobsantos92** [comment]
+1
The usage of API is to simple, This limitation not allow tests using complex objects on POST/PUT requests,

**Comment by pasaranax** [comment]
There is simple way is to add a parameter `"json_body": true` in apidoc.json, that says need to build body as json and change `Content-Type` header to `application/json`. May anybody do that?

**Comment by ezzygemini** [comment]
+1

**Comment by hussaintamboli** [comment]
@pasaranax 

I have been looking for json requests from a long time. I tried `json_body` but it's not working. I still don't see `application/json` as `Content-Type`.

Sample docstring for my api

    """
    @api {post} /uservalidation/ Create a user
    @apiVersion 0.1.0
    @apiName addUser
    @apiGroup User

    @apiParam {String} firstname First Name
    @apiParam {String} [lastname] Last Name
    @apiParam {Number} [age=18] Age

    @apiSuccess {String} id Id of the User

    @apiUse UserRegistrationError
    """

**Comment by NicolasCARPi** [comment]
Latest version should do better.
