### ISSUE TITLE
apidoc complains about missing apidoc.json 

### ISSUE THREAD

**Issue by ivan-kleshnin** [apidoc/apidoc#183]
I created "apidoc" block in vanilla node.js `package.json` file. Information is accessible to **apidoc** and everything is ok except that CLI still whines about missing apidoc.json
```
warn: Please create an apidoc.json.
```

**Comment by danger89** [comment]
Example file:
https://github.com/apidoc/apidoc/blob/master/example/apidoc.json

**Comment by BertCatsburg** [comment]
Had the same problem. And the solution was that I had an empty apidoc.json while all settings were in package.json. After removing the empty apidoc.json, everything worked.
