### ISSUE TITLE
apidoc generation don't work, if phpdoc comments are used

### ISSUE THREAD

**Issue by ErdnussFlipS** [apidoc/apidoc#186]
Please provide support for coexistence with phpdoc comments
phpdoc comment '@var' generates error

Edit: Error message
apidoc -f .php -i ./src/ -o ./docs/api
warn: parser plugin 'var' not found.
error: Cannot call method 'charAt' of undefined

**Comment by rottmann** [comment]
apiDoc can coexists with other libs.

This error is from an other problem.
Can you add `--debug` param and post the error again?

**Comment by ErdnussFlipS** [comment]
ok.

apidoc -f .php -i ./src/ -o ./docs/api --debug
debug: package.json not found!
verbose: parse file: src\Classes\Response.php

You can find the file Response.php here: https://github.com/TouchTheBeat/Backend/blob/dev/src/Classes/Response.php

**Comment by rottmann** [comment]
Did you use an older version of apidoc?

view versions with
`sudo npm list -g --depth=0`

**Comment by ErdnussFlipS** [comment]
Yes, apidoc@0.12.0

When I run apidoc from console i get follwing error:
[...]
debug: inspect file: src\Struct\Struct.php
debug: size: 164
debug: count blocks: 1
debug: count elements in block 0: 0
error: Cannot call method 'charAt' of undefined
debug: TypeError: Cannot call method 'charAt' of undefined
    at ttb-backend\tools\node_modules\apidoc\node_modules\apidoc-core\lib\workers\api_name.js:27:33
    at Array.forEach (native)
    at ttb-backend\tools\node_modules\apidoc\node_modules\apidoc-core\lib\workers\api_name.js:15:20
    at Array.forEach (native)
    at Object.postProcess (ttb-backend\tools\node_modules\apidoc\node_modules\apidoc-core\lib\workers\api_name.js:14:17)
    at ttb\ttb-backend\tools\node_modules\apidoc\node_modules\apidoc-core\lib\worker.js:95:20
    at forOwn (ttb-backend\tools\node_modules\apidoc\node_modules\lodash\dist\lodash.js:2105:15)
    at Function.forEach (ttb-backend\tools\node_modules\apidoc\node_modules\lodash\dist\lodash.js:3302:9)
    at Worker.process (ttb-backend\tools\node_modules\apidoc\node_modules\apidoc-core\lib\worker.js:92:7)
    at Object.parse (ttb-backend\tools\node_modules\apidoc\node_modules\apidoc-core\lib\index.js:196:20)

**Comment by rottmann** [comment]
Did you set a type, e.g. "get"?
`@api {get} /path Some title`

**Comment by ErdnussFlipS** [comment]
In which file? Struct.php? There is no api comment.
Struct.php: https://github.com/TouchTheBeat/Backend/blob/dev/src/Struct/Struct.php

**Comment by rottmann** [comment]
It has nothing todo with your Struct.php. Struct.php is only the last file the parser parses.

To view in which file the typ is missing try https://github.com/apidoc/apidoc/issues/170#issuecomment-65217518

**Comment by ErdnussFlipS** [comment]
I tried #170 but UserService.php (https://github.com/TouchTheBeat/Backend/blob/dev/src/Service/UserService.php) should be fine.
```
[ { global: {},
    local:
     { type: 'get',
       url: '/user',
       title: 'Requests user',
       description: '<p>Requests user data of given user id</p> ',
       version: '1.0.0',
       name: 'GetUser',
       group: 'User',
       success: [Object],
       filename: 'src/Service/UserService.php',
       groupTitle: 'User' },
    index: 3,
    version: '1.0.0' },
  { global: {},
    local:
     { type: 'post',
       url: '/user',
       title: 'Create new user',
       description: '<p>Creates a new user</p> ',
       version: '1.0.0',
       name: 'CreateNewUser',
       group: 'User',
       parameter: [Object],
       error: [Object],
       success: [Object],
       filename: 'src/Service/UserService.php',
       groupTitle: 'User' },
    index: 4,
    version: '1.0.0' },
  { global: {},
    local:
     { group: 'ttb_backend_src_Service_UserService_php',
       groupTitle: 'ttb_backend_src_Service_UserService_php' } },
  { global: {},
    local:
     { type: 'get',
       url: '/user/:id/levels',
       title: 'Request user levels',
       description: '<p>Request all levels of given user id</p> ',
       version: '1.0.0',
       name: 'GetUserLevels',
       group: 'User',
       success: [Object],
       filename: 'src/Service/UserService.php',
       groupTitle: 'User' },
    index: 6,
    version: '1.0.0' },
  { global: {},
    local:
     { type: 'delete',
       url: '/user',
       title: 'Deletes current user',
       description: '<p>Deletes current signed in user</p> ',
       version: '1.0.0',
       name: 'DeleteCurrentUser',
       group: 'User',
       success: [Object],
       filename: 'src/Service/UserService.php',
       groupTitle: 'User' },
    index: 7,
    version: '1.0.0' },
  { global: {},
    local:
     { type: 'get',
       url: '/user/draft/:id',
       title: 'Request draft',
       description: '<p>Request a specific draft</p> ',
       version: '1.0.0',
       name: 'GetDraft',
       group: 'User',
       parameter: [Object],
       success: [Object],
       filename: 'src/Service/UserService.php',
       groupTitle: 'User' },
    index: 8,
    version: '1.0.0' },
  { global: {},
    local:
     { type: 'post',
       url: '/user/draft',
       title: 'Create draft',
       description: '<p>Creates a new draft</p> ',
       version: '1.0.0',
       name: 'CreateDraft',
       group: 'User',
       filename: 'src/Service/UserService.php',
       groupTitle: 'User' },
    index: 10,
    version: '1.0.0' },
  { global: {},
    local:
     { type: 'put',
       url: '/user/draft',
       title: 'Update draft',
       description: '<p>Updates an exiting draft</p> ',
       version: '1.0.0',
       name: 'UpdateDraft',
       group: 'User',
       filename: 'src/Service/UserService.php',
       groupTitle: 'User' },
    index: 11,
    version: '1.0.0' },
  { global: {},
    local:
     { type: 'get',
       url: '/user/:id/drafts',
       title: 'Request user drafts',
       description: '<p>Request all drafts of given user id</p> ',
       version: '1.0.0',
       name: 'GetUserDrafts',
       group: 'User',
       success: [Object],
       filename: 'src/Service/UserService.php',
       groupTitle: 'User' },
    index: 12,
    version: '1.0.0' } ]
{ global: {},
  local:
   { group: 'ttb_backend_src_Service_UserService_php',
     groupTitle: 'ttb_backend_src_Service_UserService_php' } }
error: Cannot call method 'charAt' of undefined
debug: TypeError: Cannot call method 'charAt' of undefined
    at ttb-backend\tools\node_modules\apidoc\node_modules\apidoc-core\lib\workers\api_name.js:29:33
    at Array.forEach (native)
    at ttb-backend\tools\node_modules\apidoc\node_modules\apidoc-core\lib\workers\api_name.js:15:20
    at Array.forEach (native)
    at Object.postProcess (ttb-backend\tools\node_modules\apidoc\node_modules\apidoc-core\lib\workers\api_name.js:14:17)
    at ttb-backend\tools\node_modules\apidoc\node_modules\apidoc-core\lib\worker.js:95:20
    at forOwn (ttb-backend\tools\node_modules\apidoc\node_modules\lodash\dist\lodash.js:2105:15)
    at Function.forEach (ttb-backend\tools\node_modules\apidoc\node_modules\lodash\dist\lodash.js:3302:9)
    at Worker.process (ttb-backend\tools\node_modules\apidoc\node_modules\apidoc-core\lib\worker.js:92:7)
    at Object.parse (ttb-backend\tools\node_modules\apidoc\node_modules\apidoc-core\lib\index.js:196:20)
```

**Comment by rottmann** [comment]
Thanks i see now the bugs.
Fixed a related bug that cause the error in version 0.12.1.

One thing is not changed: the current version parses comment blocks with mulit-lines, you use one liner with multi column comments e.g. `/** @var string */`.
This throw warnings, but parser should now work. I will change this behavior later, so that one liner are ignored.

**Comment by ErdnussFlipS** [comment]
Thanks. In 0.12.1 it now works for me too.
