### ISSUE TITLE
Group Name is used instead of @apiName

### ISSUE THREAD

**Issue by vkosachev** [apidoc/apidoc#187]
Hi, downloaded the latest version of your awesome tool, and I seem to find a bug.

I have defined a group:
```PHP
	/**
	 * @apiDefine OpenMethods Open endpoints
	 *
	 * All these endpoints **do not** require the **oAuth** token to be present in the header or URI.
	 *
	 */
```
And then I use this group name when describing the api, and the name of this group is doubled as the name of the api (see screenshot) http://screencloud.net/v/3ZdS.

My api method is described like this: 
```PHP
/**
 * @api {get} /api/video/:token
 * @apiVersion 0.4.0
 * @apiGroup OpenMethods
 * @apiName GetVideo
 * @apiParam {String} token The UUID of the video.
 *
 * @apiExample Example usage:
 * curl http://localhost/api/video/2d9ebc00-d9b3-494c-ace0-93ed3098f7f7
 *
 * @apiSuccessExample Success-Response:
 *     HTTP/1.1 200 OK
 *     {
 *      DIRECT VIDEO FILE OUTPUT
 *     }
 * @apiErrorExample Error-Response:
 *     HTTP/1.1 400 Bad Request
 *     {
 *       "error": true,
 *       "dataset": "File does not exist"
 *     }
 */
```

If I remove the @apiGroup tag I do not see a separate method called "GetVideo", I see the route to my project as the name (something like **_var_www_myproject_myfile_php**).

Thanks.

**Comment by rottmann** [comment]
The names should be unique. I will add some more warnings/errors for this case.

**Comment by vkosachev** [comment]
Hi @rottmann , thanks for your response. Could you give more explanations on this ? Thanks

**Comment by rottmann** [comment]
Sorry, i misunderstood your post.

The double view ist correct, the groupname is in the header of a group and a prefix for each api-block.

Add a title to see what i mean:
```
 * @api {get} /api/video/:token Add a Title here
```

*I think i will remove the prefix (i am not sure why i insert it as prefix, have to prove it).*

**Comment by vkosachev** [comment]
Thank you for support, I will try this as soon as possible and postback if it solves my problem.

**Comment by vkosachev** [comment]
Hi, just checked that, yes. That worked properly. You were right about the prefixing, though it looks a little bit strange. Thank you for your support.

**Comment by luisdemarchi** [comment]
The name of the call no longer exists = / It was disorganized.
