### ISSUE TITLE
Fix the grammar in the "Highlight" paragraph

### ISSUE THREAD

**Issue by dandv** [apidoc/apidoc#188]
I've just learned about apidoc a few seconds ago. First impression on the homepage:

> Highlight is an API history, with that various API version levels can be compared. So you, or a frontend developer, can retrace what changed in the API since the last version.

Not clear what that means. is "Highlight" the name of a library? Or is there a typo hear, meaning that apidoc can highlight changes?

**Comment by rottmann** [comment]
highlight in the meaning of "special feature". apidoc highlight changes when you compare your api to an other version.
