### ISSUE TITLE
Line endings, LF vs CRLF

### ISSUE THREAD

**Issue by gotmikhail** [apidoc/apidoc#190]
I'm trying to figure out why I'm getting CRLF (DOS) line endings generated. I'm using fedora and centos, I've done a global npm install on both, apidoc is fully up to date, but as said I'm having this happen on two different linux systems.

Also, my git settings are set to change CRLF line endings to LF, so at least I'm keeping them out of the repo, but each time I run apidoc I get a change for every single generated line in the files.

Is this a setting somewhere, or is there an option to override this?

To confirm again, I'm using linux, not windows.

**Comment by rottmann** [comment]
Yes the line endings in the data files are replaced.
Will revise this.

**Comment by rottmann** [comment]
Fixed in 0.13.0 (coming soon).
Autodetection is integrated and correct line-ending will be set.

To force a line ending you can manually set it with `apidoc --line-ending=CRLF` (CRLF, CR, LF).
