### ISSUE TITLE
@apiUse usage in @apiDefine block

### ISSUE THREAD

**Issue by DWand** [apidoc/apidoc#194]
Hello.
I'm facing a little problem: some of my doc blocks have became about 2-3 times bigger than a code of the corresponding API endpoint. I've already moved general parts (such as common errors) to separate `@apiDefine` blocks but it doesn't seem to help a lot.

I have an idea to move some other parts to separate files and use them in main files. It could look like this:
```php
// UsersController.php

/**
 * @api {put} /users/{id} Edit a user
 * @apiName UpdateUser
 * @apiGroup Users
 * @apiVersion 1.0.0
 * @apiPermission admin
 *
 * @apiDescription Updates the specified user
 *
 * @apiUse ParamsURL
 * @apiParam (ParamsURL) {Integer} id An identificator of the user
 *
 * @apiUse ParamsPUT
 * @apiUse Params_User_Update
 *
 * @apiUse Response204
 *
 * @apiUse Error400_User_Update
 * @apiUse Error401
 * @apiUse Error403
 * @apiUse Error404
 * @apiUse Error409
 * @apiUse Error422_User
 * @apiUse Error500_User_Update
 */
```

```php
// UsersController.partials.php

/**
 * @apiDefine Params_User_Update
 * @apiParam (ParamsPUT) {String} login A login of the user
 * @apiParam (ParamsPUT) {String} password A password of the user or empty in case
 *                                         the old password has not to be changed
 * @apiParam (ParamsPUT) {String} name A name of the user
 * @apiParam (ParamsPUT) {String} email An email of the user
 * @apiParam (ParamsPUT) {String} phone A phone number of the user
 */

/**
 * @apiDefine Error400_User_Update
 * @apiuse Error400
 * @apiError (Error400) {Integer} code A code of the error
 *  - 1 = the `id` parameter is missing
 *  - 2 = the `login` parameter is missing
 *  - 4 = the `password` parameter is missing
 *  - 8 = the `name` parameter is missing
 *  - 16 = the `email` parameter is missing
 *  - 32 = the `phone` parameter is missing
 * @apiErrorExample {json} 400 Error example
 * HTTP/1.1 400 Bad Request
 *
 * {
 *     "code" : 1,
 *     "message" : "The required parameter \"id\" is missing."
 * }
 */

/**
 * @apiDefine Error422_User
 * @apiUse Error422
 * @apiError (Error422) {Integer} code A code of the error
 *  - 1 = the `login` parameter is empty
 *  - 2 = the `password` parameter is empty
 *  - 4 = the `login` parameter is too short
 *  - 8 = the `login` parameter is too long
 *  - 16 = the `password` parameter is too short
 *  - 32 = the `email` parameter is too long
 *  - 64 = the `phone` parameter is too long
 *  - 128 = the `name` parameter is too long
 *  - 256 = the `email` parameter has an invalid format
 */

/**
 * @apiDefine Error500_User_Update
 * @apiUse Error500
 * @apiErrorExample {json} 500 Error example
 * HTTP/1.1 500 Internal Server Error
 *
 * {
 *     "code" : 1,
 *     "message" : "Unable to update the User."
 * }
 */
```

```php
// Error401.php

/**
 * @apiDefine Error401 The 401 Unauthorized error
 * @apiError (Error401) {Integer} code    A code of the error
 * @apiError (Error401) {String}  message A description of the error
 * @apiErrorExample {json} 401 Error example
 * HTTP/1.1 401 Unauthorized
 *
 * {
 *     "code" : 401,
 *     "message" : "The requested action requires authentication."
 * }
 */
```

And a bunch of files for other errors (Error403.php, Error404.php, Error409.php, ...)

But now it is impossible to use `@apiUse` tags in `@apiDefine` blocks, so it is impossible to use the approach from above. Can you suggest me something to solve this problem?

**Comment by rottmann** [comment]
Multi inheritance is not supported at the moment.
One reason why i reduced the complexity of the parameters and mark many as deprecated, now we can think about inheritance.

But i still think it is not a good idea for a documentation, it made it hard to read the source code.

TODO: add multi inheritance

**Comment by DWand** [comment]
Are there better ways to solve such kind of problems?

It's completely okay to keep docs with source code, but source files become harder to navigate and overall feelings are worse. I don't know how to express it correctly in English, but I feel myself more tired of work when a documentation block is about a whole screen or more. Maybe I do something wrong?

**Comment by rottmann** [comment]
Did you use an code editor that can open/close comment blocks ?

**Comment by DWand** [comment]
Yes. I understand what you mean. Thanks.

However, the initial issue is still relevant. There are some blocks which can be used in several endpoints. For example, I use 422 status code for validation errors. Validation rules are declared in a model, so they can be used in create, update and any other method which changes the model. But the 422 status code can be used in many endpoints. in terms of consistency all 422 responses have the same structure, but each of them has its own set of possible error codes.

So, it could be done for example like this:
@apiDefine Error422 (defines a name, a type and a structure of the response)
@apiDefine Error422_ModelName (defines all possible error codes for some model)
@api (defines some endpoint)

It could be either inheritance or aggregation. It might be also interesting to add a description to the existing elements. But I don't know how to implement this. For example:

```
/**
 * @apiDefine Error422 The 422 Unprocessable Entity error
 * @apiError (Error422) {Integer} code A code of the error
 * @apiError (Error422) {String} message A description of the error
 */

 /**
 * @apiDefine Error422_SomeModel
 * @apiUse Error422
 * -- list all possible error codes from this model --
 */
```

Here, a description of the `code` parameter of the `Error422` entity is common for any possible model. And the `Error422_SomeModel` entity defines error codes which are specific for `SomeModel`.

**Comment by rottmann** [comment]
Add it to todo list.
