### ISSUE TITLE
Optional params

### ISSUE THREAD

**Issue by 2naive** [apidoc/apidoc#195]
Hi,

Sorry, may be I didn't understand but I have following questions:
1. How may I mark API params as **optional** or **non-optional**?
2. Why I can not declare, for example, apiError and apiErrorExample comments **near** the code they are produced?

    /**
     * @apiVersion 0.1.0
     *
     * @api {get} /voice/send Send Voice message
     * @apiName SendVoice
     * @apiGroup Voice
     **/
    ...
    ...
    ...
    /**
     * @apiErrorExample {json} Unsupported parameter type
     *     HTTP/1.1 400 BAD REQUEST
     *     {
     *         error: 'Parameter (txt) must be integer',
     *         code: 2
     *     }
     *
     */
    if (req.param('txt') != parseInt(req.param('txt')) ) {
        res.status(400).json({error: 'Parameter (txt) must be integer', code: 2});
        return;
    }

3. If I have a method that may be called e.g. GET and also POST, how shall I comment this?
    
    @api {get, post} /voice/send Send Voice message

Thanks!

**Comment by rottmann** [comment]
1. A parameter can mark as optional with brackets `@apiParam {String}  [name] ....`
2. At the moment only a comment-block is parsed, but i set this on the todo list.

**Comment by 2naive** [comment]
1-2. Thank you!
3. Yep, I know, but in my case I have to allow people to use get&post. Client's requirement
