### ISSUE TITLE
Bad parameters passed with header "Content-Type": "application/x-www-form-urlencoded"

### ISSUE THREAD

**Issue by vherilier** [apidoc/apidoc#196]
Hi,

As I try to send a POST "sample request" with the header `"Content-Type": "application/x-www-form-urlencoded"`, required by my own REST API for an authentication method, non-URL parameters (username and password) are badly passed: debbuged request shows that this parameters are appearing in the body like `"{username: XXXX, password: YYYYY}": ""`.
When, in `send_sample_request.js`, the ajax request is sent, forced `contentType: "application/json"` and JSON stringified non-URL parameters, used for data property, are overriding my own requirements and do not pass well the required parameters.
Is there a way to escape this forced encoding or does the ajax request for the sample request receive an improvement that will deal with different header/contentType directives?

Thank you for your support.

--Vincent

**Comment by 2naive** [comment]
+1

**Comment by NicolasCARPi** [comment]
Please try with newer version.
