### ISSUE TITLE
resultant apidoc html has javascript errors and does not render

### ISSUE THREAD

**Issue by pives** [apidoc/apidoc#197]
updated to latest apidoc and npm.
when i run apidoc on a clean destination directory I get no errors in generation mode but i get an error in the resultant HTML. This error is preventing every call from showing (i think)
" Uncaught TypeError: Cannot read property 'split' of undefined"   --handlebars_helper.js?v=1421697594297:120 

 npm -v
1.3.6

node -v
v0.10.33

$ /usr/lib/node_modules/apidoc/bin/apidoc -i ./ -o ./doc -v
verbose: apidoc-generator name: apidoc
verbose: apidoc-generator version: 0.12.1
verbose: apidoc-core version: 0.3.1
verbose: apidoc-spec version: 0.2.0
verbose: run parser

**Comment by pives** [comment]
If only I had some context for what was going on in the resultant js, i'd fix it :(

**Comment by rottmann** [comment]
Can you send me the generated api_data.json?

**Comment by pives** [comment]
sure thing. I’ve been trying to figure out where the issue is all morning. :-) 

I deleted all my file down to these 3 blocks and it doesn’t generate the 3rd.  the php file included is what i’m genning from.  


..................................................
Phil Ives
Co-Founder
Rain - Clear Mobile Solutions <http://raineverywhere.com/>
pives@raineverywhere.com
215.479.2353
http://about.me/phil_ives <http://about.me/phil_ives>

**Comment by pives** [comment]
i updated my comment above. -Phil

**Comment by pives** [comment]
I'm still not able to generate docs. ( i have 0 errros on first run. ) but always get an error on second run if i dont' delete the docs folder. I'd really love to use this.. but i'm gonna have to use phpdoc or something if i can't get this working soon. happy to help debug.   Just nded a place to start.

how can i follow the parser output ?

**Comment by rottmann** [comment]
Try to add -e ./doc to exclude the doc from being parsed.

**Comment by pives** [comment]
right, but it's also the first time it parses my doc. IT doesn't render most of the docblocks. I have a newer version if you want to see it. I limited it to 3 blocks and it still fails. 

hit me on twitter phil_ives or email me your email to pives ----- raineverywhere dot C0m  and i can send you an example.

**Comment by rottmann** [comment]
The problem was the [`@apiName name`](http://apidocjs.com/#param-api-name) with spaces.

You write `@apiName Get all campaigns` or `@apiName Get single campaign`, apidoc merge it under the Name `Get`, so that different blocks are mixed together and caused the error.

Name them  `@apiName GetAllCampaigns` and `@apiName GetSingleCampaign`

I will add a check on the next version, so that a meaningful error / warning will be displayed.
