### ISSUE TITLE
Tooling: PhpStorm

### ISSUE THREAD

**Issue by lflaszlo** [apidoc/apidoc#198]
Hi everybody,

If anybody have already implement any ApiDoc's templates  in PhpStorm ?

Thanks per advance,

Have a nice day,

**Comment by liusongsen** [comment]
nice,I need to!!!

**Comment by liusongsen** [comment]
http://aaronsaray.com/blog/2015/05/19/documentation-tools-for-phpstorm/

**Comment by destroyerofbuilds** [comment]
With what @liusongsen posted, what needs to be done to close this item out? @lflaszlo

**Comment by lflaszlo** [comment]
Hi no, I'm thinking at a tool to implement documentation variables.
What @liusongsen posted it's to execute easily not to implement variables.

**Comment by liusongsen** [comment]
/**
     * @api {post} api=$MODULE$.$COTROLLER$.delete $MODULE$.$COTROLLER$.delete
     * @apiSampleRequest http://mguba.n8n8.cn/index.php?api=$MODULE$.$COTROLLER$.delete
     * @apiExample {curl} Example usage:
     *     curl -i http://mguba.n8n8.cn/index.php?api=$MODULE$.$COTROLLER$.delete
     * @apiVersion 1.0.0
     * @apiName $MODULE$.$COTROLLER$.delete
     * @apiGroup $MODULE$
     * @apiPermission none
     *
     * @apiDescription $COMMETS$
     * @apiParam {Number} id 参数描述
     * @apiUse MySuccess
     * @apiUse MyError
     *
     */
    public function delete(){
        $id =core::getInput("id");

        $result=array(); //todo please replace you code
        if ($result) {
            core::outPut(1, $result);
        } else {
            core::outPut(-1);
        }
    }

**Comment by liusongsen** [comment]
This is a Wo to do a template, my project has a set of such templates, such as: save/delete/getList/get...

**Comment by liusongsen** [comment]
![image](https://cloud.githubusercontent.com/assets/3146452/8840440/bc7a5de0-3113-11e5-8310-5e3483df6077.png)
This is some of the variables that are built into the system.

**Comment by liusongsen** [comment]
I think the problem can be shut down.
