### ISSUE TITLE
Ability to override URL for specific APIs

### ISSUE THREAD

**Issue by joelbowen** [apidoc/apidoc#201]
If there's not a way to do this I'd love this to make its way into a feature list.

In my use case the majority of my APIs reside behind a versioned URL like `https://example.com/api/v1/` so in order to not have to write `/api/v1/` every time I define an API I simply include it in my url definedin the `apidoc.json` config file.

A few of my endpoints however do not reside behind this particular structure, things like logins and such. It would be great to be able to override the default url with something like `@apiUrl`

**Comment by tureki** [comment]
I have also same problem :+1:

**Comment by rottmann** [comment]
You can use [@apiSampleRequest](http://apidocjs.com/#param-api-sample-request)

**Comment by joelbowen** [comment]
@rottmann that does work for the sample request form, however I'm looking to override the generated URL in the definition.

**Comment by marijang** [comment]
+1

**Comment by zoellner** [comment]
+1
use case: main api is at /api/* but authentication is at /auth/* 
Would like to create a combined documentation. URL override per block would work for me (or one apidoc.json per sub directory)

**Comment by CullenShane** [comment]
+1 an @apiUrl definition that overrides apidoc.json would be greatly appreciated.  Having the ability to unset the URL for writing Event docs or 'Common reused structures' sections would be helpful.

**Comment by RafaO** [comment]
+1

**Comment by lidio601** [comment]
+1

**Comment by roybrey** [comment]
+1

**Comment by BirknerAlex** [comment]
+1

**Comment by DannyvdSluijs** [comment]
Would very much appreciate this, and would even work on this proposal. Is there any form of proposal or would a draft in the comments work for you @rottmann ?

**Comment by andrew-s** [comment]
I'd like to see this too, my use case is slightly different where, the language I was using wasn't appropriate for a specific task, so my API ended up getting broken up slightly with different endpoints (same API), so, I'd like to see @apiUrl as an option.

**Comment by viniciuschiele** [comment]
@DannyvdSluijs' solution looks perfectly fine, there is no reason to prepend the project URL if the endpoint is already an absolute URL.

**Comment by Vedu1996** [comment]
+1

**Comment by bholagabbar** [comment]
@rottmann Any progress? I would really like this feature as well and it's a legit usecase

**Comment by Veloyd** [comment]
+1

**Comment by NicolasCARPi** [comment]
The workaround proposed by @DannyvdSluijs works, so I have added it. It was also necessary to change some code over at apidoc-core.

**Comment by danielskeeled** [comment]
Thanks!
