### ISSUE TITLE
@apiDefine re-use as sub-types

### ISSUE THREAD

**Issue by Skoog** [apidoc/apidoc#202]
Hello,

Given the following defined block

```js
/**
 * @apiDefine UserObject
 *
 * @apiSuccess (200) {String} firstname Firstname of the User.
 * @apiSuccess (200) {String} lastname  Lastname of the User.
 */
```

and the following endpoints

```js
/**
 * @api {get} /users/:id
 * @api getUser
 * @apiDescription Get a singel user.
 *
 * @apiUse UserObject
 */
```

```js
/**
 * @api {get} /users
 * @api getUsers
 * @apiDescription Get all the users.
 *
 * @apiUse UserObject
 */
```

Is there a way to specify `UserObject` as a sub response type. 

Let's say I want an array of the `UserObject` block aa response for `/users` instead of
the single object defined in the block.

e.g. `@apiSuccess (200) {UserObject[]} An array of users`

**Comment by rottmann** [comment]
That kind of object usage is not possible, you can only do this:

```
/**
 * @apiDefine UserObject
 *
 * @apiSuccess (200) {String} MyUserObject.firstname Firstname of the User.
 * @apiSuccess (200) {String} MyUserObject.lastname  Lastname of the User.
 */

/**
 * @api {get} /users
 * @api getUsers
 * @apiDescription Get all the users.
 *
 * @apiSuccess (200) {Object} MyUserObject A User Object.
 * @apiUse UserObject
 */
```
named it `MyUserObject` to make it clear, that it has nothing todo with UserObject, but it can have the same name.

**Comment by Skoog** [comment]
Thanks,

Guess we just have to work around it with more informative descriptions.
