### ISSUE TITLE
Ordering not working with space separated names

### ISSUE THREAD

**Issue by cavb** [apidoc/apidoc#203]
Hi!
I was just trying to change the order of the docs output, but it seems that it doesn't work with space separated @apiGroup names.  

Example (apidocs.js fragment):  
```javascript 
{
  "order": [
  "API User",
  "Process Definition",
  "Resolver Group"
]
}
```
Greets!

**Comment by rottmann** [comment]
No the names should not have spaces (like variable in your programming language).
Use underscore / camelcase.
