### ISSUE TITLE
Specify a parameter for the JSON string passed in Ajax?

### ISSUE THREAD

**Issue by medero** [apidoc/apidoc#204]
In utils/send_sample_request.js, the data is passed as a single JSON.stringify string. Is there a way to prepend a parameter so this can easily be parsed from say, PHP?

```
  $.ajax({
      url: url,
      dataType: "json",
      contentType: "application/json",
      data: JSON.stringify(param),
      .........
  })
```

Such as:

```
  $.ajax({
      url: url,
      dataType: "json",
      contentType: "application/json",
      data: 'data=' + JSON.stringify(param),
      .........
  })
```

Is there any way to override this? Without that I'm left to parse the REQUEST variables without a specify parameter to reference, which would make things much easier.

**Comment by rottmann** [comment]
You can copy the template and modify it and call `apidoc -t your/template/path`
