### ISSUE TITLE
Multiple verbs for one endPoint URL

### ISSUE THREAD

**Issue by nekloth** [apidoc/apidoc#207]
I have an API endPoint, let's say http://api.mydomain.com/v1/updateInfo, that can be reached thanks to two different verbs : 
 - PUT to add new update information
 - GET to retrieve the last update information.

Can it be done today ?

**Comment by rottmann** [comment]
```
/**
 * @api {get} /updateInfo Get Update Info
 * @apiName GetUpdateInfo // this optional
 * ... get api params and descripton
 */

/**
 * @api {put} /updateInfo Put Update Info
 * @apiName PutUpdateInfo // this optional
 * ... put api params and descripton
 */
```

**Comment by nekloth** [comment]
Oh, ok great... so simple... Sorry for my "dumb" question then...
