### ISSUE TITLE
Warning on empty @param usage

### ISSUE THREAD

**Issue by rottmann** [apidoc/apidoc#208]
`@apiSuccess` leads to empty json blocks which breaks javascript frontend.

**Comment by zxqfox** [comment]
Probably you solving a problem that already was solved in jscs-jsdoc. ;-) Just fyi.

**Comment by rottmann** [comment]
Thanks! That (node-jscs)[https://github.com/jscs-dev/node-jscs] is exactly the tool i watch some time ago for validation check, but i did not find it :) I wrote it then in the wiki, to check again for such a linter.
Only found jison, but that tool is a little to much for my spare time.

**Comment by zxqfox** [comment]
@rottmann ;-) I'm trying to make a support for multiple presets (tag sets) to support `apiDoc` but still can't find a few hours to do it. So free time problems is everywhere ;-)

If I can help you or you have ideas — I'm open to talk ;-)

**Comment by NicolasCARPi** [comment]
You can try the current `dev` branch: `npm i -g apidoc/apidoc#dev`. See also #999.
