### ISSUE TITLE
Having a file as parameter in the SampleRequest

### ISSUE THREAD

**Issue by nekloth** [apidoc/apidoc#209]
I have an API (POST) that let me post a file, in addition to other parameters.

Is there a apiParam type FILE, that could display the "file" input type when I setup a sampleRequest ?

**Comment by rottmann** [comment]
Sorry currently not, the sample request api must be recreated, it does not support many things.

**Comment by emildancescu** [comment]
Hey there! Any updates on this issue? Being able to upload files would be awesome :) Thanks!

**Comment by jeremycondon** [comment]
I'll second that.  This would be a nice feature to have.

**Comment by matthova** [comment]
+1

**Comment by jaredrada** [comment]
+1 this is necessary for my use case

**Comment by hareesh-blippar** [comment]
+10 :)

**Comment by mnicolas80** [comment]
+1

**Comment by ajorquera** [comment]
+1

**Comment by psi-4ward** [comment]
+1

**Comment by hattmarris** [comment]
+1

**Comment by deadkEEper1** [comment]
+1

**Comment by oopyoung** [comment]
+1

**Comment by di3goleite** [comment]
+1

**Comment by rich186** [comment]
+1

**Comment by ajorquera** [comment]
+1

**Comment by chehabz** [comment]
+1

**Comment by meseguer1998** [comment]
+1

**Comment by syntaxsugar** [comment]
+1

**Comment by jrahhali** [comment]
+1

**Comment by wantg** [comment]
+1

**Comment by knsmathers** [comment]
+1

**Comment by alexabidri** [comment]
+1

**Comment by Vasilio777** [comment]
+1

**Comment by aibaq** [comment]
+1

**Comment by rubenve** [comment]
+1

**Comment by gongzhy22** [comment]
+1

**Comment by yarkovaleksei** [comment]
+1

**Comment by tewnut** [comment]
what is the status of this @apiParam {FILE} feature?

**Comment by chehabz** [comment]
How about we build it rather than waiting for this to be done . 👍  i'll try to fork it and work on it this weekend.

**Comment by alex-zhang** [comment]
+1

**Comment by bekbossyn** [comment]
+1

**Comment by kerberjg** [comment]
+1

**Comment by yarkovaleksei** [comment]
@chehabz Greetings. How is the work going? Did you add a type?

**Comment by aqnaruto** [comment]
hello every one ,i make a pr to implement this feature.
https://github.com/apidoc/apidoc/pull/826
@rottmann @NicolasCARPi   waiting you reply . thanks.

**Comment by aqnaruto** [comment]
pr is updating .  waiting yours reply
