### ISSUE TITLE
SampleRequest URL is always called in OPTIONS, whatever the verb

### ISSUE THREAD

**Issue by nekloth** [apidoc/apidoc#210]
I defined something like: 
 * @apiGroup myFile
 * @api {get} /myFile/ Read the file
 * @apiSampleRequest http://myurl.com/api/myFile

But, I see (thanks to Fiddler) that the request sent the URL is not a GET, but a OPTIONS.

**Comment by rottmann** [comment]
Thats a thing of your browser. It sends an option to retrieve the possible options.
That happen when your app and server are not the same ip. -> see CORS https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by nekloth** [comment]
Oh, Ok. Thank you.

Does that means I need to have an OPTIONS verb on my API side to be able to have apidoc on a different server ?

**Comment by rottmann** [comment]
Enable CORS on your server implementation, it is nothing apiDoc specific.
Example when you use a express js server http://enable-cors.org/server_expressjs.html
