### ISSUE TITLE
Version numbers and incrementing builds

### ISSUE THREAD

**Issue by KrisSiegel** [apidoc/apidoc#211]
We have a build number at the end of our application's version (2.0.0-X) which is automatically incremented via our build system upon each build. apidoc sees the build number as a separate version entirely and allows the user to choose between the version and the build number at the doc of the documentation (so 2.0.0 and 2.0.0-18 or whatever the build number may be).

It would be nice if it were changed so we could tell it to ignore certain parts of a version number that shouldn't matter to documentation. Even patches shouldn't really change APIs (though they theoretically could but at least in our environment I'd rather they not).

Hope that makes sense. Not sure if I'll have time to submit a pull request anytime soon.

**Comment by rottmann** [comment]
Make sense, but on the other side i think the "rest api version" should not depend on the build version.
Your application can have version 8.4.1-18 but still use api version 2.0.0.

**Comment by KrisSiegel** [comment]
Yeah I would like it to not show the build increment as a separate version of the API so separating that completely would work for me as well :)

**Comment by rottmann** [comment]
Set in apidoc.json 
```
{
  "version": "2.0.0"
}
```
and apidoc use the fixed value.
