### ISSUE TITLE
Default Block Version to be Package Version

### ISSUE THREAD

**Issue by tldavies** [apidoc/apidoc#212]
I was wondering if it possible to make the default version of each block to be the package version. It seems currently that if there isn't a block version then it defaults to 0.0.0. I want to be able to have it default to apidoc:version.

**Comment by tldavies** [comment]
So I guess this is partly a duplicate of Issue: https://github.com/apidoc/apidoc/issues/205 

It answered my question that this is currently not possible. And thus each block needs to have a version. 
Would love for this functionality as then we would not need to update every block version every time the api is updated.

**Comment by nazrhyn** [comment]
:+1:

**Comment by tielur** [comment]
:+1:

**Comment by rottmann** [comment]
If you not need the version, do not add @apiVersion.
in apidoc.json set
```
  "template": {
  	"withCompare": false
  }
```
Then the versions are not visible.

An auto setted version (e.g. from apidoc.json) could harm inheritance, in particular when the parent did not have version too.

**Comment by cladera** [comment]
Was this feature actually implemented? I've tested it in my project and all my blocks without @apiVersion shows 0.0.0 version instead of package.json's.
