### ISSUE TITLE
Add a 'deprecated' tag

### ISSUE THREAD

**Issue by strayobject** [apidoc/apidoc#213]
At the moment I'm using @apiDescription with span and strong tags round the word 'DEPRECATED' and it does the job, but it would be better to have a separate tag i.e. @apiDeprecated
and styling of it in the tempate file.

**Comment by rottmann** [comment]
Yep, is already on [todo](https://github.com/apidoc/apidoc/wiki/ToDo) list.

#33

**Comment by strayobject** [comment]
Did not check wiki, sorry :)
