### ISSUE TITLE
multiple types in @apiParam

### ISSUE THREAD

**Issue by hotaru355** [apidoc/apidoc#214]
I use apiDoc for documenting JavaScript and would like to use `@apiParam` to show that an input parameter can be of different types. For example:

```
/**
 * @apiParam {Object|Number} options an options object or just a number
 */
function myFunc(options) {
}
```

Unfortunately, the above example gives an error in the parser:

```
error: Empty parser result. 
{ File: 'myfile.js',
  Block: 1,
  Element: '@apiParam',
  Source: '@apiParam {Object|Number} ..'
}
```

Is there a character other than the pipe that does not blow the parser? Or is there a way to escape the pipe character? Thanks!

**Comment by rottmann** [comment]
Currently name them `mixed` and add a description.
I check to allow this feature again, it was removed because of the the size and allowedValues parameters that can be added to a type.

**Comment by Quagh** [comment]
Same request for `@apiResponse` :)

```
@apiSuccess {string|integer|null} field Description
```

**Comment by rhys-vdw** [comment]
+1

**Comment by AndrewHoos** [comment]
This would be nice, but something else that might be easier is to simply allow listing the same parameter more than once:

    @apiParam {String} [Resources] A Resource label 
    @apiParam {String[]} [Resources] A list of Resource labels

Right now this just lists the last one and ignores the first.

**Comment by allayli** [comment]
Hi, can file type param be supported in `@apiParam` ?
```javascript
@apiParam {File} [Resources] A Resource File to be uploaded
```
Thanks.

**Comment by DragonAxe** [comment]
I have something to add to this conversation.
I'm trying to document a Java API and one of my `@apiParam`s has a type of `Set<Integer>`
However apidoc throws an error because of the special characters: `<` `>`
Any tips or fixes?
`&lt;` `&gt;` doesn't work either.

**Comment by davidrapin** [comment]
+1 on this, this seems pretty critical

**Comment by skielo** [comment]
+1
I'm getting the same problem trying to document a C# class:
error: Empty parser result.
`{ File: '.\\GoalsV2Module.cs',
  Block: 4,
  Element: '@apiSuccess',
  Source: '@apiSuccess (200) {Nullable&lt;int&gt;} goal.IntegrationId' }`

Also it doesn't work with characters like: ? | ... etc

**Comment by rodrigogs** [comment]
+1

**Comment by StyleT** [comment]
any news here?

**Comment by webus** [comment]
any news ?

**Comment by tobernguyen** [comment]
+1

**Comment by LogansUA** [comment]
Still waiting for this :)

**Comment by tewnut** [comment]
How is the status for file type param?

**Comment by demisx** [comment]
+1

**Comment by cschaba** [comment]
+1

**Comment by OoDeLally** [comment]
+1

**Comment by kerberjg** [comment]
+1

**Comment by Schemiii** [comment]
+1

**Comment by NiklasMerz** [comment]
For a temporary solution se #573

**Comment by CrazySzg** [comment]
+1

**Comment by chetverikov** [comment]
+1

**Comment by chungryan** [comment]
+1

**Comment by greatzeze** [comment]
+1

**Comment by galaktuz** [comment]
+1

**Comment by demidovsky** [comment]
+1

**Comment by karankapur999** [comment]
+1

**Comment by jeffrey008** [comment]
+1

**Comment by NicolasCARPi** [comment]
The {String|Number} syntax works now.
