### ISSUE TITLE
Incorrect parsing in nested objects if param name starts with special character

### ISSUE THREAD

**Issue by Guferos** [apidoc/apidoc#215]
Hi,

I'm using mongoDB for my database and it returns id object with single parameter $oid for every object in the database. Eg.

```
{
    "_id": {
        "$oid": "54ea341e9fcf7b0a947723dc"
    },
    "name": "test-user",
    "email": "test@email.com",
    "username": "test",
    "__v": 0
}
```

If I create documentation with these parameters: 
- @apiSuccess {Object} _id Object ID created by mongoDB
- @apiSuccess {String} _id.$oid Object ID used as the User unique ID
- @apiSuccess {String} name Full name of the User.
- @apiSuccess {String} username  Username of the User. Username is used for the login purposes.
- @apiSuccess {String} email Email address of the User
- @apiSuccess {Int} __v The versionKey is a property set on each document when first created by Mongoose. This keys value contains the internal revision of the document.

it produces following result:

```
"success": {
      "fields": {
        "Success 200": [
          {
            "group": "Success 200",
            "type": "Object",
            "optional": false,
            "field": "_id",
            "description": "<p>Object ID created by mongoDB</p> "
          },
          {
            "group": "Success 200",
            "type": "String",
            "optional": false,
            "field": "_id.",
            "description": "<p>$oid Object ID used as the User unique ID</p> "
          },
          {
            "group": "Success 200",
            "type": "String",
            "optional": false,
            "field": "name",
            "description": "<p>Full name of the User.</p> "
          },
          {
            "group": "Success 200",
            "type": "String",
            "optional": false,
            "field": "username",
            "description": "<p>Username of the User. Username is used for the login purposes.</p> "
          },
          {
            "group": "Success 200",
            "type": "String",
            "optional": false,
            "field": "email",
            "description": "<p>Email address of the User</p> "
          },
          {
            "group": "Success 200",
            "type": "Int",
            "optional": false,
            "field": "__v",
            "description": "<p>The versionKey is a property set on each document when first created by Mongoose. This keys value contains the internal revision of the document.</p> "
          }
        ]
      }
```

Above result is incorrect. If you have noticed "$oid" is moved to the description and it should be in the field value. Any way to quickly fix it?

**Comment by rottmann** [comment]
Change the regex in apidoc/node_modules/apidoc-core/lib/parsers/api_param.js
```
wName: {
    b: '(\\[?\\s*', // 5 optional optional-marker
    name: '([a-zA-Z0-9\\.\\/\\\\_-]+)', // 6
```

to
```
wName: {
    b: '(\\[?\\s*', // 5 optional optional-marker
    name: '([a-zA-Z0-9\\.\\/\\\\_-\\$]+)', // 6
```

I think i can implement this in the next version too.

**Comment by Guferos** [comment]
Thanks for the response, but your new regex was failing. I've changed it slightly and it works now

```
wName: {
    b: '(\\[?\\s*', // 5 optional optional-marker
        name: '([a-zA-Z0-9\\.\\/\\\\_\\-\\$]+)', // 6
```

**Comment by ssljivic** [comment]
Just to add: When api param starts with some special chars like $ the apidic fails with an error:

```
@apiParam (myGroup)  {string}  [$foo]   Foo description 
```

```
error: Empty parser result.
```

**Comment by soderluk** [comment]
Same issue is when trying to document a JSON-LD response, e.g. including `@context` or `@type` to the response, generates an empty field.

Any ideas on this? JSON-LD is something that should be taken into account when documenting APIs.

**Comment by jeffrey008** [comment]
@ssljivic I am facing this problem, how to resolve that? My line is
```
 @apiParam {String} [$filter] A filter string.
```

**Comment by NicolasCARPi** [comment]
This is no longer an issue.
