### ISSUE TITLE
Unicode Support

### ISSUE THREAD

**Issue by drtzack** [apidoc/apidoc#217]
I want to create my doc in my local language.

Turkish chars are returning into underscore while using @apiGroup.

**Comment by rottmann** [comment]
The names can not contain umlauts/unicode.

To display text with umlauts, define a group:
```
/**
 * @apiDefine MyGroupName Title with umlauts: öäü
 */

/**
 * @api {GET} /something
 * @apiGroup MyGroupName
 */
```

I will check to extend the apiGroup with a title.
