### ISSUE TITLE
How to create a new annotation ?

### ISSUE THREAD

**Issue by remiheens** [apidoc/apidoc#218]
Hi,

I'm using your library to generate my PHP REST API but I want to add an annotation  @apiLimit to define the call limit of endpoint.

I read in your docs that I have to see in lib/plugins (the link : https://github.com/apidoc/apidoc/tree/master/lib/plugins) but It disappear on the newest version.

How can I create a new parser for a new annotation ? 

Thx a lot.

Rémi

**Comment by remiheens** [comment]
Ok I've found a solution.

I create a parser_limit.js

```js
function parse(content, source) {

	if(content.length === 0)
        return null;

    var obj = {
        limit: content.replace(/(\s+)/g, '')
    };
    
    return obj;
}

/**
 * Exports
 */
module.exports = {
    parse : parse,
    path  : 'local',
    method: 'insert'
};
```
And in template/index.html
```html
    {{#if article.limit}}
      <p>Usage Limit : {{article.limit}}</p>
    {{/if}}
```

And I generate docs with 
```apidoc -i . -o ../docs/ --parse-parsers apilimit=parser_limit.js - t ../template/```


Is this the good way to create new annotation ?

**Comment by rottmann** [comment]
Yes, this is the way how I had planned system. You can extend own annotations without forking the whole project.

**Comment by echovalley** [comment]
Hi, I also want to insert a table to my doc, so I decide to add a new param name "@apiTable" myself. But not work according to the way above. Do you have some more detail description or examples to demonstrate how to extend my own param? thankx

**Comment by remiheens** [comment]
For your annotations you have to create a filter
in parser_table.js :
```
function parse(content, source) {

    if(content.length === 0)
        return null;

    var obj = {
        table: content.replace(/(\s+)/g, '')
    };

    return obj;
}

/**
 * Exports
 */
module.exports = {
    parse : parse,
    path  : 'local',
    method: 'insert'
};
```
And in template/index.html
```
    {{#if article.table}}
      <p>Table : {{article.table}}</p>
    {{/if}}
```
And I generate docs with 
```
apidoc -i . -o ../docs/ --parse-parsers apitable=parser_table.js - t ../template/
```

**Comment by echovalley** [comment]
Thank you remiheens, but I already tried it exactly by the way, but the html output still not render anything. I use the annotation by this way:
@apiTable table output: xxx
Is it correctly? Or I miss something? 

I add this to template/index.html (Add a pair of embraced script tag)
<script id="template-table" type="text/x-handlebars-template">
{{#if article.table}}
<p>Table output: {{article.table}} </p>
{{/if}}
</script>
Does it right?

**Comment by rottmann** [comment]
Check if your table data is in the `api_data.json`.

In the template you can use `{{cl article}}` / `{{cl article.table}}` to view a debug console output of the  data.
