### ISSUE TITLE
Request Body of a apiSampleRequest is always a json

### ISSUE THREAD

**Issue by adrianvlupu** [apidoc/apidoc#219]
I declared an @apiSampleRequest on a method. When clicking the Send button from the generated documentation page, a request gets sent to my api. 

How can I control the request body formatting of that request. It always get's passed as json, like {"grant_type":"","uuid":""}.
Any way of making it send the body in a application/x-www-form-urlencoded format?

**Comment by pbojan** [comment]
:+1:

**Comment by imagepit** [comment]
+1

**Comment by drogjh** [comment]
+1

**Comment by NicolasCARPi** [comment]
Now there is!
