### ISSUE TITLE
Examples GET request issue

### ISSUE THREAD

**Issue by kushal813** [apidoc/apidoc#221]
Why is the examples in http://apidocjs.com/example/ are sending the GET api request as 
GET : http://apidocjs.com/example/api_project.json?{"id":"2"}

rather than 

GET : http://apidocjs.com/example/api_project.json?id=2

**Comment by rottmann** [comment]
The api test method will be revisit, it send always json objects.
`?id=2` is correct.

**Comment by cosmincatalin** [comment]
I was just about to notice the same behaviour.

**Comment by Furqankhanzada** [comment]
Hi @cosmincatalin @kushal813 @rottmann : for quick fix i made a change on ```send_simple_request.js``` online number ```76```

```
data: ['POST', 'PUT', 'PATCH'].indexOf(type.toUpperCase()) != -1 ? JSON.stringify(param) : $.param( param, true ),
```

**Comment by dctdevelop** [comment]
@Furqankhanzada

Tested and implemented, great work. 
I also added 'DELETE' into the array, since its also possible to send form data (although rarely) used. 

Thanks again

**Comment by dctdevelop** [comment]
Quick update, if you don't want to send empty fields, add 
```
Object.keys(param).filter(function (v) {
    return !(param[v].length > 0);
}).forEach( function(it,idx,arr){
    delete param[it];
});
```
right before the ajax call, in Addition to the code provided by @Furqankhanzada.

**Comment by jrewing** [comment]
Thanks @Furqankhanzada !

**Comment by ramiel** [comment]
Why there is no PR for this?

**Comment by iXioN** [comment]
+1 can you add a PR :-)

**Comment by rottmann** [comment]
Added in 0.14.0
