### ISSUE TITLE
parse error when using non-english charset in @api title 

### ISSUE THREAD

**Issue by hitdavid** [apidoc/apidoc#223]
parse error when using non-english charset in @api title 

when I use chinese chars in @api title (eg. @api {get} /foo/bar  中文)
the api_data.js file generated is incomplete.
the value of title field after name will appears like "name" : "_______"

some of api will not show in web html page

**Comment by hitdavid** [comment]
# a patch to make apidoc right
#python script

__author__ = 'David'
import os 

file_object = open('./apidoc/api_data.js')
dest = open('./apidoc/api_data.js.new', 'w')

name = ''
title_line_number = 0
name_line_number = 0
line_number = 0

result = ''

for line in file_object:
    line_number += 1
    if line.__contains__("\"title\""):
        strList = line.split(':')
        name = strList[1]
        title_line_number = line_number
        result = line
    else:
        if line.__contains__("\"name\""):
            if line_number == title_line_number + 1:
                valueList = line.split(':')
                result = valueList[0] + ':' + strList[1]
            else:
                result = line
        else:
            result = line
    dest.write(result)

file_object.close()
dest.close()

os.remove('./apidoc/api_data.js')
open('./apidoc/api_data.js', "wb").write(open('./apidoc/api_data.js.new', "rb").read())

**Comment by rottmann** [comment]
Can not reproduce this error.

example.js
```
/**
 * @api {get} /foo/bar 中文)
 */
```

created api_data
```
define({ "api": [
  {
    "type": "get",
    "url": "/foo/bar",
    "title": "中文)",
    "version": "0.0.0",
    "filename": "./test2.js",
    "group": "_home_rottmann_test_apidoc_umlauts_example_js",
    "groupTitle": "_home_rottmann_test_apidoc_umlauts_example_js",
    "name": "GetFooBar"
  }
] });
```

Is the file encoding of the input file utf-8 ?
