### ISSUE TITLE
Problems with Umlauts

### ISSUE THREAD

**Issue by neilyoung** [apidoc/apidoc#225]
...but not everywhere...

/**
 * @api {get} /eg/info Endgeräte-Informationen abholen
 * @apiName EGInfo
 * @apiVersion 0.0.7

 * @apiGroup Endgeräte
 */

![bildschirmfoto 2015-03-15 um 23 55 22](https://cloud.githubusercontent.com/assets/731020/6658602/cf6c0f62-cb6e-11e4-83b1-1e087fb8ff57.png)

**Comment by rottmann** [comment]
`apiGroup name` does not support umlauts.

Problem is known and on todo #217
