### ISSUE TITLE
@apiParam not parsed into url if there is a `?` after param name

### ISSUE THREAD

**Issue by weikinhuang** [apidoc/apidoc#226]
The error appears when trying to specify a symbol replacement for a param name and in the url there are query parameters:

ex `@apiParam {String} param` with value `foobar`

```
http://example.com/api/:param?access_token=abc
```

will remain unchanged as

```
http://example.com/api/:param?access_token=abc
```

however if I include a `/` it will work as expected

```
http://example.com/api/:param/?access_token=abc
```

becomes

```
http://example.com/api/foobar/?access_token=abc
```

**Comment by goryny4** [comment]
really took time to find it out

**Comment by DarkPark** [comment]
please take a look at this bug

**Comment by rottmann** [comment]
Reported the bug to path-to-regexp library devs.

**Comment by rottmann** [comment]
Not intended in the path-to-regexp lib.
Will replace the lib to use URI-Templates [rfc6570](http://tools.ietf.org/html/rfc6570).

Have to check if somebody created a rfc compatible library.

**Comment by NicolasCARPi** [comment]
Use @apiQuery for this.
