### ISSUE TITLE
-e is ignored if after -o flag

### ISSUE THREAD

**Issue by jinkim608** [apidoc/apidoc#229]
Hi, I'm working on my REST API backend for a mobile app on Node.js on Heroku platform.

When I generate the document through terminal command, it includes many random groups/methods in addition to the APIs that I annotated on m node backend's index.js file.

Here is the structure I have:

app-node-backend (directory)
> index.js
> package.json
> node_modules (directory) (modules installed through package.json dependencies)
> > apidoc (directory)
> > body-parser (directory)

I think it picks up js files in those node_modules and include them in the document-generation. Could you give me any advice on how to clear up the structure (this is my first backend application on node.js and using heroku) or if there is a way to target only one file (or exclude child directory after -i flag)?

**Comment by rottmann** [comment]
With the `-e` flag you can exclude dirs. The flag can be used many times
`-e some_dir/ -e some_other_dir/`

**Comment by jinkim608** [comment]
I just tried -e app-node-backend/node_modules/, but it seems like it still includes .js files under the directory and its subdirectories.

I tried to include individual subdirectory paths also, but the .js file in that path is still not ignored. Also, is there a specific command for including all contents and subdirectories for -e flag? Since I'm not very familiar with the terminal commands, I searched and tried several things like '/*', '/**\*', but nothing worked.

**Comment by rottmann** [comment]
Sorry, my mistake the flags use regex, try `-e some_dir\/`

**Comment by jinkim608** [comment]
With that command, I still get the same result: "APP NODE BACKEND NODE MODULES BODY PARSER LIB READ JS" as one group and many others like that show up on index.html generated. This is picked up from app-node-backend/node_modules/body_parser/lib/read.js file. My index.js is in app-node-backend directory.

I'm using zsh on OS X.

Thanks for the continuous troubleshoot effort.

**Comment by jinkim608** [comment]
I just read deerawan's comment in issue #6, but that still doesn't work for me. Maybe something on my environment?

**Comment by jinkim608** [comment]
Aha, got it. I just realized the order of the flags matter.

This worked:
    apidoc -i .\/ -e node_modules\/ -o apidoc\/

while this did NOT work (-e ignored): 
    apidoc -i .\/ -o .\/apidoc\/ -e .\/node_modules\/

Thanks again for guiding me through. I couldn't ditch and use other REST API specs/tools because I liked the in-line documentation + html generation so much.
