### ISSUE TITLE
apiParams String[] example

### ISSUE THREAD

**Issue by andyofb** [apidoc/apidoc#23]
One of the apiParam types is String[] however there is no example of how I show the required parameters in the format. Could someone please show me an example of this.

Thanks

**Comment by zhangjianwai813** [comment]
what about this
{
            "metadata": [
               [
                     {
                        "key": "name",
                        "value": "Andy"
                    },
                     {
                        "key": "name",
                        "value": "Som"
                    }
                ],
                [
                    {
                        "key": "gender",
                        "value": "male"
                    }
                ]
            ],
            "pointsFront": [
                {
                    "x": "1",
                    "y": "2"
                },
                {
                    "x": "3",
                    "y": "4"
                },
                {
                    "x": "5",
                    "y": "6"
                }
            ],
            "pointsSide": [
                {
                    "x": "7",
                    "y": "8"
                },
                {
                    "x": "9",
                    "y": "10"
                }
            ]
        }

**Comment by fontenele** [comment]
Sorry but andyofb was talking about @apiParam and not @apiSuccess.
Im trying to use with Array on input params but apidoc dont support array param at this moment :(

**Comment by darkin1** [comment]
You can do like this

```
     * @apiParam {Array} [websites] list of websites
     * @apiParam {Url} websites.url website name
```

**Comment by cameronsutter** [comment]
@darkin1 [websites] would mean that websites is optional :/

**Comment by joartcano** [comment]
Is there any way to have a parameter of Array of Objects in apidoc? Im having trouble in passing a parameter of array of objects :(

**Comment by darkin1** [comment]
@cameronsutter
In this case yes, but you could do without [], like this
```
@apiSuccess {Url} websites.url
@apiSuccess {String} banned
```
and this would be required

**Comment by cameronsutter** [comment]
I haven't found a way to do that yet, sorry

**Comment by joartcano** [comment]
Thanks for the reply. :) @cameronsutter

**Comment by peichao01** [comment]
@rottmann can not write array in this format:

* @apiSuccess {Object[]} metadata          List of metadata.
* @apiSuccess {String}   metadata[].key    The key.
* @apiSuccess {String}   metadata[].value  The value.
