### ISSUE TITLE
How to reuse apiSuccessExample blocks

### ISSUE THREAD

**Issue by pinndulum** [apidoc/apidoc#232]
When there are two methods with the same type of resource, but one method returns a collection of that resource.

I understand how to create <code>apiSuccess</code> blocks to handle this situation with <code>apiDefine</code> and <code>apiUse</code>. 

However, how can I reuse the resource object's json definition in an <code>apiSuccessExample</code> such as below?

````
@apiSuccessExample {json} Success-Response:
    HTTP:/1.1 200 OK
    {
         "_type": "resource",
         "name": "String content",
         "value": "Object value",
         ... Complex and extremely long object definitions continue here ...
    }
````
````
@apiSuccessExample {json} Collection-Success-Response:
    HTTP:/1.1 200 OK
    [
        {
             "_type": "resource",
             "name": "String content",
             "value": "Object value",
             ... Complex and extremely long object definitions continue here ...
        }
    ]
````
The only difference between the two is identifying that the Collection-Success-Response returns an array of a resource that needs only be defined once. In this way, when the underlying resource is modified, changes to the documentation need only be modified in one location.

Can this currently be done?

**Comment by rottmann** [comment]
Use @apiDefine to define a block with @apiSuccess params.

In your api-description use @apiUse to include the defined block.
