### ISSUE TITLE
Custom apidoc.json location

### ISSUE THREAD

**Issue by tyranron** [apidoc/apidoc#233]
It would be nice to have an additional CLI parameter like `-c, --config` where we can specify path to `apidoc.json` file or `package.json` file in case they are placed not in the project root directory.

**Comment by DaspawnW** [comment]
+1

**Comment by rottmann** [comment]
Added in 0.13.0.

**Comment by iamjoyce** [comment]
Hi @rottmann, I have been trying to google a solution but to no avail.

My command is `apidoc -i folderName/ -c folderName/apidoc.json -o folderName/apidoc/`

The apidoc library ignores my `-c` command regardless of `-c` placement. Is there a bug, or did I define the command wrongly?

**Comment by mikacalvo** [comment]
hello, this should be in the doc http://apidocjs.com/

thanks for the solution though
