### ISSUE TITLE
Ability to disable "Versioning" at all

### ISSUE THREAD

**Issue by tyranron** [apidoc/apidoc#234]
There are some projects (inner api's for example) where SemVer (or similar versioning) is not used.
It would be nice to have an additional parameter in `apidoc.json` (and in CLI) that disables "Versioning" feature at all, so generated output wouldn't contain any unnecessary "0.0.0" comboboxes.

**Comment by benbenw** [comment]
In apidoc.json, try this :
```javascript
"template" : {
  	"withCompare" : false
  }
```
