### ISSUE TITLE
How to declare a hash parameter?

### ISSUE THREAD

**Issue by mingmingpao** [apidoc/apidoc#236]
I want to declare a parameter of Hash type, such as {info: {name: ..., age: ...}}, how to? I attempted to declare like this 

@apiParam info.name ...
@apiParam info.age ...

But it doesn't work well with the prefix 'info.' missed

Looking forward to your reply.

**Comment by rottmann** [comment]
See http://apidocjs.com/#param-api-success - Example with Object

the syntax is the same for apiParam.

**Comment by mingmingpao** [comment]
Thank you, I'll try it and wish a good result!
