### ISSUE TITLE
apiDefine requires incorrect usage of docstring in python.

### ISSUE THREAD

**Issue by wachpwnski** [apidoc/apidoc#238]
I might be doing this completely wrong but the incorrect.py version will parse fine, but the correct.py version will not. (error: Only one definition is allowed in the same block. )

Maybe I can add these docstrings to my api acl models or have apiRoles.js and have it parse that.  It is also possible I am using apiDefine incorrectly.

https://gist.github.com/wachpwnski/5351a346c77ab8eaafb5

**Comment by rottmann** [comment]
This is correct. 
apidoc can (currently) not handle multiple apiDefine in one comment block.
