### ISSUE TITLE
why i sent sample request by post data in Request payload?

### ISSUE THREAD

**Issue by JackyZhan** [apidoc/apidoc#242]
So server-side can not get the data.
how i sent sample request by post data?

the following is the code comment.
   /**
     \* @api {post} /api.php?mod=user&code=login
     \* @apiSampleRequest /api.php?mod=user&code=login
     *
     \* @apiVersion 0.2.0
     \* @apiName login
     \* @apiGroup User
     *
     \* @apiParam {string} phone logname.
     \* @apiParam {string} pwd logpwd.
     *
     \* @apiSuccess {String} firstname  Firstname of the User.
     \* @apiSuccess {String} lastname   Lastname of the User.
     \* @apiSuccess {Date}   registered Date of Registration.
     *
     *
     \* @apiError UserNotFound The id of the User was not found.
     *
     \* @apiErrorExample Error-Response:
     \*     HTTP/1.1 404 Not Found
     \*     {
     \*       "error": "UserNotFound"
     \*     }
     */

**Comment by JackyZhan** [comment]
i could see the params in request payload by chrome's network.

**Comment by rottmann** [comment]
The test method will be replaced, a contributor submitted it some time ago for a small get test request.

**Comment by NicolasCARPi** [comment]
You can try the current `dev` branch: `npm i -g apidoc/apidoc#dev`. See also #999.
