### ISSUE TITLE
How to add multiple custom parsers

### ISSUE THREAD

**Issue by lijing241** [apidoc/apidoc#244]
--parse-parsers apientities=./parsers/api_entities.js apisqls=./parsers/api_sqls.js
Or
--parse-parsers apientities=./parsers/api_entities.js --parse-parsers apisqls=./parsers/api_sqls.js
neither one works.
I added two parsers like apientities and apisqls, but it doesn't work,only one works.What should I do to add multiple custom parsers? Thanks for your answer!

**Comment by rottmann** [comment]
Sorry, changed the bin file some time ago to nomnom and forget so set the list parameter.
Will publish today an update.

**Comment by lijing241** [comment]
thank you
