### ISSUE TITLE
api group description

### ISSUE THREAD

**Issue by jpcaruana** [apidoc/apidoc#245]
it would be nice to have a @apiGroupDescription to give more information about a group (explain what it is used for, what are the core notions behind it). It could be displayed after group name but before APIs for this group.

Bonus point if we can optionally link to a markdown file :)

**Comment by jpcaruana** [comment]
quite similar to @apiDescription in fact

**Comment by rottmann** [comment]
Currently possible with a little "hack", define a group:

/**
 * @apiDefine MyGroupName This is the title
 * Here comes the description.
 */

/**
 * @api {GET} /something
 * @apiGroup MyGroupName
 */

I will check to change @apiGroup with title and text.

**Comment by nmandyam** [comment]
Did this happen? The hack isn't working for me. But everything else woks well, thanks!
