### ISSUE TITLE
Symlinks break rescursive file search

### ISSUE THREAD

**Issue by Dylan1312** [apidoc/apidoc#246]
Hey there,

I'm trying to generate docs but am getting an error because of the presence of symlinks inside my .git folder. Tried using e flag to ignore the .git folder but am still getting the error.

The program crashes with the error 

error: ENOENT, no such file or directory (and then the name path to the symlink)

**Comment by rottmann** [comment]
Try `-e \.git`

**Comment by Dylan1312** [comment]
Hey!

So I've been running: apidoc -e \.git -f ".*\\.inc" -i .  -o ../docs

Looks like error's coming from line 80 in ib/utils/find_files.js

**Comment by rottmann** [comment]
Can't reproduce this error.

Can you add an output line in `lib/utils/find_files.js` line 80
```
var fullFilename = path.join(self.path, filename);
console.log(fullFilename); // ++
```

and run
`apidoc -e .test -f ".*\\.inc" -o ../docs`
