### ISSUE TITLE
override locale read from browser

### ISSUE THREAD

**Issue by MartinP1** [apidoc/apidoc#250]
I think it would be a good idea to have an optional parameter e. g. "locale_override" : "en" in configuration file "apidoc.json".

It looks quite strange e. g. if parameter description is written in english, and instead of "Allowed values"  "Erlaubte Werte" is displayed, in case the browser returns locale "de".

Up to now I use a modified version of locale.js in my templates directory tree specific to the certain project to get "en" as locale, and not the locale returned by the browser...
This is a little bit dangerous, if a new version of apidoc is released - with possible incompatibilities concerning locale.js.

**Comment by DaspawnW** [comment]
+1

**Comment by rottmann** [comment]
Added in 0.13.0 (coming soon):

set in `apidoc.json`
```
  "template": {
    "forceLanguage": "en"
  }
```
