### ISSUE TITLE
Split generated docs

### ISSUE THREAD

**Issue by Tjoosten** [apidoc/apidoc#252]
Make a ption to split the generated docs. Because i have a big api. But it sucks that it is generated on one file.

**Comment by rottmann** [comment]
Add it to todo list: https://github.com/apidoc/apidoc/wiki/ToDo

The split is not a big problem, the template must be modified to reload the parts.

**Comment by Tjoosten** [comment]
can i give me some example?

**Comment by everclear** [comment]
If each group was a page, it would definitely make for a better user experience on larger APIs.

**Comment by razvan-sv** [comment]
+1 for this. I guess if the split is made there won't be any need to the animation, right? (main.js lines 
```ruby
if ($(id).length > 0)
   $('html,body').animate({ scrollTop: parseInt($(id).offset().top) }, 400);
```
I'd like to have an option to disable it.

Btw, thank you very much for apidoc !!  :heart:

**Comment by jhaaaa** [comment]
+1

**Comment by jmkarin** [comment]
+1

**Comment by nbasov** [comment]
+1

**Comment by Pikoulol** [comment]
+1

**Comment by Tjoosten** [comment]
@rottmann any update on this?
