### ISSUE TITLE
Sample request displays error on text/html response 

### ISSUE THREAD

**Issue by nmartin867** [apidoc/apidoc#253]
This is really more of a question: Are response types other than application/json supported in a sample request response window/area? Successful requests with a return content-type of 'text/html' will display an error:

Error 200: SyntaxError: Unexpected token <

Is this configurable?

**Comment by rottmann** [comment]
currently not, it is a really basic module.
You can replace it with your own and create an own template
File: https://github.com/apidoc/apidoc/blob/master/template/utils/send_sample_request.js

**Comment by nmartin867** [comment]
Makes sense. I'll just modify the current template. Thanks1
