### ISSUE TITLE
Multiple input directories (aka multiple -i option)

### ISSUE THREAD

**Issue by luileito** [apidoc/apidoc#255]
It would be great if one could specify multiple -i directories.

Recently I had to document an API that had some `@apiDefine`s inside a subdir in `node_modules`. I ended up excluding many node submodules via -e option, but actually a couple of -i dirs would have sufficed.

**Comment by Digigoodz** [comment]
Hi,
have a look at my pull request: https://github.com/apidoc/apidoc/pull/239
I also use this frequently in client projects.
Would be awesome if this could be merged :)

**Comment by rottmann** [comment]
Coming soon in 0.13.0

**Comment by nolimitdev** [comment]
@rottmann It would be nice to mention in this table https://apidocjs.com/#CLI which parameters can be used multiple times. Just --input or also some other? User reading doc do not know it.
