### ISSUE TITLE
Looks like apiDoc ignores more than the first definition.

### ISSUE THREAD

**Issue by tutuca** [apidoc/apidoc#257]
I have a file with multiple resources.
Each of this have their docstring:

    class UserResource(ModelResource):
        """
        @api {get} users/users/:id/ Request Users
        @apiName User
        @apiGroup Users
        ...
        """

    class AccountResource(ModelResource):
        """
        @api {get} users/accounts/:id/ Request Accounts
        @apiName Account
        @apiGroup Users
        ...
        """

    class TeamMemberResource(ModelResource):
        """
        @api {get} users/team_members/:id/ Request TeamMembers
        @apiName TeamMember
        @apiGroup Users
        ...
        """

After rendering the generated file only shows the documentation of the first resource (User in this case).
Other resources are generated OK, in this case the only thing that is outstanding is that there is more than one resource definition in a single file.

Could that be causing the parser to skip past the remaining resources?

**Comment by rottmann** [comment]
Can you post the generated api_data.json.

**Comment by tutuca** [comment]
I can confirm that this bug is caused by an old version of APIDoc. Updating my copy fixed the issue I had.
