### ISSUE TITLE
apiName doesn't seem to be used

### ISSUE THREAD

**Issue by ghunti** [apidoc/apidoc#259]
I all.
Thanks for the great work.
I've been reading the documentation and checking the examples and either I didn't get what apiName is for or it's not being used.
On the documentation examples used for the demo, there's a ```@apiName GetUser```, but in the demo page there's not a single time the word "GetUser".

Thanks

**Comment by rottmann** [comment]
It is used for the naming and the navigation names.

```
<ul class="sidenav nav nav-list">
<li class="nav-fixed nav-header" data-group="_">
<li class="nav-header" data-group="User">
<li data-version="0.3.0" data-name="GetUser" data-group="User">
<a href="#api-User-GetUser">Read data of a User</a>
</li>
```

Later the name should be used for inline linking (not implemented yet).

I have to update the docs, the apiName change and is now optional.
The name is automatically generated from type und path: `@api {type} /path/` -> internal autogenerate this `@apiName TypePath` if apiName is not set.

**Comment by ghunti** [comment]
Hi @rottmann 
Thanks for the clarification :-D

Cheers
