### ISSUE TITLE
XSS Attack Vector

### ISSUE THREAD

**Issue by digitalkaoz** [apidoc/apidoc#263]
if my response content contains markup it will be evaluated:

```json
{            
    "html": "<script>alert(window.location.href)</script>"
}
```

the `preview` of the response for the response lacks proper escaping

**Comment by rottmann** [comment]
Don't see the problem. You can only harm somebody if you add this to your own app (doc) on your own server. The same you can do with any own hosted html page.

**Comment by digitalkaoz** [comment]
na i cant safely display `html` in json responses...

**Comment by rottmann** [comment]
But html on you page from you api. Or did you use an external api?

**Comment by digitalkaoz** [comment]
yeah but what if api returns html from a different server?
