### ISSUE TITLE
@apiSampleRequest with several @apiGroup don't works

### ISSUE THREAD

**Issue by warn974** [apidoc/apidoc#268]
Hi, 
I have a problem when I add at least two @apiGroup in my apidoc, the @apiSampleRequest  don't works except for the last @apiGroup.

In fact all http requests are send but all params are empty. 

Exemple field for @apiGroup Category (that don't work)

``` html
﻿<input placeholder="category_id" class="input-xxlarge sample-request-param" data-sample-request-param-name="category_id" data-sample-request-param-group="sample-request-param-0" type="text">
```

Exemple field for @apiGroup User (that work)

``` html
<input placeholder="cart_id" class="input-xxlarge sample-request-param" data-sample-request-param-name="cart_id" data-sample-request-param-group="sample-request-param-0" type="text">
```

I use apidoc@0.13.1

Have you any idea of my problem ? 

Regards,

**Comment by hynese** [comment]
:+1:

**Comment by NicolasCARPi** [comment]
No longer an issue.
