### ISSUE TITLE
@apiSampleRequest confusion

### ISSUE THREAD

**Issue by hynese** [apidoc/apidoc#271]
Hello,

I'm trying to get @apiExample to work.

Here's my annotation:

```
/**
  * @api {GET} /user/:id request specific User
  * @apiSampleRequest /user 
  *
  * @apiName getUser
  * @apiGroup User
  *
  * @apiExample {curl} Example usage:
  *     curl -i http://localhost/eamorr/api/user/4711
  *
  * @apiParam {Number} id User unique ID
  *
  * @apiSuccess {String} json User object
  *
  */
```

Unfortunately, when I create the docs and click on the "Send" button to test the call, it doesn't  

`https://localhost/eamorr/api/user/4711` 

instead it calls:

`http://localhost/user?{%22id%22:%224711%22}` (this is wrong)

It also sends `{"id":"4711"}` in the GET payload...

I'm confused and I can't get it to work...

**Comment by warn974** [comment]
Hi,

If you analyze your request, it's an OPTIONS method which is send, and in his header you have a param call 'Access-Control-Request-Method' that contains the type of the original request.

In my case I have only activated CORS in a middleware in my Node.js server, I use ExpressJS. 

This should help you : http://enable-cors.org/server_expressjs.html

**Comment by hynese** [comment]
Hello,

Thank you for this very useful answer. I enabled CORS on my Apache server and a GET request is now correctly being sent! Great.

I wonder, now that you're here!, if you could please answer another, related question?

I notice that when I click on the "Send" button, I notice (from Firebug) that the following request is sent:

`https://localhost/eamorr/api/user?{%22id%22:%221234%22}` (i.e. an "id" key/value is embedded in a JSON string)

I have my server set up so that it should respond to:

`https://localhost/eamorr/api/user/1234`

I wonder do you have any suggestions?

Thank you,

**Comment by YadrovSergey** [comment]
I have the same problem.
