### ISSUE TITLE
-bash: apidoc: command not found

### ISSUE THREAD

**Issue by jabr9983** [apidoc/apidoc#277]
I have been following the process for installing apidoc but it won't let me use it after installing and verifying the path. Has anyone else had this issue?

**Comment by chateauv** [comment]
Have installed the module in my project but running apidoc command gives me command not found. So I added the path to my Windows Env path and now when typing apidoc -h I get /usr/bin/env: node: No such file of directlory. Do I need to hcnage this line in the apidoc file ? What/where its should be pointing to ?

**Comment by veken1199** [comment]
I have the same issue now, @jbrauchler I wonder if you found a solution for that. it has been like 2 years lol

**Comment by akstrifork** [comment]
You can find the binary in the node_modules somewhere, like this: 
`node_modules/apidoc/bin/apidoc ...`

**Comment by Zoro916** [comment]
I have the same issue now...the version of Node?

**Comment by WillZt** [comment]
You need to configure environment variables if  you use Windows, like that add "C:\Users\Administrator\AppData\Roaming\npm" to "Path".

**Comment by Zoro916** [comment]
@WillZt I use Mac os.
