### ISSUE TITLE
Recurring custom types

### ISSUE THREAD

**Issue by RomkeVdMeulen** [apidoc/apidoc#278]
I'm working on an API that sometimes returns multiple levels of nested data. Some of the data consists of types that are used multiple times. Right now I'm using this construction to re-use return types multiple times:

```
/**
 * @api {get} /getMultiple
 * @apiUse TopLevelType
 */
```

```
/**
 * @apiUse SubLevelType
 *
 * @apiDefine TopLevelType
 * @apiSuccess {SubLevelType[]} sublevelItems A collection of items of recurring type
 */
```

```
/**
 * @apiDefine SubLevelType Type: SubLevelType
 * @ApiSuccess (SubLevelType) {String} subpropertyOne This is a string
 * @ApiSuccess (SubLevelType) {Number} subpropertyTwo This is a number
 */
```

This way my recurring SubLevelType is in a separate group, and I can include it again elsewhere:

```
/**
 * @api {get} /getOne
 * @apiUse SubLevelType
 * @apiSuccess {SubLevelType} singleItem A single item of recurring type
 */
```

However I can only go so deep using define and use before it stops working. Besides, I don't think this is how I'm supposed to use `@apiSuccess` and groups.

Is there a better way of defining recurring types? I like the way [Swagger](http://editor.swagger.io/) does it, with the schema of custom types mentioned in the API resource description, as well as a list of all custom types at the bottom.

**Comment by rottmann** [comment]
Correct, the group name was only for inheriting / naming things.
A type or custom type system is not implemented yet, i will watch swagger for this too (not invent the complete wheel again).

**Comment by Romke-vd-Meulen** [comment]
Thank you for your quick response!

**Comment by pascalopitz** [comment]
Any more thoughts on this. Would need something like this too :/

**Comment by Zodiase** [comment]
Any particular reason this `todo` is closed?

**Comment by ftoulemon** [comment]
Same need.
Here is a workaround:

- Define your type as a new API in a dedicated `apiGroup`
- Add a link where you use it

Example:

Definition:

```
@api {OBJECT} MyObject MyObject
@apiGroup Custom types
[...]
```

Use:
```

[...]
@apiParam {[MyObject}(#api-Custom_types-ObjectMyobject)} objectParam Description
[...]
```

(And you can use [order](http://apidocjs.com/#configuration) to have the "Custom type" section on top.)

**Comment by henhal** [comment]
Same need, and new to apidoc. @ftoulemon, any chance you could show an example of the rendered result of that workaround?

**Comment by ftoulemon** [comment]
I fixed the typo in my previous comment.
Here is the example:

```
"""
@api {OBJECT} Event Event
@apiGroup Custom types
@apiVersion 1.1.7
@apiParam {Number} _id ID.
@apiParam {Boolean} activated Activation status.
@apiParam {String="Alarm", "Information", "Warning", "Error"} type Event type.
"""

"""
@api {Get} url/getEvent Get Event
@apiDescription Small description
@apiVersion 1.1.7
@apiGroup Event group
@apiParam {Integer} Event ID
@apiSuccess {[Event](#api-Custom_types-ObjectEvent)} events The requested event(s).
"""
```

Output:

![output](https://i.imgur.com/j7mNkDC.png)

https://imgur.com/a/NfgKR

**Comment by fracz** [comment]
While the workaround is somewhat sufficient, I think this issue should not be considered closed because it's still only workaround with hacky definition like `@apiSuccess {[Event](#api-Custom_types-ObjectEvent)}`.

**Comment by Yooooomi** [comment]
Still needed, having the possibility to declare custom types and array of custom type would be great.

For now, the user has to click to see the type, it is not explained under the request

**Comment by NicolasCARPi** [comment]
@Yooooomi Pull requests are welcome.

**Comment by demonly** [comment]
I use jsdoc with apidoc to resolve this.
Define types with jsdoc, and use a extend filter to transform all non-built-in types to a link to jsdoc type definition.

Example:
```javascript
/**
 * @api example This is a example.
 * @apiParam {Bar} bar A example parameter.
 * @apiSuccess {Number} code code
 */
```
```bash
apidoc -i src -e node_modules -o apidoc/ --parse-filters apitype=./apidocExtend/filters/api_type.js
```
Output:
```html
<a href="../jsdocs/global.html#Bar">Bar</a>
```

Here is the extend filter.
api_type.js
```javascript
const internalTypes = ['string', 'array', 'number', 'object', 'null', 'boolean', 'bool', 'num', 'str', 'obj'];

function parseType(type) {
  return type.replace(/(?:(\w+)([#.~]))?(\w+)/gim, (str, namespace = 'global', opreator = '', name) => {
    if (internalTypes.includes(name.toLowerCase())) {
      return type;
    }
   // link to another document built by jsdoc
    return `<a href="../jsdocs/${namespace}.html#${opreator}${name}">${str}</a>`;
  });
}

function postFilter(parsedFiles) {
  const tagNames = ['success', 'parameter'];

  parsedFiles.forEach(function (parsedFile) {
    parsedFile.forEach(function (block) {
      tagNames.forEach((tagName) => {
        if (block.local[tagName] && block.local[tagName].fields) {
          const { fields } = block.local[tagName];
          Object.values(fields).forEach((field) => {
            field.forEach((tag) => {
              tag.type = parseType(tag.type);
            });
          });
        }
      });
    });
  });
}
```

**Comment by Ajuriaa** [comment]
> I fixed the typo in my previous comment. Here is the example:
> 
> ```
> """
> @api {OBJECT} Event Event
> @apiGroup Custom types
> @apiVersion 1.1.7
> @apiParam {Number} _id ID.
> @apiParam {Boolean} activated Activation status.
> @apiParam {String="Alarm", "Information", "Warning", "Error"} type Event type.
> """
> 
> """
> @api {Get} url/getEvent Get Event
> @apiDescription Small description
> @apiVersion 1.1.7
> @apiGroup Event group
> @apiParam {Integer} Event ID
> @apiSuccess {[Event](#api-Custom_types-ObjectEvent)} events The requested event(s).
> """
> ```

is there a new way to do this??? currently the object declaration part still works, but the hyperlink hacky `@apiSuccess {[Event](#api-Custom_types-ObjectEvent)}` no longer works, it returns 
`warn: The use of square brackets for object properties is deprecated. Please use dot notation instead: "@apiSuccess {[driver](#api-Interfaces-ObjectIdriver)} driver The requested driver."` and it does not get rendered. :(
