### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by jabr9983** [apidoc/apidoc#279]
error: Undefined error. 
{ File: 'TodoApiDocJs/node_modules/swagger-tools/node_modules/superagent/lib/node/response.js',
  Block: 3,
  Element: '@constructor',
  Source: '@constructor\n@extends {Stream}' }

This is all I am getting for an error what do I need to do to solve this kind of thing?

**Comment by rottmann** [comment]
exclude the node_modules path with `-e`

**Comment by jabr9983** [comment]
So I should be able to just run apidoc -i TodoApiDocJs/ -o apidoc -e=/node_modules/swagger-tools/node_modules/superagent/lib/node/response.js and it would solve the issue then correct?

**Comment by rottmann** [comment]
You can exclude the the complete node_modules dir, or did it include any apidoc-annotation ?

**Comment by jabr9983** [comment]
It didn't include any apidoc annotation as far as I know I am new to epidoc so, just trying to figure everything out.

**Comment by jabr9983** [comment]
That seems to have worked thanks
