### ISSUE TITLE
ApiGroup description

### ISSUE THREAD

**Issue by jpcaruana** [apidoc/apidoc#28]
it would be great to have an @apiGroupDescription that would behave the same as @apiDescription but that wound be displayed at the beginning of a group section.

**Comment by laurent22** [comment]
Unfortunately, the apiGroupDescription tag seems to be have removed, but not sure what it has been replaced with. Anyone knows?

**Comment by rottmann** [comment]
Use @apiDefine to define a Groupname with a Title and optional Description.

I will extend @apiGroup to include the Title and Description directly with apiGroup.

**Comment by laurent22** [comment]
@rottmann, that's great I got it working apiDefine. Thanks a lot!
