### ISSUE TITLE
worng parsing non-english characters in @apiGroup

### ISSUE THREAD

**Issue by deadman2000** [apidoc/apidoc#282]
all non-english characters in @apiGroup replaced by "_"  symbols
![screen](https://cloud.githubusercontent.com/assets/12889180/8156971/0afaeb76-137b-11e5-975c-a5b67c933293.png)

/**
- @api {get} /user/:id Запрос состояния
- @apiName GetUser
- @apiGroup ЮЗЕР
  *
- @apiParam {Number} id Users unique ID.
  *
- @apiSuccess {String} firstname Firstname of the User.
- @apiSuccess {String} lastname  Lastname of the User.
  *
- @apiSuccessExample Success-Response:
-     HTTP/1.1 200 OK
-     {
-       "firstname": "John",
-       "lastname": "Doe"
-     }
  *
- @apiError UserNotFound The id of the User was not found.
  *
- @apiErrorExample Error-Response:
-     HTTP/1.1 404 Not Found
-     {
-       "error": "UserNotFound"
-     }
  */

**Comment by rottmann** [comment]
That is correct, all names are currenlty not Unicode ready.

**Comment by deadman2000** [comment]
it will be corrected in future?

**Comment by rottmann** [comment]
yes

**Comment by wind930** [comment]
@deadman2000 @rottmann 
i have the same issues recently, but i found some code in 
- apidoc-core/lib/workers/api_group.js 
- apidoc-core/lib/workers/api_name.js 

```javascript
//replace special chars
//group = group.replace(/[^\w]/g, '_');
```

```javascript
      // replace special chars
     //name = name.replace(/[^\w]/g, '_');
```

it works when i noted this line

<img width="1354" alt="2015-07-19 17 36 36" src="https://cloud.githubusercontent.com/assets/6129347/8765404/ef186000-2e3c-11e5-9630-adbfa8c437fc.png">

If your intention is to replace special characters (perhaps initially you just want to replace the non English characters), but the rule is you make, so maybe now you can remove this line of code, to ensure that the various language can work normally
If I say no wrong, I don't know if you can fix this problem.
Thank you!

**Comment by sp0ker** [comment]
Hi,
I have still the problem. Does anyone know how fix this issue ?

**Comment by NicolasCARPi** [comment]
Support for special characters will come in a future release (hopefully).
