### ISSUE TITLE
apidcoc documenting unnecessary files

### ISSUE THREAD

**Issue by jabr9983** [apidoc/apidoc#283]
When I run apidoc it is trying to document files that have my express modules and such in them but have no documentation. I have tried using the exclude command and that allows me to run apidocs properly but still includes those documents in the documentation. Does anyone know a way to fix this?

**Comment by KrisSiegel** [comment]
I just ran into this exact issue; if you have a fix or figured out your issue it is helpful to post information about it instead of just closing it.

![image](https://cloud.githubusercontent.com/assets/1885826/8993945/3360d552-36d6-11e5-92c0-733ad66421cb.png)

**Comment by KrisSiegel** [comment]
Oh I see this is problem a duplicate of #281?

**Comment by KrisSiegel** [comment]
Just for reference if someone else lands here: the fix is documented under #109. Basically ```-e``` is expecting a regex, not a path, and is currently not documented.
