### ISSUE TITLE
Is there a way to set the language in the apidoc.js?

### ISSUE THREAD

**Issue by artvel** [apidoc/apidoc#284]
The default language seems to be german but I would like to change it to english.

**Comment by rottmann** [comment]
The default Lanuage is english, the template has an auto-detect and switches to the browsers language.

In `apidoc.json` set `template.forceLanguage: "en"` to disable auto-detect and force a language.

**Comment by artvel** [comment]
Thx very much for the great support, it is just like you said. The auto-detection was it, but we just have a simple api documention where we described everything in english.
Therefore template.forceLanguage is the right solution for us.
