### ISSUE TITLE
Setting and sending optional parameter goes differently

### ISSUE THREAD

**Issue by sincerekamal** [apidoc/apidoc#285]
Hi,

In my API documentation, I added below line

````  @apiParam [query1] ````

to make query1 as optional parameter. In my Node.js, I'm trying to fetch the value using req.param('query1').

In the APIDOC generated webpage,

1. If I pass ```` query1 ```` in the url, I could able to get the value.

2. But If I pass the ```` query1 ```` value in the parameter textbox,  it's ```` undefined ````. When I tried debugging, the ```` console.log(req.query) ```` outputted as  ```` { '{"query1":"true"}': '' } ````

**Comment by rottmann** [comment]
The send sample request is a very basic add-on from a contributor and it will be replaced.

**Comment by davestewart** [comment]
I assume that replacing this will catch multiple, empty, optional arguments...

`/users/:page/:items`

...generating this kind of URL:

`http://localhost:8000/users//?{}`

?

PS.. What is the `?{}` that seems to get passed the whole time?
