### ISSUE TITLE
How to document one of a set of possible params to a single endpoint

### ISSUE THREAD

**Issue by skypanther** [apidoc/apidoc#286]
I'm documenting an existing API. An endpoint requires one of three querystring parameters (multiple params would not be accepted). What is the correct way to specify this in the code comments?

```
http://foo.example/endpoint?id=123
http://foo.example/endpoint?name=bar
http://foo.example/endpoint?code=1a2b3c
```

I have tried documenting it four ways, none of which worked:

This gave me an `error: Empty parser result.` error: 
```
 * @apiParam [{String}] id   Unique ID
 * @apiParam [{String}] name Friendly name
 * @apiParam [{String}] code  Customer code
```

I got the same error with: 
```
 * @apiParam {String|String|String} id|name|code   Unique ID, friendly name, or customer code
```

This treated the `id` as the param name and put name|code at the beginning of the description:
```
 * @apiParam {String} id|name|code   Unique ID, friendly name, or customer code
```

I also tried creating three separate doc blocks each listing a single required param. This showed just the first and ignored the two "duplicates" in the resulting output.

I looked at some JavaDoc resources and don't see a way to document this case. So, perhaps it's not supported.

**Comment by liko28s** [comment]
this is how to write optional parameters, however it is not an "exclusive or"
```
* @apiParam {String} [id] Unique ID
* @apiParam {String} [name] customer code
* @apiParam {String} [code] Friendly name 
```

**Comment by skypanther** [comment]
I've found the solution in #115 

```
/**
     * @api {get} /endpoint Endpoint description
     *
     * @apiParam {String=val1, val2, val3} parameterName Your description 
     *
*/
```

Outputs:

### Parameters

|Field | Type | Description|
|-----|----|----|
|parameterName | String | Your description<br/>Allowed values: `val2`, `val2`, `val3`

**Comment by valtido** [comment]
Shouldn't list of val(s) be wrapped in "? "val1", ...
