### ISSUE TITLE
@apiDefine issue

### ISSUE THREAD

**Issue by NikolayGalkin** [apidoc/apidoc#288]
Hi,

I have one question. Does apiDoc support @apiDefine in separate file? For example, I have two files: errors.js and controller.js written in Node.js. Controller.js requires errors.js file. So the main idea is to define all HTTPErrors in errors.js file with @apiDefine but include them via @apiUse in controller.js For now it's not working for me :(

Thanks

**Comment by rottmann** [comment]
Yes, view https://github.com/apidoc/apidocjs.com/tree/gh-pages/source/example_full

`@apiDefine CreateUserError` is defined in `_apidoc.js` and used in `example.js`.

**Comment by NikolayGalkin** [comment]
Sorry! You are right! Need more read documentation and examples. Thanks!

**Comment by FujiBilly** [comment]
should I require _apidoc.js in example.js??
