### ISSUE TITLE
Force English to be as only doc language

### ISSUE THREAD

**Issue by voronianski** [apidoc/apidoc#289]
Is is possible to force apidoc to make all documentation title, button names etc. in English? 

Somehow generated doc have all titles in my native language:

![](https://dl.dropboxusercontent.com/u/100463011/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-06-19%20%D0%B2%2018.04.35.png)

Thanks!

**Comment by rottmann** [comment]
Yes, look at https://github.com/apidoc/apidoc/issues/284
