### ISSUE TITLE
Add @apiDeprecated

### ISSUE THREAD

**Issue by reloaded** [apidoc/apidoc#290]
I think it would be extremely helpful if we had the ability to mark an API endpoint as deprecated and visually render it in the docs as deprecated.

**Comment by rottmann** [comment]
Already on [todo](https://github.com/apidoc/apidoc/wiki/ToDo) list.

**Comment by kytwb** [comment]
:+1: though.

**Comment by mik115** [comment]
Hi, 
Any news on when this feature will be included in the official release?

**Comment by massimiliano-delia** [comment]
Hello,
It would be great to having this in the next release. Any chance? :D
