### ISSUE TITLE
Default Template "article -> h1" using groupTitle instead of name

### ISSUE THREAD

**Issue by daviddpd** [apidoc/apidoc#294]
Testing this out to document an internal project I'm working on, it seems that each article had the same name (was ignoring "apiName").

Correct me if I'm wrong, but I think the desired result/output is suppose to have article.name in place of article.groupTitle.

```html
--- a/template/index.html
+++ b/template/index.html
@@ -98,7 +98,7 @@
 <script id="template-article" type="text/x-handlebars-template">
   <article id="api-{{article.group}}-{{article.name}}-{{article.version}}" {{#if hidden}}class="hide"{{/if}} data-group="{{article.group}}" data-name="{{article.name}}" data-version="{{article.version}}">
     <div class="pull-left">
-      <h1>{{article.groupTitle}}{{#if article.title}} - {{article.title}}{{/if}}</h1>
+      <h1>{{article.name}}{{#if article.title}} - {{article.title}}{{/if}}</h1>
     </div>
     {{#if template.withCompare}}
     <div class="pull-right">
```

**Comment by rottmann** [comment]
The name is only an identifier, on the other side output of the groupTitle was not the perfect solution.

**Comment by DannyvdSluijs** [comment]
+1 Would like to see this resolved.

**Comment by loevda** [comment]
I have the same issue. apiName is ignored. Any idea how to work around it?

**Comment by rcrooks** [comment]
I think you'd just have to modify the output template -- the data is there.

loevda wrote:

**Comment by loevda** [comment]
Thanks
Will try that. I was just hoping that I was doing something wrong.
