### ISSUE TITLE
Support non-english field name

### ISSUE THREAD

**Issue by yinrong** [apidoc/apidoc#295]
apidoc is great, but it does not allow field name to be non-english. Compilers support that, so I suppose apidoc should too.

Possible fix:
apidoc-core/lib/parsers/api_param.js
        name:                '(\\S+)', // 6

**Comment by yinrong** [comment]
In addition, I just found the group name can't be non-english too. Could you fix this too?

**Comment by rottmann** [comment]
Same as #282
