### ISSUE TITLE
Add custom CSS

### ISSUE THREAD

**Issue by wadmiraal** [apidoc/apidoc#296]
Is it possible to add a custom CSS file to the loaded HTML? Any plans to support it if not?

**Comment by rottmann** [comment]
Copy the template and modify it for your needs.
Or run a grunt/gulp task that adds you custom css to the generated css.

**Comment by wadmiraal** [comment]
Thanks for the quick reply.

I though about the Gulp/Grunt solution, but was wondering if there was a lighter solution. Like a setting.

For the template, what do you mean? I tell apidoc to look for the index.html somewhere (using the config file)? Or are you saying I modify what apidoc generates? Because I re-generate the documentation regularly; that wouldn't be an option, in my case.

**Comment by wadmiraal** [comment]
I went with a Gulp task in the end. A bit overkill for 10 lines of CSS, but
it works like a charm. Thanks for the great tool.
