### ISSUE TITLE
Group forum

### ISSUE THREAD

**Issue by jabr9983** [apidoc/apidoc#301]
I think it would be really beneficial to have a group forum for apidoc rather than just having people check here you might be able to get a little help with solving issues if you had a forum page.

**Comment by rottmann** [comment]
Good idea! Currently we have only the issues and the [Gitter Talk](https://gitter.im/apidoc/talk)

**Comment by jabr9983** [comment]
I was unaware of gitter talk thanks for sharing.

**Comment by destroyerofbuilds** [comment]
@jabr9983 is Gitter Talk sufficient for your needs? Can this issue be closed out?

**Comment by jabr9983** [comment]
yes sorry I forgot to close
