### ISSUE TITLE
Is the interactive doc working for folks?

### ISSUE THREAD

**Issue by jhaaaa** [apidoc/apidoc#302]
I can't get it to return anything but "Error 0:"

At face value, the doc is accurate and I'm entering the correct Authorization value (it all works using cURL) -- but why isn't the call from the apidoc working?

Anyone run into this issue? I am guessing that it is a very simple solution -- I'm just missing it.

**Comment by jhaaaa** [comment]
I have an API that I can call using cURL and Postman. I configured the apidoc to call the API in exactly the same way.

When I make a call using the interactive doc piece, I am getting an "Error 0:" as the response. 

Can someone give me a hint as to what this error means?

**Comment by gaving** [comment]
Sounds like you're maybe running into #189 (requests sent as JSON instead of query strings) which as of yet hasn't been fixed in the core.

**Comment by jhaaaa** [comment]
Hi @gaving - thank you for the lead on #189! It sounds like it could also be #293 -- I am getting the log errors mentioned in the reply to my post. Perhaps once we get CORS enabled, I'll see #189. ;-) Thank you again!

**Comment by davestewart** [comment]
If using PHP add this script - it works right out of the box!

http://stackoverflow.com/questions/8719276/cors-with-php-headers#9866124

And enabled me to test this on my localhost setup :)
