### ISSUE TITLE
anyone can you add @apiQuery, @apiBody notations?

### ISSUE THREAD

**Issue by breaklee** [apidoc/apidoc#303]
i want to customize @apiQuery, @apiBody  tags in apidoc.

how can i add or anyone can help me?

**Comment by rottmann** [comment]
Create your api_query api_body js files.
View the parser, worker, filter for examples: https://github.com/apidoc/apidoc-core/tree/master/lib/

Small explanation (still not documented yet, my fault) https://github.com/apidoc/apidoc/issues/157#issuecomment-64324533

You can run apidoc then with
`apidoc -parse-parsers apiquery=./api_query.js --parse-parsers apibody=./api_body.js`

**Comment by Mech7** [comment]
Can @apiBody be a standard option? I needed this too.

**Comment by rottmann** [comment]
I try to keep apidoc as small an clean as possible. This year i added a plugin-functionality, so your requests could be implemented with a plugin.
An example you can find here: https://github.com/willfarrell/apidoc-plugin-schema
