### ISSUE TITLE
support RTL

### ISSUE THREAD

**Issue by ahmadina** [apidoc/apidoc#306]
Hi, Can i use RTL in apidoc?

**Comment by rottmann** [comment]
Don't know what exactly you mean.

**Comment by ahmadina** [comment]
apidoc support RTL?

**Comment by rottmann** [comment]
apidoc generates the doc from the code "as it is". To format the HTML-Page you can modify the template https://github.com/apidoc/apidoc/tree/master/template and use your modified template with `apidoc -t`

**Comment by arielhasidim** [comment]
+1 for RTL support.
For me as someone who writes documentations in Hebrew there is also a similar need for adaptation RTL support.
For the ux/ui to be RTL we need the whole UI-stracture should be the opposite right-to-left (side-menu element on the right etc) and direction + text-align attributes.
