### ISSUE TITLE
parser error :  plugin not found

### ISSUE THREAD

**Issue by antoine-gallix** [apidoc/apidoc#307]
While generating doc for my API, I recieve the following warning :

**Comment by rottmann** [comment]
Can you post the debug output `apidoc --debug`

**Comment by antoine-gallix** [comment]
Ok it was the parser was triggered by a comment in the previously generated
doc/main.js file. Only with the warning line, it was not clear where the
parsed did find the @api- command.

debug: inspect file: ./doc/main.js
debug: size: 23758
debug: count blocks: 9
debug: count elements in block 0: 3
debug: count elements in block 1: 0
debug: count elements in block 2: 0
debug: count elements in block 3: 0
debug: count elements in block 4: 0
debug: count elements in block 5: 0
debug: count elements in block 6: 0
debug: count elements in block 7: 0
debug: count elements in block 8: 4
debug: api found in block: 0
debug: found @apiSuccess in block: 0
debug: found @apiSuccess in block: 0
warn: parser plugin 'param' not found in block: 0

The problem is solved using the -f and -e options to restrict parsed files.


*Antoine*

**Comment by brunerson** [comment]
Hey there @antoine-gallix can you elaborate on how you got this to work? I am having the same problem.

**Comment by antoine-gallix** [comment]
The story is a little bit old, but I remember that you should specify the
minimal directory or file, that contain the source you want to generate doc
from, to prevent the parser to try to find markup in erroneous places. In
my case, the parser was looking into some previously generated doc file and
finding some @commands in it and crashing on it. -f allow to specify where
your api markup is located, -e to exclude directories from parsing. you can
see the help in apidoc --help

*Antoine*

**Comment by brunerson** [comment]
Thanks! This worked for me too.
