### ISSUE TITLE
Passing array parameters does not work

### ISSUE THREAD

**Issue by balauru** [apidoc/apidoc#309]
One of my params is declared as an array

```ruby
@apiParam {String[]} fields Array of fields to be included in the response
```

In the web interface no matter what I try the request will include the param as a string, the request looks like:

```curl
....collections/42/items?fields=123
```

instead of

```curl
collections/42/items?fields[]=123
```

**Comment by rottmann** [comment]
Sorry, the sample request module is not usable for "complex" requests at the moment.
Its on the todo list, will replace the plugin.
