### ISSUE TITLE
Order in generated json

### ISSUE THREAD

**Issue by CodersBrothers** [apidoc/apidoc#31]
I saw that the order of endopoints documentation are alphabetically. Thats cool... sometimes.

Will be more cool add a parm in documentation like @apiOrder 1
This will be cool to custom orders, or as simple like the order that you writte your documentation is the order that will be generated the JSON.

**Comment by isogram** [comment]
+1 . @apiOrder inside group

**Comment by njwangchuan** [comment]
+1

**Comment by williamknn** [comment]
This feature isn't implemented yet? So... +1

**Comment by Tinixi** [comment]
+1

**Comment by xuanskyer** [comment]
A stupid way: **Start with numbers**

like this: @apiGroup 1. group name

:)
