### ISSUE TITLE
Multiple @apiUses render in the wrong order

### ISSUE THREAD

**Issue by davestewart** [apidoc/apidoc#310]
Using multiple @apiUse tags appear to render in the wrong order.

Consider the following code:

```
/**
 * @apiDefine Status
 * @apiSuccess {Number}     status          The HTTP status of the call
 * @apiSuccess {String}     message         A human-friendly summary of the result of the call
 */

/**
 * @apiDefine Success
 * @apiSuccess {Number}     data.id         The user's id
 * @apiSuccess {String}     data.firstName  The user's first name
 * @apiSuccess {String}     data.lastName   The user's last name
 */

/**
 * @api {get}               /users          Request all users
 * @apiGroup user
 * @apiName all
 *
 * @apiParam {Number}       id              The id of the requested user
 * @apiParam {String}       name            The user's name
 *
 * @apiUse Status
 * @apiSuccess {Object[]}   data            An array of users
 * @apiUse Success
 */
$app->get('/users', '\\controllers\\UserController:all');
```

In the last section of the last DocBlock, I'm hoping to render:
- The default API status output
- A custom {Object[]} param
- The default output for all users in this REST group

However, The actual output order is:
- A custom {Object[]} param
- The default API status output
- The default output for all users in this REST group

The result is as follows:

![api-doc-api-use-issue](https://cloud.githubusercontent.com/assets/132681/8974040/f54aaa8e-3664-11e5-91de-38c6c2406340.png)

**Comment by taurenshi** [comment]
I came into the same issue. Is there any workaround?

**Comment by mauler** [comment]
https://github.com/apidoc/apidoc/pull/457
