### ISSUE TITLE
What do users of apidoc typically use to document non-RESTful APIs?

### ISSUE THREAD

**Issue by KrisSiegel** [apidoc/apidoc#311]
I haven't been able to find any answers or suggestions to this so figured this would be a good place to ask.

Essentially I'm working on a project that has multiple RESTful endpoints that we are documenting with apidoc which works great but it would be even better if we had a single location for documentation; what do people who use apidoc use for documenting methods / objects / etc?

Thanks!

**Comment by rottmann** [comment]
javadoc / jsdoc / phpdoc ...

**Comment by KrisSiegel** [comment]
That's the route we'll most likely need to take but having documentation in two different places in two different formats is not ideal. I really like apidoc but I'm not sure what the best solution will ultimately be.

**Comment by jaydenseric** [comment]
I use [JSDoc](http://usejsdoc.org). The two have a similar syntax for inline documentation and don't clash. Pretty sure both JSDoc and APIDoc allow you to do your own templating based off a JSON result. It would indeed be nice to see a package that compiles documentation based off both.

**Comment by rcrooks** [comment]
fyi, for the videojs 5 API docs (http://docs.videojs.com/docs/api/index.html), we did a hack on JSDoc to make it work for ES2015 code. This involved dispensing with native JSDoc templating and also the code inspection. We extracted and parsed just the comments (but retained code line numbers) and I then wrote a custom template for the JSON. You can find all the code at https://github.com/videojs/docs/ - some of the code is inevitably specific to videojs, but not much - I deliberately wrote it with the idea of porting it to other APIs.
