### ISSUE TITLE
Invalid information showing up as groups

### ISSUE THREAD

**Issue by KrisSiegel** [apidoc/apidoc#312]
I recently came across an issue when upon documentation generation multiple paths to files are being put into the generated documentation as groups. This also occured in a previous bug #281 (which I suspect is the same as #283) though it was unfortunately closed without resolution.

If you'll look closely at the screenshot below you'll notice that these files are literal paths, with the slash replaced with spaces, to files within the `./node_modules/` directory even though I am explicitly excluding those from being documented in my command which is as follows:

``` bash
apidoc -i ./ -o /Users/kris/Workspace/MyProject/docs -e ./node_modules/ -e ./public/ext-lib/
```

![image](https://cloud.githubusercontent.com/assets/1885826/8994145/950dacac-36d7-11e5-9738-7e6eaf46dcec.png)

**Comment by jabr9983** [comment]
I just created a separate project without having the node modules I know it isn't the most convenient fix but it gets rid of them at least.

**Comment by KrisSiegel** [comment]
Upon further review and research I have found #109 and removing the slash for node_modules makes it work.

This ticket needs to remain open and be resolved in a couple of ways, in my opinion.

1. I can't find any documentation for -e except in the changelog or if I search for other issues. This needs to be added to the website.

2. The changelog has an example of using -e which is as follows: ```apidoc -e node_modules/```. However, this information is wrong. So the only available "documentation" is outdated. Why is there no changelog outlining the change away from paths into using regular expressions? Or did that original example never work anyway?

3. You may want to revisit the way specifying directories / files works as I don't find regex intuitive; most projects simply let you specify paths.

**Comment by NicolasCARPi** [comment]
`apidoc -h` will tell you that it's a regex expected.

I agree that using a regex is not very user friendly but it can be seen as a feature as a regex is more powerful than a simple path.

Feel free to add a PR to apidoc-core repo for a new flag with paths only.
