### ISSUE TITLE
Various issues around optional parameters

### ISSUE THREAD

**Issue by davestewart** [apidoc/apidoc#313]
It seems that the functionality around optional parameters needs some work.

(I could make separate issues, but I suspect they are related)

Firstly, optional arguments set up in doc comments...

```
	/**
	 * @api {get}				/users/:page/:items			Request all users
	 * @apiGroup user
	 * @apiName all
	 *
	 * @apiParam {Number}		[page=1]		The page from which to start the query
	 * @apiParam {Number}		[items=10]		The number of items to return per page
	 */
```
... have the following issues:

1) the default values don't appear in the form generated by the sampleUrl.

2) if the form *is* submitted with empty fields, the URL is malformed (`http://localhost:8000/users//`) so returns a 404 in my app

3) There is no classname or other attribute in the template to indicate to JavaScript that these fields are flagged as optional, so any URL should be built appropriately

4) unrelated, but what is the `?{}` at the end of the generated URL?

Thanks,
Dave

**Comment by rottmann** [comment]
Stop using the Sample Request function, it was a rudimentary add-on for a simple post to an URL. This module will be replaced.

**Comment by davestewart** [comment]
This is one of the standout best features of APIDoc - testing your documented parameters - so I probably won't stop using it.

With regards to your comment about it being replaced, is there a timescale?

Or is there any point getting involved myself?

**Comment by rottmann** [comment]
Pull Request are welcome :-)  There is no timescale, currently house renovation and family take all of my free time.

**Comment by davestewart** [comment]
Yes, I know how that is!

I would be very glad to help (assuming I get time as well!).

If you could:

a) point me to the relevant parts in the APIDoc code
b) let me know if there are any contribution guidelines (code style, plugin architecture, etc)

That would help!

Thanks,
Dave
