### ISSUE TITLE
parser plugin 'return'

### ISSUE THREAD

**Issue by coderxlsn** [apidoc/apidoc#316]
warn: parser plugin 'return' not found in block: 3
warn: parser plugin 'param' not found in block: 3
warn: parser plugin 'return' not found in block: 3

text

@return \Zend\View\Model\JsonModel

**Comment by rottmann** [comment]
Did you mix javadoc with apidoc comments?

**Comment by YannDoW** [comment]
I had the same problem. You cannot mix Javadoc and Apidoc comments. Put them in two separate blocks and you'll be fine.

**Comment by coderxlsn** [comment]
No. I use php phpdoc

**Comment by YannDoW** [comment]
Same thing: don't mix phpdoc and apidoc. Put them in two separate comment blocks.
