### ISSUE TITLE
Separated git repo for outputted doc

### ISSUE THREAD

**Issue by kelckhyw21** [apidoc/apidoc#318]
I am going to make a separated git version control of outputted doc. So I outputted the doc in different directory, and make the directory be a new git repo. 

After I change sth and output again, git(sourcetree) only can locate the first line of `api_project.js`, `api_project.json`, `api_data.js` and `api_data.json` are changed but not the actual line. 

How to solve it?

**Comment by rottmann** [comment]
Sorry, did not understand this. Maybe a line ending encoding problem?
But not specific problem of apidoc.
