### ISSUE TITLE
How do I write an common API Group description?

### ISSUE THREAD

**Issue by YannDoW** [apidoc/apidoc#319]
I have a set of end points that belong to the same @apiGroup
I cannot find a way to write a description that would be inserted just after the group's main title and before the first end point. I need to write an introduction text about the whole set of end-points that belong to this group. I tried omitting the @api token but it won't work. Something like this:

```php
/**
* @apiGroup User
* @apiDescription These end-points allow you to deal with a user: reading its data and changing them. It requires authentication bla bla bla
*/

/**
* @api {get} /v1/user/:id Get a user data
* @apiGroup User
* @apiName get
* @apiDescription Get a user data by his id bla bla bla
*/

/**
* @api {post} /v1/user Add a user
* @apiGroup User
* @apiName post
* @apiDescription Add a user bla bla bla
*/
```

**Comment by rottmann** [comment]
@apiDescription is only for the method itself.

You can add a separte Block to describe the group

```
/**
 * @apiDefine User The Title.
 * Some Description.
 */

/**
 * @api {get} /v1/user/:id Get a user data
 * @apiGroup User
 * @apiName get
 * @apiDescription Get a user data by his id bla bla bla
 */
```

**Comment by YannDoW** [comment]
Excellent, this is exactly what I needed. Thanks!

**Comment by dozykeys** [comment]
Nice
