### ISSUE TITLE
api error name did not get parse correctly

### ISSUE THREAD

**Issue by yujinlim** [apidoc/apidoc#320]
Hi, I wanted to insert colon in between the error name, but apparently it get parse as separate words.

```
  /**
   * @apiDefine JsonHeaderError
   * @apiError AUTH:CHECK:HEADER_APPLICATION_JSON The <code>AUTH:CHECK:HEADER_APPLICATION_JSON</code> error, header application/type is not set to JSON
   * @apiErrorExample {json} Error-Response:
   *     {
   *     	 "error": "AUTH:CHECK:HEADER_APPLICATION_JSON"
   *     }
   */
```

it returns,

| Type         | Description |
| ------------- | ------------- |
| AUTH       | :CHECK:HEADER_APPLICATION_JSON The `AUTH:CHECK:HEADER_APPLICATION_JSON` error, header application/type is not set to JSON  |

**Comment by rottmann** [comment]
Only alphanumeric values are allowed for names at the moment.

**Comment by rottmann** [comment]
Addes support for : in 0.14.0.
