### ISSUE TITLE
Api Function Permissions

### ISSUE THREAD

**Issue by bhupinder7** [apidoc/apidoc#326]
Hi

Thank you creating this great tool. It is very good in terms creating documentation of rest API's in different languages.I was looking something like this from a long time. Actually, I have a requirement for my rest api to show particular api functions to particular clients. To elaborate, is it possible to do permission  based on which client should see which functions, and we as API creator will see every function ?

Thanks

**Comment by allayli** [comment]
Yes, I think it is possible. And looking forwards to this feature!

**Comment by rottmann** [comment]
You can write a js snippet (e.g. a Grunt task) that read the api_data.js/.json and remove all entries that has the permission "private" and write the remaining back to api_data.js/.json

In your source you must add on each function a permission:
```
/**
 * @api {get} /path Some Api
 * @apiPermission private
 * ...
 */

/**
 * @api {get} /path Some Api
 * @apiPermission public
 * ...
 */
```
