### ISSUE TITLE
How to show "General" navigation tab ?

### ISSUE THREAD

**Issue by bhupinder7** [apidoc/apidoc#328]
Hi I was looking in the example and came across a navigation tab on left side called "General".

http://apidocjs.com/example/#api-_

Just wondering how can i define this in my rest api as it does not reference any api function ?

**Comment by rottmann** [comment]
You can add a custom header / footer file. http://apidocjs.com/#headerfooter
The default title for the header in the navigation is General.

**Comment by bhupinder7** [comment]
thanks, i will give a try.
