### ISSUE TITLE
Is it possible to have multiline @api descriptions?

### ISSUE THREAD

**Issue by janusdn** [apidoc/apidoc#330]
Hi,

I am wondering if it is possible to have @api description across multiple lines.

I have somewhat long descriptions for the @api part which exceeds the limit of our coding standard. I have set up my IDE to automatically format the code according to standard, and so the IDE breaks the lines in two e.g.:
 
  * @api {put} endpoint/ Bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla
  *      bla bla bla bla. 

This result in only the last line being used as the description.

Thanks.

**Comment by rottmann** [comment]
For description use [`@apiDescription`](http://apidocjs.com/#param-api-description)

**Comment by janusdn** [comment]
Thanks.

**Comment by demisx** [comment]
I have this long line that exceed 120 chars triggers tslint warning. Can you please show me how I can break it into multiple lines? I've tried ` * @apiDescription {get} /kkk...`, but that didn't compile. Thanks!

```
 * @api {get} /kkk/:someCode/sss/:anotherCode/alis?[param1=:param1_value]&[param2=:param2_value]&[param3=:param3_value]&[ln=:languageCode]&[wfl=:workflowCode]... 1. Get ad list items
```
