### ISSUE TITLE
Error 200: SyntaxError: Unexpected token A

### ISSUE THREAD

**Issue by satyagvns** [apidoc/apidoc#331]
This happens all of sudden. I am not able to get this error in google.

My comments were:

/**
* @api {POST} /APINAME API COMMENTS
* @apiName APINAME
* @apiGroup General
* @apiVersion 1.1.0
* @apiDescription Display API RESULTS
* @apiSampleRequest <Request URL>
* @apiParam {String} params1 
* @apiParam {String} params2
* @apiParamExample {json} Request-Example:
*        {
*            JSON Strings
*        }
* @apiSuccessExample {json} Success-Response :
*        {
*            JSON Strings
*        }
**/

**Comment by rottmann** [comment]
```
/**
 * @api {POST} /APINAME API COMMENTS
 * @apiName APINAME
 * @apiGroup General
 * @apiVersion 1.1.0
 * @apiDescription Display API RESULTS
 * @apiSampleRequest
 * @apiParam {String} params1
 * @apiParam {String} params2
 * @apiParamExample {json} Request-Example:
 * {
 *     JSON Strings
 * }
 * @apiSuccessExample {json} Success-Response:
 * {
 *     JSON Strings
 * }
 */
```

**Comment by satyagvns** [comment]
Same I have used in my comments. I request could you please tell me the difference

**Comment by rottmann** [comment]
It is the same. Check /* * */

**Comment by satyagvns** [comment]
Thanks @rottmann.

I need your help on below comments

/**
 * @api {GET} /APINAME1 API COMMENTS
 * @apiName APINAME1
 * @apiGroup General
 * @apiVersion 1.1.0
 * @apiDescription Display API RESULTS
 * @apiSampleRequest
 * @apiParam {String} params1
 * @apiParam {String} params2
 * @apiParamExample {json} Request-Example:
 * {
 *     JSON Strings
 * }
 * @apiSuccessExample {json} Success-Response:
 * {
 *     JSON Strings
 * }
 */
 =================================================
/**
 * @api {POST} /APINAME2 API COMMENTS
 * @apiName APINAME2
 * @apiGroup General
 * @apiVersion 1.1.0
 * @apiDescription Display API RESULTS
 * @apiSampleRequest
 * @apiParam {String} params1
 * @apiParam {String} params2
 * @apiParamExample {json} Request-Example:
 * {
 *     JSON Strings
 * }
 * @apiSuccessExample {json} Success-Response:
 * {
 *     JSON Strings
 * }
 */

when I change some values in first section and second section. But the values are getting changed in the first section not in the second section.

I request what change that i have to do in the second section to make work proper

Thanks,
Satya

**Comment by rottmann** [comment]
Please use 3 \`\`\` to wrap your code.

Each block must be separated with own /** start */ end comments.

**Comment by satyagvns** [comment]
Hi Rottmann,

I request could you please explain it with my above example.

Regards,
Satya

**Comment by rottmann** [comment]
```
/**
 * @api {GET} /APINAME1 API COMMENTS
 * @apiName APINAME1
 * @apiGroup General
 * @apiVersion 1.1.0
 * @apiDescription Display API RESULTS
 * @apiSampleRequest
 * @apiParam {String} params1
 * @apiParam {String} params2
 * @apiParamExample {json} Request-Example:
 * {
 *     JSON Strings
 * }
 * @apiSuccessExample {json} Success-Response:
 * {
 *     JSON Strings
 * }
 */

/**
 * @api {POST} /APINAME2 API COMMENTS
 * @apiName APINAME2
 * @apiGroup General
 * @apiVersion 1.1.0
 * @apiDescription Display API RESULTS
 * @apiSampleRequest
 * @apiParam {String} params1
 * @apiParam {String} params2
 * @apiParamExample {json} Request-Example:
 * {
 *     JSON Strings
 * }
 * @apiSuccessExample {json} Success-Response:
 * {
 *     JSON Strings
 * }
 */
```
