### ISSUE TITLE
Order of apiSuccess/apiError/apiUse

### ISSUE THREAD

**Issue by kenyiu** [apidoc/apidoc#333]
hi there, am wondering if there are any methods for me to arrange the order of apiSuccess/apiError/apiUse? 
I have something like this:

```
@apiUse InvalidParameters

@apiError (404 NOT FOUND) {Object}   data
...
```

I was hoping the `InvalidParameters` comes earlier than `404 NOT FOUND`, but it turns out to be another way round.

Thanks in advance.

**Comment by rottmann** [comment]
No there is currently no order for this. Added it to [todo](https://github.com/apidoc/apidoc/wiki/ToDo)

**Comment by MathynMovin** [comment]
Any updates on this issue? Not using the order in which @apiUse tags are defined decreases the usability of these tags quite a lot.

**Comment by bryceliu** [comment]
+1

**Comment by mauler** [comment]
@kenyiu  check if this solves your problem:
https://github.com/apidoc/apidoc/pull/457

**Comment by guirip** [comment]
Hey
Sorry to wake up an old topic, maybe I should have started a new one (tell me).

From what I've read [here](http://apidocjs.com/#configuration), `order` configuration should allow to define the order in which the elements appear in the generated documentation.

My configuration is in the `package.json` file, and properly read from there (as I can update the description/etc), but the `order` attribute I set has absolutely no effect:

`    "order": [
      "Name",
      "Permission",
      "Param",
      "Success",
      "Error",
      "Example"
    ]
`

What am I missing ?

I am using `apidoc@0.17.6` with `node@8.5.0`.

**Comment by NicolasCARPi** [comment]
Order should now be how it was defined in the source code.

You can try the current `dev` branch: `npm i -g apidoc/apidoc#dev`. See also #999.
