### ISSUE TITLE
apidoc cli command doesn't work

### ISSUE THREAD

**Issue by mvucinic** [apidoc/apidoc#338]
I have tried couple of variations of cli apidoc command, but all of them resolve into same error:

```sh
error: No files found. 
{ Path: './' }
```

I have tried:
  -  apidoc
  -  apidoc -i "./"
  -  apidoc -i "/Users/MyUser/Myrepo/"
 
Help?

**Comment by rcrooks** [comment]
do you have an apidoc.json file? the docs say that is optional, but I couldn't get it to work without one.

**Comment by shineycoding** [comment]
@rottmann I’m the same problem, windows 7 OS

**Comment by shineycoding** [comment]
@rottmann 
D:\JAVA
λ apidoc -i myapp/ -o apidoc/ -t mytemplate/
warn: Please create an apidoc.json configuration file.
error: No files found.
{ Path: '.' }

**Comment by rottmann** [comment]
Can you post the debug output `--debug`

**Comment by shineycoding** [comment]
@rottmann 
D:\JAVA
λ apidoc -i myapp/ -o apidoc/ -t mytemplate/ --debug
debug: package.json not found!
debug: apidoc.json not found!
warn: Please create an apidoc.json configuration file.
verbose: apidoc-generator name: apidoc
verbose: apidoc-generator version: 0.13.1
verbose: apidoc-core version: 0.4.1
verbose: apidoc-spec version: 0.2.0
debug: load parser language: .clj, ./languages/clj.js
debug: load parser language: .coffee, ./languages/coffee.js
debug: load parser language: .erl, ./languages/erl.js
debug: load parser language: .litcoffee, ./languages/coffee.js
debug: load parser language: .pm, ./languages/pm.js
debug: load parser language: .py, ./languages/py.js
debug: load parser language: .rb, ./languages/rb.js
debug: load parser language: default, ./languages/default.js
debug: load parser: api, ./parsers/api.js
debug: load parser: apidefine, ./parsers/api_define.js
debug: load parser: apidescription, ./parsers/api_description.js
debug: load parser: apierror, ./parsers/api_error.js
debug: load parser: apierrorexample, ./parsers/api_error_example.js
debug: load parser: apiexample, ./parsers/api_example.js
debug: load parser: apiheader, ./parsers/api_header.js
debug: load parser: apiheaderexample, ./parsers/api_header_example.js
debug: load parser: apigroup, ./parsers/api_group.js
debug: load parser: apiname, ./parsers/api_name.js
debug: load parser: apiparam, ./parsers/api_param.js
debug: load parser: apiparamexample, ./parsers/api_param_example.js
debug: load parser: apipermission, ./parsers/api_permission.js
debug: load parser: apisuccess, ./parsers/api_success.js
debug: load parser: apisuccessexample, ./parsers/api_success_example.js
debug: load parser: apiuse, ./parsers/api_use.js
debug: load parser: apiversion, ./parsers/api_version.js
debug: load parser: apisamplerequest, ./parsers/api_sample_request.js
debug: load worker: apierrorstructure, ./workers/api_error_structure.js
debug: load worker: apierrortitle, ./workers/api_error_title.js
debug: load worker: apigroup, ./workers/api_group.js
debug: load worker: apiheaderstructure, ./workers/api_header_structure.js
debug: load worker: apiheadertitle, ./workers/api_header_title.js
debug: load worker: apiname, ./workers/api_name.js
debug: load worker: apiparamtitle, ./workers/api_param_title.js
debug: load worker: apipermission, ./workers/api_permission.js
debug: load worker: apisamplerequest, ./workers/api_sample_request.js
debug: load worker: apistructure, ./workers/api_structure.js
debug: load worker: apisuccessstructure, ./workers/api_success_structure.js
debug: load worker: apisuccesstitle, ./workers/api_success_title.js
debug: load worker: apiuse, ./workers/api_use.js
debug: load filter: apierror, ./filters/api_error.js
debug: load filter: apiheader, ./filters/api_header.js
debug: load filter: apiparam, ./filters/api_param.js
debug: load filter: apisuccess, ./filters/api_success.js
verbose: run parser
error: No files found.
{ Path: '.' }

**Comment by rottmann** [comment]
The file extension is '.java' (lowercase) ?

**Comment by kubp** [comment]
@rottmann I have the same problem.

**Comment by rottmann** [comment]
Can you post an example file (or send me by mail)?

**Comment by kubp** [comment]
@rottmann I just made example.js
```
/**
 * @api {get} /user/:id Request User information
 * @apiName GetUser
 * @apiGroup User
 *
 * @apiParam {Number} id Users unique ID.
 *
 * @apiSuccess {String} firstname Firstname of the User.
 * @apiSuccess {String} lastname  Lastname of the User.
 */
```

I ran
```
sudo npm uninstall -g apidoc
sudo npm install -g apidoc
```
and everything works fine now

**Comment by juanimarchese** [comment]
Hey, Im having this same problem!

**Comment by juanimarchese** [comment]
debug: read: package.json
debug: read: apidoc.json
verbose: apidoc-generator name: apidoc
verbose: apidoc-generator version: 0.16.1
verbose: apidoc-core version: 0.7.1
verbose: apidoc-spec version: 0.2.0
debug: No plugins found.
debug: load parser language: .clj, ./languages/clj.js
debug: load parser language: .coffee, ./languages/coffee.js
debug: load parser language: .erl, ./languages/erl.js
debug: load parser language: .ex, ./languages/ex.js
debug: load parser language: .exs, ./languages/ex.js
debug: load parser language: .litcoffee, ./languages/coffee.js
debug: load parser language: .lua, ./languages/lua.js
debug: load parser language: .pm, ./languages/pm.js
debug: load parser language: .py, ./languages/py.js
debug: load parser language: .rb, ./languages/rb.js
debug: load parser language: default, ./languages/default.js
debug: load parser: api, ./parsers/api.js
debug: load parser: apidefine, ./parsers/api_define.js
debug: load parser: apidescription, ./parsers/api_description.js
debug: load parser: apierror, ./parsers/api_error.js
debug: load parser: apierrorexample, ./parsers/api_error_example.js
debug: load parser: apiexample, ./parsers/api_example.js
debug: load parser: apiheader, ./parsers/api_header.js
debug: load parser: apiheaderexample, ./parsers/api_header_example.js
debug: load parser: apigroup, ./parsers/api_group.js
debug: load parser: apiname, ./parsers/api_name.js
debug: load parser: apiparam, ./parsers/api_param.js
debug: load parser: apiparamexample, ./parsers/api_param_example.js
debug: load parser: apipermission, ./parsers/api_permission.js
debug: load parser: apisuccess, ./parsers/api_success.js
debug: load parser: apisuccessexample, ./parsers/api_success_example.js
debug: load parser: apiuse, ./parsers/api_use.js
debug: load parser: apiversion, ./parsers/api_version.js
debug: load parser: apisamplerequest, ./parsers/api_sample_request.js
debug: load worker: apierrorstructure, ./workers/api_error_structure.js
debug: load worker: apierrortitle, ./workers/api_error_title.js
debug: load worker: apigroup, ./workers/api_group.js
debug: load worker: apiheaderstructure, ./workers/api_header_structure.js
debug: load worker: apiheadertitle, ./workers/api_header_title.js
debug: load worker: apiname, ./workers/api_name.js
debug: load worker: apiparamtitle, ./workers/api_param_title.js
debug: load worker: apipermission, ./workers/api_permission.js
debug: load worker: apisamplerequest, ./workers/api_sample_request.js
debug: load worker: apistructure, ./workers/api_structure.js
debug: load worker: apisuccessstructure, ./workers/api_success_structure.js
debug: load worker: apisuccesstitle, ./workers/api_success_title.js
debug: load worker: apiuse, ./workers/api_use.js
debug: load filter: apierror, ./filters/api_error.js
debug: load filter: apiheader, ./filters/api_header.js
debug: load filter: apiparam, ./filters/api_param.js
debug: load filter: apisuccess, ./filters/api_success.js
verbose: run parser
error: No files found. 
{ Path: '/pipeline/source/api/' }

**Comment by Oxicode** [comment]
+1 mismo problema

**Comment by Johz** [comment]
+1 
 warn: Please create an apidoc.json configuration file.
error: No files found.

**Comment by zimplexing** [comment]
+1 mismo problema

**Comment by juanimarchese** [comment]
Same problem here

**Comment by pushkeryadav** [comment]
I was also facing same problem in windows 10 OS , but then i checked that and find the regular expression i was passing was [copied reg from documentation page]

`apidoc -f ".*\\.js$" `

it should be `apidoc -f ".*\.js$" ` . One extra backslash.

This is in windows 10 OS. Don't know about Linux or Mac.

**Comment by Lzok** [comment]
Could you solve the problem? How?
I tried 
`apidoc -i ./app/controllers/  -o ../apiDoc/`
`apidoc -i app/controllers/  -o ../apiDoc/`
and others, and I receive the error "error: No files found."

**Comment by discipline19810128** [comment]
➜  apidocjs.com sudo npm install -g apidoc
/usr/local/bin/apidoc -> /usr/local/lib/node_modules/apidoc/bin/apidoc
/usr/local/lib
└─┬ apidoc@0.17.6
  ├─┬ apidoc-core@0.8.3
  │ ├─┬ glob@7.1.2
  │ │ ├── fs.realpath@1.0.0
  │ │ ├─┬ inflight@1.0.6
  │ │ │ └── wrappy@1.0.2
  │ │ ├── inherits@2.0.3
  │ │ ├─┬ minimatch@3.0.4
  │ │ │ └─┬ brace-expansion@1.1.8
  │ │ │   ├── balanced-match@1.0.0
  │ │ │   └── concat-map@0.0.1
  │ │ ├── once@1.4.0
  │ │ └── path-is-absolute@1.0.1
  │ ├── iconv-lite@0.4.18
  │ ├── klaw-sync@2.1.0
  │ └── semver@5.3.0
  ├─┬ fs-extra@3.0.1
  │ ├── graceful-fs@4.1.11
  │ ├── jsonfile@3.0.1
  │ └── universalify@0.1.0
  ├── lodash@4.17.4
  ├─┬ markdown-it@8.3.1
  │ ├─┬ argparse@1.0.9
  │ │ └── sprintf-js@1.0.3
  │ ├── entities@1.1.1
  │ ├── linkify-it@2.0.3
  │ ├── mdurl@1.0.1
  │ └── uc.micro@1.0.3
  ├─┬ nomnom@1.8.1
  │ ├─┬ chalk@0.4.0
  │ │ ├── ansi-styles@1.0.0
  │ │ ├── has-color@0.1.7
  │ │ └── strip-ansi@0.1.1
  │ └── underscore@1.6.0
  └─┬ winston@2.3.1
    ├── async@1.0.0
    ├── colors@1.0.3
    ├── cycle@1.0.3
    ├── eyes@0.1.8
    ├── isstream@0.1.2
    └── stack-trace@0.0.10

➜  apidocjs.com sudo apidoc -i myapp/ -o apidoc/ -t mytemplate/
warn: Please create an apidoc.json configuration file.
error: No files found.
{ Path: '/Users/xpxin/dev/apidocjs.com' }
➜  apidocjs.com sudo apidoc -i myapp/ -o apidoc/ -t mytemplate/ --debug
debug: package.json not found!
debug: apidoc.json not found!
warn: Please create an apidoc.json configuration file.
verbose: apidoc-generator name: apidoc
verbose: apidoc-generator version: 0.17.6
verbose: apidoc-core version: 0.8.3
verbose: apidoc-spec version: 0.3.0
debug: No plugins found.
debug: load parser language: .clj, ./languages/clj.js
debug: load parser language: .coffee, ./languages/coffee.js
debug: load parser language: .erl, ./languages/erl.js
debug: load parser language: .ex, ./languages/ex.js
debug: load parser language: .exs, ./languages/ex.js
debug: load parser language: .litcoffee, ./languages/coffee.js
debug: load parser language: .lua, ./languages/lua.js
debug: load parser language: .pl, ./languages/pm.js
debug: load parser language: .pm, ./languages/pm.js
debug: load parser language: .py, ./languages/py.js
debug: load parser language: .rb, ./languages/rb.js
debug: load parser language: default, ./languages/default.js
debug: load parser: api, ./parsers/api.js
debug: load parser: apidefine, ./parsers/api_define.js
debug: load parser: apidescription, ./parsers/api_description.js
debug: load parser: apierror, ./parsers/api_error.js
debug: load parser: apierrorexample, ./parsers/api_error_example.js
debug: load parser: apiexample, ./parsers/api_example.js
debug: load parser: apiheader, ./parsers/api_header.js
debug: load parser: apiheaderexample, ./parsers/api_header_example.js
debug: load parser: apigroup, ./parsers/api_group.js
debug: load parser: apiname, ./parsers/api_name.js
debug: load parser: apiparam, ./parsers/api_param.js
debug: load parser: apiparamexample, ./parsers/api_param_example.js
debug: load parser: apipermission, ./parsers/api_permission.js
debug: load parser: apisuccess, ./parsers/api_success.js
debug: load parser: apisuccessexample, ./parsers/api_success_example.js
debug: load parser: apiuse, ./parsers/api_use.js
debug: load parser: apiversion, ./parsers/api_version.js
debug: load parser: apisamplerequest, ./parsers/api_sample_request.js
debug: load parser: apideprecated, ./parsers/api_deprecated.js
debug: load worker: apierrorstructure, ./workers/api_error_structure.js
debug: load worker: apierrortitle, ./workers/api_error_title.js
debug: load worker: apigroup, ./workers/api_group.js
debug: load worker: apiheaderstructure, ./workers/api_header_structure.js
debug: load worker: apiheadertitle, ./workers/api_header_title.js
debug: load worker: apiname, ./workers/api_name.js
debug: load worker: apiparamtitle, ./workers/api_param_title.js
debug: load worker: apipermission, ./workers/api_permission.js
debug: load worker: apisamplerequest, ./workers/api_sample_request.js
debug: load worker: apistructure, ./workers/api_structure.js
debug: load worker: apisuccessstructure, ./workers/api_success_structure.js
debug: load worker: apisuccesstitle, ./workers/api_success_title.js
debug: load worker: apiuse, ./workers/api_use.js
debug: load filter: apierror, ./filters/api_error.js
debug: load filter: apiheader, ./filters/api_header.js
debug: load filter: apiparam, ./filters/api_param.js
debug: load filter: apisuccess, ./filters/api_success.js
verbose: run parser
error: No files found.
{ Path: '/Users/xpxin/dev/apidocjs.com' }




<h1>I have the same problem.</h1>

**Comment by dinhanhhuy** [comment]
i'm here with same problem :(
```sh
$ apidoc -i ./app/controllers/  -o ../apiDoc/
$ apidoc -i app/controllers/  -o ../apiDoc/
```
output:
```
...
verbose: run parser
error: No files found. 
{ Path: '/Users/huyda/Desktop/Project/project/api' }
```

**Comment by prakashmuvi** [comment]
Hi,
APidocjs library is working fine in my windows system. I am getting error when i am using in linux server.It is showing me parse when i use cli command of apidoc .
apidoc -i <sourc path> -o <target-path>

It is showing me parse error.
