### ISSUE TITLE
apiparam that can have two different types

### ISSUE THREAD

**Issue by rcrooks** [apidoc/apidoc#339]
I have an apiparam that depending on other params in the request body, may take a string value or an array of strings. Is there a way to specify this? I tried:

`@apiParam (Request Body Fields) {String|String[]}`

but no go. Is there a way to do this?

**Comment by rcrooks** [comment]
see there is already an issue on this - will close

**Comment by olegdizus** [comment]
I don't understand how you solve the issue. What if api can receive different types (e.g. Number or String) and correctly process them.

**Comment by rottmann** [comment]
```
* @apiParam {mixed} myvar Here comes the description
*                         String: description here
*                         Number: description here
```

**Comment by olegdizus** [comment]
Looks like hack, but thanks anyway!

**Comment by gjycdd** [comment]
I had the same problem.
Where can i find the list of type?
http://apidocjs.com,only show a part of list.
As you show, it's a solution.
Is there a better way?
