### ISSUE TITLE
Error: param.forEach is not a function

### ISSUE THREAD

**Issue by brunerson** [apidoc/apidoc#340]
Hey! I've just started trying to integrate some comments into my restify API and I'm unable to build the actual docs. I ran "apidoc -e node_modules" and after all my files are inspected I get this error. It looks like it might be internal, or I'm doing something wrong. Any help?
 
error: params.forEach is not a function
debug: TypeError: params.forEach is not a function
    at /usr/local/lib/node_modules/apidoc/node_modules/apidoc-core/lib/workers/api_param_title.js:77:24
    at Array.forEach (native)
    at /usr/local/lib/node_modules/apidoc/node_modules/apidoc-core/lib/workers/api_param_title.js:74:33
    at Array.forEach (native)
    at /usr/local/lib/node_modules/apidoc/node_modules/apidoc-core/lib/workers/api_param_title.js:68:20
    at Array.forEach (native)
    at Object.postProcess (/usr/local/lib/node_modules/apidoc/node_modules/apidoc-core/lib/workers/api_param_title.js:67:17)
    at /usr/local/lib/node_modules/apidoc/node_modules/apidoc-core/lib/worker.js:95:20
    at /usr/local/lib/node_modules/apidoc/node_modules/lodash/index.js:3159:15
    at baseForOwn (/usr/local/lib/node_modules/apidoc/node_modules/lodash/index.js:2089:14)

**Comment by rottmann** [comment]
Can you add `--debug` and check / post the output.

**Comment by brunerson** [comment]
Sorry this is the end of the --debug output

**Comment by brunerson** [comment]
Here's a link to a gist with the entire output: https://gist.github.com/brunerson/0104a1e80de0ddaadd89

**Comment by rottmann** [comment]
Did you use somewhere the deprecated `apiParamTitle` ?
You should use instead `apiDefine` to the define a title:
```
/**
  * @apiDefine TitleName Some title text
  */

/**
 * @api ....
 * @apiParam (TitleName) {String} var Some description.
 */
```

**Comment by brunerson** [comment]
No I didn't... I used apiDefine and apiParam. I'm not sure what's going on!

**Comment by brunerson** [comment]
I figured out the problem! It was that I had '.' in some group names. For example:
@apiParam (user.save) {String} user

**Comment by brunerson** [comment]
Thanks for your help @rottmann !!
