### ISSUE TITLE
Multiline codeblocks

### ISSUE THREAD

**Issue by Mech7** [apidoc/apidoc#341]
Is it possible to add multi line codeblocks?
If i now add something in the description like:
```
<pre> 
some code here
more code
</pre>
```
It will be renderd at 1 line. the same for 
```<code>``` blocks

**Comment by rottmann** [comment]
apidoc uses markdown, add 4 spaces at the beginning of each line.

**Comment by leoliaolei** [comment]
I have to comment out line 252 in `\node_modules\apidoc\node_modules\apidoc-core\lib\parser.js`
to make multiline work

````
// remove line breaks
// values[field] = values[field].replace(/(\r\n|\n|\r)/g, ' ');
````

**Comment by kellertobias** [comment]
@rottmann except of funny spaces in the same line, I dont get anything else. Could you please update the code according to the above proposal as this really solves the problem.

**Comment by blacktemplar** [comment]
Still having this issue!
