### ISSUE TITLE
@apiForm or @apiBody for POST or PUT form description

### ISSUE THREAD

**Issue by rogeriotaques** [apidoc/apidoc#342]
Might be a good idea to have a ```@apiForm``` or ```@apiBody``` tags in order to describe form fields out from ```@apiParam```. 

As far as I understood, the ```@apiParam``` should be used to describe fields submitted within a form or given parameters over the URL, but sometimes the API requires both: a parameter on the URL and a form within a POST or PUT method.

e.g:

```{post} api/user/update/:id``` 

and

```
POST: {
  "name": "Jorge",
  "surname": "Luccas" 
}
```

In that case, if just using ```@apiParam``` to describe both params, all of it will be described as parameters and for sure become confusing for API users who are reading the docs.

**Comment by rottmann** [comment]
@apiParam can handle this.
Normally you don't have the same names in the URL or the POST vars, so your example will look like
```
@apiParam {String} id      Some ID.
@apiParam {String} name    Some Name.
@apiParam {String} surname Some Surname.
```
For the person that read the API source-code it is in first glance not important if `id` is an URL parameter or a POST value. Important is that `id` exists and what `id` is.

In detail you view if `id` will be a post or request var.

If `:id` in your URL would be `:name` too, then you have a problem, but only a naming problem, that you can solve whithout code change, just rename it to something unique e.g. `:req_name`
`{post} api/user/update/:req_name`
```
@apiParam {String} req_name Some ID.
@apiParam {String} name     Some Name.
@apiParam {String} surname  Some Surname.
```

**Comment by rogeriotaques** [comment]
@rottmann thanks for your reply.

Yes, usually params haven't same name in URL and POST, but actually, that's the point. Even though using different names,  ```@apiParam``` just create an unique table containing all parameters.

So, when looking at created table, sometimes it's hard to identify where does params should be passed, distracting and creating some confusion for who is reading the docs. That said, why not create a special tag just for hold those parameters passed thru POST methods?

I mean, putting those params in different tables might be easier to read and understand the docs.

What do you think?

**Comment by rcrooks** [comment]
If I'm understanding the request correctly, you can already do this using the group names for params, e.g.:
 * @apiParam (Path Parameters) {String} account_id Video Cloud account ID.
 *
 * @apiParam (Request Body Fields) {String} name video title
 * @apiParam (Request Body Fields) {String} [description] video short description

Here Path Parameters and Request Body Fields are displayed in separate tables. Is that what you are looking for?

**Comment by rogeriotaques** [comment]
@rcrooks, thank you!

I thing you got the point perfectly.

That's exactly what I need. Using the group name makes the API docs clear regarding on what params are supposed to be in the URL and what must be passed within a POST.

So, once it is solved, let me close the ticket.

Cheers. R.
