### ISSUE TITLE
use sampleUrl to send requests for different APIs to the same proxy?

### ISSUE THREAD

**Issue by rcrooks** [apidoc/apidoc#344]
I am documenting a bunch of different APIs. For each API request, it's necessary to fetch a temporary access token for authentication, so I need to route requests through a proxy that does that. I can't set up test apps in the paths of the actual API URLs.
So what  I would like to do is have all sample requests for all APIs send the full request to same proxy, which will fetch an access token, make the request, and return the response.

Is there a way to do that using sampleUrl and @apiSampleRequest? It seems that the existing implementation assumes that the test address will have the same domain as the API and only wants to send along the endpoint and params.

**Comment by rottmann** [comment]
The current sample request test methods are really basic, i think you must implement your own handler for the proxy access with an own template.
Within the template replace the [send_sample_request.js](https://github.com/apidoc/apidoc/blob/master/template/utils/send_sample_request.js) with your own fetch function.

**Comment by rcrooks** [comment]
Ok, thanks

-- 
Robert Crooks
Director of Learning Services

On October 19, 2015 at 3:37:47 AM, Peter Rottmann (notifications@github.com) wrote:

The current sample request test methods are really basic, i think you must implement your own handler for the proxy access with an own template.
Within the template replace the send_sample_request.js with your own fetch function.
