### ISSUE TITLE
Can't see multiple versions in generated doc

### ISSUE THREAD

**Issue by sustbird** [apidoc/apidoc#347]
As instructed in documentation and presentation, I created a new file _apidoc.js in the same dir as apidoc.json/Gruntfile, with old docblock. But after generating documentation, I can't see the old version in version dropdown list in the generated doc. Can anybody please point out what I am missing...

**Comment by rottmann** [comment]
Can you post parts of you _apidoc.js

**Comment by sustbird** [comment]
Thanks for your reply, The content is below:

/**
*
* @api {post} /api/v1/oauth/token/validate Validate access_token
* @apiVersion 1.0.0
* @apiName ValidateAccessToken
* @apiGroup Authentication
* @apiPermission none
*
* @apiParam {Number} client_id Client id
* @apiParam {String} access_token Access Token
*
* @apiSuccess {String} valid Returns validity in boolean true/false
* @apiSuccessExample {json} Success-Response:
*     HTTP/1.1 200 OK
*     {
*        "valid": true,
*      }
*
* @apiError valid Returns true/false
* @apiError [errors] json format error for all fields
* @apiErrorExample {json} Error-Response
*     HTTP/1.1 400 Bad Request
*     {
*       "valid": false,
*          "errors": [
*           {
*           "client_id": [
*              "The client id field is required."
*              ]
*           }
*          ]
*     }
*/

**Comment by sustbird** [comment]
Hi, I got the problem, actually I filtered out the _apidoc.js through grant filter. Now moved the _apidoc.js file right dir and its working fine.
