### ISSUE TITLE
using CLI --parse-parsers doesn't seem to work

### ISSUE THREAD

**Issue by lagrz** [apidoc/apidoc#348]
Hi,

Trying to see if there is anyway to automatically "prettify " the json for `apiSuccessExample` and `apiErrorExample`.

I tried building a parse filter using the examples given in the [Docs](http://apidocjs.com/#extend) and using it in the CLI with the `--parser-parse` parameter but it doesn't seem like its even running.

`apidoc --parse-parsers apiSuccessExample=json_filter.js -i . -o docs/`

heres the json_filter.js which i copied from [here](https://github.com/apidoc/apidoc-core/blob/master/lib/parsers/api_example.js) and slightly modified:

```javascript

function parse(content, source) {
    var parseRegExpFirstLine = /(@\w*)?(?:(?:\s*\{\s*([a-zA-Z0-9\.\/\\\[\]_-]+)\s*\}\s*)?\s*(.*)?)?/;
    var parseRegExpFollowing = /(^.*\s?)/gm;

    var title = '';
    var text = '';
    var type;

    var matches;
    if ( (matches = parseRegExpFirstLine.exec(source)) ) {
        type = matches[2];
        title = matches[3];
    }

    parseRegExpFollowing.exec(content); // ignore line 1
    while ( (matches = parseRegExpFollowing.exec(source)) )  {
        text += matches[1];
    }

    if (text.length === 0)
        return null;

    try{
        var c = text;
        c = JSON.parse(c);
        c = JSON.stringify(c, 4);
        text = c;
    }catch(e){ }

    return {
        title  : title,
        content: text,
        type   : type || 'json'
    };
}

module.exports = {
    parse : parse,
    path  : 'local.success.examples',
    method: 'push'
};
```

BTW I'm pretty sure there's a better way to prettify the json this just happened to come in mind at the moment.

**Comment by rottmann** [comment]
Lowercase the name `apidoc --parse-parsers apisuccessexample=json_filter.js` and it works.
