### ISSUE TITLE
Empty Groups for Future Versions Showing when Old Versions Selected

### ISSUE THREAD

**Issue by treygrainger** [apidoc/apidoc#349]
Say I have two groups of API's in version 0.6.0, and four groups of API's in 0.7.0. If I select 0.6.0 at the top of the page, it correctly removed the two groups that don't exist in 0.6.0 from the side-navigation, but it unfortunately still leaves those groups in the main documentation section (with nothing underneath them.

The groups should be removed if a version is selected that they don't appear within.

![image](https://cloud.githubusercontent.com/assets/1043085/10708921/ba6a6cca-79e8-11e5-8306-082759b7237f.png)
![image](https://cloud.githubusercontent.com/assets/1043085/10708918/ad6a2ce0-79e8-11e5-9e59-a85e89397f14.png)

------------------

![image](https://cloud.githubusercontent.com/assets/1043085/10708927/f5d970e4-79e8-11e5-97ce-7aadaf1fc6ea.png)
![image](https://cloud.githubusercontent.com/assets/1043085/10708923/cbe84bd4-79e8-11e5-9ba6-d277334a162c.png)
![image](https://cloud.githubusercontent.com/assets/1043085/10708925/e3d00e9e-79e8-11e5-9b83-4af5ebaee109.png)

Note that this header with empty content should NOT appear in the documentation since this version doesn't support that header (it was correctly removed from the navigation bar already, just not the content).

**Comment by rottmann** [comment]
Fixed in the next release.
