### ISSUE TITLE
Get rid of default User section in output

### ISSUE THREAD

**Issue by skypanther** [apidoc/apidoc#353]
I realize this is a really dumb question, but how do I get rid of the default sample User API content in my output? I've searched the docs, open/closed issues, etc. and don't see any mention of this.

I'm using the latest version of apidoc and the `^0.10.1` version of grunt-apidoc. There is no User api / section in my source file (I have just a single source, index.js file). Adding a User section overrides the default, but I don't need or want a users endpoint in my api.

I tried adding `@apiIgnore` blocks, but that didn't work. Maybe I didn't exactly match the block definitions of the defaults.

My grunt file is very simple:

```javascript
module.exports = function (grunt) {
	grunt.initConfig({
		settings: {
			param: ''
		},
		apidoc: {
			myapp: {
				src: "./",
				dest: "../generated/"
			}
		}
	});
	grunt.loadNpmTasks('grunt-apidoc');
	grunt.registerTask('default', ['apidoc']);
};
```

```shell
≫ grunt
Running "apidoc:myapp" (apidoc) task

grunt-apidoc
warn: parser plugin 'param' not found in block: 0
info: Done.
>> grunt-apidoc finished.

Done, without errors.
```

![screen shot 2015-10-28 at 9 41 09 am](https://cloud.githubusercontent.com/assets/507996/10790156/10fdce70-7d58-11e5-9604-a6902d53727a.png)

**Comment by rottmann** [comment]
Can you try to set the full path to your project instead of `src: "./",`

**Comment by skypanther** [comment]
I'm afraid that didn't do it. I tried setting both the src and dest to a full path and got the same results. I tried without grunt, using the `apidoc -i input_path -o output_path` with both relative and absolute paths and also get the same results.

**Comment by rottmann** [comment]
Can't reproduce this. You can mail me the files so i can try to check it.
