### ISSUE TITLE
@apiName - http://apidocjs.com/#param-api-name - not showing up

### ISSUE THREAD

**Issue by ORESoftware** [apidoc/apidoc#357]
Enjoying working with apidoc so far - I am having trouble understanding what the apiName field is for-

http://apidocjs.com/#param-api-name

according to the docs it should always be used but I am not seeing it anywhere in the docs that your lib generates!

for example:

```
   /**
     *
     * @api {post} /autosuggest get results from searching an Algolia index
     * @apiVersion 1.0.0
     * @apiName SearchAlgoliaIndex
     * @apiGroup autosuggest
     * @apiParam {String} name of Algolia index
     * @apiSuccess {String} firstname Firstname of the User.
     * @apiSuccess {String} lastname  Lastname of the User.
     *
     */

```

yields this:

https://lectal-api-staging.herokuapp.com/docs/#api-autosuggest

...there is no sign of "@apiName"

I also have this weird message when running apidoc from the command line:
```warn: parser plugin 'apipermissio' not found in block: 1```

...
please help, thanks!
-alex

**Comment by rottmann** [comment]
apiName is used for naming and navigation items. Someday it should be used for internal linking too.

`apipermissio` `n` missing: `apipermission`

**Comment by dansantner** [comment]
fyi, I was equally confused by this field not showing up anywhere in the doc...

**Comment by rcrooks** [comment]
Here is what I think: the link text in the side navigation picks up whatever text is at the end of @api - I think it would be better if it took that text from @apiName , and @api contained the endpoint only.

It is possible that tha @apiname value is used for the `sort` in the .json file, but I haven't verified that.
