### ISSUE TITLE
Paragraph tags added to parameter type in generated api_data.js

### ISSUE THREAD

**Issue by hareesh-blippar** [apidoc/apidoc#358]
In api_data.js that is generated, the parameter-type and description fields are getting embedded inside paragraph tags by mistake. For example, if I had a parameter-type called `Integer`, it gets displayed as `<p>Integer</p>` instead.

`Here is the example json generated showing the <p> tags`

        "Parameter": [
          {
            "group": "Parameter",
            "type": "\<p>Integer\</p> ",
            "optional": false,
            "field": "groupId",
            "description": "\<p>Group Id\</p> "
          }

**Comment by rottmann** [comment]
Fixed in 0.13.2
