### ISSUE TITLE
Selected item in menu still off (as in issue 176)

### ISSUE THREAD

**Issue by svenhemmer** [apidoc/apidoc#359]
Hi, i'm currently using apidoc (version 0.10.1) to document a REST-API in java and am running into the same problems as described here:
https://github.com/apidoc/apidoc/issues/176

I checked the main.js file and saw that the bugfix mentioned in issue 176 is already in the code. The changed offset seems to be a valid soultion for certain screen-resolutions/ratios. When I reduce the browser-width to a rather narrow extend, the menu suddenly behaves correctly.
 
P.S. Really like apidoc, thx for all the hard work

**Comment by lwm** [comment]
+1, same version, seeing this one too [here](http://docs.tracdelight.com).

**Comment by rottmann** [comment]
It seems scrollspy got the wrong position while the webfonts loading.
Fixed it in the next release, implement googles webfontloader to avoid this problem.
