### ISSUE TITLE
ApiGroup converted to snake case in HTML

### ISSUE THREAD

**Issue by olalonde** [apidoc/apidoc#363]
I have an api with the following group name:

```
@apiGroup Key Value Store
```

The generated HTML looks right in the menu (spaces are preserved):

```html
<a href="#api-Key_Value_Store">Key Value Store</a>
```

However, in the main body, the api group's spaces are replaced with underscores `_`:

```html
<h1>Key_Value_Store - Delete key</h1>
```

**Comment by rottmann** [comment]
apiGroup name should only be a single word.
You can define a text for the name separately:
```
/**
 * @apiDefine KeyValueStore This is Key Value Store
 * optional description
 */

/**
 * @api ...
 * @apiGroup KeyValueStore
 * ...
 */

**Comment by olalonde** [comment]
Thanks.
