### ISSUE TITLE
@apiHeader problem

### ISSUE THREAD

**Issue by diego1686** [apidoc/apidoc#364]
Hi! I have an API that needs an access token to authenticate users in some methods. So, I added this:

@apiHeader {String} x-access-token Users unique access token

But when I tried to use the Api Sample Request, I got HTTP 403 response because the header is not sent good! Here is an example:

The app sends the access token on this way, and it works good
![ok](https://cloud.githubusercontent.com/assets/1087468/11186566/ede07538-8c60-11e5-86ba-28e78cf62a86.jpg)

But, the api doc sends it on this way:
![error](https://cloud.githubusercontent.com/assets/1087468/11186567/efd9abde-8c60-11e5-9e33-91efb1a9a9ae.jpg)

What I'm doing wrong? Thanks!

**Comment by afialho** [comment]
I have the same issue. @diego1686, did you fix that?

**Comment by diego1686** [comment]
@afialho Yes! The issue was in the CORS configuration of my Express server. I added my custom access token to the Access-Control-Allow-Headers header and allowed the OPTIONS request. Try adding this and let me know if it works for you:

```javascript
// handle CORS requests
app.use(function(req, res, next){
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET,PUT,POST,DELETE,OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "X-Requested-With,content-type,x-access-token");

  if ('OPTIONS' == req.method)
    res.send(200);
  else
    next();
})
```

**Comment by timcan** [comment]
I was having the same problem documented above with NodeJS + Express + ApiDocJS, testing through both the latest Chrome and Firefox browsers and @diego1686 CORS configuration did the trick.
