### ISSUE TITLE
Allow for definition of queryParams like apiParam 

### ISSUE THREAD

**Issue by victorbstan** [apidoc/apidoc#365]
I'm wondering if there is something that would allow me to define `queryParam` the way that `apiParam` is defined, but which is separate from `apiParam`. I think it's possible to have both types of params in an API, but I don't see this being supported by this api documentation generator.

**Comment by rottmann** [comment]
Normally we have unique names in query and in post data, so a distinction is not necessary.
If the names in query and body are equal, the names could be change, e.g. for the query queryVar1, queryVar2,...
