### ISSUE TITLE
@apiDefine for @apiSuccess is to specific to define a generic success parameter.

### ISSUE THREAD

**Issue by DannyvdSluijs** [apidoc/apidoc#370]
I would like to define (@apiDefine) my generic types used in the return(@apiSuccess) such as String values with are only allowed to have a (large) range of allowed values. But the define requires me to mention where the apiSuccess is located in the success

Must be 
```js
/**
 * @apiDefine StateNames
 *
 * @apiSuccess {String="MOVEMENT", "TEMPERATURE"} event.states.name The name of the state that has changed
 */
```

Like it to be:
```js
/**
 * @apiDefine StateNames
 *
 * @apiSuccess {String="MOVEMENT", "TEMPERATURE"}
 */

**Comment by rottmann** [comment]
Single / plain results are not supported.

**Comment by DannyvdSluijs** [comment]
@rottmann Can you provide some more info. Not getting your note.

**Comment by rottmann** [comment]
Currently a field name of the return result is needed, a plain result without any context / name is not provided.
