### ISSUE TITLE
@apiError mentions Error 4xx possible errors could be in other ranges for example 501

### ISSUE THREAD

**Issue by DannyvdSluijs** [apidoc/apidoc#371]
<img width="815" alt="screen shot 2015-11-20 at 17 24 37" src="https://cloud.githubusercontent.com/assets/618940/11296189/9b71c4b6-8fab-11e5-801a-130c5934ac5f.png">

Also it seems that the examples explain it in such a way that there is an error type and description (See http://apidocjs.com/source/example_inherit/example.js) with 
```js
/**
 * @apiDefine UserNotFoundError
 *
 * @apiError UserNotFound The <code>id</code> of the User was not found.
 *
 * @apiErrorExample Error-Response:
 *     HTTP/1.1 404 Not Found
 *     {
 *       "error": "UserNotFound"
 *     }
 */
```

Where UserNotFound becomes the field and the "The <code>id</code> of the User was not found." becomes the description.

**Comment by rottmann** [comment]
You can define and set your error groups
```
@apiError (404) {String} var1 Some description.
@apiError (501) {String} var2 Some description.
```
With separate define you can set a custom title
```
@apiDefine 501 My custom 501 title.
```

**Comment by DannyvdSluijs** [comment]
@rottmann How does this resolve the rendering? I believe changing Error 4xx into Error would already make the UI better informative. Do you see this different ?

**Comment by felipefrancisco** [comment]
It would be great to be able to customize this block title.
