### ISSUE TITLE
Howto create the doc to static files

### ISSUE THREAD

**Issue by loevda** [apidoc/apidoc#374]
Hi,

I'm new to apidoc and I'd like to create/export the doc to static html files.
Any idea how to do it?

Thanks

**Comment by rcrooks** [comment]
I haven't thought too much about this, but we did something similar with 
a JSDoc implementation by porting the code that generates the content 
into a Grunt process. You can find the code for this here: 
https://github.com/videojs/docs -- you won't be able to directly reuse 
anything, but it might give you some ideas. Handlebars, which drives 
most of the content generation for APIDOC, works fine in nodejs, so 
that's not an issue.

Robert

loevda wrote:

**Comment by loevda** [comment]
Hi,

Thanks for pointing me. That what I have been looking at but being new to handlebars and grunt I guess I have some reading ahead of me. Anyway I have been looking at https://github.com/patrickkettner/grunt-compile-handlebars  and https://www.npmjs.com/package/grunt-static-handlebars. The thing is that I need to integrate the doc into a django based portal. 
Anyway as soon as I have time to get into it and if I get it working I'll post it here.

David
