### ISSUE TITLE
Question - is there someone supporting apidoc?

### ISSUE THREAD

**Issue by juliangut** [apidoc/apidoc#376]
I'm seeing last merged PR is from May 19th, from May there have been only two commits and last activity from @rottmann was Nov 12th (to update README file) I'd hardly say that is supporting when there are 19 open PR and 98 issues (99 with this one)

Just to know

**Comment by rottmann** [comment]
Currently i stuck on some projects, thats why no PR is merged. Hope i get soon time to merge all PR.

**Comment by DannyvdSluijs** [comment]
@rottmann I hope you won't take this as a negative feedback as I can relate to your situation not having enough time available for everything you would like to do. But maybe reading http://hintjens.com/blog:106 would thing some light on how you could also merge the pull requests.

**Comment by juliangut** [comment]
@DannyvdSluijs that post is golden, thank you for your contribution, I'm going to dive deeper into that idea

**Comment by nazrhyn** [comment]
It's possible some of the authors of those pending PRs would also be willing to join as a direct contributor to manage some of these open issues and PRs. I'm not sure how one would find out, though.

**Comment by YMA-MDL** [comment]
I'd like to help, not sure I have the skills though. But I have some spare time I'd like to spend on it. (I guess helping on test and merges)

**Comment by NicolasCARPi** [comment]
I agree that PRs that take too long to merge is an issue. And I disagree about the optimistic merging mentionned in @DannyvdSluijs 's linked blog post (merging without waiting for CI to finish and without code review, that's a bit extreme).

There is a middle ground to find. This project has suffered from the lack of time of the main author, but @rottmann quickly gave me more access rights when I asked for them, and I was able to help this project move forward. So my point is that if you think that a repository/project is lacking maintainers, dying, please do step in and help, all you have to do is ask! ;)
