### ISSUE TITLE
Suggestion: descriptions for API groups would be useful

### ISSUE THREAD

**Issue by rcrooks** [apidoc/apidoc#385]
maybe @apiGroupDescription or something

I'm finding that when there are several groups, I'm missing this.

**Comment by rottmann** [comment]
You can use apiDefine
```
/**
 * @apiDefine MyGroupName Some Title
 * Some description
 * More description
 */

use it with:

/**
 * @api ....
 * @apiGroup MyGroupName 
 */
```

**Comment by rcrooks** [comment]
ah, right, thanks!

Peter Rottmann wrote:

**Comment by rcrooks** [comment]
sorry @rottmann but still can't get this to work - there has to be an @apiUse somewhere.
I tried:
    * @apiDefine assetGroup
    * the asset group is for....

then

    * @apiGroup Assets @apiUse assetGroup

or 
    * @apiGroup Assets
    * @apiUse assetGroup

The first treats assetGroup as part of the group name. the second doesn't display the description anywhere.

**Comment by rottmann** [comment]
With apiUse you include a whole defined block, that block could have many annotations like apiParam, apiSuccess, ....

With only the name you include only the needed parts of the "calling" annotation.
In your case use only
```
* @apiDefine assetGroup Here must be a title
* the asset group is for....

then

* @apiGroup assetGroup
```

**Comment by rcrooks** [comment]
ah, yes -- THANK YOU!
