### ISSUE TITLE
204 (noContent) status code won't clear last ouput from sampleUrl

### ISSUE THREAD

**Issue by bahjaat** [apidoc/apidoc#386]
Doing a first request to a sampleUrl, gives me a 200 with json data in the response area.
Doing a second request and the reponse is a 204 (noContent), the response area is not cleared.
Using 204 when deleting information btw.

**Comment by dzgrief** [comment]
I met the same problem. I hope this problem can be settled as soon as possible.

**Comment by NicolasCARPi** [comment]
It does now.
