### ISSUE TITLE
POST sample request with nested attributes

### ISSUE THREAD

**Issue by potatogopher** [apidoc/apidoc#388]
I am currently trying to use `@apiSampleRequest` with nested attributes. My issue is that when I input my parameters, it is sending like so:
    ```{
    data: "foo",
    data.user: "bar",
    data.user.email: "baz",
    }```

I am expecting it to send like:

``` { data: { user: { email: "something"} } }```

I am getting my input parameters from the following code: 

```
 * @apiParam (Request Fields) {Object} data Holds incoming data
 * @apiParam (Request Fields) {Object} data.user User data
 * @apiParam (Request Fields) {String} [data.user.name] The users full name.
```

What changes do I need to make to do this properly?

**Comment by andrerecinto** [comment]
:2 :+1:

**Comment by rottmann** [comment]
If i see some or somebody report me something, i will add it to the readme
https://github.com/apidoc/apidoc#plugins-extend-apidoc

**Comment by potatogopher** [comment]
@rottmann 
Was there a change to satisfy this?

**Comment by rottmann** [comment]
The sendSampleRequest Plugin must be rewritten. There are some Pull-Request that i have to review, but i think a complete new Plugin with all needed functionality is necessary (currently we fix and fix a broken code, that solves an other problem).

**Comment by demisx** [comment]
Ran into the same issue. Has this ever been implemented?

**Comment by neelbhanushali** [comment]
Bump

**Comment by neelbhanushali** [comment]
@rottmann kindly keep this issue open. This feature is needed.

**Comment by NicolasCARPi** [comment]
@neelbhanushali I believe #828 will implement this, right?

**Comment by neelbhanushali** [comment]
@NicolasCARPi yes

**Comment by neelbhanushali** [comment]
@NicolasCARPi when #828 be merged?
