### ISSUE TITLE
Single endpoint for RPC-style API

### ISSUE THREAD

**Issue by dvv** [apidoc/apidoc#389]
Hello,

Wonder if there is a workaround to document several "functions" of the same group which all available at say `https://foo.bar.baz/rpc`?

TIA,
--Vladimir

**Comment by rottmann** [comment]
apiDoc is for REST APIs in which we have unique Endpoints, but you can try to attach the function name:
```
@api {post} /rpc?function=unique_name Hello World
```

**Comment by dvv** [comment]
Thank you!
