### ISSUE TITLE
what determines the api verison?

### ISSUE THREAD

**Issue by aq2004723** [apidoc/apidoc#392]
HI.
I wrote documents with apidoc and it really easy to use 

But something is confusing me

A API have two version and the version info is part of the url. ( also use @apiVersion) And as result, there have two independent  api doc  .  Is there any method to merge them and can switch version by switches?

Pardon me for my broken english :)

**Comment by rottmann** [comment]
When you give each annotation block a version you can switch the versions in the generated doc in the right top corner.

```
/**
 * @api {get} /something
 * @apiVersion 1.0.0
 */

/**
 * @api {get} /something
 * @apiVersion 2.0.0
 */
```

**Comment by aq2004723** [comment]
@rottmann 

but my url like that
```
/**
 * @api {get} /v1.0/something
 * @apiVersion 1.0.0
 */

/**
 * @api {get} /v2,0/something
 * @apiVersion 2.0.0
 */
```

and there are two entries

**Comment by rottmann** [comment]
Workaround, set the same name:
```
/**
 * @api {get} /v1.0/something
 * @apiName Something
 * @apiGroup Somegroup
 * @apiVersion 1.0.0
 */

/**
 * @api {get} /v2.0/something
 * @apiName Something
 * @apiGroup Somegroup
 * @apiVersion 2.0.0
 */
```

In the next release i will add the version number to the sampleUrl (template-settings), so that it has not to be written in `@api {get} /version/`

**Comment by aq2004723** [comment]
ok  I known.  Thank you.
