### ISSUE TITLE
Unintended Parsing of File Comment Header

### ISSUE THREAD

**Issue by meanjoe45** [apidoc/apidoc#393]
Hello,

First off thanks for the project. It has really come in handy.

The issue I'm having comes into play with a file comment header block that I have on all of my files. It is not formatted like a apidoc block, but apidoc is picking it up anyway and parsing it. I only noticed this because I have an email address in the comment header. The parser hiccups on `@` in the email address. Here is a boiled down test file:

**test.js**

``` javascript
//******************************************************************************
// Copyright (c) 2015-2016 MyCompany, LLC -- All rights reserved
//
// AUTHOR: me me@theproblem.com 2015/11/10
//******************************************************************************
'use strict';

/**
 * @apiDefine Test Test
 *
 * API endpoints that interact with test resources.
 */

/**
 * @api {GET} /tests [GET] /tests
 * @apiName Tests
 * @apiGroup Test
 *
 * @apiVersion 1.0.0
 *
 * @apiPermission none
 *
 * @apiDescription Retrieves an array of all phones for the current user.
 *
 * @apiHeader {String} authorization Authorization token
 *
 * @apiSuccess (200) {Object} tests Array of tests
 */
```

I run this file with the following command and receive the given output (note that I'm currently running apidoc v0.14.0):

```
~/workspace (api-design) $ ./node_modules/.bin/apidoc -i ./test-api -o ./doc-test
warn: parser plugin 'theproblem' not found in block: 0
info: Done.
~/workspace (api-design) $
```

There is the easy workaround of changing the comment header to use `//~~~` as the first/last lines instead of the current `//***` so this isn't a show stopper. My understanding is `//***` comments shouldn't be considered an apidoc block, so I'm making this issue.

Thanks again.

**Comment by rottmann** [comment]
The parser try to find @api between `/**` and `*/`, your comment block has a beginning with `/**`.
When you add a space it should be not problem `// **********`

Set it on todo too, the block finding regexp must be modified (for all languages).

**Comment by NicolasCARPi** [comment]
The proposed fix (add a space) seems adequate. Anyway, this is an apidoc-core issue.
