### ISSUE TITLE
How to format response json in pretty format in apidoc?

### ISSUE THREAD

**Issue by stone-wlg** [apidoc/apidoc#394]
Hi,
I used sampleUrl to test my api, and i got a string format, ex:"{\"is_succeed\":true,\"data\":[]}" (not pretty json format as apidoc sample) response after i clicked send button. But i am sure that my api response header with Content-Type: application/json and it is json data.

**Comment by lincolnbrito** [comment]
I have the same issue

**Comment by afialho** [comment]
@stone-wlg @lincolnbrito and me fixed it and create a pull request.

**Comment by afialho** [comment]
@stone-wlg The fix here at my fork too https://github.com/afialho/apidoc

**Comment by gaving** [comment]
:+1: for this

**Comment by mrpatiwi** [comment]
+1

**Comment by eckdanny** [comment]
just started using apidoc today and ran into this issue myself. Traced to [send_sample_request.js#L91](https://github.com/apidoc/apidoc/blob/0.14.0/template/utils/send_sample_request.js#L91) (PUT and POST samples working just fine for me). That conditional block that clobbers some ajax config was removed in b33716d. Perhaps this issue, #396 and #397 can be closed, and we need a version bump?

Hope this helps. I'm using the [npm package](https://www.npmjs.com/package/apidoc) btw which is tagged at 0.14.0.

**Comment by zdavis** [comment]
This is an issue for us as well. Would be great to see the PR merged :)

**Comment by koustuvsinha** [comment]
same issue, would like to see a pretty printed json output

**Comment by rottmann** [comment]
Merged in the next version.
