### ISSUE TITLE
Is there a way to add introduction to the API as the simple text with some headings

### ISSUE THREAD

**Issue by DaDer** [apidoc/apidoc#398]
Is there a way to easily add a new section with e.g. description of the authentication process or how to handle pagination. I would like to add a general section at the top of the API doc. I am looking for the best approach to this problem. Maybe somebody considered similar case ?

**Comment by rcrooks** [comment]
Use the description field of the Json file. Sorry for brief reply - on phone

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.5.3&pv=9.2&source=email_footer_2]
On Sun, Jan 10, 2016 at 19:17, apidoc/apidoc
<reply@reply.github.com>
wrote:
Is there a way to easily add a new section with e.g. description of the
authentication process or how to handle pagination. I would like to add a
general section at the top of the API doc. I am looking for the best approach to
this problem. Maybe somebody considered similar case ?

**Comment by rottmann** [comment]
Pagination is not present in the current template (for this you must create your own template).
A header description could be added with a .md file, see http://apidocjs.com/#headerfooter

**Comment by afialho** [comment]
@Dader, you should use a header.md file. See: http://apidocjs.com/#headerfooter
