### ISSUE TITLE
How to Post paramaters by using @apiSampleRequest 

### ISSUE THREAD

**Issue by amitvoip25** [apidoc/apidoc#401]
I have created a forms for Strings @param , various fields using @apiSample request , for POST/post
method , when i send the fields , it gives me 404 error , does @apiSampleRequest can-not be used with 
@api post ? 
<img width="1440" alt="screen shot 2016-01-14 at 6 57 16 pm" src="https://cloud.githubusercontent.com/assets/16662589/12325972/dd7aaf94-baf3-11e5-9c15-323bd48ffc72.png">

My apidoc code is as below .
    /**
     * @apiDefine CreateUserError
     * @apiError NoAccessRight Only authenticated Admins can access the data.
     * @apiError UserNameTooShort Minimum of 5 characters required.
     */
    /**
     * @api {post} /CustomerInsert/ Create a New User
     * @apiName Customer Insert
     * @apiGroup User
     * @apiVersion 0.1.0
     * @apiPermission none
     * @apiSampleRequest "http://localhost:4567/customer/insert"
     * @apiParam {String} firstname     firstname of customer
     * @apiParam {String} lastname      lastname of customer
     * @apiParam {String} phoneNumber   phoneNumber of customer
     * @apiParam {String} emailId       emailId of customer
     * @apiParam {String} userName      userName of customer
     * @apiParam {String} password      password of customer
     *
     * @apiSuccess {String} firstname   firstname of customer
     * @apiSuccess {String} lastname    lastname of customer
     * @apiSuccess {String} phoneNumber phoneNumber of customer
     * @apiSuccess {String} emailId     emailId of customer
     * @apiSuccess {String} userName    userName of customer
     * @apiSuccess {String} password    password of customer
     * @apiUse CreateUserError
     */

config.json
{
  "name": "XYZ",
  "version": "0.1.0",
  "description": "Backend Server APis ",
  "title": "XYZ"
}

**Comment by rottmann** [comment]
Try to use a newer version. Some contributors update the sendSampleRequest-Plugin.
