### ISSUE TITLE
Issue with objects in post parameter

### ISSUE THREAD

**Issue by vishal5308** [apidoc/apidoc#404]
@apiParam (Parameters for register using Google Account) {Object} user User Object
## @apiParam (Parameters for register using Google Account) {String} user.google_id Google access token  

Post parameter observed from chrome -> network panel
{"user":"","user.google_id":"dfgsdfgfdgsd"}

It should be

{
  'user':{
     'google_id':'dfgsdfgfdgsd'
 }
}

---

![screenshot at jan 25 13-38-13](https://cloud.githubusercontent.com/assets/7370932/12545507/f1272c0c-c368-11e5-8603-01d7316c20d4.png)

**Comment by abhisekbera** [comment]
I change some part of doc/utils/send_sample_request.js to work for Object fields.

The changed part of code is given below-

      // create JSON dictionary of parameters
      var param = {};
      $root.find(".sample-request-param:checked").each(function(i, element) {
          var group = $(element).data("sample-request-param-group-id");
          $root.find("[data-sample-request-param-group=\"" + group + "\"]").each(function(i, element) {
            var key = $(element).data("sample-request-param-name");
            var value = element.value; 
            var fieldtype = $(element).next("span").text();
            fieldtype = $(fieldtype).text();
			if (fieldtype == 'String') {
				param[key] = escapeHtml(value);
			}	
			if (fieldtype == 'Object') {
				if (value == '') {
					param[key] = JSON.parse('{}');
				}
				else {	
					param[key] = JSON.parse(value);
				}	
			}	
          });
      });

Below is the uploaded pix of my request.
![screenshot from 2017-01-18 18 42 13](https://cloud.githubusercontent.com/assets/13553464/22065975/b2d1779c-ddb0-11e6-943f-e0cc180fba4f.png)

It is working perfectly for me.

**Comment by NicolasCARPi** [comment]
Please try the new version ;)
