### ISSUE TITLE
create @apiGernerateSuccessFromParams

### ISSUE THREAD

**Issue by m-amr** [apidoc/apidoc#408]
To document the response i use  @apiSuccess and @apiSuccessExample
@apiSuccess to document field of response
@apiSuccessExample is an example for response

I have to duplicate the response structure and any change will be done in two places 
so fi we can auto generate @apiSuccessExample from @apiSuccess
using @apiGernerateSuccessFromParams will be better

Thank.

**Comment by rottmann** [comment]
Not sure if i understand you correct, but you can define a block and use it many times.

```
/**
 * @apiDefine MySuccessMessage
 * @apiSuccess {string} name Something
 * @apiSuccessExample Some Example
 */

/**
 * @api {get} /endpoint1 MyApi1
 * @apiUse MySuccessMessage
 */

/**
 * @api {get} /endpoint2 MyApi2
 * @apiUse MySuccessMessage
 */
```

**Comment by m-amr** [comment]
I mean auto generate @apiSuccessExample from  @apiSuccess 
since that  @apiSuccess  contain all the details about the returning fields
we can auto generate success example from it.

**Comment by rottmann** [comment]
But with what kind and size of content?

A random Content could confuse a user.

example of generated example
```
{
  "firstname": "Lore ipsum",
  "lastname": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
  "number1": "4711",
  "number2": "4235872359723589"
}
```
I dont think that a random example is a good idea.
