### ISSUE TITLE
Cyrillic symbols

### ISSUE THREAD

**Issue by Hunternnm** [apidoc/apidoc#409]
Hello! When using the tool, I had a problem - do not display Cyrillic characters attribute `@apiGroup`. The file is `api_data.js` displayed like this: 
```
"group": "_____",
```
Ubuntu 15.10...

**Comment by rottmann** [comment]
`@apiGroup <name>` support only alphabetical chars.
You can define a name and use it with
```
/**
 * @apiDefine MyGroupName Insert you Cyrillic chars here
 */

/**
 * @api ....
 * @apiGroup MyGroupName
 */
```

**Comment by Hunternnm** [comment]
Thank you so much! It works!
