### ISSUE TITLE
Can't generate docs...getting "info: Nothing to do." message

### ISSUE THREAD

**Issue by calloncampbell** [apidoc/apidoc#410]
Trying to generate doc for ASP.NET Web Api using C#. After installing ApiDoc, creating a apidoc.json file in the project root and running the following command...I get "info: Nothing to do". 

 apidoc -i controllers/ --debug -o docs/

Where is the docs on info/error messages? 
What am I doing wrong?
Suggestions?

**Comment by rottmann** [comment]
If nothign to do, then no apidoc annotation was found in your source files. Could you paste a example doc source.

**Comment by sliontc** [comment]
Same happened here in Windows.

/**
 * @apiDefine RequestHeader
 *
 * @apiHeader {Object} x-api-key 访问接口需要的秘钥.
 * @apiHeader {Object} content-type 访问类型.
 *
 * @apiHeaderExample 请求信息头样例:
 *     
 *     {
 *       "content-type": "application/json",
 *       "x-api-key":"fdsaf32fjdslfds"
 *     }
 */

/**
 * @apiDefine expertApi 专家库接口
 */

/**
 * @apiDefine ckcestApi 咨询接口
 */

/**
 * @apiDefine otherApi 其他接口
 */

/**
 * @apiDefine fromsize
 * 
 * @apiParam from 页码
 * @apiParam size 页面大小
 */

 /**
  * @api {post} /searchAuthors 专家查询
  * @apiDescription 根据姓名，机构，关键词查询对应的专家
  * @apiName searchAuthors
  * @apiGroup expertApi
  * @apiUse RequestHeader
  * @apiParam keywords 关键词
  * @apiParam name 姓名
  * @apiParam organization 机构
  * @apiUse fromsize
  * @apiParamExample {json} 参数请求样例:
  *     {
  *       "name": "张三",
  *       "keywords":"计算机",
  *       "organization":"浙江大学"
  *     }
  *
  * @apiSuccessExample {json} 返回样例:
  {
  "total": 459,
  "data": [
    {
      "org": "浙江大学",
      "items": [
        {
          "_index": "authors",
          "_type": "author",
          "_id": "AVKivlZDIQ5bdb3rOMK7",
          "_score": 9.583894,
          "_source": {
            "kId": null,
            "auid": 7533493,
            "clc": "TK",
            "ccd": null,
            "keywords": "计算机",
            "isCore": null,
            "isFirst": 1,
            "isValid": 1,
            "xkmc": "动力与电气工程,能源科学技术"
          }
        }
      ]
    }
  */

**Comment by rottmann** [comment]
@sliontc under linux it is ok... i have to try it under windows.

**Comment by chrisx84** [comment]
@rottmann under linux is not ok, im running into the same issue on ubuntu when trying to generate my api docs from my laravel based api

**Comment by rottmann** [comment]
Can you post the debug output `--debug`

**Comment by ashnamuh** [comment]
also mac os..

**Comment by NicolasCARPi** [comment]
Please try again with latest version.
