### ISSUE TITLE
Define request parameters/values

### ISSUE THREAD

**Issue by mnicolas80** [apidoc/apidoc#411]
Hi!

Is there any way we can define the value(s) for specific parameter(s) in sample requests?
For example, if we need to test a api and always send predefined value for a provided parameter (e.g. username="developer"), how we can achieve it?

Thank you

**Comment by rottmann** [comment]
You can set default values
`@apiParam [(group)] [{type}] [field=defaultValue] [description]`
`@apiParam {string} Name="default" Some description`

But the send sample request module did not use the default value at the moment (you can modify the template for this).

**Comment by omidgfx** [comment]
What about default value for this?
```
@api {get} /user/:uuid=some_uuid Get User Details
```
I need a default value for :uuid for sake of sending a sample request.

I already tried
```
@api {get} /user/[:uuid=some_uuid] Get User Details
@api {get} /user/{:uuid=some_uuid} Get User Details
@api {get} /user/[uuid=some_uuid] Get User Details
@api {get} /user/{uuid=some_uuid} Get User Details
```

But non of above worked...
