### ISSUE TITLE
Possible bug in response format of GET method?

### ISSUE THREAD

**Issue by mnicolas80** [apidoc/apidoc#412]
Hi,

I am working on a API and using both POST/GET methods. The server always returns json responses.
I monitored that the Sample Request when POST data, the requested content-type is always "application/json". But when, I GET data, the content-type is plain text.
As a result, in the second case, the APIDOC stringifies the response and does not keep the right formatted response in the relevant html div.

Bellow, I found the code that is related to this issue in file "utils/send_sample_request.js" between lines 78-96:
```
      // send AJAX request, catch success or error callback
      var ajaxRequest = {
          url        : url,
          dataType   : "json",
          contentType: "application/json",
          headers    : header,
          type       : type.toUpperCase(),
          success    : displaySuccess,
          error      : displayError
      };

      if (type === 'get') {
          ajaxRequest.url = url + paramToQueryParms(param)
          //ajaxRequest.dataType = "text";
          //ajaxRequest.contentType = "text/plain";
      } else {
          if ( ! $.isEmptyObject(param)) {
              ajaxRequest.data = JSON.stringify(param);
          }
      }
```
As you see, I have commented 2 lines in GET type check. In this way, APIDOC worked without changing the formatted response.

Please advice!
Thank you

**Comment by TerryFranklin** [comment]
I have also encountered this issue, and can confirm that the above fix is a valid work around.
