### ISSUE TITLE
Generate PDF APIdoc version

### ISSUE THREAD

**Issue by sbowler** [apidoc/apidoc#413]
I haven't seen any other tools to do this so I wonder if apidoc could provide an option to also generate a PDF version of the API document. This might be nice to distribute without the need of the web server to be available to view the API.

Perhaps this can all be handled just by a template or this may be better as a plugin, although I haven't seen any plugins for apidoc. What are your thoughts?

**Comment by rottmann** [comment]
You can create a project, which uses [apidoc-core](https://github.com/apidoc/apidoc-core) to gather the api data and then use your own template to generate a pdf file.

Or use e.g. [grunt-apidoc](https://github.com/apidoc/grunt-apidoc) which creates the doc with apidoc and after this task use a pdf generator task that creates the pdf from the doc/index.html.

**Comment by kgupta4** [comment]
I have same problem, I am not able to create similar doc or pdf which can be used to share the documentation with third parties. Please let me know how can I do so.
