### ISSUE TITLE
0.15.0 : First-level @apiSuccess fields missing with @apiUse including @apiSuccess

### ISSUE THREAD

**Issue by hstonge** [apidoc/apidoc#418]
### To reproduce
1- Save the following as `test.js`:
```
/**
 * @apiDefine Pagination
 *
 * @apiParam {Number} page The page requested page number
 * @apiSuccess {Boolean} hasNextPage Indicates if further result pages are available
 */

/**
 * @api {get} /test
 * @apiName TestAPI
 * @apiGroup Tests
 *
 * @apiUse Pagination
 *
 * @apiSuccess {Object[]} results A collection of results
 * @apiSuccess {Number} results.id
 * @apiSuccess {String} results.name
 */
```
2- Execute `npm install apidoc@0.15.0`
3- Execute `./node_modules/apidoc/bin/apidoc -i . -o docs`
4- Open `docs/index.html`

### Results
Notice that the first-level _results_ @apiSuccess field is missing, while its children fields are still correctly indented.

Remove the line `@apiUse Pagination`, and the _results_ field is now showing properly.

This problem did not occur in 0.14.0 and previous versions.

### Screenshot
**With 0.15.0**
![capture d ecran 2016-02-16 a 11 31 04](https://cloud.githubusercontent.com/assets/7944194/13082945/d7b759f6-d4a0-11e5-9777-584cd556e02f.png)

**With 0.14.0**
![capture d ecran 2016-02-16 a 11 39 26](https://cloud.githubusercontent.com/assets/7944194/13083220/066e5474-d4a2-11e5-8ec6-0f8010d60295.png)

**Comment by hstonge** [comment]
Further testing reveals that it is in fact the very first @apiSuccess that seems to disappear, no matter if its hierarchical or not.

**Comment by rottmann** [comment]
Found the problem: i updated lodash library, but overlooked that _.merge is now splittet in _.merge and _.mergeWidth (which now has the customizer function).

Will publish an update soon.

**Comment by hstonge** [comment]
Thanks @rottmann for the quick update!
