### ISSUE TITLE
@apiDefine block used without @apiUse statement

### ISSUE THREAD

**Issue by brendonboshell** [apidoc/apidoc#420]
I have two @apiDefine blocks:

    /**
     * @apiDefine AuthenticationHeaders
     * @apiError (401) 401 You are not authenticated to perform the request.
     */

    /**
     * @apiDefine UsersStandardErrors
     * @apiError (400) InvalidEmail The email address is invalid.
     */

plus two API blocks:

    /**
     * @api {post} /users Create a new user account.
     * @apiVersion 1.0.0
     * @apiName CreateUser
     * @apiGroup Users
     *
     * @apiUse AuthenticationHeaders
     * @apiUse UsersStandardErrors
    */

    /**
     * @api {post} /clients Create a new client.
     * @apiVersion 1.0.0
     * @apiName CreateClient
     * @apiGroup Clients
     *
     * @apiUse AuthenticationHeaders
     *
     */

Given the above, my expectation was to have the 401 and 400 errors included for `POST /users` and just the 401 error for `POST /clients.` However, it appears that both blocks are included in both API docs. Both items in api_data.json have the following `error` property:

    "error": {
      "fields": {
        "400": [
          {
            "group": "400",
            "optional": false,
            "field": "InvalidEmail",
            "description": "<p>The email address is invalid.</p>"
          }
        ],
        "401": [
          {
            "group": "401",
            "optional": false,
            "field": "401",
            "description": "<p>You are not authenticated to perform the request.</p>"
          }
        ]
      }
    }

Is this a bug or intended behaviour?

**Comment by rottmann** [comment]
Did you use the latest 0.15.1 ?

**Comment by brendonboshell** [comment]
Apologies for wasting your time. I was running 0.15.0. Issue is resolved with 0.15.1.
