### ISSUE TITLE
0.15.0 and 0.15.1 send formUrlEncoded instead json.

### ISSUE THREAD

**Issue by fedefarina** [apidoc/apidoc#424]
Hi rottmann! great tool. I have an issue with 0.15.0 and 0.15.1 with content type in post requests. By default 0.14.0 send json content type but new releases send payload as formurlencoded. Here´s and example of the issue, request must be json but is sent as formurlencoded:

/**
 * @api {post} apps Create a new app associated with an account
 * @apiName Create a new app
 * @apiGroup App
 *
 * @apiVersion 0.1.0
 *
 * @apiParam {String} name  The app name
 *
 * @apiParamExample {json} Request-Example:
 * {
 *    "name": "anAppName",
 * }
 *
 * @apiHeader {String} Authorization Authorization value.
 *
 * @apiHeaderExample {json} Header-Example:
 * {"Authorization": "Bearer anAccessToken" }
 *
 * @apiUse EmptyField
 * @apiUse UnAuthorized
 *
 * @apiSuccess {Object} app  Created app
 *
 *
 * @apiSuccess {Object} account  Account related to given credentials
 *
 * @apiSuccessExample Success-Response:
 *  HTTP/1.1 200 OK
 *  {
 *    "data": {
 *      "accessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjE0NSwiaWF0IjoxNDU1MTQ4NzM1fQ.rlYktUwJvyVu25edkycdTI0fo5l7cetiXITrL8qY1oU",
 *      "account": {
 *        "email": "accountEmail@domain.com",
 *        "id": 145,
 *        "created_at": "2016-02-10T00:48:50.667Z",
 *        "updated_at": "2016-02-10T00:48:50.667Z",
 *        "name": "nombre",
 *        "phoneNumber": null,
 *        "status": "active",
 *        "role": "user"
 *      }
 * }
 *
 *
 */

**Comment by rottmann** [comment]
I stop modifying the sampleRequest Plugin (i never want to built in within apidoc) and only merge "every" pull request into it. The Addon needs to be rewritten from ground, every patch cause other problems.

Hope one of the last contributors to the sampleReqest Plugin can fix it:
[@Alphmega](https://github.com/Alphmega)
[@Senorsen](https://github.com/Senorsen)
[@slab](https://github.com/sldab)
[@zenozeng](https://github.com/zenozeng)
[@nekocode](https://github.com/nekocode)
[@b6pzeusbc54tvhw5jgpyw8pwz2x6gs](https://github.com/b6pzeusbc54tvhw5jgpyw8pwz2x6gs)
