### ISSUE TITLE
Generate a documentation by permission

### ISSUE THREAD

**Issue by Julienh** [apidoc/apidoc#425]
Hi,

Is it possible to generate a documentation by permission?
For example I have 2 permissions (Admin, User) and I want to generate a documention for User and hide all Admin only methods.

Thanks for you work :)

**Comment by KhodeN** [comment]
Great idea!

**Comment by rottmann** [comment]
This must be done manually.
View: https://github.com/apidoc/apidoc/issues/326#issuecomment-164471812
