### ISSUE TITLE
Group descriptions from previous versions are displayed

### ISSUE THREAD

**Issue by andrewbott** [apidoc/apidoc#428]
This issue relates to:
apidoc@0.14.0
apidoc-core@0.5.1

When using @apiDefine to detail Group titles and descriptions, apidoc correctly inherits the @apiDefine block with the @api method of the same version when generating e.g. api_data.js, but the webform shows the group title and description from whichever api method is referenced last in  api_data.js ( or so it seems ), rather than the version selected on the webform.

E.g. (using python comment blocks ):  apidoc -f .py

"""
@apiDefine MyGroup My Group Title
My Group Description
@apiVersion 1.0.0
"""
"""
@apiDefine MyGroup My Group Title
My UPDATED Group Description
@apiVersion 1.0.1
"""

"""
@api {get} /my/method/ My method
@apiVersion 1.0.0
@apiGroup MyGroup
""""

"""
@api {get} /my/method/ My method
@apiVersion 1.0.1
@apiGroup MyGroup
""""

**Comment by rottmann** [comment]
Thanks, seems a bug in the template, i have to review it.
The generated .json file is correct.
