### ISSUE TITLE
Automatic formatting of the examples

### ISSUE THREAD

**Issue by VieuxChameau** [apidoc/apidoc#429]
Hello,

it would be great to add the ability to format all the provided examples of the different @api*Example annotations. Because if the example is badly format in the javadoc you have exactly the same output.

Maybe add it as a global property in apidoc.json or a new param in the annotation

Thanks

**Comment by rottmann** [comment]
Could you give me an example?

**Comment by VieuxChameau** [comment]
Hi,

For example if you write the documentation like this in your code

```
/**
 * @api {get} /user/:id
 * @apiSuccessExample {json} Success-Response:
 *     HTTP/1.1 200 OK
 *     {"firstname": "John","lastname": "Doe"}
 */
```

The json example will be exactly the same. It would be nice to be able to have the generated output to be pretty-printed/formatted.

**Comment by i-m-developer** [comment]
Facing the same issue apidoc now generates quite pretty formatted json example but when i click on version drop down and select previous one it turns in to same ugly format with scrollbar at bottom like the pic in attachment
![apidoc pic](https://cloud.githubusercontent.com/assets/10174211/24194891/f618f586-0eb4-11e7-93ce-08f59dcabd0e.png)

**Comment by NicolasCARPi** [comment]
The json will be correctly formatted if you use like this (remove the HTTP code):

~~~php
/**
 * @api {get} /user/:id
 * @apiSuccessExample {json} Success-Response:
 *     {"firstname": "John","lastname": "Doe"}
 */
~~~

![2019-10-20-020038_380x193_scrot](https://user-images.githubusercontent.com/3043706/67152762-63f1dc80-f2dd-11e9-801a-3c11cc923736.png)
