### ISSUE TITLE
rquest about params format

### ISSUE THREAD

**Issue by Rekoe** [apidoc/apidoc#430]
use the last update ver
when i make the apidoc the @ apiSmallRquest get the all request by data

```
name=xxx&age=10
```

 not

```
 {"name":"abc","age":10}
```

when i check the send_sample_request.js file ,i found the not same code about

```
      // send AJAX request, catch success or error callback
      var ajaxRequest = {
          url        : url,
          headers    : header,
          data       : param,
          type       : type.toUpperCase(),
          success    : displaySuccess,
          error      : displayError
      };

      $.ajax(ajaxRequest);
```

it may be

```
 // send AJAX request, catch success or error callback
      $.ajax({
          url: url,
          dataType: "json",
          contentType: "application/json",
          data: JSON.stringify(param),
          headers: header,
          type: type.toUpperCase(),
          success: displaySuccess,
          error: displayError
      });
```

why this happen ,and how can do?

@rottmann

**Comment by sonicwong** [comment]
It look like you need to change the code in file: utils/send_sample_request.js

data : param   ==>  data : JSON.stringify(param)

**Comment by AndrasCodeNasher** [comment]
I had the same issue about the formation of the JSON-object. But there seems to be a problem with the suggested soloution. I am learning apidoc right now and want to document a small simple rest-API with some GET and POST methods. 
The problem with `data = JSON.stringify(param),` is that my sample-GET-calls have always a "?{}" appended. 
My soloution looks like that:
`      // send AJAX request, catch success or error callback
      var ajaxRequest = {
          url        : url,
          headers    : header,
          data       : param,
          type       : type.toUpperCase(),
          success    : displaySuccess,
          error      : displayError
      };

      if (type === 'post') {
          if ( ! $.isEmptyObject(param)) {
              ajaxRequest.data = JSON.stringify(param);
          }
      }

      $.ajax(ajaxRequest);`

**Comment by NicolasCARPi** [comment]
This is done.
