### ISSUE TITLE
Single class implements multiple endpoints - possible to document?

### ISSUE THREAD

**Issue by saritasa** [apidoc/apidoc#433]
For example Django Rest Framework viewset

allows to define in a single class

GET /users
GET /users/DD
DELETE /users/ID
PUT, PATCH /users/ID

is it possible to document multiple methods within a single class? I tried to put two '@api' inside single docstr but it didn't help, second always overwrites the first.

```python
class UsersAPIView(viewsets.mixins.CreateModelMixin,
                   viewsets.mixins.ListModelMixin,
                   viewsets.mixins.RetrieveModelMixin,
                   viewsets.mixins.UpdateModelMixin,
                   viewsets.mixins.DestroyModelMixin,
                   viewsets.GenericViewSet):
    """
    @api {get} /user/:id Request User information
    @apiName GetUser
    @apiGroup User

    @apiParam {Number} id Users unique ID.

    @apiSuccess {String} firstname Firstname of the User.
    @apiSuccess {String} lastname  Lastname of the User.

    @api {get} /users/ Request User List information
    @apiName GetUsers
    @apiGroup User
    """
    queryset = AppUser.objects.all()
    permission_classes = (IsAuthenticated,)
    serializer_class = CustomUserDetailSerializer
```

**Comment by mauler** [comment]
Try to create a method with passou statement for each one eg nil_post

**Comment by amitmahbubani** [comment]
@saritasa Try putting the definitions in seperate comments blocks, like:

```"""
    @api {get} /user/:id Request User information
    @apiName GetUser
    @apiGroup User

    @apiParam {Number} id Users unique ID.

    @apiSuccess {String} firstname Firstname of the User.
    @apiSuccess {String} lastname  Lastname of the User.
    """
    """

    @api {get} /users/ Request User List information
    @apiName GetUsers
    @apiGroup User
    """
```

**Comment by amismailphp** [comment]
Any one has solution? I am facing the same problem.

**Comment by rottmann** [comment]
As @amitmahbubani wrote, use define and use:

Define:
```
"""
@apiDefine UserInfo
@apiParam {Number} id Users unique ID.

@apiSuccess {String} firstname Firstname of the User.
@apiSuccess {String} lastname  Lastname of the User.
"""
```
and use:
```
"""
@api {get} /user/:id Request User information
@apiName GetUser
@apiGroup User
@apiUse UserInfo
"""

"""
@api {post} /user/:id Post User information
@apiName PostUser
@apiGroup User
@apiUse UserInfo
"""
```

**Comment by amismailphp** [comment]
Thanks for reply,
I am using PHP 
This is my code and not working, it selects only one of the 2 apis

`/**
     * @api {get} /areas/:areaId/lessons List Lessons Under Area 
     * 
     * @apiVersion 0.0.1
     * @apiName ListLessons
     * @apiGroup Lessons
     *  
     * @apiSuccess {Object} data includes list of Lessons.
     * @apiSuccessExample {json} Success-Response:
     *     HTTP/1.1 201 Created
     *     {
     *        "data": [
     *          {
     *            "id": "57037d812ef10212c63a1721",
     *            "title": "First lesson title",
     *            "description": "First lesson description",
     *            "ui": "{\"css_class\": \"foo\"}",
     *            "created_at": "2016-04-05 08:55:29",
     *            "updated_at": "2016-04-07 11:56:38"
     *          },
     *          {
     *            "id": "570385212ef10212c63a1722",
     *            "title": "Second lesson title",
     *            "description": "Second lesson description",
     *            "ui": "{\"css_class\": \"foo\"}",
     *            "created_at": "2016-04-05 09:28:01",
     *            "updated_at": "2016-04-05 09:28:01"
     *          },
     *        ]
     *      }
     * 
     * @apiUse AreaNotFoundError
     * 
     */
    
    
    /**
     * @api {get} /sections/:sectionId/lessons List Lessons Under Section
     * 
     * @apiVersion 0.0.1
     * @apiName ListLessons
     * @apiGroup Lessons
     *  
     * @apiSuccess {Object} data includes list of Lessons.
     * @apiSuccessExample {json} Success-Response:
     *     HTTP/1.1 201 Created
     *     {
     *        "data": [
     *          {
     *            "id": "57037d812ef10212c63a1721",
     *            "title": "First lesson title",
     *            "description": "First lesson description",
     *            "ui": "{\"css_class\": \"foo\"}",
     *            "created_at": "2016-04-05 08:55:29",
     *            "updated_at": "2016-04-07 11:56:38"
     *          },
     *          {
     *            "id": "570385212ef10212c63a1722",
     *            "title": "Second lesson title",
     *            "description": "Second lesson description",
     *            "ui": "{\"css_class\": \"foo\"}",
     *            "created_at": "2016-04-05 09:28:01",
     *            "updated_at": "2016-04-05 09:28:01"
     *          },
     *        ]
     *      }
     * 
     * @apiUse SectionNotFoundError
     * 
     */
    public function index($parentId) {
        $parentResourceController = $this->parentResourceController;
        $parent = $parentResourceController::findModel($parentId);

        if (!$parent instanceof $this->parentResourceModel)
            return $parent;

        return $this->collection($parent->lessons, new LessonTransformer());
    }`

**Comment by rottmann** [comment]
You have to blocks with the same name and group.
Change the second block to:
`* @apiName ListLessonsUnderGroup`
and it work.

I have to add a warning / error for such cases, set it on todo.

**Comment by amismailphp** [comment]
It Works, many thanks for you.
