### ISSUE TITLE
Deep Link Support

### ISSUE THREAD

**Issue by BarrySkidmore** [apidoc/apidoc#435]
We are currently using apiDoc 0.12 and deep links appear to fail on page load but not from within page usage.  Trying to link a user to a specific documentation section thus fails.

Is there a plan to support deep links in apiDoc or does a newer version already support it?

**Comment by rottmann** [comment]
You can set links with hash e.g. http://apidocjs.com/example/#api-User-PutUser

**Comment by BarrySkidmore** [comment]
Interesting, so it appears to be a bug.  https://console.cloudinsight.alertlogic.com/api/assets/#api-Assets_Queries-General_Query-1.0.0 - This link works fine after the page loads, but does not work when visiting the link directly in Safari or Chrome on a Mac.

**Comment by NicolasCARPi** [comment]
Please reopen if bug is still here.
