### ISSUE TITLE
Is it possible to parse one single file?

### ISSUE THREAD

**Issue by flogr** [apidoc/apidoc#436]
I have one file i want to be parsed called "Service.php", path "/project/rest/Service.php". Is it possible to parse only this one?

I tried:

apidoc -i "/project/rest/Service.php" -o apidoc/

doesnt work, says no files. Also played with regex in -f param, but doesnt work either.

**Comment by rottmann** [comment]
No only dirs.

Copy your file to a temp folder and create the doc from this folder.

**Comment by flogr** [comment]
Thanks a lot, copying to a temp folder works fine for me, too ;)
