### ISSUE TITLE
apidoc.json not found if specify multiple input files

### ISSUE THREAD

**Issue by hwdavidward** [apidoc/apidoc#437]
When multiple input sources are specified using the command line the apidoc.json is not found.The tool warns "Please create an apidoc.json configuration file." even though the apidoc.json is located in one (or both) of the folders.

Example:

app
----api
-------apidoc.json
-------resource.py
----shared
-------something.py
----docs
-------{generated content}

> apidoc -i app/api/ -i app/shared/ -o app/docs/static/ 
warn: Please create an apidoc.json configuration file.
info: Done.

The result is working documentation but with none of the apidoc.json configurations.

**Comment by hwdavidward** [comment]
Is there an easy fix for this?

**Comment by rottmann** [comment]
Currently it reads the apidoc.json only in the base dir, where you call apidoc.

**Comment by hwdavidward** [comment]
Correct, but is there an easy way to provide a path to the apidoc.json instead? I have a shared dir that I would like to include as well.

**Comment by rottmann** [comment]
You can cwd to api dir with adidoc.json
