### ISSUE TITLE
Apidoc not working for Flask-JWT's authentication url

### ISSUE THREAD

**Issue by hussaintamboli** [apidoc/apidoc#438]
I have started using apidoc for generating REST api documentation. I have tried different things with it.

In my flask based api application, I use JWT (flask-jwt in particular) for authentication. The doc gets generated properly, but the request from the doc doesn't happen properly.

This is where I have put the docsting for generating the doc

```
def authenticate(username, password):
    """
    @api {post} /auth Authentication url
    @apiName Authentication
    @apiGroup Login

    @apiParam {String} username Username of the user
    @apiParam {String} password Password of the user

    @apiSuccess {String} access_code JWT

    @apiSuccessExample Success Response
    HTTP/1.1 200 OK
    {
       "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGl0eSI6IjM5MDA4MGExLWY0ZjctMTFlNS04NTRkLTI4ZDI0NDQyZDNlNyIsImlhdCI6MTQ1OTE3ODE0NSwibmJmIjoxNDU5MTc4MTQ1LCJleHAiOjE0NTkxNzg0NDV9.nx_1a4RmvJ7Vlf1CvnMzqoTfzChcuJnDb1Tjy1_FnXw"
    }

    @apiErrorExample Invalid Credentials
    {
      "description": "Invalid credentials",
      "error": "Bad Request",
      "status_code": 401
    }
    """
    user = session.query(User).filter_by(username=username).first()
    if user and user.is_correct_password(password):
        return user
    return False
```

And when I generate the doc, it get's generated properly

```
$ apidoc -i onehop/ -o doc
```
1. But when I pass credentials from the generated doc, the request fails. The request data I get in flask's request is '' (empty)
2. It also fails even after including the Content-Type header in the docstring. The request data I get in flask's request is username=test@example.com&password=test123

I have confirmed above by putting debug points in Flask-JWT's code

```
def _default_auth_request_handler():
    data = request.get_json()   # My debug poing
    username = data.get(current_app.config.get('JWT_AUTH_USERNAME_KEY'), None)
    password = data.get(current_app.config.get('JWT_AUTH_PASSWORD_KEY'), None)
```

But when I make the same request using `postman` it happens properly.

I also saw the the test code of flask-jwt, where it makes a `post` request to the `auth` url

```
def post_json(client, url, data):
     data = json.dumps(data)
    resp = client.post(url, headers={'Content-Type': 'application/json'}, data=data)
    return resp, json.loads(resp.data)
```

How do I post `json` data to an `api` in apidoc?

Postman headers
![postman headers](https://cloud.githubusercontent.com/assets/2324958/14318332/f22da712-fc29-11e5-9240-a35a0e13ff8b.png)

Apidoc headers
![apidoc headers](https://cloud.githubusercontent.com/assets/2324958/14318340/fce30242-fc29-11e5-9750-8b5d604aedcd.png)

**Comment by NicolasCARPi** [comment]
Please try the latest version.
