### ISSUE TITLE
Order

### ISSUE THREAD

**Issue by DarkCobalt** [apidoc/apidoc#439]
Hi,

You have standart order alfabetic, but i want use order that how I have write methods in file.
I see your metods order apidoc.json but i have 3 diffrend api and one file configuration....

if you can add order alfabetic as optional in configuration file, that was great!

**Comment by rcrooks** [comment]
@DarkCobalt you can specify the order (both groups and methods) using the "order" field in the apidoc.json:

    "order": [
      "Players",
      "Get_Single_Player",
      "Get_All_Players",
      "Create_a_Player",
      "Update_a_Player",
      "Publish_a_Player",
      "Delete a Player",
      "Player_Configurations",
      "Get_a_Player_Configuration",
      "Update_a_Player_Configuration",
      "Player_Embeds",
      "Get_Single_Embed",
      "Get_All_Embeds",
      "Create_an_Embed",
      "Publish_an_Embed",
      "Delete_an_Embed",
      "Embed_Configurations",
      "Get_an_Embed_Configuration",
      "Update_an_Embed_Configuration",
      "Get_Configuration_Combinations"]

(note that spaces in group/method names need to be replaced by underscores (_) )

**Comment by Asoul** [comment]
Thanks @rcrooks. But add underscores is too tricky, should add some documentation for it.
