### ISSUE TITLE
CLI not working in linux box

### ISSUE THREAD

**Issue by pranaydutta89** [apidoc/apidoc#440]
apidoc cli is not working while its in linux box , even after installing globally its giving error as  "-bash: apidoc: command not found", however its working fine in windows machine. please help me with the issue

**Comment by rottmann** [comment]
I develop it on a linux machine, check your paths in ~/.bashrc and reopen the machine and try it again

Set 
`export NODE_PATH=/usr/local/lib/node_modules`
or
`export NODE_PATH="/usr/lib/node_modules`

depending on where your modules are.

**Comment by veken1199** [comment]
i still have this issue @rottmann
