### ISSUE TITLE
it seems that input option on config works yet not output

### ISSUE THREAD

**Issue by incodemode** [apidoc/apidoc#442]
I used input option on config like this:
```
"input": {
  		"locations": [
    		"./apidoc_endPoints/*.js"
    	]
    },
```
yet I have been trying to use several other ways for output as 
```
"output": {
  		"location": "./docs/"
    },
```
I have been searching for the code where this is defined so I can understand it and if not added, then add it, can you guide me to that code? so I can develop/document it and use it?

**Comment by rottmann** [comment]
View defaults for details https://github.com/apidoc/apidoc-core/blob/master/lib/index.js
Or did you mean the grunt file? 

Dont know what you mean with "locations" or "location", config output uses "dest".
