### ISSUE TITLE
Headers disappear when comparing versions

### ISSUE THREAD

**Issue by code-troll** [apidoc/apidoc#443]
Hi, I'm using the version 0.15.1 of apidoc-generator and I'm experienced what I think is an issue.

I have a change in the header of a resource in my API between two version and when I'm comparing the versions I see that the header is disappearing.

This makes imposible to see the differences in the header parameters.

**Comment by pjotre86** [comment]
Hey!
+1
Same problem here. The disappearing header is also confusing even when the header itself did not change.
Would be cool if someone could fix this!

**Comment by PunchyRascal** [comment]
+1 here

**Comment by PunchyRascal** [comment]
Also other data disappears, such as _Allowed values_ in @apiSuccess declaration

**Comment by Perdiga** [comment]
+1

Does anyone know how to solve this bug, or any workaround?
Is there a way to compare headers too ?? When I change version don't change header.

**Comment by goncalomcunha** [comment]
Same here. Any news on this?

**Comment by Jeroenimoo0** [comment]
+1
