### ISSUE TITLE
install bug

### ISSUE THREAD

**Issue by wirwolf** [apidoc/apidoc#446]
npm install apidoc -g
npm http GET https://registry.npmjs.org/apidoc
npm http 200 https://registry.npmjs.org/apidoc
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token 
npm ERR! �Y[o�6�+��k��H�4�!:
                                 }Pt]_�!�M�Z]
������bS�n�������u�6uhz����    ��m�8���yo�]��K*Ӈ��R������:�|5HS�v��o�FG0��'�c6��5��L�	��	�X���&8�[kr�,�ګ�S�}o:�u_�
npm ERR! ��:��Ї8{��}m�"�ڔ���

**Comment by rottmann** [comment]
not an apidoc problem
