### ISSUE TITLE
Space in Parameter Type throws error

### ISSUE THREAD

**Issue by BenSower** [apidoc/apidoc#448]
This example (note the space in the Api-Success Object type) 

```
/**
 * @api {get} /user/:id Request User information
 * @apiName GetUser
 * @apiGroup User
 *
 * @apiParam {Number} id Users unique ID.
 *
 * @apiSuccess {String Space} firstname Firstname of the User.
 */
```

throws this error:

```
error: Empty parser result. 
{ File: './apidoctest.js',
  Block: 1,
  Element: '@apiSuccess',
  Source: '@apiSuccess {String Space} firstname Firstname of the User.' }
```

This seems to happen for the other Object types, too. Is this expected behaviour?

(Javascript, 0.15.1 installation of apidoc under Ubuntu)

**Comment by rottmann** [comment]
Currently yes. All parser regexpressions are reduced to basic functionality, e.g. names without spaces and so on.

**Comment by paylease-kpalmer** [comment]
Do you have any plans to support spaces in the future?

**Comment by lydiardfan** [comment]
Do you have any plans to support spaces in the future?
