### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by jiangzhixiao** [apidoc/apidoc#449]
When i send a url request,i got the below error
1、Click send
![image](https://cloud.githubusercontent.com/assets/7273487/14339919/ce2036f6-fcb4-11e5-8dfa-0c69658b068d.png)
2、Get these Error
![image](https://cloud.githubusercontent.com/assets/7273487/14339946/11cdcd96-fcb5-11e5-89da-2a86e394967f.png)

**Comment by Laro88** [comment]
Most likely the server does not have any cross site allowed.
In Restify a setup could look like this.
```
var server = restify.createServer();

server.use(
  function crossOrigin(req,res,next){
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "X-Requested-With");
    return next();
  }
);
```

**Comment by jiangzhixiao** [comment]
@Laro88 I resolve h色s
