### ISSUE TITLE
apidoc annotations on same line in comments instead of new line

### ISSUE THREAD

**Issue by shwethakiranmaiye** [apidoc/apidoc#450]
Hi,
I am converting Yang models to Java files. I am unable to display the comments in new line after compilation of yang models to java files.

Can I render documentation even though all the api parameters are on same line?
Ex: 
 /**
     * @api {get} /user/:id Request User information  @apiName User 
     * address @apiName GetUser @apiGroup User @apiParam {Number} id
     * Users unique Id.
     */

**Comment by rottmann** [comment]
Each @ Annotation must start in a new line.

```
/**
* @api {get} /user/:id Request User information @apiName User address
* @apiName GetUser @apiGroup User @apiParam {Number} id Users unique Id.
*/
```
