### ISSUE TITLE
For a param that is an array of strings, is it possible to specify the max length of strings and the array?

### ISSUE THREAD

**Issue by rcrooks** [apidoc/apidoc#451]
I have a param that is an array of strings, and there are max length limits for both the strings and the array.

I tried:

    @param {string{..128}[]{..150} 

but it doesn't parse correctly. Couldn't think of another way....

**Comment by rottmann** [comment]
Only simple structure definitions are currently possible.
You can add the details to the description `@apiParam {string[]} myvar <code>Size:</code>max 150 entries, each with max 128 chars.`

**Comment by rcrooks** [comment]
thanks Peter
