### ISSUE TITLE
Use java constant like Javadoc

### ISSUE THREAD

**Issue by TakiuGit** [apidoc/apidoc#454]
ApiDoc does not curently support the usage of constant  like Javadoc :

```
String user = "bob";
/**
 * @api {get} /toto hello {@value #user} 
 * @apiName getHello
 * @apiGroup hello
*/
```

Give "hello {@value #user}" instead of "hello bob".

**Comment by NicolasCARPi** [comment]
This would mean that the parser needs to understand the code outside the comments, right? Feel free to make a PR over at apidoc/apidoc-core but I don't think this will be implemented.
