### ISSUE TITLE
Cascade use of @apiUse and @apiDefine

### ISSUE THREAD

**Issue by TakiuGit** [apidoc/apidoc#455]
It's curently impossible to use @ApiUse and @ApiDefine in the same block:

For practical reason i need to define my parameter as :
```
/**
 * @ApiDefine MyParam
 * @ApiParam String foo this is a foo
 */
```

I also need to define a function that use this parameter : 
```
/**
 * @ApiDefine MyFunction
   ...
 * @ApiUse MyParam
 */
```
And then use it (with adding other parameter or override some)
```
/**
 * @Use MyFunction
    ...
 * @ApiParam String foo2 this is a foo2
 */
```

I've seen an issue talking about fixing it, is it still in progress ? Or is there other solution to this kind of problem ?

**Comment by TakiuGit** [comment]
Did you have any feedback on it ?

**Comment by rottmann** [comment]
Multi sub inheritance is not supported and currently not on my todo.

Basic function of apidoc should be a readable source code without searching on different files or positions for the annotation, that explain the api.

You can define multiple things and use them:
```
/**
  * @apiDefine MyParam
  * @apiParam {string} fot this is a foo 
 */

/**
 * @apiDefine SomethingElse
 * @apiParam {string} foo2 this is a foo2
 */

/**
 * @api {get} /some/api
 * @apiUse MyParam
 * @apiUse SomethingElse
 *
 * @apiParam {string} foo3 this is a foo3
 */
```
