### ISSUE TITLE
Serving on a subfolder, index.html has hrefs and srcs on root

### ISSUE THREAD

**Issue by schoettler** [apidoc/apidoc#460]
I have served apidoc on /docs, but all the files are returning 404, because the index.html is looking for the files relatively:

`src="vendor/require.min.js"`

Should be: 

`src="docs/vendor/require.min.js"`

**Comment by rottmann** [comment]
Yes relative to docs/ dir.
You open index.html within docs/ and from there index.html opens vendor/....  relative to itself.
Or did you move index.html?

**Comment by schoettler** [comment]
As i suspected, it was an error at my end.

I'm using `koa-mount` and placed the relative directory to `/docs` instead of `/docs/`.
