### ISSUE TITLE
Add custom parser to system?

### ISSUE THREAD

**Issue by marktopper** [apidoc/apidoc#463]
How can I add a custom parser to the apidoc?

```
// Just a test
var FooBar = function()
{
    return 'FooBar';
};

/**
 * Exports
 */
module.exports = {
    parse : FooBar,
    path  : 'local.foo.bar',
    method: FooBar
};
```

And then I want to trigger it on `@apiFooBar`.

**Comment by rottmann** [comment]
`$ apidoc --parse-parsers foobar=/path/to/foobar.js`


method is not your Function, that is parse: FooBar
method mean how the Data (that was extracted with parse: FooBar) will be inserted in the data tree
`method : 'insert'` or `method : 'push'` (e.g. for arrays)

For examples look at https://github.com/apidoc/apidoc-core/tree/master/lib/parsers

**Comment by marktopper** [comment]
Thanks.

However now I just get the warning `warn: parser plugin 'apifoobar' not found in block: 0`.

Any ideas?

**Comment by marktopper** [comment]
Nevermind, had to use `$ apidoc --parse-parsers apifoobar=/path/to/foobar.js`.
