### ISSUE TITLE
v0.16.0 broken

### ISSUE THREAD

**Issue by Kurairaito** [apidoc/apidoc#466]
Hello,

The new version at tag 0.16.0 is broken and trying to generate a doc throw : 

> error: Maximum call stack size exceeded

downgrading to 0.15.0 resolve the issue

I installed it via npm under windows 10 x64

**Comment by rottmann** [comment]
Can you provide some details: os, node version

**Comment by rottmann** [comment]
Thanks i think i know what the problem is.

**Comment by rottmann** [comment]
I forgot Windows ;) In apidoc/node_modules/apidoc-core/lib/plugin_loader.js there is a function detect with a check for slash and not with "C:\" too. Fix it later, currently not in the office.
If you want you can replace and check it.

**Comment by Kurairaito** [comment]
I couldn't find the file you mentionned, but I can continue with older version for the moment.

**Comment by rottmann** [comment]
New version 0.16.1 is up.

**Comment by Kurairaito** [comment]
I confirm that 0.16.1 fixes the issue
