### ISSUE TITLE
Sample requests sending parameters as URL Encoded (15.1)

### ISSUE THREAD

**Issue by ftlio** [apidoc/apidoc#469]
I'm serving up apidocs off of a different port than the API.  This may be CORS related, but the sample requested generated to test:

/*\*                                                                                                                                  
- @api {post} /example  
- @apiName example  
- @apiGroup group  
- @apiVersion 1.0.0  
-   
- @apiParam {String} param1  
- @apiParam {String} param2  
-   
- @apiSuccess {String} success_string  
  **/

Is resulting in the following when data is sent using the sample request:

**REQUEST HEADERS**
POST /example HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Content-Length: 51
Accept: application/json, text/javascript, _/_; q=0.01
Origin: http://localhost:4000
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
DNT: 1
Referer: http://localhost:4000/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8

param1=value1&param2=value2

Just in case:
**RESPONSE HEADERS**
HTTP/1.1 400 Bad Request (because I'm expecting JSON)
Content-Type: application/json
Content-Length: 175
Access-Control-Allow-Origin: http://localhost:4000
Access-Control-Expose-Headers: api-version, content-length, content-md5, content-type, date, request-id, response-time
Date: Sun, 24 Apr 2016 20:16:39 GMT
Connection: keep-alive

Is there any way to get it to send JSON? (Everything works when I send JSON manually).

**Comment by heisian** [comment]
This issue has nothing to do with CORS or running your server from a different port.

I think the best way to solve this would be to set your server to accept `application/x-www-form-urlencoded` or `multipart/form-data` depending on the request method.  This should be a pretty stock setting on any web app.

Yes, the apidoc framework could be modified to send `application/json` but I don't think it's really the focus of this suite to provide what essentially would be something similar to [Postman](https://www.getpostman.com/).  Unless @rottmann is interested in allowing the user to specify how the request data is sent, I would examine your own server/web app configuration before asking to modify this codebase.

**Comment by NicolasCARPi** [comment]
New version should fix this issue.
