### ISSUE TITLE
how to use the [group] of @apiSuccess ? where do need use the [group] of @apiSuccess?

### ISSUE THREAD

**Issue by mingkaili** [apidoc/apidoc#471]
(http://apidocjs.com/#param-api-success ) the following is the explanation, but I don`t know what the meaning is. Could you explain it again?

@apiSuccess [(group)] [{type}] field [description]
Success return Parameter.
Usage: @apiSuccess {String} firstname Firstname of the User.
Name	Description
(group) optional	All parameters will be grouped by this name.
Without a group, the default Success 200 is set.
You can set a title and description with @apiDefine.
{type}optional	Return type, e.g. {Boolean},  {Number},  {String}, {Object}, {String[]} (array of strings), ...
field	Return Identifier (returned success code).
descriptionoptional	Description of the field.

I want to know how to use (group). Here is example.
example 1:
@apiSuccess (success200) {String} name   it is name
@apiSuccess (success300) {String} name   it is name

I don't know what case i can use it like example 1.

Thanks for your help.

**Comment by mingkaili** [comment]
gogogo

**Comment by rottmann** [comment]
You don't need the group, it is optional.

You can use the group for different https-status codes, or when your api respond different things depending on the params.

You can use a single group too to rename the header of the output (generated doc)

```
/**
 * @apiDefine MyGroup Super awesom group
 */

/**
 * @api {get} /some/api
 * @apiSuccess (MyGroup) {string} nam it is a name
 */
```

When you watch the example http://apidocjs.com/example/ you see a header "Success 200"
When you create a doc with an own group, the header "Success 200" will be replaced with your description, e.g. "Super awesom group"

**Comment by mingkaili** [comment]
@rottmann thanks.
