### ISSUE TITLE
Questions about templates, Accept/other headers and sample code

### ISSUE THREAD

**Issue by psidari** [apidoc/apidoc#475]
Is there another location on GitHub or elsewhere where I can look for extended/customized templates?
Is there any support for showing headers especially content type support info (JSON, XML, etc.)?

Has anyone build support for displaying sample code for APIs in different languages (C#, Perl, Python, Ruby, Java, etc.)?

Thanks.

- Phil

**Comment by rottmann** [comment]
Did not know if somebody create a template, i admit it is a much work to create a template (have to make it easier).
