### ISSUE TITLE
Question on having Multiple GET method in multiple lines

### ISSUE THREAD

**Issue by omairsuleman** [apidoc/apidoc#476]
Hi, 
I'm new to API economy and APIdoc.  APIDoc appears to handy utility to generate RESTful API documentation in quick and fast. 

While going through the APIDoc params, I was not able to understand on how to describe multiple URL for single API name e.g  @apiName SearchContact  in a separate lines. 

sample GET method. 
GET /search-contacts
GET /search-contacts/{searchContactId}
GET /search-contacts/{searchContactId}/contacts

Does APIDoc has  param to support such request or have to tweak the index.js to add multiple URL.

Thanks in advance
OS

**Comment by rottmann** [comment]
You can style the name as you want, the params get described with apiParam
```
/**
 * @api {get} /search-contacts/{searchContactId}
 * @apiParam {int} searchContactId Some ID.
 */

or

/**
 * @api {get} /search-contacts/:searchContactId
 * @apiParam {int} searchContactId Some ID.
 */
```

**Comment by omairsuleman** [comment]
Thanks for your reply - I shall try and update on the suggested approach.. 
I wanted to check on the scope of expansion and collapse rather then long list of data-elements to show and scrolling down take long. if such function is available  using APIDoc parmas...for example expand and then click to collapse (See-shot below).
Please advice 
![image](https://cloud.githubusercontent.com/assets/19246074/15295902/80c4379c-1bc5-11e6-9479-85f1472d9ea8.png)

**Comment by rottmann** [comment]
You can copy and modify the included template and add a expand/collapse function via jquery to nested elements.
