### ISSUE TITLE
ApiExample doesn't support Header Tokens in curl Requests?

### ISSUE THREAD

**Issue by hypematic** [apidoc/apidoc#477]
Hello, i'm trying to get my ApiDoc to show results live from @apiExample with a custom HTTP Header that i have set up for Authentication the curl request works fine on the CMD but for some reason it fails and i keep getting 401's when trying it with ApiDoc

curl -H "API-Token: XXXXXXXXXXXXXXXXXXX" -H "Accept: application/json" http://testing.app.api.com/api/v1/object/example

Works fine on the CMD, on the actual apiDoc however i get a 401, is there any way to make this work with ApiDoc?

**Comment by NicolasCARPi** [comment]
See: https://github.com/apidoc/apidoc/issues/604#issuecomment-542440118
