### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by mdsadiq** [apidoc/apidoc#479]
I am getting following message upon installing apidoc :
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for.

**Comment by rottmann** [comment]
Is in progress, i need a sync function form node-fs-extra, but still not available.
https://github.com/jprichardson/node-fs-extra/issues/240

**Comment by Natinux** [comment]
it seems that it was implemented : [node-fs-extra/pull/286](https://github.com/jprichardson/node-fs-extra/pull/286)
[apidoc-core](https://github.com/apidoc/apidoc-core) still using wrench and I am unable to `npm install `.


Can you please update apidoc-core to fs-extra too?
