### ISSUE TITLE
Language Switcher

### ISSUE THREAD

**Issue by devanthonyp** [apidoc/apidoc#48]
Is there a documentation for switching default language.. example.. the default is english.. but i want to have japanese documentation etc...

**Comment by MartinP1** [comment]
I think it would be a good idea to have an optional parameter e. g. "locale_override" in configuration file "apidoc.json".
Up to now I use a modified version of locale.js in my templates directory tree specific to the certain project to get "en" as locale, and not the locale returned by the browser...
This is a little bit dangerous, if a new version of apidoc is released. with possible incompatibilites concerning locale.js.
