### ISSUE TITLE
Maven Repository

### ISSUE THREAD

**Issue by Gabroz** [apidoc/apidoc#480]
Hello, I'd like to use ApiDoc for the Documentation of an API and I was wondering if it would be possible to have a Maven repository in order to include it in the Maven project.

And does ApiDoc support Powershell?

Thank you in advance :)

**Comment by rottmann** [comment]
apidoc is an npm based javascript project, feel free to add it to maven repository.

There is no special support for Powershell, but you can run as a cmd line tool .
