### ISSUE TITLE
Can't re-use @apiDefine-d block with @apiGroup 

### ISSUE THREAD

**Issue by melya** [apidoc/apidoc#483]
I've defined block below:

```
/**
* @apiDefine RestAPIGroup
* @apiGroup Internal API
*/
```

And trying to `@apiUse` it: 

```
/**
* @api {delete} /api/users UsersDelete
* @apiUse RestAPIGroup
*/
...
/**
* @api {post} /api/users UsersCreate
* @apiUse RestAPIGroup
*/
```

ER: grouped api documentation by "Internal API"
AR: default `@apiGroup` applied

**Comment by rottmann** [comment]
The api, name and group are the unique id for a api method.
Currently the group will not be overwritten, i will proof if we can change this, so that the group can be inherited.
