### ISSUE TITLE
How to define a type for the parameter file

### ISSUE THREAD

**Issue by oopyoung** [apidoc/apidoc#485]
How to define a type for the parameter file?
The following code:
@apiParam {File} thumb 
but the request-tool can't choose file;

**Comment by myking520** [comment]
https://github.com/myking520/apidoc
a sample modify for this

**Comment by Naktibalda** [comment]
@myking520 why didn't you make a pull request with this feature?

**Comment by NavneetPal** [comment]
> How to define a type for the parameter file?
> The following code:
> @apiParam {File} thumb
> but the request-tool can't choose file;

The above code works for me...Thanks
