### ISSUE TITLE
CLI Not working on a docker image

### ISSUE THREAD

**Issue by juanimarchese** [apidoc/apidoc#488]
Hi, Im running the cli to generate the doc, and this error is given to me. Im using wercker.

Locally this works... Not a clue!

debug: read: package.json
debug: read: apidoc.json
verbose: apidoc-generator name: apidoc
verbose: apidoc-generator version: 0.16.1
verbose: apidoc-core version: 0.7.1
verbose: apidoc-spec version: 0.2.0
debug: No plugins found.
debug: load parser language: .clj, ./languages/clj.js
debug: load parser language: .coffee, ./languages/coffee.js
debug: load parser language: .erl, ./languages/erl.js
debug: load parser language: .ex, ./languages/ex.js
debug: load parser language: .exs, ./languages/ex.js
debug: load parser language: .litcoffee, ./languages/coffee.js
debug: load parser language: .lua, ./languages/lua.js
debug: load parser language: .pm, ./languages/pm.js
debug: load parser language: .py, ./languages/py.js
debug: load parser language: .rb, ./languages/rb.js
debug: load parser language: default, ./languages/default.js
debug: load parser: api, ./parsers/api.js
debug: load parser: apidefine, ./parsers/api_define.js
debug: load parser: apidescription, ./parsers/api_description.js
debug: load parser: apierror, ./parsers/api_error.js
debug: load parser: apierrorexample, ./parsers/api_error_example.js
debug: load parser: apiexample, ./parsers/api_example.js
debug: load parser: apiheader, ./parsers/api_header.js
debug: load parser: apiheaderexample, ./parsers/api_header_example.js
debug: load parser: apigroup, ./parsers/api_group.js
debug: load parser: apiname, ./parsers/api_name.js
debug: load parser: apiparam, ./parsers/api_param.js
debug: load parser: apiparamexample, ./parsers/api_param_example.js
debug: load parser: apipermission, ./parsers/api_permission.js
debug: load parser: apisuccess, ./parsers/api_success.js
debug: load parser: apisuccessexample, ./parsers/api_success_example.js
debug: load parser: apiuse, ./parsers/api_use.js
debug: load parser: apiversion, ./parsers/api_version.js
debug: load parser: apisamplerequest, ./parsers/api_sample_request.js
debug: load worker: apierrorstructure, ./workers/api_error_structure.js
debug: load worker: apierrortitle, ./workers/api_error_title.js
debug: load worker: apigroup, ./workers/api_group.js
debug: load worker: apiheaderstructure, ./workers/api_header_structure.js
debug: load worker: apiheadertitle, ./workers/api_header_title.js
debug: load worker: apiname, ./workers/api_name.js
debug: load worker: apiparamtitle, ./workers/api_param_title.js
debug: load worker: apipermission, ./workers/api_permission.js
debug: load worker: apisamplerequest, ./workers/api_sample_request.js
debug: load worker: apistructure, ./workers/api_structure.js
debug: load worker: apisuccessstructure, ./workers/api_success_structure.js
debug: load worker: apisuccesstitle, ./workers/api_success_title.js
debug: load worker: apiuse, ./workers/api_use.js
debug: load filter: apierror, ./filters/api_error.js
debug: load filter: apiheader, ./filters/api_header.js
debug: load filter: apiparam, ./filters/api_param.js
debug: load filter: apisuccess, ./filters/api_success.js
verbose: run parser
error: No files found. 
{ Path: '/pipeline/source/api/' }

**Comment by rottmann** [comment]
Did you try to `cd` into your workdir and run apidoc inside the dir?

**Comment by juanimarchese** [comment]
It doesnt work... Simply apidoc doesnt find any fields

**Comment by fzumstein** [comment]
I have the same issue on a docker image when I run `apidoc` on a mapped volume from another container (via  `volume_from`):

```
verbose: run parser
debug: inspect file: ./__init__.py
debug: size: 0
debug: inspect file: ./orders.py
debug: size: 7165
debug: inspect file: ./session.py
debug: size: 643
debug: inspect file: ./system.py
debug: size: 692
info: Nothing to do.
```

When I `COPY` the files into the image, then it runs correctly in the docker container.

**Comment by rottmann** [comment]
But this can not be apiDoc specific, when you mount volumes they are for the application (apidoc) visible/accessible like any other dir.
Can you try to run apidic with the full path to your files `apidoc -i /path/to/mounted/volume`

**Comment by rottmann** [comment]
Can you post your Dockerfile and start scripts?

**Comment by fzumstein** [comment]
I've put together a minimal sample and it's indeed working there. So I guess it's something else that's not right in my specific project...

**Comment by fzumstein** [comment]
FYI: a host volume mapping was overriding my volume_from. all good now.
