### ISSUE TITLE
How to do proper multiline description in python

### ISSUE THREAD

**Issue by danielnelson** [apidoc/apidoc#493]
My python code is indented using 4 spaces, this seems to cause multiline descriptions to be rendered as code blocks unless an unconventional indention style is used.

In this example the last line is rendered as a code block:

```
"""
@apiDescription This is the Description.
It is multiline capable.

Last line of Description.
"""
```

The only way I could find to avoid this is to have no indention on extra lines, something like this:

```
    """
    @apiDescription This is the Description.
It is multiline capable.

Last line of Description.
    """
```

**Comment by NicolasCARPi** [comment]
This bug doesn't seem to appear anymore.
