### ISSUE TITLE
Variables inside @apiDefine blocks

### ISSUE THREAD

**Issue by jmkarin** [apidoc/apidoc#494]
I would like to see support for variables inside @apiDefine blocks. There are many cases where I have content that varies by one or two words in a set spot in the content but otherwise appears repeatedly. If I could use a variable inside @apiDefine then specify the value I want for that variable in my @apiUse declaration it would make life a lot easier.

Something like this might work, requiring the variables to be named $varN (or similar) where N is a 0-based index:

~~~~
@apiDefine Error1
@apiError (404 Error) $var0NotFound Could not locate a $var0 object with the specified ID.

@apiErrorSample Error-Sample
HTTP 1.1/ 404 Not Found
{"error":"could not locate $var0 object $var1 }

...

@apiUse Error1(User,c9648da0-3a4a-11e6-bdf4-0800200c9a66)

...

@apiUse Error1(Account,9648cda0-43aa-161e-dfb4-080a60200c96)

etc.

**Comment by rottmann** [comment]
This is specific to your project, for this i would use a grunt task to generate the doc and after that a second task to replace all the vars.

Replace all vars in the generated `apidoc_date.json` with `str.replace(/\$var0/g, 'My Value');`
