### ISSUE TITLE
Inconsistent display issues with List of endpoints on left side of doc

### ISSUE THREAD

**Issue by jmkarin** [apidoc/apidoc#499]
Using the default templates, my generated documentation is sometimes exhibiting some odd display issues when I use the links to the various endpoints available in the left pane. These do not happen all of the time, but I have seen both of the following happen with the latest Chrome on a Windows 7 machine (my work laptop):
1. The highlight lags behind the endpoint by one click. If I'm moving around the documentation a lot, after a time I seem to get into a state where the endpoint prior to the last one I clicked is highlighted as if it were the currently displayed documentation. This is consistent once it happens until I close the browser window.  If I click on a different endpoint the highlight moves so it remains one endpoint behind the currently shown documentation.
2. The highlight travels one endpoint at a time in sequence to get from its starting point to a new endpoint I've clicked. That is to say, instead of seeing the old endpoint highlighted and then immediately seeing the new endpoint highlighted when I click, each endpoint between them on the list is briefly highlighted as the highlight box moves to the current endpoint and then stops.

It's also worth noting that this documentation is not on a server; it is being viewed by opening the index.html file sitting on my local machine.

**Comment by rottmann** [comment]
Yeah, the old bootstrap bug... tried to fix it many times, but then it make problem again... i really must replace this old template ;-)

**Comment by rottmann** [comment]
Bootstrap updated in v0.17.0
