### ISSUE TITLE
@apiSampleRequest How can i test url parameter

### ISSUE THREAD

**Issue by SangHakLee** [apidoc/apidoc#502]
apidoc's @apiSampleRequest parameter is  query string parameter
But, I need a Url parameter

Example
/test/:id  ( param id:10 )

apidoc @apiSampleRequest make /test?id=10
But i want 
/test/10

**Comment by scriptsure** [comment]
ditto for me on this... seems to be placing them as named parameters in the URL. We are using node/express and of course we need it like test/10... not /test?id=10...

aaron

**Comment by 285858315** [comment]
We are using node/express and we need /test?id=10 !!!!

**Comment by Pravinslk** [comment]
@SangHakLee Have you find a solution ?

**Comment by Pravinslk** [comment]
@rottmann how to get url like this test/10/news
here @api {get} tset/:id/news Get News this is wrong :(

**Comment by neelbhanushali** [comment]
@Pravinslk add `@apiParam` for the url param.

```
@apiParam {Integer} id
```

It will generate an input for the input, if you fill it and send, it generates a url that you want.

**Comment by rbrynteson** [comment]
Looking for similar and running into problems.  So I have:

/**
            * @api {get} /AuditLogs/:API_Key/:CustomerID/:HideLogin Read system audit log
            * @apiVersion 1.0.0
            * @apiName AuditLogs
            * @apiGroup Admin
            * @apiDescription Return all audit log records for a customer
            * 
            * @apiParam {String} API_Key Authorization value generated API Key
            * @apiParam {String} CustomerID Multi-Tenant Customer ID
            * @apiParam {Boolean} HideLogin Choose to hide login events from return
            * 
            * @apiSuccess {String} ID Message ID
            * @apiSuccess {String} User User who made the change
            * @apiSuccess {String} Message Message about the change
            * @apiSuccess {Date} ActionDate Time change was made
            * 
            * @apiSampleRequest /AuditLogs/:API_KEY
*/

So I'm noticing two things:

1. Although I have "url" defined in my apidoc.json file it doesn't add it to the @apiSampleRequest so it doesn't know where to send the request.  I can manually add the url to the @apiSampleRequest but don't think I'm supposed to need to.

2. I'm also looking for the parameters to be in the URL and not querystring.  As you can see, I have the @apiParam but it still makes it a query string. 

Here is my apidoc.json file

{
  "name": "API",
  "description": "API Docs",
  "title": "API Docs",
  "url": "https://some.where.com",
  "template": {
    "withCompare": false,
    "withGenerator": true
  }
}

**Comment by NicolasCARPi** [comment]
Use `@apiQuery`.

**Comment by NicolasCARPi** [comment]
You can try the current `dev` branch: `npm i -g apidoc/apidoc#dev`. See also #999.
