### ISSUE TITLE
How the api url generate？

### ISSUE THREAD

**Issue by icoding** [apidoc/apidoc#503]
/**
     * @api {post} /ide/historyContent  historyContent
     * @apiVersion 2.0.0
     * @apiName  脚本历史内容
     * @apiGroup IDE
     *
     * @apiParam {String} taskCode 脚本code.
     * @apiParam {int} version 版本.
     *
     * @apiSuccessExample Success-Response:
     *     HTTP/1.1 200 OK
     *     {
     *       "code": "000000",
     *       "msg": "success",
     *       "data":"select * from"
     *     }
     *
     */

result api_data is
{
    "type": "post",
    "url": "/ide/historyContent",
    "title": "historyContent",
    "version": "2.0.0",
    "name": "______",
    "group": "IDE",

why the name is '_____'   , How to define it ？

**Comment by rottmann** [comment]
https://github.com/apidoc/apidoc/issues/470#issuecomment-214460195
