### ISSUE TITLE
Script error for: locales/it.js

### ISSUE THREAD

**Issue by okihouse** [apidoc/apidoc#505]
I use apidoc pretty well. 

but, now I have some problem.

```
GET http://okihouse.github.io/dnbb_document/locales/it.js?v=1469516898224
```

```
Uncaught Error: Script error for: locales/it.js
http://requirejs.org/docs/errors.html#scripterrorC
```

It is my apidoc.
http://okihouse.github.io/dnbb_document/
and source is...
https://github.com/okihouse/dnbb_document/tree/gh-pages

How I solve this problem?

**Comment by rottmann** [comment]
You don't have the it.js in https://github.com/okihouse/dnbb_document/tree/gh-pages/locales
Source: https://github.com/apidoc/apidoc/blob/master/template/locales/it.js
