### ISSUE TITLE
How to use $ (dollar sign) in @apiParam

### ISSUE THREAD

**Issue by supasate** [apidoc/apidoc#506]
My apiParam name begins with `$`. 

Ex. I have an api like `GET /search&$center=[13.730537954909,100.56983580503]&$radius=1000.`

I write apidoc as follows. 
```
@apiParam {Number[]} $center Center point of an area to search in [lat, long] format.
@apiParam {Number} $radius Circle radius to search around the center point.
```

When compiling, it shows the following error.
```
error: Empty parser result. 
{ File: 'src/services/search/index.js',
  Block: 1,
  Element: '@apiParam',
  Source: '@apiParam {Number[]} $center Center point of an area to search in [lat, long] format.' }
```

If I remove `$`, it is able to complie.

So, how can I use `$` in @apiParam?

**Comment by rottmann** [comment]
Currently only alphanumeric chars are allowed. Sorry.
