### ISSUE TITLE
Cannot Parse Files Lacking Any Extension

### ISSUE THREAD

**Issue by darth-cheney** [apidoc/apidoc#508]
We cannot seem to get apiDoc to parse files *that don't have extensions at all*. We are bundling a python API as a part of a larger program, and the packaging process requires that some of our python scripts use filenames without an extension.
  
Something like `apidoc -f ".*$"` doesn't appear to work. Is there something undocumented that I'm missing or is it not possible, and all files have to have an extension of some sort?

**Comment by rottmann** [comment]
a simple dot should do it `$ apidoc -f .`
