### ISSUE TITLE
Is it possible to have the _apidoc.js file outside the source folder?

### ISSUE THREAD

**Issue by miquecg** [apidoc/apidoc#509]
This is the layout of my project, Erlang by the way:

```
myservice
├── apps
│   └── coolapp
│       ├── doc
│       │   └── api
│       ├── ebin
│       ├── include
│       └── src
├── deps
├── rel
├── apidoc.json
└── _apidoc.js
```

I don't want to put anything related to apidoc inside the `apps` folder. For the moment I'm creating my docs with the following command: `apidoc -i apps/coolapp/src -o apps/coolapp/doc/api` but the global definitions in `_apidoc.js` only work if the file is placed along the source.

Is this expected or I'm doing something wrong?

Many thanks!

**Comment by rottmann** [comment]
_apidoc.js is a normal file like your other project files too within the source folder.
You can name it as you want, e.g. "history.js", or "histoiry.erl", or "/apps/coolapp/src/xyz.js", or ".hidden_api.erl", but it must be in the source folder.

**Comment by miquecg** [comment]
Ok. I'll change its name to `something.erl`.
