### ISSUE TITLE
Cannot disable syntax highlighting for @apiExample

### ISSUE THREAD

**Issue by felixfbecker** [apidoc/apidoc#510]
I tried setting the type to `plain`, `text` and `none`, but the output is always colorized:
![image](https://cloud.githubusercontent.com/assets/10532611/17506405/e7f796cc-5e08-11e6-8904-ce766c0d57ae.png)

**Comment by rottmann** [comment]
`$ apidoc --markdown false`

**Comment by felixfbecker** [comment]
@rottmann that will disable it for _all_ uses, and not only syntax highlighting, but also markdown support in general, correct? I need markdown in syntax highlighting support, just not in some few cases.

**Comment by rottmann** [comment]
Yes for all, for a specific thing you can change the template to fit your needs.

**Comment by felixfbecker** [comment]
So it is not possible to disable it by setting the type? Like
```
@apiExample {text}
  whatever
```
