### ISSUE TITLE
No Mobile Theme

### ISSUE THREAD

**Issue by volomike** [apidoc/apidoc#515]
I tried to view this documentation on an iPhone5 in portrait mode. It didn't fit. 

I'd like to suggest that you introduce a media query like so:

```
@media all and (max-width:420px) {
  /* mobile stuff goes here */
}
```

And then, utilize `vw` font and section sizing based on viewport width.

Or, show a notice for the user to switch their phone to landscape mode.

However, when I tried to view the theme even on mobile and tablet landscape modes, you have something seriously wrong with it there because it shows everything enormous.

If one can't even view this theme on an iPad in landscape mode -- it's pretty much a showstopper. So, at least target that, if not also the iPhone5 in landscape mode as your base-minimum, and then anything below that on screen width you can at least show a notice to tilt the screen to landscape mode.

Google Chrome gives you a super easy way to test media queries (change to mobile, tablet, and other screen widths and sizes), when you show the Developer Console. The latest Firefox also has this.

**Comment by Oxicode** [comment]
+1

**Comment by hwdavidward** [comment]
+1

**Comment by NicolasCARPi** [comment]
It is now more responsive.
