### ISSUE TITLE
apidoc send incorrect content type

### ISSUE THREAD

**Issue by tkraus42** [apidoc/apidoc#516]
Hello,

can please please someone help me?
Apidoc send always the content-type "application/x-www-form-urlencoded", but I need "application/json". I try now to resolve this problem since a week, but nothing helps.

The online example project sends "application/json", but if I download the example the POST and PUT method sends "application/x-www-form-urlencoded".

Thank you very much

**Comment by BruceHem** [comment]
maybe I ask if you have resolved this issue? and how?

**Comment by maguon** [comment]
+1
