### ISSUE TITLE
 Only one definition or usage is allowed in the same block

### ISSUE THREAD

**Issue by neilyoung** [apidoc/apidoc#517]
Hi,

I'm having a class, which defines an object WifiConfig. There I'm having this:

WifiConfig.java
  /**
   * @apiDefine WifiConfig Wifi Configuration Object
   * Wifi Configuration Object
   *
   * @apiParam {String} [.ssid]
   * @apiParam {String} [.passphrase]
   */

Now I wanted to quote this definition in another class as param. The class in fact is having a property of type WifiConfig, so I'm doing this in the other file:

DeviceConfig.java
  /**
   * @apiDefine DeviceConfig Device Configuration Object
   * Device Configuration Object
  * @apiUse WifiConfig
   */

Getting "Only one definition usage is allowed in the same block". How can I recover from this?

**Comment by PunchyRascal** [comment]
Maybe you should and the comments on separate lines, like so:
`/**
 * @apiDefine
 * ...
 */`
