### ISSUE TITLE
@apiGroup with spaces is not appearing correctly in method title.

### ISSUE THREAD

**Issue by juanimarchese** [apidoc/apidoc#526]
If you create an api group called for example "Developer Accounts" in the tittle of any method that belong to that group you will see the group's name like "Developers_Accounts". The menu is showing the text correctly thought. 

Can anyone fix this? 

Also specials characters are not supported (' for example).

**Comment by rottmann** [comment]
`@apiGroup name` support only a name, so it is correct that _ replace spaces.

If you want a title you can define it:

```
/**
 * @apiDefine MyGroupName A title for a group with spaces
 */

/**
 * @api {GET} /path ...
 * @apiGroup MyGroupName
 */
```
