### ISSUE TITLE
@apiGroup multilevel

### ISSUE THREAD

**Issue by juanimarchese** [apidoc/apidoc#527]
I want to add  something like a group of a group. It's possible? 

Thanks

**Comment by rottmann** [comment]
Currently apiDoc has only less levels and did not use multi inheritance (keep it simple).

You can name groups e.g.
```
@apiGroup Top1Sub1
@apiGroup Top1Sub2
@apiGroup Top2Sub1Sub1
@apiGroup Top2Sub1Sub2
.
.
.
```
and modify the template to fit your needs. (don't know what you want todo with the groups).
