### ISSUE TITLE
[Meta] Is apidoc being maintained anymore?

### ISSUE THREAD

**Issue by justinnichols** [apidoc/apidoc#532]
5 months is quite a while in the open source world and that's when the last merge/update was made to this system.  I love this system as it fully lets the API documentation live with the source code.  There are a large number of issues and a growing list of pull requests (mine is very recent so I don't expect it to be merged immediately [assuming it will be merged]), but it has me concerned that it's no longer being worked on.

**Comment by justinnichols** [comment]
Thanks for closing with no response.  I know this wasn't the place for this question, but I know of no other place to go.  Sure hope this project stays alive.

**Comment by rottmann** [comment]
I answered and closed >40 Issues. Project is still alive and i will merge pulls, if i got some time.
https://github.com/apidoc/apidoc-core/pull/37#issuecomment-242967950 ;)

I read your pull request before, but i did not had the time to merge it. Your request will be merged, in the past some people need a private api annotation and until now it was only with some additional code possible to split the docs.

**Comment by justinnichols** [comment]
Understood and thanks.  I was mainly asking due to the 5 month lag in pull requests, but I will admit I did not take a look at recently addressed issues/etc in terms of the time-frame addressed.  My apologies for not digging deeper.

Thanks for maintaining this as it really is an awesome project!  I will do my best to help support it with any kinds of improvements I can make as well (in addition to `@apiPrivate` ).
