### ISSUE TITLE
Send Sample Request with json parameters

### ISSUE THREAD

**Issue by lunkadbhushan** [apidoc/apidoc#533]
Hi, I want to send a sample request as below:
{
    "method": "method_name",
    "id": "1",
    "params": {
        "mobileno": "1234576890"
    }
}

Can you please guide me?
Thanks

**Comment by WickeDev** [comment]
I also need URL parameters as like #502 
/test/:id ( param id:10 )

how could I help this? or any plan for this?

**Comment by koko-ng** [comment]
I just sent a pull request: #601, if it doesn't get accepted right now I have also done a plugin: https://github.com/koko-ng/apidoc-contentType-plugin

**Comment by dereckmartin** [comment]
I was encountering the same issue.  I have a post request which needs and :id, but also post a json body.

I was grouping my params where one was for url and the others were for the json body.  This caused one or the other to be processed.  Once I put them all into the same group (or no group), the placeholders were properly translated for the sample request.

I should note, I also have alsoapplied the unofficial patch to send a json object when Content-Type is set to application/json referenced in #27 

https://github.com/delphian/apidoc/commit/61a2206bae7d60c5742e42eaccee7e5469d32c84

**Comment by bandaiah8** [comment]
Hello koko-ng, You saved my time, Thank you for making it a plugin.

**Comment by danger89** [comment]
Actually this is already possible with apiDoc. Just by defining your own parameter type (default Parameter).

```
/**
 * @api {put} /users/:id Update existing user
 * @apiVersion 1.0.0
 * @apiName PutUser
 * @apiGroup User
 *
 * @apiParam {Number} id Users unique ID.
 * 
 * @apiParam (Request body) {Object} user Update user object
 * @apiParam (Request body) {String} user_name Username
 * @apiParam (Request body) {Sting} user_email User e-mail
 * @apiParam (Request body) {String} user_password Password
 * 
 */
```

Between parentheses you can define whatever you want, in my case `Request body`.

Example:
![image](https://user-images.githubusercontent.com/628926/35749856-40c6e21c-0853-11e8-8798-ab5893349778.png)

**Comment by chovy** [comment]
This produces a form data payload, not a json request payload.

**Comment by danger89** [comment]
Uhh Correct, I didn't say this was ideal.. It is not. Maybe the plugin helps you:
https://github.com/apidoc/apidoc/issues/533#issuecomment-280932135

**Comment by Jenfong** [comment]
Apidoc Authorization not work in post api.
I debug the apidoc page
http://localhost:3000/apidoc/utils/**send_sample_request**.js?v=1590046043673
`  function sendSampleRequest(group, name, version, type)
...
        // Optional header
        var header = {};
`
  
I found the **post** api the "Authorization" value is empty (header["Authorization"]="" ),I debug the sendSampleRequest function,during the header["Authorization"] can found the input value,but after the looping **header["Authorization"]=""** 

1. it's not work ,can't set the header "Authorization" value
`
     * @api {post} /api/v1/commitJob commit job
     * @apiDescription commit job
     * @apiName job
     * @apiGroup jobi     
     * @apiHeader (jwt token){String} Authorization  jwt authorization
     * @apiHeaderExample {json} Request-Example:
     * {
     *  "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbl9uYW1lIjoiaHVudGVyIiwiaWF0IjoxNTg5NzgyNjYyLCJleHAiOjE1ODk5NTU0NjJ9.ART87U90VZTkuuJznifGJWhbGSsv9eW7kkUaRopXfgE"  
     * }  
`

2. it's work ,cant set the header "Authorization" value
`
    /**
     * @api {get} /api/v1/aipJob 查询aip任务
     * @apiDescription 查询aip任务
     * @apiName aipJob
     * @apiGroup AipCli
     * @apiHeader (jwt token){String} Authorization  jwt authorization
     * @apiHeaderExample {json} Request-Example:
     * {
     *  "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbl9uYW1lIjoiaHVudGVyIiwiaWF0IjoxNTg5NzgyNjYyLCJleHAiOjE1ODk5NTU0NjJ9.ART87U90VZTkuuJznifGJWhbGSsv9eW7kkUaRopXfgE"  
     * }   
`

**Comment by NicolasCARPi** [comment]
This can be closed now.

@Jenfong please open a new issue for the Authorization problem you are describing.
