### ISSUE TITLE
Reuse objects in apiSuccess, etc.

### ISSUE THREAD

**Issue by rusekr** [apidoc/apidoc#534]
Hello!
Have to APIs:
get /users
and
get /users/:id

Boths returs user object { id: .. , login: .., ..}. First as array? second as one object.
Can I "define" structure of that object in one place and then use it like:

@apiSuccess {userObject[]} in first case and 
@apiSuccess {userObject} in second 

with generated URI to documentation block where userObject structure deifned 
?

**Comment by rottmann** [comment]
You can define blocks with apiDefine and apiUse, for an example watch: http://apidocjs.com/#param-api-define.
But a single objects can not be described.

**Comment by rusekr** [comment]
Got it, thanks!
