### ISSUE TITLE
Request: optional versions alternative

### ISSUE THREAD

**Issue by geramy92** [apidoc/apidoc#535]
Hey there,
Actual it is only possible to have version comparing if I save a lot of old code. For some release structures that means really much overhead in old files. (Also that doesn't look nice in GIthub/Gitlab/whereever - okay that can be done with tags and a small grunt task or whatever but thats not nice)

To solve that it would be possible to use old "api_data.json or api_data.js" to generate new versions on top of that. Is that possible?

In my mind that looks like that:
optional new option: --useOldData or --oldDataJson=some/path/to/that/file
and it loads that file and adds only new stuff or changed stuff but doesn't delete the old versions

greetings

**Comment by rottmann** [comment]
You can disable versioning:
http://apidocjs.com/#configuration
Set in apidoc.json the template.withCompare to false.

The data is still there, but it display only the current.

**Comment by geramy92** [comment]
I don't want to disable that. I want to have only a better way to save old versions.

**Comment by rottmann** [comment]
Only manually.

With grunt/gulp-Task or npm you could copy the current doc to `old.version`.
Create then the new doc, clone it, so you have new for the next old copy.
In the clone merge all old api-data files with the new.

This saves you from creating a history file.

Would be nice, if you can provide a gulp / grunt Task, so others can use it too.
