### ISSUE TITLE
can I generate doc with my own comments?

### ISSUE THREAD

**Issue by wudicaidou** [apidoc/apidoc#537]
my comments are like this:
      /**
     \* 
     \* methodName2
     \* @param a
     \* @param b
     \* @param c
     \* @author  Cai
     \* @time    2016年10月13日-下午7:52:41
     */
    public void methodName2(String a, String b, String c) {

```
}
```

**Comment by rottmann** [comment]
You can extend apidoc with own parsers `apidoc --parse-filters api-time.js`
`api-time.js` is your file, for examples watch https://github.com/apidoc/apidoc-core/tree/master/lib/parsers

or create a plugin https://github.com/apidoc/apidoc-plugin-test
