### ISSUE TITLE
How can I Insert custom field to api_data.js or api_data.json via plugin?

### ISSUE THREAD

**Issue by WickeDev** [apidoc/apidoc#542]
I was trying to write plugin for support web socket protocol in my project.

but this plugin feature seem like for parsing.

how can I insert my custom field to output api_data.js or api_data.json?

**Comment by rottmann** [comment]
For an example view https://github.com/apidoc/apidoc-core/blob/master/lib/parsers/api_version.js

The parse function return the data that will be inserted into the tree (api_data.json).
```
module.exports = {
    parse     : parse,
    path      : 'local.my_field',
    method    : 'insert',
    markdownFields: [ 'my_field ], // if you have markdown in your field
};
```

If your path is a global field, you need a worker https://github.com/apidoc/apidoc-core/tree/master/lib/workers
global (virtual, only internal, no output) tree data will normally inserted into local trees (api_data.json) with a worker function.

**Comment by WickeDev** [comment]
Oh I got it! thank you for your answer.
