### ISSUE TITLE
Query Param

### ISSUE THREAD

**Issue by PSJMcNeill** [apidoc/apidoc#543]
Trying to combine this with the Swagger integration plugin. It works brilliantly apart from methods were I have for example 2 Path parameters and 2 Query Params. When I run the apidoc-swagger it picks all the params up as Paths.

Is there a way to indicate a query param in ApiDoc?

**Comment by rottmann** [comment]
apiDoc did not separate query and post parameter. You can change the name of a query parameter, to show that it is a query parameter, e.g. `/path/:id` to `/path/:queryId` and describe it in apiDoc with `@apiParam {int} queryId Description of ID.`

Todo something with it, you should ask @fsbahman https://github.com/fsbahman/apidoc-swagger 
or write a script that transform names with `query` prefix to something swagger need.
