### ISSUE TITLE
[Propsal] Generate frontend services

### ISSUE THREAD

**Issue by sp90** [apidoc/apidoc#544]
Wouldn't it be nice to make it generate a front-end service(lib) for fx ng1, ng2, polymer, react and so forth which just gave u services based on the documentation written in the backend. And then some visual docs how to use the generated lib ofc

**Comment by rottmann** [comment]
This seems to be an idea for an extra project.

You can use https://github.com/apidoc/apidoc-core to retrieve the plain api-data and then transform them to your needs.
