### ISSUE TITLE
How to specify query type parameter?

### ISSUE THREAD

**Issue by ajmas** [apidoc/apidoc#545]
How should we indicate query type parameters in the docs? I am think of URLs such as 'name' in the following example:

`http://..../api/user?name=john`

I didn't see anything in the documentation.

**Comment by rottmann** [comment]
`@apiParam {type} varname Description`
`@apiParam {String} name A name`
apiDoc does not make a difference between query parameters or content parameters.

**Comment by ajmas** [comment]
Would it be worth making this clear in the documentation?

**Comment by renatoargh** [comment]
This is a problema to my API docs, I have to distinguish between 3 types of parameters; query params, url params (those in the placeholder) and body params (usually JSON). Having only one place to pass all the parameters sucks a lot, even though the lib it self is amazing

**Comment by mindcreations** [comment]
Same issue for me. I was starting to adopt APIDOC but stopped when I've seen this limit.

**Comment by rottmann** [comment]
Can you provide a use case?

The only case i image is a post with 3 times the same field (e.g. ID). But why?
```
/**
 * @api {POST} /path/:url_id/?query_id=:query_id
 * @apiParam {int} url_id URL ID.
 * @apiParam {int} query_id Query ID.
 * @apiParam {int} id Body ID.
 */
```

**Comment by renatoargh** [comment]
@rottmann we need at least a way to differentiate between url params and body params since both may be needed on the same API endpoint. You may need to pass a body json to a specific url, and both may need to be documented.

**Comment by ftoulemon** [comment]
Looking at [swagger](http://petstore.swagger.io/#!/store/getInventory), it uses a `parameter type` column.

I'm not fond of the column, but maybe the information can be added as a label (like `optional`), or with a simple icon next to the data type, like the one next to the permission note (`{}` for body, `?` for query, `/` for path, ...).

Or maybe the `(group)` parameter of the `@apiParam` tag can be used for this?

```
@apiParam (body) {int} id ...
@apiParam (query string) {int} data ...
```

**Comment by rottmann** [comment]
Yes the group can be used for that (it is not the primary use case).

**Comment by ftoulemon** [comment]
Do we just come full cirlce (#16) ?

**Comment by mindcreations** [comment]
For a use case refer to this REST API [OpenAM 13 REST](https://backstage.forgerock.com/docs/openam/13/dev-guide/chap-client-dev#rest-api-filter-sort-page)

Examples:
- You can use the query string parameters **_prettyPrint=true** to make the output easier to read.
- You can use **_pageSize=100** to limit the number of results returned.

**Comment by fabamb** [comment]
I believe that the use of "group" is versatile enough to cover the different needs. 
It is more than "workaround". It is the rith "answer".
I currently use it to distinguish the "placeholder" in the URL (aka :id), the ones to be passed as a query string parameters (es: "?limit=100")
and fields in json body (passed to to post and put methods).
But, different from other solutions with specific @apiXXX param, there is no limit to your fantasy.

**Comment by renatoargh** [comment]
hey @fabamb can you post an example of how using *group* may help me differentiate the origin of the parameters? thanks a lot

**Comment by fabamb** [comment]
Well
I believe that the only occasion on which there is a real utility in distinguishing the parameter passed in the url from those passed in the body is in the case of modification of a resource via PUT.

Then, consider the case of user modification shown in the example used by the apidoc documentation.
Original example sets only the name parameter, omitting the :id param in the url.

(I must say that I do not think there is a real need to highlight the "placeholder" in the url, because anyone with a little familiarity with Restful API knows that you have to pass the id of the resource when you do a GET or PUT or DELETE it)

If you put in source file
@apiParam (Path Param) {String} :id  The User ID.
@apiParam (Parameters) {String} Name Name of User.

you will obtain to describe both parameters in two different tables.

**Comment by marc-ferrer** [comment]
> I believe that the only occasion on which there is a real utility in distinguishing the parameter passed in the url from those passed in the body is in the case of modification of a resource via PUT.

So documentation clearness is out of the radar?
The way Apidoc works now you have to add the query parameters to make it clear that they can be used `@api {POST} /path/:url_id/?query_id=:query_id`, which is just a mess when you have several query parameters imho.
And what about headers? How do I let them know that there is a parameter in the header?

I know there is a workaround, but I would prefer to have a column in the parameters row indication what kind of parameter `query_id` is. Seems clearer to me.

> ... because anyone with a little familiarity with Restful API knows that you have to pass the id of the resource when you do a GET or PUT or DELETE it

@fabamb I totally agree, but Apidoc should not make any assumtpions regarding user's knowledge.

**Comment by TimboKZ** [comment]
Any progress on this?

**Comment by rob2d** [comment]
I was looking into this and APIDoc params can be extended:

http://apidocjs.com/#extend

I don't think I can the OK to extend this on my work time, but perhaps I'll scratch my curious itch since the code is so nicely laid out. In the meantime, if anyone else gets time to extend for support of some of these things, please let me know :)

**Comment by danger89** [comment]
Yea using groups this can work great.

![image](https://user-images.githubusercontent.com/628926/35821555-a8f6456e-0aa9-11e8-9ef5-ed0194e911d9.png)

```
 /**
 * @apiParam (Query string) {String} _fields Provide only the database fields where you are interested in. Eg: 
 * ```
 * _fields=first_name,last_name
 * ```
 * @apiParam (Query string) {String} _order[field_name] Order either ascending (ASC) or descending (DESC). Eg: 
 * ```
 * _order[first_name]=ASC
 * ```
 * @apiParam (Query string) {String} field_name[SELECTOR] Filter the data based on a selector. `field_name` should be the database field. 
 * Available selectors: EQ (default), NEQ, REAT, SMALL, EQGREAT, EQSMALL, IN, LIKE. Eg: 
 * ```
 * first_name[LIKE] = %Melroy%
 * ```
 */

Or with a body message (JSON):
![image](https://user-images.githubusercontent.com/628926/35821628-f26ddb12-0aa9-11e8-87e4-f6c2053e8e91.png)

```

**Comment by demisx** [comment]
The "Send a Sample Request" doesn't work for me if I have an endpoint that has both, URL and query string params. You have to select one or another via a radio button when sending a sample request, but I need both.

**Comment by Charishma-Madupu** [comment]
I'm also facing the same issue. I have an endpoint that has both path and query parameters. When sending a sample request, I'm getting a select option, to select either path or query params.

Do we have any other option to use both at a time while sending the sample request ??

**Comment by NicolasCARPi** [comment]
Ok so the answer is to use groups.

**Comment by danger89** [comment]
Well, yes not ideal still. But we use groups due to the lack of a better solution.

**Comment by NicolasCARPi** [comment]
@danger89 The issue here is that this project was lacking attention for several years due to lack of time of the creator. I've taken over as maintainer and I'm primarily focusing my efforts on bug fixing to get a new release out. Issues like this where a workaround is available are not a priority. Once the codebase is sane again and not full of TODO, we can revisit this issue :)

Right now I'm trying to reduce the huge number of open issues. I hope you understand this approach.

**Comment by neelbhanushali** [comment]
If the request is `GET`, all the `@apiParam`s go as query params

**Comment by neelbhanushali** [comment]
If the request is `GET`, all the `@apiParam`s go as query params

I see no need to specify a type for the param or how it should be sent.

But there can be a possibility for edge cases.

**Comment by mindcreations** [comment]
> If the request is `GET`, all the `@apiParam`s go as query params
> I see no need to specify a type for the param or how it should be sent.
> But there can be a possibility for edge cases.
The HTTP specification permits this or at least does not forbid it and it is honoured by the Http server. That said if I can retrieve body and querystring, I must be able to document it. See [this old long discussion](https://stackoverflow.com/questions/978061/http-get-with-request-body) on the subject.
