### ISSUE TITLE
Ingore URL prefix

### ISSUE THREAD

**Issue by Oreste-Luci** [apidoc/apidoc#547]
Is there a way to ignore url prefix for a specific endpoint?

I have defined `url` as `/api/v1` and this is prefixed to all the urls in the generated documentation. I would like a couple of endpoints not to have this prefix, or maybe a different one. Is there a wat to do this?

Thanks

**Comment by rottmann** [comment]
Overwrite in your method-block
`@apiSampleRequest http://www.example.com`
or disable:
`@apiSampleRequest off`

View the docs http://apidocjs.com/#param-api-sample-request
