### ISSUE TITLE
sampleURL and array types

### ISSUE THREAD

**Issue by arevak** [apidoc/apidoc#548]
Your form generator for something like an array of objects isn't usable at the moment.  My understanding of how you would correctly define something like that is

~~~
/**
 * @apiParam {Object[]} items
 * @apiParam {String} items.sku
 * @apiParam {Number} items.qty
 */
~~~

This produces 3 outputs on the form one for items, items.sku and items.qty, it really needs to produce an output that you can add groups to to either generate

~~~
Content-Type: application/json:
{
    items: [
        {
            sku: "A",
            qty: 1
        }
   ]
}
~~~

OR

~~~
Content-Type: www-url-form-encoded
items[0][sku]=A&items[0][qty]=1
~~~

**Comment by adelatuduce** [comment]
Do we have any updates in this being available any time soon?

**Comment by rottmann** [comment]
We need somebody who wants to rewrite the send sample request plugin **and** support it.
The plugin should be independent from the template (as far as possible), a separate project.

I never wanted to include the pull requests for the current (many times patched) plugin, but many people asked for it and i hoped the contributors would support it in the future.

**Comment by NicolasCARPi** [comment]
You can try the current `dev` branch: `npm i -g apidoc/apidoc#dev`. See also #999.
