### ISSUE TITLE
Request body with array

### ISSUE THREAD

**Issue by Znarkus** [apidoc/apidoc#549]
Hi!

How would I document this?

```
POST /batch-insert
[
  { "name": "Name 1" },
  { "name": "Name 2" }
]
```

I understand that `@apiParam` can be used to document request body, but `@apiParam {String[]} name` implied `{ "name": ["Name 1", "Name 2"] }` I think.

**Comment by dfreire** [comment]
I feel your pain.
While a solution is not implemented I use an underscore:
` * @apiParam {Object[]} _ array of objects with:`

It keeps the api legible enough...

**Comment by renatoargh** [comment]
hey @dfreire what does the _ do?

**Comment by dfreire** [comment]
Nothing. It is just a placeholder that is easy to read on the documentation output.

**Comment by koko-ng** [comment]
Hi,

**Comment by machineghost** [comment]
@kok-ng What you are describing isn't what OP described.  The documentation you defined would describe a request of:

    {
        names: [{ name} ] 
    }

But what OP was asking for (and what I'm looking for also) is how to document:

     [
         { "name": "Name 1" },
        { "name": "Name 2" }
    ]

**Comment by fedemengo** [comment]
Any update on this one?

**Comment by NicolasCARPi** [comment]
@fedemengo No, but you're welcome to contribute! ;)

Recently a lot of work has been put in reducing the number of open PR/issues. This issue will be addressed eventually. Right now issues that are not bugs have a lower priority.
