### ISSUE TITLE
support Model definition on a apiParam

### ISSUE THREAD

**Issue by thkdog** [apidoc/apidoc#554]
Like above, the @apiParam {User} stands for @model User

```
// in api
/**
 * @api {get} /user/:id Request User information
 *
 * @apiParam {User} id Users unique ID.
 */

// in model
/**
 * @model User
 *
 * @apiParam {int} id Users unique ID.
 * @apiParam {string} username Users nickname.
 */
```

**Comment by ftoulemon** [comment]
See [my comment on this issue](https://github.com/apidoc/apidoc/issues/278#issuecomment-263863921)

**Comment by rottmann** [comment]
As workaround ftoulemons solutions works to describe custom resource objects,
or use the group for that `@apiParam (User){int} id Users unique ID.`
