### ISSUE TITLE
Splitting long line in @api tag breaks docs generation

### ISSUE THREAD

**Issue by miguelrs** [apidoc/apidoc#557]
I have a API endpoint with quite a long URL plus quite a lot of params, like:

```
/**
 * @api {get} /{account}/{section}/{sub-section}/do/something/in/particular?key={api-key}&token={token}&param-one={value-one}&param-two={value-two}&param-three={value-three}
 * @apiDescription This is the description, which can be multi-line, this works ok!
 */
```

I _must not_ have that long line, because I have PhpCS to prevent me to add lines longer than 120 chars... 😓 

Is there any way to allow splitting really long URLs in the `@api` tag?

--- 

What I tried so far:

👎  1) If I split the long line like this:
```
/**
 * @api {get} /{account}/{section}/{sub-section}/do/something/in/particular?key={api-key}&token={token}
 *     &param-one={value-one}
 *     &param-two={value-two}
 *     &param-three={value-three}
...
```

It fails when trying to generate the docs with:
```
grunt-apidoc
warn: Please create an apidoc.json configuration file.
error: Empty parser result. 
{ File: 'src/My/App/Bundle/MyBundle/Controller/MyController.php',
  Block: 9,
  Element: '@api',
  Source: '@api {get} /{account}/{section}/{sub-section}/do/something/in/particular?key={api-key}&token={token}\n    &param-one={value-one}\n    &param-two={value-two}\n    &param-three={value-three}' }
>> grunt-apidoc error: Execution terminated (set 'options: { debug: true }' in Gruntfile.js for details.
Warning: Task "apidoc:MyAPI" failed. Use --force to continue.
```

👎  2) I could make it build the docs successfully splitting the line just in 2 lines, and adding no tabs at all, like this:
```
/**
 * @api {get} /{account}/{section}/{sub-section}/do/something/in/particular?key={api-key}&token={token}
 * &param-one={value-one}&param-two={value-two}&param-three={value-three}
...
```

But then the docs look bad - the line gets hidden, like this (note the blur is mine 😄 ):

![slack](https://cloud.githubusercontent.com/assets/7236632/20803146/1d82b5a6-b7e6-11e6-8909-0e6789d29235.png)

**Comment by rottmann** [comment]
Currently not, additional lines are used for the description.
I set it on todo.

**Comment by NicolasCARPi** [comment]
@miguelrs IMHO you should add a `phpcs:ignore` comment before the long line so PHPCs is happy, you're happy, apidoc is happy and everyone is happy. :D 

I just tried it with a very long line, it's fine it seems anyway, so I can close this issue.
