### ISSUE TITLE
Remove "api" from every param name

### ISSUE THREAD

**Issue by jaredreich** [apidoc/apidoc#558]
It's verbose and unnecessary to have "api" in front of every param name. This is comparable to jsdoc having "js" in front of every block tag.

@api → @endpoint
@apiDefine → @define
@apiDescription → @description
@apiError → @error
@apiErrorExample → @errorExample
@apiExample → @example
@apiGroup → @group
@apiHeader → @header
@apiHeaderExample → @headerExample
@apiIgnore → @ignore
@apiName → @name
@apiParam → @param
@apiParamExample → @paramExample
@apiPermission → @permission
@apiSampleRequest → @sampleRequest
@apiSuccess → @success
@apiSuccessExample → @successExample
@apiUse → @use
@apiVersion → @version

**Comment by ftoulemon** [comment]
Useful to discriminate apidoc tags from, for example, doxygen tags.

**Comment by jaredreich** [comment]
Why is this necessary in this project but not in jsdoc?

**Comment by rottmann** [comment]
If apiDoc had existed before jsdoc, it wont be necessary ;-)
See it as a kind of namespace, to separate apidoc from other doc-annotations.

**Comment by ftoulemon** [comment]
I don't know much about jsdoc, but afaik it is used to document the code (like doxygen), while apidocjs documents only the api. So you can use apidocjs + doxygen on a project, but not jsdoc + doxygen (well you can, but they do the same job).

**Comment by jaredreich** [comment]
Fair comments, but I would say an overwhelming majority of folks using apidoc are not using doxygen (or any other doc-annotation for that matter).

**Comment by moazzamk** [comment]
I use doxygen and apidoc. My vote is we keep the api prefix.

**Comment by rottmann** [comment]
My Todo-List grows and grows and i am really unhappy :angry: that i did not find the time to update the latest pulls and that is why i am pretty sure, that i will not change the the **basic** annotation syntax.

Nearly all regex must be changed then too and problems with other doc-annotations must be solved then too, ... for what? There is no benefit, only to save 3 little chars.

Ive started to integrate a plugin system, with the plugins you can modify all annotations and replace everything to fit your needs. If a plugin connector function is missing, i will integrate them (pull is welcome, if i had time :eyes: ), but the annotation system will not be changed without a better reason.

Example is here: https://github.com/apidoc/apidoc-plugin-test
