### ISSUE TITLE
Improve Date Format

### ISSUE THREAD

**Issue by liko28s** [apidoc/apidoc#563]
Hi guys, it seems that the support for date type parameters can be improved by adding support for several formats.
I currently have one resource:
Http://example.com/devices/:lastSyncDate
In code, you can receive dates in Unix Timestamp or yyyy-mm-dd format (or any valid date format)

So the date type can be
```
@apiParam {Date{'yyyy-mm-dd'}} lastSyncDate Date in yyyy-mm-dd Format
@apiParam {Date{'U'}} lastSyncDate Date in Unix Timestamp Format
```

the expected output will be
![image](https://cloud.githubusercontent.com/assets/9079747/21118987/5f9b9934-c08e-11e6-99b0-c7ec89e93d73.png)

Can be [php Date](http://php.net/manual/es/function.date.php) or any languaje especification

**Comment by rottmann** [comment]
We did not have a better resource description, you can set it as e.g.
`* @apiParam {Date='yyyy-mm-dd', 'U'}} lastSyncDate Date in yyyy-mm-dd Format`
