### ISSUE TITLE
Document Response Headers

### ISSUE THREAD

**Issue by esatterwhite** [apidoc/apidoc#568]
It looks like `@apiHeader` is only for request headers.
Is there a way to document the response headers? 
There should be

**Comment by JelmerD** [comment]
You can use the "MyHeaderGroup" part for this.

http://apidocjs.com/#param-api-header

Just name a group "Request Headers"  and the other "Response Headers"

**Comment by esatterwhite** [comment]
Ah. Yep, that does it.
Thanks.
