### ISSUE TITLE
Long URI @api Definition Cuts Off

### ISSUE THREAD

**Issue by calebadams** [apidoc/apidoc#570]
I have a long @api definition URI that will cut off in the allocated pre tag in all web browsers. I've attached a screenshot to illustrate what I'm talking about. I tried creating a custom style sheet and adding overflow-x: auto to the pre tag, which fixes the issue by adding a scroll bar but for some reason wipes out the HTTP request type (ex., GET, POST, etc.). So my solution was not acceptable. Anyone else have problems with this?

![longuri](https://cloud.githubusercontent.com/assets/11083557/21459520/d472c738-c90c-11e6-806c-ba2e90aefc70.png)

**Comment by rottmann** [comment]
Fixed in the next version.
