### ISSUE TITLE
Getting Started Instructions Don't Explain What to do With Generated Files

### ISSUE THREAD

**Issue by machineghost** [apidoc/apidoc#574]
The getting started instructions (http://apidocjs.com/#getting-started) have a great and thorough explanation of how to document APIs, and how to generate documentation files from documented JS files. However, it has no instructions at all for what one is supposed to do with those generated files.

Presumably they should be served somehow through Express, ideally whenever a browser GET request is made to the endpoint, but it's not clear from the docs how to make that happen. Even a very basic example demonstrating the "wiring up" of the documentation for a single API would be helpful.

**Comment by rottmann** [comment]
What you wanna do with the generated files belongs to you.
There are so many languages and api-server out there, that it is not the job of apiDoc to explain them (i think e.g. expressjs has many and really good examples and tutorials).

**Comment by machineghost** [comment]
It's totally reasonable to say explaining how to serve the files is out of scope, but at the *very* least could you at least say somewhere that the library generates static HTML files designed to be served however you see fit?  I could not tell from the docs whether the library generated static files, or something that was designed to be wired in to Express, or a standalone library, or ...
