### ISSUE TITLE
Method type not displayed

### ISSUE THREAD

**Issue by ab-smith** [apidoc/apidoc#577]
Hi,
   Between version 0.16 and 0.17, I lost the display of the method type (GET, POST,etc.).
Thank you.

**Comment by eladkarakuli** [comment]
+1

**Comment by okihouse** [comment]
Parameter optional information is not displayed too.

<img width="394" alt="2017-01-15 8 11 25" src="https://cloud.githubusercontent.com/assets/13760160/21962069/de2995a4-db5e-11e6-8503-f654c56cb4c0.png">

**Comment by rottmann** [comment]
Fixed in 0.17.2
