### ISSUE TITLE
error: Can not read: apidoc.json, please check the format (e.g. missing comma).

### ISSUE THREAD

**Issue by nileshbhope** [apidoc/apidoc#580]
I am getting this error & here is debug info

```
C:\>apidoc -i D:\TestAPIDoc\TestAPIDoc\ -o D:\TestAPIDoc\TestAPIDoc\apidoc --deb
ug
debug: read: D:\TestAPIDoc\TestAPIDoc\package.json
error: Can not read: apidoc.json, please check the format (e.g. missing comma).
debug: Error: Can not read: apidoc.json, please check the format (e.g. missing c
omma).
    at PackageInfo._readPackageData (C:\Users\nileshbhope\AppData\Roaming\npm\no
de_modules\apidoc\lib\package_info.js:78:19)
    at PackageInfo.get (C:\Users\nileshbhope\AppData\Roaming\npm\node_modules\ap
idoc\lib\package_info.js:36:27)
    at Object.createDoc (C:\Users\nileshbhope\AppData\Roaming\npm\node_modules\a
pidoc\lib\index.js:111:44)
    at Object.<anonymous> (C:\Users\nileshbhope\AppData\Roaming\npm\node_modules
\apidoc\bin\apidoc:113:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
```

package.json

`
{
  "name": "test-apidoc",
  "version": "0.0.0",
  "description": "TestAPIDoc",
  "main": "server.js",
  "author": {
    "name": "nileshbhope",
    "email": ""
  },
  "devDependencies": {},
  "dependencies": {}
}
`
apidoc.json

`
{
  "name": "test-api-doc",
  "version": "0.2.0",
  "description": "apiDoc example"
}
`
Please let me know if I am missing some configuration steps?

Thanks

**Comment by rottmann** [comment]
Can not reproduce this. The files are ok. Are there some file permission problems?

**Comment by nileshbhope** [comment]
I am using sample blank NodeJS application & installed apidoc using npm as global module. Even started command prompt as Administrator, it seems its not a file permission issue.

**Comment by rottmann** [comment]
Can you add in `C:\Users\nileshbhope\AppData\Roaming\npm\no
de_modules\apidoc\lib\package_info.js` line 77 
```
        } catch (e) {
console.log(e); // <--
```

**Comment by nileshbhope** [comment]
Hi,

After adding above line I am getting this warning message.

`

D:\>apidoc -i D:\TestAPIDoc\TestAPIDoc\ -o D:\TestAPIDoc\TestAPIDoc\apidoc
[SyntaxError: Unexpected string]
warn: Please create an apidoc.json configuration file.
info: Done.

D:\>
`

But files are created now.

**Comment by superdiazzz** [comment]
I have same issue, where should i put apidoc.json?

**Comment by NicolasCARPi** [comment]
@superdiazzz place it in the same folder as your source files or use the `-c` flag.
