### ISSUE TITLE
Minor: Querying From Docs Breaks Left-Hand Highlighting

### ISSUE THREAD

**Issue by machineghost** [apidoc/apidoc#583]
First off let me just say that I love `apidoc`; thanks a ton for making it.

Second, I just wanted to point out that if you make queries (enabled via a `"sampleUrl": "/api",` setting) the results appear to throw off the calculation for which endpoint should be highlighted on the left-hand side.

Hopefully this is an easy fix (eg. "call recalculateSections() after every query").

**Comment by NicolasCARPi** [comment]
This doesn't seem to happen now.
