### ISSUE TITLE
Loading ....

### ISSUE THREAD

**Issue by HaraldBregu** [apidoc/apidoc#585]
Still didn't fix how to load the index.html in my node server. It continue to give me a loading, but nothing started.
<img width="680" alt="schermata 2017-01-21 alle 09 57 41" src="https://cloud.githubusercontent.com/assets/1328379/22173337/111d3442-dfc0-11e6-9ce9-ff923fdd845e.png">
<img width="580" alt="schermata 2017-01-21 alle 09 57 21" src="https://cloud.githubusercontent.com/assets/1328379/22173339/12aee634-dfc0-11e6-812d-f48d7c7e3fc6.png">

**Comment by rottmann** [comment]
Not apidoc specific, problem with your server.
Try `http-server` in your documentation dir and open `http://localhost:8080` if it works, then there is a problem with your node server.
