### ISSUE TITLE
ApiDoc cannot find file

### ISSUE THREAD

**Issue by alisinabh** [apidoc/apidoc#586]
Hi everyone,

After update when i try to run ``apidoc`` on my project i get following error:
```
error: ENOENT: no such file or directory, open 'C:\Users\Alisinabh\Source\Repos\MyProject\iDocDefs.cs'
```
I also found out every file or folder starting with 'A' will have same issue. The 'A' and its next char will be ignored.

Im using Node v4.4.4 on windows 10

ApiDoc version: 0.17.3 (problem seems to be in >= 0.17)

Thank you

**Comment by alisinabh** [comment]
I also updated my Node to v6.9.4,
problem still presists

**Comment by lamaral** [comment]
I have the same problem. Apparently apidoc is removing the first two characters from the filename. 
```error: ENOENT: no such file or directory, open 'C:\...\handlers\nfig_handler.py'```

**Comment by alisinabh** [comment]
Hi @lamaral

I have fixed this issue and made a pull in apidoc-core project. You can revert your apidoc version to 0.16.x to fix issue temporary.

**Comment by rottmann** [comment]
Thanks, updated in 0.17.4

**Comment by alisinabh** [comment]
My pleasure 💜

Cheers!
