### ISSUE TITLE
"Error: Object "my_file" has no method 'startsWith'" after updating to 0.17.5

### ISSUE THREAD

**Issue by cel03** [apidoc/apidoc#591]
After installing apidoc without setting a specific version, it was automatically updated to 0.17.5 (i guess its packages were updated too).

Then i'm getting the following when generating the doc: 

> error: Object /opt/my_project/src/create.py has no method 'startsWith'

I uninstalled apidoc an installed the 0.17.4 version, but there was no effect. 

These are the packages now:

Nodejs 0.10.28
apidoc@0.17.4
├── nomnom@1.8.1 (underscore@1.6.0, chalk@0.4.0)
├── fs-extra@2.0.0 (jsonfile@2.4.0, graceful-fs@4.1.11)
├── winston@2.3.1 (cycle@1.0.3, stack-trace@0.0.9, eyes@0.1.8, isstream@0.1.2, async@1.0.0, colors@1.0.3)
├── markdown-it@8.2.2 (uc.micro@1.0.3, mdurl@1.0.1, linkify-it@2.0.3, entities@1.1.1, argparse@1.0.9)
├── apidoc-core@0.8.2 (semver@5.3.0, iconv-lite@0.4.15, glob@7.1.1, klaw-sync@1.1.0)
└── lodash@4.17.4 

And that's the debug log:

debug: package.json not found!
debug: read: /opt/my_project/src/apidoc.json
debug: read header file: /opt/my_project/src/header.md
debug: read header file: /opt/my_project/src/footer.md
verbose: apidoc-generator name: apidoc
verbose: apidoc-generator version: 0.17.4
verbose: apidoc-core version: 0.8.2
verbose: apidoc-spec version: 0.3.0
debug: No plugins found.
debug: load parser language: .clj, ./languages/clj.js
debug: load parser language: .coffee, ./languages/coffee.js
debug: load parser language: .erl, ./languages/erl.js
debug: load parser language: .ex, ./languages/ex.js
debug: load parser language: .exs, ./languages/ex.js
debug: load parser language: .litcoffee, ./languages/coffee.js
debug: load parser language: .lua, ./languages/lua.js
debug: load parser language: .pl, ./languages/pm.js
debug: load parser language: .pm, ./languages/pm.js
debug: load parser language: .py, ./languages/py.js
debug: load parser language: .rb, ./languages/rb.js
debug: load parser language: default, ./languages/default.js
debug: load parser: api, ./parsers/api.js
debug: load parser: apidefine, ./parsers/api_define.js
debug: load parser: apidescription, ./parsers/api_description.js
debug: load parser: apierror, ./parsers/api_error.js
debug: load parser: apierrorexample, ./parsers/api_error_example.js
debug: load parser: apiexample, ./parsers/api_example.js
debug: load parser: apiheader, ./parsers/api_header.js
debug: load parser: apiheaderexample, ./parsers/api_header_example.js
debug: load parser: apigroup, ./parsers/api_group.js
debug: load parser: apiname, ./parsers/api_name.js
debug: load parser: apiparam, ./parsers/api_param.js
debug: load parser: apiparamexample, ./parsers/api_param_example.js
debug: load parser: apipermission, ./parsers/api_permission.js
debug: load parser: apisuccess, ./parsers/api_success.js
debug: load parser: apisuccessexample, ./parsers/api_success_example.js
debug: load parser: apiuse, ./parsers/api_use.js
debug: load parser: apiversion, ./parsers/api_version.js
debug: load parser: apisamplerequest, ./parsers/api_sample_request.js
debug: load parser: apideprecated, ./parsers/api_deprecated.js
debug: load worker: apierrorstructure, ./workers/api_error_structure.js
debug: load worker: apierrortitle, ./workers/api_error_title.js
debug: load worker: apigroup, ./workers/api_group.js
debug: load worker: apiheaderstructure, ./workers/api_header_structure.js
debug: load worker: apiheadertitle, ./workers/api_header_title.js
debug: load worker: apiname, ./workers/api_name.js
debug: load worker: apiparamtitle, ./workers/api_param_title.js
debug: load worker: apipermission, ./workers/api_permission.js
debug: load worker: apisamplerequest, ./workers/api_sample_request.js
debug: load worker: apistructure, ./workers/api_structure.js
debug: load worker: apisuccessstructure, ./workers/api_success_structure.js
debug: load worker: apisuccesstitle, ./workers/api_success_title.js
debug: load worker: apiuse, ./workers/api_use.js
debug: load filter: apierror, ./filters/api_error.js
debug: load filter: apiheader, ./filters/api_header.js
debug: load filter: apiparam, ./filters/api_param.js
debug: load filter: apisuccess, ./filters/api_success.js
verbose: run parser
error: Object /opt/my_project/src/create.py has no method 'startsWith'
debug: TypeError: Object /opt/my_project/src/create.py has no method 'startsWith'
    at /opt/generic/nodejs-v0.10.28/lib/node_modules/apidoc/node_modules/apidoc-core/lib/utils/find_files.js:142:20
    at Array.map (native)
    at FindFiles.search (/opt/generic/nodejs-v0.10.28/lib/node_modules/apidoc/node_modules/apidoc-core/lib/utils/find_files.js:141:19)
    at Parser.parseFiles (/opt/generic/nodejs-v0.10.28/lib/node_modules/apidoc/node_modules/apidoc-core/lib/parser.js:91:27)
    at /opt/generic/nodejs-v0.10.28/lib/node_modules/apidoc/node_modules/apidoc-core/lib/index.js:213:24
    at Array.forEach (native)
    at Object.parse (/opt/generic/nodejs-v0.10.28/lib/node_modules/apidoc/node_modules/apidoc-core/lib/index.js:208:25)
    at Object.createDoc (/opt/generic/nodejs-v0.10.28/lib/node_modules/apidoc/lib/index.js:113:22)
    at Object.<anonymous> (/opt/generic/nodejs-v0.10.28/lib/node_modules/apidoc/bin/apidoc:113:12)
    at Module._compile (module.js:456:26)

It occurs with all my files now: even if i exclude this one in the log, the next one will also result an error.

**Comment by rottmann** [comment]
Sorry did not mention it, but node v6 LTS is needed, you hav 0.10.28

**Comment by cel03** [comment]
Since 0.17.5 version?

**Comment by cel03** [comment]
I'm trying to install 0.17.4 version, but it also doesn't work (the same error occurs).  Which apidoc version doesn't have node v6 LTS dependency?

**Comment by rottmann** [comment]
< 0.17
you can use [nvm](https://github.com/creationix/nvm) to switch to the new version, create the doc and switch back to your 0.10 version.

**Comment by fireworks27** [comment]
you can try install < 0.17
````
sudo npm install apidoc@0.12 -g
````
pro test effective
