### ISSUE TITLE
Heading markdown not parsed properly

### ISSUE THREAD

**Issue by nospoon** [apidoc/apidoc#596]
The markdown syntax inside .md files is not being parsed properly in generated output.
If I use a heading markdown like `#Example Heading`, it does not parse it into a heading but instead displays as is, with preceding #.

**Comment by ftoulemon** [comment]
See [this page](https://github.com/apidoc/apidoc/blob/master/MARKDOWN.md). Your need a space `' '` after the `#`

`# Example`

**Comment by nospoon** [comment]
I missed that, thank you.
