### ISSUE TITLE
Required parameters

### ISSUE THREAD

**Issue by nospoon** [apidoc/apidoc#597]
Would it be possible to add functionality to mark required parameters?

I could not find any mention of that in the documentation, so probably the only way currently is to specify that in the description. It would be nice to have something that would stand out a bit more, like additional "Required" column for parameters or the parameter name showing in bold.

**Comment by stephen-last** [comment]
Are you using `@apiParam`..?

[http://apidocjs.com/index.html#param-api-param](http://apidocjs.com/index.html#param-api-param)

The table shows `field` and `[field]`. The one with brackets is marked as optional.

So I take it that all fields are required, and ones in brackets are optional (and it adds an `optional` flag in the output HTML table).

**Comment by nospoon** [comment]
Thanks for pointing this out.
