### ISSUE TITLE
 Optional parameter is sent at URL even when empty.

### ISSUE THREAD

**Issue by leandrozacarias** [apidoc/apidoc#599]
## Generated doc with optional parameter:

![image](https://cloud.githubusercontent.com/assets/10941191/22947860/9b95c4d2-f2e3-11e6-937e-16c22b3b0d7a.png)

## Examples of requests:

![image](https://cloud.githubusercontent.com/assets/10941191/22947901/ba17e052-f2e3-11e6-9238-19f3a89dce45.png)

Should optional parameters be ignored when empty?

**Comment by dzgrief** [comment]
I also hope to have this feature.

**Comment by jdegger** [comment]
Seconded! It's unexpected behaviour for the param to be sent whenever the param is optional. I don't want to send an empty string, I just want to omit the field.

**Comment by tommybananas** [comment]
I'm not sure optional by itself will cut it since there needs to be a difference between a blank string and not sending the parameter at all when blank

**Comment by tommybananas** [comment]
I've submitted a pull request for this feature https://github.com/apidoc/apidoc/pull/647

**Comment by NicolasCARPi** [comment]
Closing. Thanks @tommybananas for the PR !
