### ISSUE TITLE
Ability to ignore node_modules directory

### ISSUE THREAD

**Issue by brandonhamilton** [apidoc/apidoc#6]
Is there an easy way to ignore the node_modules directory in the application path? It would make sense to ignore this by default.

I am running apiDoc in the root of my project, and it crashes when parsing lodash within its own node_modules subdirectory:

> apidoc: inspect file: ./node_modules/apidoc/node_modules/lodash/vendor/benchmark.js
> apidoc: Error: EISDIR, illegal operation on a directory
>     at Object.fs.readSync (fs.js:476:19)
>     at Object.fs.readFileSync (fs.js:310:28)
>     at Parser.parseFile (node_modules/apidoc/lib/parser.js:57:16)
>     at main (node_modules/apidoc/lib/apidoc.js:282:28)
>     at Object.<anonymous> (node_modules/apidoc/bin/apidoc:126:25)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)
> apidoc: Error: EISDIR, illegal operation on a directory

**Comment by ORESoftware** [comment]
+1  this needs to be in README.md please

**Comment by xavicolomer** [comment]
This works for me:

```
apidoc({
    src: 'path/to/api/docs',
    dest: 'docs/api',
    debug: true,
    includeFilters: [ '.*\\.js$' ],
    excludeFilters: [ 'node_modules' ]
  }, done);
```

**Comment by chovy** [comment]
can i add ignore directories to the apidoc.json file somehow? I just read the .gitignore
