### ISSUE TITLE
Example params all seem the same..?

### ISSUE THREAD

**Issue by stephen-last** [apidoc/apidoc#600]
These all seem to be the same:

- [@apiErrorExample](http://apidocjs.com/index.html#param-api-error-example)
- [@apiExample](http://apidocjs.com/index.html#param-api-example)
- [@apiHeaderExample](http://apidocjs.com/index.html#param-api-header-example)
- [@apiParamExample](http://apidocjs.com/index.html#param-api-param-example)
- [@apiSuccessExample](http://apidocjs.com/index.html#param-api-success-example)

I think the API for `apidoc` would be cleaner and more flexible with something like:

```js
@apiCodeExampleGroup Requests
@apiCodeExample {json} (Requests) Successful Request
{
  "test": 123
}
@apiCodeExample {json} (Requests) Error Request
{
  "test": 123
}
```

These two `@apiCodeExample`'s would then be grouped (two tabs).

You could also do ordering (the order in which they appear under the API name) by adding to the `@apiCodeExampleGroup` - something like `@apiCodeExampleGroup Requests {1}`.

Also, I can't see a list of available `type`'s for these example params. The examples I can see show `json`, `js` and `curl`. Are there any more?

**Comment by NicolasCARPi** [comment]
> Also, I can't see a list of available type's for these example params.

@rottmann I couldn't find it from the code. What actually is parsing the `language-python` or `language-curl` class to make the code highlight?

**Comment by rottmann** [comment]
@NicolasCARPi the prettify scripts highlight the code: https://github.com/apidoc/apidoc/tree/master/template/vendor/prettify, since release these are not updated.

**Comment by NicolasCARPi** [comment]
ok thanks. Given that the [upstream is archived](https://github.com/googlearchive/code-prettify), I'll look into alternatives.

**Comment by NicolasCARPi** [comment]
Got something working with prism.js:

![out](https://user-images.githubusercontent.com/3043706/83355262-a04ee600-a35e-11ea-9452-a2aafd594eac.gif)
