### ISSUE TITLE
Not able to send authorization token

### ISSUE THREAD

**Issue by P3arl** [apidoc/apidoc#604]
Hi,

I am adding Authorization header in java code like below but it is not sending the token and not showing any response. Please respond how to send header in  GET/POST api call using apidocjs.
`/**
     * 
     * @api {GET} getScoredStudentDetails getScoredStudentDetails

     * @apiGroup RestService

     * @apiHeader {String} Authorization bearer bd970a05-0ec1-4412-8b28-657962f0f778

     * @apiDescription Returns details of all students and scores for a assessment
     * @apiParam {int} institutionId Unique identifier for an institution (e.g. 299)
     * @apiParam {String} formId External assessment id (e.g. 2487)
     * @apiParam {String} clientType="PS" External Assessment System Identifier (e.g. google, canvas)
     * @apiSuccess {JSON} ScoredStudentDetailsResponseDTO POJO object containing information about 
     * scored students in an assessment, status as success and success message
     * @apiError {JSON} ScoredStudentDetailsResponseDTO POJO object containing status as failed and error message
     *  
     *  @apiSuccessExample Success Response (Example):
        {
            "status": "success",
            "message": "scored student details fetched successfully",
            "students": [
             {
                "studentId": "student1@email.com",
                "email": "student1@email.com",
                "studentName": "student1@email.com",
                "score": 2
             },
             {
                "studentId": "student2@email.com",
                "email": "student2@email.com",
                "studentName": "student2@email.com",
                "score": 1
            `}
            ]
        }
     *  @apiErrorExample Error Response (Example):
     * { 	
     *      status": "failed",
            "message": "no records found."
        }
     * 
     * 
     * @apiSampleRequest rest/ps/getScoredStudentDetails
     */
`

**Comment by sven-piller** [comment]
As far as I understand the @apiHeader you are using the wrong syntax

     @apiHeader [(group)] [{type}] [field=defaultValue] [description]

For your example it should be 

     @apiHeader {String} Authorization='bearer bd970a05-0ec1-4412-8b28-657962f0f778'

**Comment by P3arl** [comment]
Thanks for the reply.

I tried the same, but still it is not working.

I have tried all these things -
1. @apiHeader {String} Authorization='bearer bd970a05-0ec1-4412-8b28-657962f0f778'
2. @apiHeader {String} Authorization bearer description
3. @apiHeader Authorization bearer bd970a05-0ec1-4412-8b28-657962f0f778

I am not sure how to send the header in api call using apidocjs.

Can you please guide if i am missing some step in order to achieve this.

Note : I am able to send/hit all the other requests using apidocjs who does not require auth in the header

**Comment by ksoul78** [comment]
Hello 
I'm processing this way to document the Header 

`@apiHeader {String="Bearer :token"} Authorization Replace <code>:token</code> with supplied Auth Token `

Authorization | String | Replace :token with supplied Auth Token `Valeurs autorisées : "Bearer :token"`

**Comment by P3arl** [comment]
Hi ksoul78,

Thanks for the comment, but it is still not working.

**Comment by wangle201210** [comment]
u can do like this 

/**
        @apiVersion 0.0.1
        @apiHeader {String} Authorization Bearer + token
        @apiHeaderExample {json} 头部列子:
        {
          "Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sLnRcL2FwaVwvYXV0aFwvbG9naW4iLCJpYXQiOjE1MjM0MjcwMDAsImV4cCI6MTUyMzQzNzgwMCwibmJmIjoxNTIzNDI3MDAwLCJqdGkiOiJxZDNJa1JGOFdrVWVWQk50Iiwic3ViIjo3LCJwcnYiOiI4N2UwYWYxZWY5ZmQxNTgxMmZkZWM5NzE1M2ExNGUwYjA0NzU0NmFhIiwidXNlciI6eyJpZCI6N319.oilxJtv04JbhmBztLWNbweXgq7tuHZO9ShwFEGVKskg"
        }
        @apiGroup test
        @api {post} tests 测试上传article
        @apiName test_article_save
        @apiParam {String} test test.
        @apiSampleRequest tests
        @apiSuccessExample {json} 成功返回:
        HTTP/1.1 201 OK
        {
            "data": {
                "test": "ssss",
                "updated_at": "2018-04-11 21:55:25",
                "created_at": "2018-04-11 21:55:25",
                "id": 24,
                "title": "ssss24"
            }
        }
    */

**Comment by NicolasCARPi** [comment]
Headers are correctly sent. The correct syntax is:

~~~php
 * @apiHeader {String} Authorization='bearer bd970a05-0ec1-4412-8b28-657962f0f778' Some description
~~~
