### ISSUE TITLE
apidoc blocked by content security policy

### ISSUE THREAD

**Issue by chrisveness** [apidoc/apidoc#605]
Trying to use apidoc, I found it wouldn't load; Chrome devtools reported "EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive...", at `handlebars.min.js`.

I'm not able to add "unsafe-eval" to the CSP (rather undermines CSP!).

It looks as though `eval` is fairly fundamental to handlebars, but could be got around by precompiling the handlebars templates.

Is it or would it be possible to have apidoc precompile the handlebars templates?

**Comment by redfive** [comment]
Just hit this problem trying to load html pages generated by the tool in our Jenkins instance. I can update the CSP but would like to see this resolved so we can make the CSP more protective.

Any plans to get to this soon? If not, perhaps a pointer to where this fix might come in would get a PR from the community?

**Comment by NicolasCARPi** [comment]
So it looks like handlebars will never work with CSP. One might need to use a static precompiled file instead (a feature currently missing from apidoc).

See https://github.com/wycats/handlebars.js/issues/1443

See https://github.com/apidoc/apidoc/issues/666

Right now, this issue cannot be solved and you'll need a permissive CSP. Let's see how hard it is to implement that static html output!

**Comment by NicolasCARPi** [comment]
Closing because it's a limitation on the JS template engine being used and fixing this would probably mean a rewrite of a good part of this project.
