### ISSUE TITLE
apiUse within an apiDefine block

### ISSUE THREAD

**Issue by alekaizer** [apidoc/apidoc#607]
Hi guys,

I've tried this type of declaration and get this error:

**Declaration**

```
"""
@apiDefine A
...
...
"""

"""
@apiDefine B
...
...
"""

"""
@apiDefine C
...
...
@apiUse A
@apiUse B
"""

"""
@apiDefine D
...
...
@apiUse B
"""
```

**Error**
```
error: Only one definition or usage is allowed in the same block. 
{ File: './path/to/file',
  Block: 4,
  Element: '@apiUse',
  Source: '@apiUse DEFINITION' }

```

I believe we should be able to do so, so we can define different kind of object and then use them in the definitions of the endpoint.

Or have mini-classes that we use in different others mega classes, that will save some works, and we can actually write the classes definitions while writing the class or the models(in a Django application for example)

Any thoughts is welcomed :)

**Comment by rottmann** [comment]
apiDoc did not support complex inheritance, only 1 level with define and use. 
My goal is not to create a full OOP-Style documentation language, it should be kept simple and human readable, without jump to different locations to read the source code.
