### ISSUE TITLE
Question: How to manage @api path update?

### ISSUE THREAD

**Issue by ftoulemon** [apidoc/apidoc#611]
If I have something like:

    @api {GET} /path/example Example
    @apiVersion 1.0.0

and I wand to change the path to:

    @api {GET} /newpath/example Example
    @apiVersion 2.0.0

I would usually copy the first one in the file `_apidoc.js` to keep the history.
But if I do this, I end up having it duplicated in the generated documentation, as apidoc use the path to identify each block.

So my question is: how do you manage this case?

Do you lose the history if you change the path?
Is there a way to tag a block `obsolete` or `deleted` and filter it so it doesn't appear in the output doc?

**Comment by rottmann** [comment]
You can mark it as apiDeprecated.
But for this case we did currently not have a solutions.
One solution could be an additional apidoc.json parameter to exclude older api-blocks from the current version view.

**Comment by NicolasCARPi** [comment]
I believe this is not an issue anymore.
