### ISSUE TITLE
Html breaks during comparison

### ISSUE THREAD

**Issue by osmanozeroz** [apidoc/apidoc#616]
Hi,
When comparing, html tags appear.
![image](https://cloud.githubusercontent.com/assets/4309941/23845281/d9adcbf6-07cf-11e7-9a6c-b1f46ecdfe95.png)

![image](https://cloud.githubusercontent.com/assets/4309941/23845297/eada3c66-07cf-11e7-8e64-a4a07809e8fc.png)

![image](https://cloud.githubusercontent.com/assets/4309941/23845316/0f678b1a-07d0-11e7-8c3c-3e0f5edd81af.png)

**Comment by NicolasCARPi** [comment]
Closing as duplicate of #538
