### ISSUE TITLE
Ruby multiline comments break RSpec. Can we have # blocks?

### ISSUE THREAD

**Issue by sebastialonso** [apidoc/apidoc#620]
apiDocs works greats with the `=begin =end` blocks, but it breaks the Rspec tests.

Can the hash (#) comments be supported? Are there plans for this? (I tried with those and they failed, so there should be no support unless I'm missing something)

**Comment by arianf** [comment]
`=begin =end` also isn't recommended by the rubocop style guide: 
https://github.com/rubocop-hq/ruby-style-guide#no-block-comments

**Comment by smoothdvd** [comment]
@sebastialonso @arianf You can use Doxygen style like perl
```
Perl (Doxygen)
#**
# This is a comment.
#*
```

**Comment by NicolasCARPi** [comment]
Hello,

Feel free to open a PR with the correct regex for this file: https://github.com/apidoc/apidoc-core/blob/master/lib/languages/rb.js#L6

(warning: different repo!)
