### ISSUE TITLE
apiGroup encoding is not utf-8 ? 

### ISSUE THREAD

**Issue by RifeWang** [apidoc/apidoc#621]
If i named apiGroup in chinese like : 
```
/**
 * @apiGroup 用户
 */
```
, it cann't show in browser, I guest it's encoding is not utf-8. So maybe its a problem need to solve.

**Comment by Abel94** [comment]
```php
/**
 * @apiDefine user 用户
 */
```
就可以给名称为user的group定义一个别名。

甚至还可以添加描述信息：
```php
/**
 * @apiDefine user 用户
 * 描述信息
 */
```

**Comment by RifeWang** [comment]
@Abel94 看来目前只能通过 apiDefine 的方式定义中文别名，thank you !

**Comment by wanlxp** [comment]
I have the problem too, why not resolve it
