### ISSUE TITLE
String Arrays ({string[]}) Don't Work in Generated Form

### ISSUE THREAD

**Issue by machineghost** [apidoc/apidoc#627]
When you define a string array parameter for an endpoint in it's APIDoc documentation, and then have APIDoc add a form for testing the endpoint to the documentation, that form doesn't work.  This is because, instead of having multiple inputs for string arrays APIDoc generates only a single text input (with "String[]" as a label on the right-side).

APIDoc should ideally generate a very simple control with a text input, a "plus button" which adds more text inputs, and a "minus removal button" next to every text input except the first.

**Comment by maheshgawali** [comment]
it would be big help if this is supported in apidoc.
