### ISSUE TITLE
Add input and output paths to apidoc.json

### ISSUE THREAD

**Issue by lietu** [apidoc/apidoc#630]
I don't see any obvious reason why, but it seems it's not possible to define all the required arguments for `apidoc` on the config file, but I need to always run it with `apidoc -i input_dir -o output_dir`.

Please add `input` and `output` properties to the `apidoc.json` -file, that are used unless the arguments are provided on CLI. This way it'll be possible to tell developers that all they need to do is to run `apidoc` to update the documentation.

**Comment by FredericMartinez** [comment]
Only solution, use a `Makefile`, so all developers just run your command (with params).

```
.PHONY: apidoc
apidoc: ## Generate API doc
	@docker run --rm -ti -v `pwd`:/app -w /app dmitrymomot/apidoc -i your_input_folder -o your_outpur_folder
```
And then run `make apidoc`.

If you have a better option, tell me :)

**Comment by lietu** [comment]
Well this is of course rather opinionated, but imo almost any other option is better than make due to it's numerous issues: http://www.conifersystems.com/whitepapers/gnu-make/

I e.g. would much prefer to have `./gen-apidoc` -bash script like this:
```
#!/usr/bin/env bash
docker run --rm -ti -v `pwd`:/app -w /app dmitrymomot/apidoc -i your_input_folder -o your_outpur_folder
```

And then on e.g. Windows you'd have a similar `gen-apidoc.bat`, and now you have `gen-apidoc` command that does it, without having to deal with all the issues of Make.

Anyway, ultimately the best solution is to add the support for those options to be added to the configuration file.

**Comment by FredericMartinez** [comment]
> Anyway, ultimately the best solution is to add the support for those options to be added to the configuration file.

👍

**Comment by NicolasCARPi** [comment]
Hello, I have it working on the dev branch. I still need to rewrite parts of the code so it looks less quirky, and add proper tests before I push but this will be available in the next release.

In `apidoc.json` you can now have:

~~~json
"input": [
   "mysrc"
],
"output": "/tmp/apidoc-output",
~~~

Input is an array and output a string. Note that CLI parameters will override config file values, as is expected in most software.

Now you can just `apidoc -c /path/to/apidoc.json` and it'll work.
