### ISSUE TITLE
@apiError Example is Unhelpful

### ISSUE THREAD

**Issue by machineghost** [apidoc/apidoc#631]
The current documentation for `@apiError` provides only a single example:

> @apiError UserNotFound The id of the User was not found.

However, that example isn't very helpful, as it doesn't actually explain how to use the other parameters.  After a great deal of searching I finally found this:

> @apiError (500 Internal Server Error) InternalServerError The server encountered an internal error

The simple addition of `(500 Internal Server Error)` answered the question that I had just spent 30+ minutes trying to figure out (how do I get my errors to stop being grouped under `Error 4xx`?)

Please please switch to the latter example in the docs; without it there is absolutely no way for a user to know they need to include the code and the named wrapped in parentheses, because the documentation just says:

>(group)optional	All parameters will be grouped by this name.
Without a group, the default Error 4xx is set.
You can set a title and description with @apiDefine.

which would lead one to naively try (and then be confused when it doesn't work):

    * @apiError 500 MyError an error

**Comment by ehallander9591** [comment]
While your case for more examples might be a valid one,

[@apiError](http://apidocjs.com/#param-api-error)

does state the the [(Group)] is optional and defaults to Error 4xx

The group option is present on many of the tags.

Cheers

**Comment by machineghost** [comment]
Well the main thing I don't see documented is combining the number and name, eg.:

   (500 Internal Server Error)

But while that might be the only missing bit, without it a lot the whole thing just doesn't make sense:
 I mean honestly, what programmer do you know who thinks `500` as a "group"?  None right? We think of `500` is an HTTP status code, not a group.  But when you see that example with a "group" of `(500 Internal Server Error)` then the whole thing falls in to place.

Also, I was using a version of API doc that was a few versions back, when I provided a group of `500` it did not change where the entry was grouped.  But this is probably a non-issue from me using an out-of-date version with the latest docs.

**Comment by tjdavenport** [comment]
Just ran into this. A more clear example would really help.

**Comment by NicolasCARPi** [comment]
Example added ;)

**Comment by Mithil467** [comment]
The added example has been removed probably because I cannot find it on https://apidocjs.com/#param-api-error @NicolasCARPi @machineghost

**Comment by NicolasCARPi** [comment]
@Mithil467 That's because the example was added to the example code in example folder of this repo, the doc hasn't changed.

Correct repo is here: https://github.com/apidoc/apidocjs.com
