### ISSUE TITLE
String[] work wrong 

### ISSUE THREAD

**Issue by alenka1710** [apidoc/apidoc#634]
if i use array of string in apidoc i receive an array with only one string item which consists of all items
![image](https://cloud.githubusercontent.com/assets/17640487/25431619/f864f4b6-2a89-11e7-9e9d-898a464747cb.png)

**Comment by BakhtiyarKBTU** [comment]
@alenka1710 may be u must send like "str1", "id100", "12g" ?

**Comment by alenka1710** [comment]
BakhtiyarKBTU, it is result witch generate me apidoc, in a success way i want to have array of strings

**Comment by NicolasCARPi** [comment]
This looks like the error is coming from the server's reply, not apidoc.
