### ISSUE TITLE
How to use enum valune in java?

### ISSUE THREAD

**Issue by mingoooook** [apidoc/apidoc#636]
I like to use enum.

ex.
```java
public enum Pay {CREDIT, CASH, MOBILE}
```
and use this as api parameters.

I want reuse enum api parameters in apidoc.
Please let me how.

**Comment by leeponlp** [comment]
I am now facing the same question like you , if you have knew , please tell me ,3q

**Comment by NicolasCARPi** [comment]
Hello, this is not supported AFAIK.
