### ISSUE TITLE
Resolve header and footer files relative to config

### ISSUE THREAD

**Issue by dertieran** [apidoc/apidoc#637]
Right now the header and footer which are defined in the `apidoc.json` are resolved relative to the `options.src` path(s) or the working directory.
Could they also be resolve relative to `options.config` because they are defined in there?
[Link to code](https://github.com/apidoc/apidoc/blob/master/lib/package_info.js#L97)

**Comment by NicolasCARPi** [comment]
It is correctly loaded now (at least in `dev` branch).
