### ISSUE TITLE
Elixir - Generates compile warnings on 1.4

### ISSUE THREAD

**Issue by johnkelly** [apidoc/apidoc#640]
Relevant Discussion:
https://github.com/rrrene/credo/issues/291

The use of module attributes was changed in elixir 1.4 to generate an error if it isn't used. The syntax should probably change a more traditional comment syntax like Go, Java, Java, etc to eliminate this warning.

**Comment by techgaun** [comment]
@johnkelly what would be a good format to adopt here? Something like below maybe fine?
```
#{
# @api {get} /user/:id Request User information
# @apiName GetUser
# @apiGroup User
#
# @apiParam {Number} id Users unique ID.
#
# @apiSuccess {String} firstname Firstname of the User.
# @apiSuccess {String} lastname  Lastname of the User.
#}
```

**Comment by johnkelly** [comment]
yes, I think that would work. @techgaun

**Comment by techgaun** [comment]
@johnkelly I've made appropriate changes to use this pattern. Hopefully the PR can be merged. But you could try my branches if you wish to test my changes

**Comment by thiamsantos** [comment]
Any news on this?

**Comment by henryj** [comment]
would love to see this get resolved. Not sure if it's the best work-around but currently I put @apidoc at the end of the module to avoid the warnings.
