### ISSUE TITLE
jQuery Error on (Working) XML-Returning API Endpoint

### ISSUE THREAD

**Issue by machineghost** [apidoc/apidoc#643]
I have an endpoint which returns XML, and when I hit it directly I get back XML text, as expected.

However, when I try to use the APIDoc page to fetch that endpoint, I get a jQuery error:

    Uncaught TypeError: Cannot read property 'ownerDocument' of null

This only happens with my XML endpoints; all of my JSON-returning endpoints work just fine in APIDoc.  The reason seems to be this code:

    function displaySuccess(data, status, jqXHR) {
          var jsonResponse;
          try {
              jsonResponse = JSON.parse(jqXHR.responseText);
              jsonResponse = JSON.stringify(jsonResponse, null, 4);
          } catch (e) {
              jsonResponse = data;
          }
          $root.find(".sample-request-response-json").html(jsonResponse);
          refreshScrollSpy();
      };

which expects all APIs to return JSON or non-XML text.  A very simple fix to allow XML would be to change:

          } catch (e) {
              jsonResponse = data;
          }

to:

          } catch (e) {
              jsonResponse = data.documentElement || data;
          }

which would append the XML as a node.  This will work, but you'll only get to see the text inside the XML tags, not the XML itself.

To show all of the XML, including tags you could simply do something like:

          } catch (e) {
              if (data.documentElement) data = (new XMLSerializer()).serializeToString(data)
              jsonResponse = data;
          }

which would actually serialize the XML into text so that everything (tags and all) could be viewed.

**Comment by NicolasCARPi** [comment]
Hello,

This has been fixed in #793.
