### ISSUE TITLE
Hide Send sample request

### ISSUE THREAD

**Issue by adelatuduce** [apidoc/apidoc#645]
Hello,

Is it possible to hide the Send sample request section? If so, how can it be done?

Thank you.

**Comment by danyg79** [comment]
You can do it by @apiSampleRequest off

**Comment by kaaax0815** [comment]
Version: apidoc 0.27.1
Setting `@apiSampleRequest off` doesnt work

**Comment by randonia** [comment]
Just wanted to chime in and say it works for me using `"apidoc": "^0.27.1",`. I have `sampleUrl` defined in my config if that helps.

The `@apiSampleRequest off` is per-API not globally. IIRC disabling it globally has some confusion about its functionality in latest (see: #947)

```javascript
/**
 * @api {GET} / Get Example
 * @apiName GetExample
 * @apiGroup Example
 * @apiVersion  1.4.0
 * @apiDescription This is a sample description
 *
 * @apiSampleRequest off
 */
```

![image](https://user-images.githubusercontent.com/483267/113444336-8b8d1580-93a8-11eb-8f02-43e6f934f22a.png)

**Comment by reng99** [comment]
> Version: apidoc 0.27.1
> Setting `@apiSampleRequest off` doesnt work

"sampleUrl": true was defined in config can help

**Comment by soumpanhaoudom** [comment]
> > Version: apidoc 0.27.1
> > Setting `@apiSampleRequest off` doesnt work
> 
> `"sampleUrl": true` was defined in config can help

thank you very much. Your comment is really useful.

**Comment by Lukas-Heiligenbrunner** [comment]
In my case setting ` "sampleUrl": null` in the config did the trick to disable the form globally without a @apiSampleRequest off comment.
