### ISSUE TITLE
SampleUrl question

### ISSUE THREAD

**Issue by kawen11** [apidoc/apidoc#648]
In the web  I sendthe sampleUrl which I set in apidoc.json file,  but it returns error:

Error 0: 
undefined

what's wrong?

**Comment by kawen11** [comment]
No 'Access-Control-Allow-Origin' header is present on the requested resource. 

What's the solution?

**Comment by RifeWang** [comment]
set 'Access-Control-Allow-Origin' in your server, if you use express framework , you can add code in app.js like:
```
//设置跨域访问
app.all('*', function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  res.header("Access-Control-Allow-Methods","PUT,POST,GET,DELETE,OPTIONS");
  res.header("Content-Type", "application/json;charset=utf-8");
  next();
});
```

**Comment by lizhong43403** [comment]
Sample Url does not seem to support an instance of file submission. Can this be added to the optimization?
