### ISSUE TITLE
How to set http request headers content-type to "application/json"

### ISSUE THREAD

**Issue by maguon** [apidoc/apidoc#649]
The apidoc default content-type is application/x-www-form-urlencoded ,but my sever api accept type is application/json ,and api  parameter type is Object . How  set apidoc or rewrite api_data.js to do that. Thanks~

**Comment by koko-ng** [comment]
See my pull request: #601

**Comment by uscbsitric** [comment]
Content-Type: application/json

**Comment by yangyang-zhang** [comment]
Did you solve this problem? I encountered the same problem.

**Comment by uscbsitric** [comment]
can you send me the original link of the article where you read this?  is this laravel or angular 2(3,4 or 5)    On Monday, October 22, 2018, 7:32:51 PM GMT+8, yangyang <notifications@github.com> wrote:  
 
 
Did you solve this problem? I encountered the same problem.

**Comment by frabanca** [comment]
Looks like there is a misconfiguration in the `apiDoc/utils/send_sample_request.js` file on line 97.

To solve this I changed this code:
```
var ajaxRequest = {
            url        : url,
            headers    : header,
            data       : param,
            type       : type.toUpperCase(),
            success    : displaySuccess,
            error      : displayError
        };
```

to this

```
var ajaxRequest = {
          url        : url,
          headers    : header,
          data       : JSON.stringify(param),
          contentType: 'application/json',
          dataType   : 'json',
          type       : type.toUpperCase(),
          success    : displaySuccess,
          error      : displayError
      };
```

@maguon @koko-ng  @yangyang-zhang  can you check if this works also for you?

**Comment by NicolasCARPi** [comment]
You can try the current `dev` branch: `npm i -g apidoc/apidoc#dev`. See also #999. If you're sending json, the correct Content-Type header will be set.
