### ISSUE TITLE
@apiDefineVariable will be cool?

### ISSUE THREAD

**Issue by CodersBrothers** [apidoc/apidoc#65]
Will be cool the possibility for define variables?
For example in my case, the url for endpoints its 

```
http://54.10.24.100/api/v1/
```

I have this in aaaaaall endpoints of my documentation, but now we have domain:

```
http://www.domain.com
```

 And we make a subdomain for api like 

```
http://api.domain.com
```

The problem its that now i need change in all documentation the url. Will be cool define this in one file, like a config file, something like when we are programming, with all general variables, structures...
And i say more. Maybe will be cool that other params must be a variable: for example the structures. Like something more general. And you can inject where you want. You can @apiDefineVariable and you can put all text that you want and later you can inject when you put @apiVariable.

Example:

```
@apiDefineVariable Host http://api.domain.com/

@api {post} {@apiVariable Host}/v1/users/ Create user
```

**Comment by guillaumeleone** [comment]
Very cool feature. Any idea when it will be possible to use it ?
