### ISSUE TITLE
Multiple @apiUse in @apiDefine

### ISSUE THREAD

**Issue by mold** [apidoc/apidoc#652]
I've defined multiple common parameters using @apiDefine and want to group them in "super" @apiDefine for use with endpoints that support all parameters:

Query params:
```
/**
 * @apiDefine QueryString
 *
 * @apiParam (Query params) {String} [query]
 *   Search string used as a filter on the query.
 */

/**
 * @apiDefine QueryCount
 * @apiParam (Query params) {Boolean} [count=false]
 *   If true, only returns a count i.e. number of results matching the
 *   query.
 */
```

"Super" @apiDefine:
```
/**
 * @apiDefine QueryParams Query parameters
 *   These parameters are available to all API endpoints performing
 *   some sort of query.
 *
 * @apiUse QueryString
 * @apiUse QueryCount
 * @apiUse QueryPage
 * ... etc
 */
```

But when I try this I get the error `error: Only one definition or usage is allowed in the same block.`

It would be nice to be able to group @apiDefine's like this.

**Comment by tyranron** [comment]
+1

Having this feature makes docs creation a lot more DRY and flexible.

**Comment by rottmann** [comment]
Multi inheritance is not supported, view https://github.com/apidoc/apidoc/issues/194#issuecomment-70288961
