### ISSUE TITLE
Nullable apiSuccess

### ISSUE THREAD

**Issue by Sven65** [apidoc/apidoc#654]
I have an API with multiple types of responses on an endpoint, and I want to specify that some of the response fields are nullable (Not there all the time), and considering the JSDoc standard of adding a `?` in the type doesn't work with apidoc, how do I do this?

**Comment by ChristianTucker** [comment]
Bump

**Comment by uphlewis** [comment]
Any movement on this?

**Comment by NicolasCARPi** [comment]
Use `[nullableField]`. See commit above.

You can try the current `dev` branch: `npm i -g apidoc/apidoc#dev`. See also #999.
