### ISSUE TITLE
Problems with russuian characters in group,groupTitle fields

### ISSUE THREAD

**Issue by ViacheslavBlinov** [apidoc/apidoc#657]
Hi, guys.
I have problems with russuian characters in group and groupTitle fields.
When i'm trying to generate documentation - i receive underscore symbols instead of russian characters.
![image](https://user-images.githubusercontent.com/12586507/27290520-280b308e-5516-11e7-82a0-4d6ccdc94aed.png)
Fix it, please.

Thank you.

**Comment by rottmann** [comment]
Currently only alphanumeric latin1 chars are allowed as names.
