### ISSUE TITLE
[New feature] set sampleUrl just on the page

### ISSUE THREAD

**Issue by vipzhicheng** [apidoc/apidoc#660]
First reason is that I want to add apidoc process into our CI, make every branch of repo has its own apidoc. each branch has it's own sampleUrl, a little bit different.

So I realize set it in apidoc.json it not enough, so I want to set it on the page, maybe just one operations in settings area. Or every api has their own sampleUrl setting.

**Comment by Naktibalda** [comment]
I am not sure if I understand you correctly, but I had a similar issue - I wanted to make sample requests to current domain without editing url field manually.

I was able to achieve that by editing 2 generated javascript files and I automated this process by setting url and sampleUrl to `http://API-URL` in apidoc.js configuration file.
```js
  "url": "http://API-URL",
  "sampleUrl": "http://API-URL",
```
and using this shell script to generate and update documentation:
```sh
apidoc -i application/ -o httpdocs/docs
sed -i -e 's/"url": "http:\/\/API-URL/"url": window.location.origin + "/g' httpdocs/docs/api_data.js
sed -i -e 's/"http:\/\/API-URL"/window.location.origin/g' httpdocs/docs/api_project.js
```
