### ISSUE TITLE
How to test the api using the samples

### ISSUE THREAD

**Issue by Huarong** [apidoc/apidoc#661]
There are  @apiParamExample and @apiSuccessExample in the comments.

How can we test the api directly from the samples in the comments.

I know there is a test form if samleUrl is set, but we still need to fill the form manually.

I want to make it automatic and can test all the api in one run.

**Comment by rottmann** [comment]
The examples are only examples, not tests.
The send sample request plugin enables you to use the defined apiParam to send data.
Currently it has not integrated a test system with predefined test cases.

**Comment by Huarong** [comment]
I think this is valuable.

Right now we need to write samples both in the api docs and unittest. This is a waste of effort and will we can not confirm the samples in api docs are always right without unittest.

**Comment by neelbhanushali** [comment]
<img src="https://camo.githubusercontent.com/09376560942ff18a058c34314b9bb328948a915e/687474703a2f2f692e696d6775722e636f6d2f425972773275612e676966" alt="upvote">

**Comment by NicolasCARPi** [comment]
@Huarong While I understand your point of view, apidoc IS NOT a test suite for API endpoints.

For that, you should use a testing library. For instance, in my PHP project, I'm using Codeception API testing: https://codeception.com/docs/10-APITesting and it's great.

Here the purpose of this project is to generate static documentation from special comments in the code. Then some sort of plugin was added to allow making requests from the documentation. But transforming this into a fully fledged test suite is in my opinion out of scope and would need a tremandous amount of work to make it worth it. There are already [pages and pages](https://www.npmjs.com/search?q=keywords:REST%20API%20testing) of libraries for testing REST API. We should focus on one thing and do it well. I hope you understand my view.

**Comment by haizadvnet** [comment]
Have a look into https://github.com/haizadvnet/apidoc-plugin-codeception. I just started to work into it. I am using Codeception to do the unit testing. More work to be done.
