### ISSUE TITLE
Use of URL specified into apidoc.json as costant into @apiExample 

### ISSUE THREAD

**Issue by aalonzi** [apidoc/apidoc#664]
I have apidoc.json like: 
{ "name": "REST API Documentation", "version": "1.0.0", "title": "REST API Documentation", "url" : "https://send.siteurl.com/api/v1", } 

Can I use "url" field into @apiexample TAG, eg: 

curl  -X GET -i __url__/devices/ 

?
--

**Comment by rottmann** [comment]
After the docs are generated you could write a small js code to replace your constant with the url in apidoc_data.json file.
