### ISSUE TITLE
Trim() resolves Can not read: apidoc.json error

### ISSUE THREAD

**Issue by jaime-fuhr** [apidoc/apidoc#665]
JSON.parse will fail if text contains a leading space.

**package_info.js**

Add trim() to the file read operation 

**Line 74, change**
`result = JSON.parse( fs.readFileSync(jsonFilename, 'utf8') );`
to
`result = JSON.parse( fs.readFileSync(jsonFilename, 'utf8').trim() );`

**Comment by rottmann** [comment]
But which valid json contain leading space?
