### ISSUE TITLE
Generate HTML during compile?

### ISSUE THREAD

**Issue by rcrooks** [apidoc/apidoc#666]
This is just an idea. I've been struggling with getting API references into Drupal, and it occurred to me that it would be a lot easier if the output of compiling included fully static HTML instead of generating most of it at runtime via JS/Handlebars. I don't think there's any reason not to do this, as the data for HTML doesn't change after compile.
The key to this would be to do the Handlebars/JS part in Node during the compile. I know there's not a DOM, but you can create one using https://www.npmjs.com/package/xmldom - I've done something similar with JSDoc in a situation where I needed to short-circuit the compile process and generate the JSON differently than JSDoc was doing (at the time).

**Comment by NicolasCARPi** [comment]
Hello,

This sounds like a good idea, but given that developer time is precious, unless you provide a PR, this probably won't be implemented.

**Comment by NicolasCARPi** [comment]
Reopening as having a static HTML will allow restrictive CSP header to work. See #605.

**Comment by NicolasCARPi** [comment]
See https://github.com/apidoc/apidoc/pull/840
