### ISSUE TITLE
Documentation in perl only works in files with .pm extension

### ISSUE THREAD

**Issue by jeffdoubleyou** [apidoc/apidoc#667]
As described in the title, apidoc will not generate any documentation unless the file extension is .pm.

A work around is to add ### before and after the apidoc blocks or other language comment blocks, such as:

```
=pod
/**
@api {get} /user/:id Request User information
@apiName GetUser
@apiGroup User

@apiParam {Number} id Users unique ID.

@apiSuccess {String} firstname Firstname of the User.
@apiSuccess {String} lastname  Lastname of the User.
*/
=cut
```

$ apidoc -v
verbose: apidoc-generator name: apidoc
verbose: apidoc-generator version: 0.17.6
verbose: apidoc-core version: 0.8.3
verbose: apidoc-spec version: 0.3.0

**Comment by rottmann** [comment]
You are welcome to add missing file extension as a pull requests for [apidoc/apidoc](https://github.com/apidoc/apidoc) and [apidoc/apidoc-core](https://github.com/apidoc/apidoc-core)
