### ISSUE TITLE
warn: parser plugin 'param' not found in block: 1

### ISSUE THREAD

**Issue by ichenhua** [apidoc/apidoc#672]
$ apidoc -v
verbose: apidoc-generator name: apidoc
verbose: apidoc-generator version: 0.17.6
verbose: apidoc-core version: 0.8.3
verbose: apidoc-spec version: 0.3.0
verbose: run parser
**warn: parser plugin 'param' not found in block: 1**
verbose: parse file: .\api\main.js
**warn: parser plugin 'param' not found in block: 1**
verbose: parse file: .\apidoc\main.js
**warn: parser plugin 'param' not found in block: 1**
verbose: parse file: .\doc\main.js
verbose: parse file: .\myapp\app.js
verbose: run worker
verbose: worker preProcess: apierrorstructure
verbose: worker preProcess: apierrortitle
verbose: worker preProcess: apigroup
verbose: worker preProcess: apiheaderstructure
verbose: worker preProcess: apiheadertitle
verbose: worker preProcess: apiparamtitle

**Comment by rottmann** [comment]
`@apiparam` not `@param`

**Comment by mikefuhan** [comment]
I am having the same warning although I confirmed I am using @apiParam
------
apidoc -v
verbose: apidoc-generator name: apidoc
verbose: apidoc-generator version: 0.17.6
verbose: apidoc-core version: 0.8.3
verbose: apidoc-spec version: 0.3.0
verbose: run parser
verbose: parse file: ./apidoc.js
**warn: parser plugin 'param' not found in block: 1**
verbose: parse file: ./doc/main.js
verbose: run worker
verbose: worker preProcess: apierrorstructure
verbose: worker preProcess: apierrortitle
verbose: worker preProcess: apigroup
verbose: worker preProcess: apiheaderstructure
verbose: worker preProcess: apiheadertitle
verbose: worker preProcess: apiparamtitle
verbose: worker preProcess: apipermission
verbose: worker preProcess: apistructure
verbose: worker preProcess: apisuccessstructure
verbose: worker preProcess: apisuccesstitle
verbose: worker preProcess: apiuse
verbose: worker postProcess: apierrorstructure
verbose: worker postProcess: apierrortitle
verbose: worker postProcess: apigroup
verbose: worker postProcess: apiheaderstructure
verbose: worker postProcess: apiheadertitle
verbose: worker postProcess: apiname
verbose: worker postProcess: apiparamtitle
verbose: worker postProcess: apipermission
verbose: worker postProcess: apisamplerequest
verbose: worker postProcess: apistructure
verbose: worker postProcess: apisuccessstructure
verbose: worker postProcess: apisuccesstitle
verbose: worker postProcess: apiuse
verbose: run filter
verbose: filter postFilter: apierror
verbose: filter postFilter: apiheader
verbose: filter postFilter: apiparam
verbose: filter postFilter: apisuccess
verbose: create dir: doc/
verbose: copy template /usr/local/lib/node_modules/apidoc/template/ to: doc/
verbose: write json file: doc/api_data.json
verbose: write js file: doc/api_data.js
verbose: write json file: doc/api_project.json
verbose: write js file: doc/api_project.js
info: Done.

**Comment by chovy** [comment]
I'm also getting this on a brand new project with only one apidoc block

**Comment by cuda12** [comment]
Had the same issue when I had the output folder within the input folder (if this makes any sense!)

File structure that resulted in the warning:
`myApi/
- api.php
- doc/`
with the command  `$ apidoc -i . -o doc/`

file structure without the warning:
`myApi/
- src/api.php
- doc/`
with the command `$ apidoc -i src/ -o doc/`

**Comment by eyedean** [comment]
Yup, if it happens to read its own output, it bugs with this error.

So in short, you should not have your output folder (`-o {OutputFolder}`) be included in your input folders (`-i {InputFolder}`).

**Comment by thevikasthakur** [comment]
> Yup, if it happens to read its own output, it bugs with this error.
> 
> So in short, you should not have your output folder (`-o {OutputFolder}`) be included in your input folders (`-i {InputFolder}`).

This helped me

**Comment by dozykeys** [comment]
> Yup, if it happens to read its own output, it bugs with this error.
> 
> So in short, you should not have your output folder (`-o {OutputFolder}`) be included in your input folders (`-i {InputFolder}`).

Related to Merlin? @eyedean ....worked like magic. Thanks
