### ISSUE TITLE
How to set "info" popover in apidocs

### ISSUE THREAD

**Issue by lmj0011** [apidoc/apidoc#674]
On the [example page], I see this popover and info icon:

![info_apidocs](https://user-images.githubusercontent.com/9396189/30195319-56c3de7a-941e-11e7-806b-27fb4b698a5c.png)

But there's no where in the documentation about how to add it to an apidoc.

[example page]: http://apidocjs.com/example/

**Comment by ftoulemon** [comment]
Define the permission:
```
"""
@apiDefine myPermission Lorem ipsum...
"""
```

Use it for your API:
```
"""
@api ...
@apiPermission myPermission
"""
```

**Comment by lmj0011** [comment]
what about the popover icon, How do you get that to show?

**Comment by ftoulemon** [comment]
It appears automagically once your permission is defined.

**Comment by lmj0011** [comment]
Ah ok, I try your solution then.

**Comment by lmj0011** [comment]
:+1:  https://github.com/apidoc/apidoc/issues/674#issuecomment-328019688
