### ISSUE TITLE
What is the minimum supported version of node?

### ISSUE THREAD

**Issue by Naktibalda** [apidoc/apidoc#675]
[package.json](https://github.com/apidoc/apidoc/blob/master/package.json#L34) says that it is 0.10,
but apidoc fails on 0.12.18 with 
```
/usr/lib/node_modules/apidoc/node_modules/fs-extra/lib/index.js:3
const assign = require('./util/assign')
^^^^^
SyntaxError: Use of const in strict mode.
```
fs-extra claims that they still support node 4.x
Your .travis.yml only runs tests on node 6.

Please bump the minimum version of node to the one you actually support.

**Comment by rottmann** [comment]
Before it was 0.10, since some contributor pull requests it is 6.x
Not updated in package.json yet.

**Comment by genitrust-bsingh** [comment]
Soooo what version is it?
