### ISSUE TITLE
@apiDeprecated not working

### ISSUE THREAD

**Issue by motoringm** [apidoc/apidoc#676]
Hi Team,
@apiDeprecate is not working for me. Please find the sample block below.

/**    
    * @apiDeprecated use now (#User:getDetails).
    * @api {get} /v1/user/details?email=:email Get user details
    * @apiName Details
    * @apiGroup User
    * @apiVersion 1.0.0
---
*/
I am returning the following warning.
warn: parser plugin 'apideprecated' not found in block: 0

Please help me to fix the error in the above block. Also, how do I link to the same Group and method name with a different version, say v2?

Thanks

**Comment by fengyts** [comment]
Hi Team,
@apideprecate is not working for me too.

**Comment by motoringm** [comment]
It is in the todo list https://github.com/apidoc/apidoc/wiki/ToDo
Might be under development.

**Comment by rottmann** [comment]
Your example work and is ok:

![screenshot-localhost 8080-2017-09-12-11-39-25](https://user-images.githubusercontent.com/381201/30319043-168a17f4-97af-11e7-902d-c55f7e0c4df4.png)

**Comment by motoringm** [comment]
Many thanks @rottmann for your advice.
I think I have to update the apidoc. My current version is  apidoc 0.16.1.

Thanks

**Comment by motoringm** [comment]
@rottmann  I updated to latest version. 
The warning  - warn: parser plugin 'apideprecated' not found in block: 0 - disapperared after the update.
However @apideprecated is not working for me.

  /**
    * @apiDeprecated Please do not use this API
    * 
    * @api {get} /v1/user/details/?name=:vrm Get user details
    * @apiName User Details
    * @apiGroup Get User
    * @apiVersion 1.0.0
---
--
*/
Thanks
