### ISSUE TITLE
[Question] Read documentation from multiple JSON files

### ISSUE THREAD

**Issue by tommelo** [apidoc/apidoc#677]
Is there a way to generate the documentation from multiple JSON files?

Example:

Service 1(Build Phase): apidoc - i src/ -o apidoc (generates **service1.json**)
Service 2(Build Phase): apidoc - i src/ -o apidoc (generates **service2.json**)

Then in the **main.js** I could list and include those files to generate the documentation.

**Comment by rottmann** [comment]
apiDoc generates the doc from all knwon file extensions in a dir, you can include different dirs with:
`apidoc -i src1 -i src2 -i src3`

**Comment by tommelo** [comment]
got it.
I was wondering if I could generate just the JSON file instead of the full page (html, css, js).
I'll change my build strategy, thanks @rottmann
