### ISSUE TITLE
How to make "body" available to put values just like "parameters" ?

### ISSUE THREAD

**Issue by bang** [apidoc/apidoc#678]
Hi! 

First of all, good work! This tool is amazing!

I have some endpoints in my API that requires data sent in the body directly. But I couldn't find something like "@apiParam" nor "@apiParamExample" in such way that the tool generate a "textbox" for the body(for send JSON input, for example) just like happens with "@apiParam" . Looking at the documention I couldn't find a "workaround" to solve that. I thought that maybe you can give me another way or suggestion to solve that. 

Thanks!

**Comment by jachinlin** [comment]
i meet the same problem. this is what i change in the template. https://github.com/apidoc/apidoc/pull/679

**Comment by NicolasCARPi** [comment]
You can try the current `dev` branch: `npm i -g apidoc/apidoc#dev`. See also #999.
