### ISSUE TITLE
behave incorrectly when apiSuccess is complex

### ISSUE THREAD

**Issue by phpcyy** [apidoc/apidoc#682]
```
/**
 * @apiDefine page
 * @apiParam {number} page 页码
 * @apiParam {number} pageSize 每页条数
 * @apiSuccess {number} code 错误码
 * @apiSuccess {string} message 消息
 * @apiSuccess {object} data 数据
 */
...
codes here.
...
/**
 * @api {get} /orders/prices 3、获取订单下的小订单
 * @apiGroup Orders
 * @apiUse page
 *
 * @apiParam {string} orderId 订单id  
 * @apiSuccess {object} data.orderInfo 订单信息
 * @apiSuccess {string} data.orderInfo.name 订单名称
 * @apiSuccess {number} data.orderInfo.cost 订单金额
 * @apiSuccess {string} data.orderInfo.beginTime 开始时间
 * @apiSuccess {string} data.orderInfo.endTime 结束时间
 * @apiSuccess {number} data.orderInfo.status 订单状态，1、待媒介处理，2、执行中，3、已完成，-1、已取消
 * @apiSuccess {object[]} data.list 小订单列表
 * @apiSuccess {string} data.list.id id
 * @apiSuccess {number} data.list.cost 订单金额
 * @apiSuccess {number} data.list.mediaType 媒体类型，1、微信，2、微博
 * @apiSuccess {number} data.list.priceType 价格类型，微信：1、单条，2、头条，3、次条，4、尾条；微博：1、硬广直达，2、硬广转发，3、软广直发，4、软广转发
 * @apiSuccess {number} data.list.status 订单状态，1、待沟通，2、待执行，3、成功，-1、拒单，-2流单
 * @apiSuccess {number} data.list.media 小订单对应的公众号
 * @apiSuccess {number} data.total 小订单总数
 */
```
As you can see, `data.orderInfo` is an object, and `data.list` is an object array, but their children aren't behind their proper parent after I run `apidoc` command.
![image](https://user-images.githubusercontent.com/13944592/30698920-e5d2564e-9f15-11e7-8ec2-428784fdfdb7.png)

**Comment by cnodin** [comment]
i had this problem.May be it's a bug?

**Comment by cyudfd** [comment]
> ```
> /**
>  * @apiDefine page
>  * @apiParam {number} page 页码
>  * @apiParam {number} pageSize 每页条数
>  * @apiSuccess {number} code 错误码
>  * @apiSuccess {string} message 消息
>  * @apiSuccess {object} data 数据
>  */
> ...
> codes here.
> ...
> /**
>  * @api {get} /orders/prices 3、获取订单下的小订单
>  * @apiGroup Orders
>  * @apiUse page
>  *
>  * @apiParam {string} orderId 订单id  
>  * @apiSuccess {object} data.orderInfo 订单信息
>  * @apiSuccess {string} data.orderInfo.name 订单名称
>  * @apiSuccess {number} data.orderInfo.cost 订单金额
>  * @apiSuccess {string} data.orderInfo.beginTime 开始时间
>  * @apiSuccess {string} data.orderInfo.endTime 结束时间
>  * @apiSuccess {number} data.orderInfo.status 订单状态，1、待媒介处理，2、执行中，3、已完成，-1、已取消
>  * @apiSuccess {object[]} data.list 小订单列表
>  * @apiSuccess {string} data.list.id id
>  * @apiSuccess {number} data.list.cost 订单金额
>  * @apiSuccess {number} data.list.mediaType 媒体类型，1、微信，2、微博
>  * @apiSuccess {number} data.list.priceType 价格类型，微信：1、单条，2、头条，3、次条，4、尾条；微博：1、硬广直达，2、硬广转发，3、软广直发，4、软广转发
>  * @apiSuccess {number} data.list.status 订单状态，1、待沟通，2、待执行，3、成功，-1、拒单，-2流单
>  * @apiSuccess {number} data.list.media 小订单对应的公众号
>  * @apiSuccess {number} data.total 小订单总数
>  */
> ```
> 
> As you can see, `data.orderInfo` is an object, and data.list is and object array, but their childs aren't behind their proper parent after I run `apidoc` command.
> ![image](https://user-images.githubusercontent.com/13944592/30698920-e5d2564e-9f15-11e7-8ec2-428784fdfdb7.png)

I'm also facing the same issue.
My current workaround is to separate the object in its own `(group)`.

**Comment by NicolasCARPi** [comment]
You can try the current `dev` branch: `npm i -g apidoc/apidoc#dev`. See also #999.
