### ISSUE TITLE
Ability to hide deprecated endpoints

### ISSUE THREAD

**Issue by KieranP** [apidoc/apidoc#683]
@apidoc @rottmann This is a fantastic tool. So firstly, thank you for creating it :-)

We have a lot of older versions of endpoints that have been replaced with newer versioned endpoints. We have tagged them as @apiDeprecated and it tags them as such, but after a while, all the deprecated endpoints clog up the page. So an option to hide all deprecated endpoints would be really handy.

**Comment by bato3** [comment]
You can use: [@apiIgnore](http://apidocjs.com/#param-api-ignore) or @apiPrivate

But I propose strike titles for deprecated methods on list
