### ISSUE TITLE
Integrating Extra Html into Documentation Perfect way

### ISSUE THREAD

**Issue by jaiminmoslake7020** [apidoc/apidoc#686]
I want to add dynamic data which can be got from a REST API in json format and add extra HTML at end of a page. and add a link in Navbar at the end or top.

Way I think I have.

1.  Integrate into index.html add my component wherever I want to add it. But it is important that it does not remove my changes when I update all documentation means I run command.

apidoc -i  RESOURCE_PATH -o DESTINATION_PATH 

It should not have to change index.html and remove my content.

2. Create another new HTML file [let's assume it is error_status.html] in the same folder as DESTINATION_PATH and my html component that and load your layout with navbar. But when  i 

apidoc -i  RESOURCE_PATH -o DESTINATION_PATH 

It should not remove N.html and remove my error_status.html.

3. Put a link in header or footer and create my content file outside of the DESTINATION_PATH.

What will be good idea to implement it.

**Comment by NicolasCARPi** [comment]
You could also have some sort of script that does the change you want after the apidoc has run.
