### ISSUE TITLE
Symlinked folders are ignored by apidoc

### ISSUE THREAD

**Issue by henhal** [apidoc/apidoc#687]
Hi,

So I have two API:s that share a lot of `@apiDefine` and such, so I put all these in a few files in a common folder. Then, from my two API directories I symlinked the common directory. However, I noticed that apidoc seems to skip all files in symlinked directories?

Directory structure:

```
./common/common_definitions.js
./my_api/my_api1.js
./my_api/my_api2.js
./my_other_api/my_other_api1.js
./my_other_api/my_other_api2.js

```
1. Example that does not work:

```
$ cd my_api
$ ln -s ../common
$ ls -l

common -> ../common
my_api1.js
my_api2.js

$ apidoc

error: Referenced groupname does not exist / it is not defined with @apiDefine.
```

2. If I symlink each individual file inside the common directory, it works fine:

```
$ cd my_api
$ ln -s ../common/common_definitions.js
$ ls -l

common_definitions.js -> ../common/common_definitions.js
my_api1.s
my_api2.js

$ apidoc
info: Done.
```

3. If I *copy* the common directory, it also works fine.

```
$ cd my_api
$ cp -R ../common .
$ ls -l

common
my_api1.js
my_api2.js

$ apidoc
info: Done.
```

Since I have multiple files in my common directory, I do not want to rely on symlinking each individual file. Duplicating the common directory obviously also defeats the purpose of extracting common code. 

My two workarounds are currently either 1) create a wrapper script around `apidoc `that temporarily copies the common files, or 2) run apidoc on the parent directory containing both my API:s and the common files, and to use the `-e` flag to exclude the API I am NOT generating docs for, but this is also not very nice...

```
$ ls -l

common
my_api
my_other_api

$ apidoc -c my_api -e my_other_api -o my_api/doc
$ apidoc -c my_other_api -e my_api -o my_other_api/doc

```

Is there a way to get directory symlinks working?

**Comment by pereiradiogo** [comment]
Any solution for this?

**Comment by NicolasCARPi** [comment]
From what I could gather, it seems the [core lib is using the klaw-sync lib to find files](https://github.com/apidoc/apidoc-core/blob/master/lib/utils/find_files.js#L65). And I could not find anything about following symlinks in this library.

So I'm closing this issue since there is nothing that can be done here (except maybe changing the library to find files...).
