### ISSUE TITLE
How to post an array of string in the parameter input

### ISSUE THREAD

**Issue by UnKn0wn27** [apidoc/apidoc#689]
I tried something like this: 
`@apiParam {String[]} arrstrInsert array of string`

But it only takes one parameter, inserting something like this:

> "str1", "str2"

Will give me this:

> "\"str1\", \"str2\""

How can go over this issue?

**Comment by bato3** [comment]
Why you write here. This is app for generate API documentation. 

How can I not know something as simple as sending arrays using HTTP?

`&arrstrInsert[]=str1&arrstrInsert[]=str2`
