### ISSUE TITLE
Problem with special characters

### ISSUE THREAD

**Issue by carlosscheffer** [apidoc/apidoc#690]
I'm having problems with special characters.

As below.

![usuario](https://user-images.githubusercontent.com/31517030/31348330-aee9b47c-acf5-11e7-8a14-8ab5891d4023.png)

>    /**
>      * @api {get} /:empresa/usuario Buscar todos Usuários
>      * @apiName listarUsuarios
>      * @apiGroup Usuário
>      */

**Comment by GnanaprakashChandiran** [comment]
Same issues occurs to me

**Comment by mustafaerguven** [comment]
Same issue as #282

**Comment by NicolasCARPi** [comment]
Support for special characters will come in a future release (hopefully).

**Comment by NicolasCARPi** [comment]
Should be fixed with upcoming version ;)
