### ISSUE TITLE
@apiParam File

### ISSUE THREAD

**Issue by stanislav-web** [apidoc/apidoc#691]
Hi, everyone!
How do i describe "for examle" for @apiParam File upload ?

**Comment by alex-zhang** [comment]
+1

**Comment by bato3** [comment]
-1

HTTP protocol has standard for sending files: [rfc1867](https://tools.ietf.org/html/rfc1867), so if you want this in this format you describe this as: `@apiparam {File} upload Form-based File Upload in HTML`.

If you want send file content write: `@apiparam {Binnary} upload File content`

**Comment by bato3** [comment]
see: https://github.com/apidoc/apidoc/issues/691

**Comment by Naktibalda** [comment]
Existing pull request #521

**Comment by NicolasCARPi** [comment]
See @bato3's answer.
