### ISSUE TITLE
[proposal] @apiDev

### ISSUE THREAD

**Issue by SpareShade** [apidoc/apidoc#693]
Hi!
Thank you for this great tool!!!

How about introducing @apiDev annotation that would allow placing a label about the dev status and note for the given api point/function?

I am using apidoc to first outline and define the api, and then start building.

Such annotation would be great to get a quick overview of what is complete, in progress, etc.

**Comment by dericcain** [comment]
@SpareShade What you could do is use HTML inside of your comments. For instance, you could do something like this...

```php
/*
 * @apiDescription This endpoint handles authenticating the user. We are using Oauth2 in order to 
 authenticate users. We are using the Password Grant method, which does not have any callbacks 
 and acts very similar to a normal login with username and password. A successful request will 
 return a response with an access token which is required to make all subsequent API calls. With 
 that said, be sure and store the <code>access_token</code> received in the response so that it 
 can be attached to the header in order to authorize all future requests.
 * <blockquote><a href="https://www.oauth.com/oauth2-servers/access-tokens/password-grant/" target="_blank">Read more about Oauth2 Password Grant</a></blockquote>
 * The <code>access_token</code> is a long-lived token and has an expiration of 365 days, so there is no need in refreshing the tokens.
*/
```
For me, the `blockquote` is parsed as HTML and I end up with a nicely formatted comment that stands out a bit.

![screen shot on 2017-10-24 at 08 22 37](https://user-images.githubusercontent.com/9561913/31945358-96c9c62a-b894-11e7-8dd9-79231076a05a.png)

This could be used as a workaround for what you are attempting to do.

**Comment by SpareShade** [comment]
@dericcain Thank you for the response. Yeah, its great that apidoc is quite flexible in that it allows you to use simple html elements (bootstrap is your friend too); you can even customise the template itself.

I thought that the @apiDev, beside the html markup, could also be used to export segments of the api documentation based on the @apiDev status (ie. similar to what you can now do with @apiPrivate).

but its just an idea ...

**Comment by bato3** [comment]
Or  support for `@TODO`. 

BTW: you can use `@TODO` and check it by other tools

**Comment by NicolasCARPi** [comment]
If this is still needed, please open a PR to add this new tag.
