### ISSUE TITLE
[proposal] Extend version format

### ISSUE THREAD

**Issue by andrdru** [apidoc/apidoc#696]
In some cases semver format is not enough
It would be great to set api version as text value like "dev" or "coolFeature"
UPD and yes, this software rocks! thank you!

**Comment by NicolasCARPi** [comment]
apidoc uses semver for parsing and "dev" won't validate. I tried removing the validation test: https://github.com/apidoc/apidoc-core/blob/master/lib/parsers/api_version.js#L13-L15

but now it's the `semver` library throwing an error:

~~~
{"message":"Invalid Version: dev","level":"error"}
~~~

Feel free to propose a PR for this change if you really need that feature.
