### ISSUE TITLE
How to set language forever in apidoc？ There was a problem when I use wkhtmltopdf

### ISSUE THREAD

**Issue by TGhoul** [apidoc/apidoc#697]
**This is my HTML page.**
![1509676650 1](https://user-images.githubusercontent.com/14310807/32358710-44de2292-c083-11e7-9601-9df3f1bc8a69.jpg)

**This is use wkhtmltopdf generate pdf file**
![1509676575 1](https://user-images.githubusercontent.com/14310807/32358720-597e5b7c-c083-11e7-9ab6-98f70ff23df5.jpg)

**I think this is a language problem,pdf converter don't recognize the dynamic transformation of language**

**Comment by bato3** [comment]
In `apidoc.json` set: 

 ```
{ "template": {
      "forceLanguage": "pl"
}
}
```

**Comment by NicolasCARPi** [comment]
That is probably because the way the page is generated with handlebars.js, it won't work fine with pdf. But exporting in pdf would be a good feature to have though.
