### ISSUE TITLE
Format apiSuccess as a json object

### ISSUE THREAD

**Issue by glalaj** [apidoc/apidoc#705]
In most of the APIs we are documenting, the response is a json object.  
I am trying to figure out how to format these Json's into an easily-readable fashion. For example, what I want is:
```
{
    "status": 200,
    "message": "Updated successfully",
    "details":  "Settings for user e.smith where updated successfully"
}
```

What is get is:
{"status": 200, "message": "Updated successfully", "details":  "Settings for user e.smith where updated successfully" }

Currently I can ensure an intermediate formatting by adding extra newlines between each line. This is what the comments would look like: 

```
* @apiSuccess (200) {Object} message {
*
*   "status": 200,
*
*  "message": "Updated successfully",
*
*   "details":  "Settings for user e.smith where updated successfully"
*
*  }
```

However, there are 2 issues:

1. Adding these extra lines makes the documentation in the code rather long.
2. In case that the Json object is nested (which happens most of the time), I can't figure out how to achieve indentation

I think this may be related to #704 (with the difference that they are formatting the request while I am formatting the response)

**Comment by NicolasCARPi** [comment]
This is done now.
