### ISSUE TITLE
How to generate popover like in the example

### ISSUE THREAD

**Issue by bennesp** [apidoc/apidoc#708]
In the example there is a popover but it's not explained how to generate it, and I can't figure out through the source. Is someone aware of how to do it?

The popover I am talking about is this:

![https://image.ibb.co/dOz9nc/Schermata_2018_02_21_alle_22_45_28.png](https://image.ibb.co/dOz9nc/Schermata_2018_02_21_alle_22_45_28.png)

Thanks

**Comment by d-sko** [comment]
Hello... a little late but here is how you do this:

1. add a `@apiDefine` for the Permission:
```
/**
 * @apiDefine admin Admin access rights needed.
 * Optionally you can write her further informations about the permission.
 */
```
2. add it tho the route documentation
```
/**
 * [...]
 * @api {get} /user/:id
 * @apiPermission admin
 * [...]
 */
```
