### ISSUE TITLE
 parser plugin 'apiprivate' not found in block: 4

### ISSUE THREAD

**Issue by nbrouka** [apidoc/apidoc#711]
While generating doc for my API, I recieve the following warning :

parser plugin 'apiprivate' not found in block: 4

What does it mean?

**Comment by ehallander9591** [comment]
FYI, this began showing up in my usage as well

/**
 * @api {PUT} SYSTEM_MISSION_SAVE SYSTEM_MISSION_SAVE-130
 * @apiPrivate
 * @apiName SYSTEM_MISSION_SAVE
 * @apiHeader {string} authorization Bearer {Your authentication token pasted here}
 * @apiDescription Save the current mission
 * @apiSampleRequest off
 * @apiGroup System
 *
 * @apiVersion 2.0.0
 *
 * @apiParam (Request) {reqrsp.RequestType} requestType Must be <a href="../protobuf/mpxs.reqrsp.html#.SYSTEM_MISSION_SAVE">SYSTEM_MISSION_SAVE</a>
 * @apiParam (Request) {int32} [requestId] Client provided ID returned in Response.requestId field
 * @apiSuccess (Response) {reqrsp.Status} status SUCCESS  The Request was processed successfully
 * @apiSuccess (Response) {int32} requestId The Request ID from the Request object
 *
 * @apiError (ErrorCode) {reqrsp.ErrorCode} INVALID_PLANNING_STATE  The request is not supported for the current PlanningState
 * @apiError (ErrorCode - Common) {reqrsp.ErrorCode} SERVICE_UNAVAILABLE  The Planning Service Engine is currently unavailable
 * @apiError (ErrorCode - Common) {reqrsp.ErrorCode} AUTH_INVALID_TOKEN  The Request was made with an invalid or expired token
 * @apiError (ErrorCode - Common) {reqrsp.ErrorCode} AUTH_CREDENTIALS_REQUIRED  The Request was made without a token
 * @apiError (ErrorCode - Common) {reqrsp.ErrorCode} AUTH_CREDENTIALS_BAD_FORMAT  The Request was made with an improperly formatted token
 * @apiError (ErrorCode - Common) {reqrsp.ErrorCode} AUTH_CREDENTIALS_BAD_SCHEME  The Request Header does not contain "authorization: Bearer + {valid token}"
 * @apiError (ErrorCode - Common) {reqrsp.ErrorCode} AUTH_REVOKED_TOKEN  The Request was made with a revoked token
 * @apiError (ErrorCode - Common) {reqrsp.ErrorCode} AUTH_REVOKED_TOKEN  The Request was made with a revoked token
 * @apiError (ErrorCode - Common) {reqrsp.ErrorCode} WRONG_CONTEXT_FOR_COMMAND  The MissionContext that is provided is the wrong context for the command requested.
 */

**Comment by moyara** [comment]
I had same issue. Figured out that @apiPrivate only works on the top of comment block.
Try moving @apiPrivate up and it works.

**Comment by bradleypeabody** [comment]
I have the same issue, nothing has resolved it.  I've tried putting @apiPrivate at various places in the block (top, just below @api and at bottom), makes no difference.

Minimal reproducable example:

```
// src/test1.go
package test

import "net/http"

type InternalAPIHandler struct {}

func (h *InternalAPIHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	/**
	 * @api {get} /internal-test1/:id Testing
	 * @apiPrivate
	 * @apiName InternalTest
	 * @apiGroup Internal
	 */
}
```

Command: `apidoc --debug --private true -i src/ -o doc/`

Output:
```
debug: package.json not found!
debug: apidoc.json not found!
warn: Please create an apidoc.json configuration file.
verbose: apidoc-generator name: apidoc
verbose: apidoc-generator version: 0.17.6
verbose: apidoc-core version: 0.8.3
verbose: apidoc-spec version: 0.3.0
debug: No plugins found.
debug: load parser language: .clj, ./languages/clj.js
debug: load parser language: .coffee, ./languages/coffee.js
debug: load parser language: .erl, ./languages/erl.js
debug: load parser language: .ex, ./languages/ex.js
debug: load parser language: .exs, ./languages/ex.js
debug: load parser language: .litcoffee, ./languages/coffee.js
debug: load parser language: .lua, ./languages/lua.js
debug: load parser language: .pl, ./languages/pm.js
debug: load parser language: .pm, ./languages/pm.js
debug: load parser language: .py, ./languages/py.js
debug: load parser language: .rb, ./languages/rb.js
debug: load parser language: default, ./languages/default.js
debug: load parser: api, ./parsers/api.js
debug: load parser: apidefine, ./parsers/api_define.js
debug: load parser: apidescription, ./parsers/api_description.js
debug: load parser: apierror, ./parsers/api_error.js
debug: load parser: apierrorexample, ./parsers/api_error_example.js
debug: load parser: apiexample, ./parsers/api_example.js
debug: load parser: apiheader, ./parsers/api_header.js
debug: load parser: apiheaderexample, ./parsers/api_header_example.js
debug: load parser: apigroup, ./parsers/api_group.js
debug: load parser: apiname, ./parsers/api_name.js
debug: load parser: apiparam, ./parsers/api_param.js
debug: load parser: apiparamexample, ./parsers/api_param_example.js
debug: load parser: apipermission, ./parsers/api_permission.js
debug: load parser: apisuccess, ./parsers/api_success.js
debug: load parser: apisuccessexample, ./parsers/api_success_example.js
debug: load parser: apiuse, ./parsers/api_use.js
debug: load parser: apiversion, ./parsers/api_version.js
debug: load parser: apisamplerequest, ./parsers/api_sample_request.js
debug: load parser: apideprecated, ./parsers/api_deprecated.js
debug: load worker: apierrorstructure, ./workers/api_error_structure.js
debug: load worker: apierrortitle, ./workers/api_error_title.js
debug: load worker: apigroup, ./workers/api_group.js
debug: load worker: apiheaderstructure, ./workers/api_header_structure.js
debug: load worker: apiheadertitle, ./workers/api_header_title.js
debug: load worker: apiname, ./workers/api_name.js
debug: load worker: apiparamtitle, ./workers/api_param_title.js
debug: load worker: apipermission, ./workers/api_permission.js
debug: load worker: apisamplerequest, ./workers/api_sample_request.js
debug: load worker: apistructure, ./workers/api_structure.js
debug: load worker: apisuccessstructure, ./workers/api_success_structure.js
debug: load worker: apisuccesstitle, ./workers/api_success_title.js
debug: load worker: apiuse, ./workers/api_use.js
debug: load filter: apierror, ./filters/api_error.js
debug: load filter: apiheader, ./filters/api_header.js
debug: load filter: apiparam, ./filters/api_param.js
debug: load filter: apisuccess, ./filters/api_success.js
verbose: run parser
debug: inspect file: src/test1.go
debug: size: 272
debug: count blocks: 1
debug: count elements in block 0: 3
debug: api found in block: 0
debug: found @api in block: 0
warn: parser plugin 'apiprivate' not found in block: 0
debug: found @apiGroup in block: 0
verbose: parse file: src/test1.go
verbose: run worker
verbose: worker preProcess: apierrorstructure
verbose: worker preProcess: apierrortitle
verbose: worker preProcess: apigroup
verbose: worker preProcess: apiheaderstructure
verbose: worker preProcess: apiheadertitle
verbose: worker preProcess: apiparamtitle
verbose: worker preProcess: apipermission
verbose: worker preProcess: apistructure
verbose: worker preProcess: apisuccessstructure
verbose: worker preProcess: apisuccesstitle
verbose: worker preProcess: apiuse
verbose: worker postProcess: apierrorstructure
verbose: worker postProcess: apierrortitle
verbose: worker postProcess: apigroup
verbose: worker postProcess: apiheaderstructure
verbose: worker postProcess: apiheadertitle
verbose: worker postProcess: apiname
verbose: worker postProcess: apiparamtitle
verbose: worker postProcess: apipermission
verbose: worker postProcess: apisamplerequest
verbose: worker postProcess: apistructure
verbose: worker postProcess: apisuccessstructure
verbose: worker postProcess: apisuccesstitle
verbose: worker postProcess: apiuse
verbose: run filter
verbose: filter postFilter: apierror
verbose: filter postFilter: apiheader
verbose: filter postFilter: apiparam
verbose: filter postFilter: apisuccess
verbose: create dir: doc/
verbose: copy template /usr/local/lib/node_modules/apidoc/template/ to: doc/
verbose: write json file: doc/api_data.json
verbose: write js file: doc/api_data.js
verbose: write json file: doc/api_project.json
verbose: write js file: doc/api_project.js
info: Done.
```

**Comment by anthony-dallagnola** [comment]
I'm having the same issue but I found a way to generate the doc. As moyara suggested, the apiPrivate must be on top but there are a few mandatory annotations.
@apiVersion
@api 
@apiGroup
With these and apiPrivate on top the warn is still here but the doc is generated.

**Comment by mikacalvo** [comment]
⚠️ you wrote @APIGroup and not @apiGroup, that's not the issue but still 😂 
I have the warning as well, interested in the resolution

**Comment by mbush92** [comment]
Looking at api-core there is no parser for apiPrivate, so even though the docs generate, I think that it will always generate the doc even with `--private false`

This is the parser object definition in index.js in the api-core repo.

`parsers: {
    api: "./parsers/api.js",
    apidefine: "./parsers/api_define.js",
    apidescription: "./parsers/api_description.js",
    apierror: "./parsers/api_error.js",
    apierrorexample: "./parsers/api_error_example.js",
    apiexample: "./parsers/api_example.js",
    apiheader: "./parsers/api_header.js",
    apiheaderexample: "./parsers/api_header_example.js",
    apigroup: "./parsers/api_group.js",
    apiname: "./parsers/api_name.js",
    apiparam: "./parsers/api_param.js",
    apiparamexample: "./parsers/api_param_example.js",
    apipermission: "./parsers/api_permission.js",
    apisuccess: "./parsers/api_success.js",
    apisuccessexample: "./parsers/api_success_example.js",
    apiuse: "./parsers/api_use.js",
    apiversion: "./parsers/api_version.js",
    apisamplerequest: "./parsers/api_sample_request.js",
    apideprecated: "./parsers/api_deprecated.js"
  },`

**Comment by SebHoremans** [comment]
By default private APIs will be ignored. To include private APIs add --private attribute to command line.
Exemple to create a full doc with private and non-private APIs : apidoc -o private-doc --private
Exemple to create a "public" doc with only non-private APIs : apidoc -o public-doc

**Comment by NicolasCARPi** [comment]
Continuation on #744
