### ISSUE TITLE
nomnom@1.8.1: Package no longer supported

### ISSUE THREAD

**Issue by Jimbolino** [apidoc/apidoc#715]
deprecation notice
Nomnom is deprecated. Check out https://github.com/tj/commander.js, which should have most, if not all of the capability that nomnom had. Thank you!

https://github.com/harthur/nomnom

https://www.npmjs.com/package/nomnom

**Comment by younes0** [comment]
in the meantime, you can ignore this warning to install the package:
`npm_config_loglevel=silent npm install apidoc`

**Comment by manishsaraan** [comment]
I have already merged the pr #752 which replaces nomnom  with commander but i dont have publish npm package permission. 
Let me ask rottmann for permission.

**Comment by romain-faust** [comment]
@manishsaraan any news on this ?

**Comment by manishsaraan** [comment]
I got the npm token but i am unable to publish with it. Will publish as soon as i get it working.

**Comment by romain-faust** [comment]
Ok, thank you :)

**Comment by manishsaraan** [comment]
apidoc npm package updated with version@0.17.7
