### ISSUE TITLE
[Meta] Is apidoc being maintained anymore?

### ISSUE THREAD

**Issue by lmj0011** [apidoc/apidoc#717]
Is there anyone maintaining this repo anymore?

Last commit was almost a year ago, seems to be abandoned. https://github.com/apidoc/apidoc/commit/ae652811ca1ca71293291c3eb9747a932310265e

see: https://github.com/apidoc/apidoc/issues/532

**Comment by lmj0011** [comment]
Can anyone suggest an active fork of this repo?

**Comment by rottmann** [comment]
Let me know too, i am searching for an active Maintainer too.
