### ISSUE TITLE
when I input 2 to id I want to get url like '/test/2'  but I have been got '/test?id=2'

### ISSUE THREAD

**Issue by wangle201210** [apidoc/apidoc#718]
/**
     *  @api {get} test/:id getArticle
     *  @apiVersion 0.0.1
     *  @apiGroup test
     *  @apiName test_article_get
     *  @apiParam {Number} id Users unique ID.
     *  @apiSampleRequest test
    */    
when I input 2 to id I want to get url like '/test/2'  but I have been got '/test?id=2'
how can i do?

**Comment by NicolasCARPi** [comment]
use @apiQuery
