### ISSUE TITLE
html to pdf

### ISSUE THREAD

**Issue by kingmayko** [apidoc/apidoc#720]
I use the html-pdf to convert index.html to pdf, but always showing loading, has any options of apidoc to avoid this.

**Comment by KantarBruceAdams** [comment]
I have just started using [wkhtmltopdf](https://wkhtmltopdf.org) for this. It works but there is one annoying caveat. Because the documentation is rendered via javascript I have to run the command with a delay of 2s to allow it to load even for a hello world complexity document. For example:

    wkhtmltopdf --javascript-delay 2000 index.html helloWorld.pdf
