### ISSUE TITLE
https to Http server, or HTTP to HTTPS server

### ISSUE THREAD

**Issue by ptrnov** [apidoc/apidoc#721]
was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint.
This request has been blocked; the content must be served over HTTPS.

can use both http & https.

**Comment by poju0424** [comment]
If you want to serve both 80 and 443 port, just use Nginx

**Comment by ptrnov** [comment]
I've tried several ways with
Content-Security-Policy-Report-Only: default-src https: 'unsafe-inline' 'unsafe-eval'; 
I'm not sure the problem is, from webservis, can you give me some ideas for enlightenment before I move to service Ngeink

**Comment by ptrnov** [comment]
apakah ini benar ? please check the link https://github.com/spree/spree/issues/8165

**Comment by ptrnov** [comment]
Is this true ? please check the link https://github.com/spree/spree/issues/8165

**Comment by NicolasCARPi** [comment]
Hello,

All requests are loaded through HTTPS now.
