### ISSUE TITLE
Nested param

### ISSUE THREAD

**Issue by flaviolpgjr** [apidoc/apidoc#725]
Hi, I'm trying to build the following structure, but I'm not getting success:

{
          "inhabitant": {
          "name": "Gabriel test",
          "email": "pre@gmail.com",
          "password": "abc123",
          "cpf": "98672252284",
          "birthday": "1989-10-21",
          "facebook_id": "89",
          "terms": true
        }
}

@apiParam (inhabitant) {String} inhabitant.name User name.
      @apiParam (inhabitant) {String} inhabitant.email User email.
      @apiParam (inhabitant) {String} inhabitant.password User password, is mandatory when facebook id is not passed.
      @apiParam (inhabitant) {String} inhabitant.cpf Cpf of the user.
      @apiParam (inhabitant) {String} inhabitant.birthday Birth of the user.
      @apiParam (inhabitant) {String} inhabitant. [facebook_id] User id of the user, it is only passed when the user will log in with facebook.
      @apiParam (inhabitant) {Boolean = true, false} inhabitant.terms Whether the user accepts the terms of use or not.
the parameters are coming to me, like this:

 {"inhabitant.name" => "", "inhabitant.birthday" => "", "inhabitant.password" => "", "inhabitant.cpf" => , "inhabitant." => "inhabitant.terms" => "", "controller" => "auth / users", "action" => "register"}

Thank you very much in advance.

**Comment by mrvini** [comment]
you would need to add someting like this before  you define your object details
```@apiparam (inhabitant) {object} inhabitant```

**Comment by flaviolpgjr** [comment]
I got a different friend


      @apiParam (inhabitant) {String} inhabitant [name] Username.
      @apiParam (inhabitant) {String} inhabitant [email] User email.
      @apiParam (inhabitant) {String} inhabitant [password] User password is mandatory when facebook id is not passed.
      @apiParam (inhabitant) {String} inhabitant [cpf] Cpf of the user.
      @apiParam (inhabitant) {String} inhabitant [birthday] Birth of the user.

But anyway, thanks for the help.
