### ISSUE TITLE
Has anyway to support #id number reference in url?

### ISSUE THREAD

**Issue by cuongnv-ibl** [apidoc/apidoc#733]
With 
http://apidocjs.com/example_basic/#api-User-GetUser
http://apidocjs.com/example_basic/#api-User-CreateUser

also Support #id number
http://apidocjs.com/example_basic/#1
http://apidocjs.com/example_basic/#2

**Comment by rottmann** [comment]
Currently not, in a new template the whole anchor management must be rebuild.
