### ISSUE TITLE
parser plugin 'param' not found in block: 1

### ISSUE THREAD

**Issue by densolomon** [apidoc/apidoc#734]
While generating doc for my API, I recieve the following warning :

parser plugin 'param' not found in block: 1

What does it mean?

**Comment by dev-aitch** [comment]
hello @densolomon, I have same issue, did you overcome this issue ?

**Comment by cncal** [comment]
Some codes like `@param`  might exist in your `-i` path.

**Comment by NicolasCARPi** [comment]
See #707
