### ISSUE TITLE
Can we have multiple apidefine in single document?

### ISSUE THREAD

**Issue by Nitin-ProductManager** [apidoc/apidoc#737]
Hi,

I have been using your tool and have nicely put all my APIs in order.
Problem is I have multiple groups & each group name have space & characters in them.
The issue is resolved by @apiDefine (it looks really nice with this) but it seems I can only use it once.

Is there a workaround?

**Comment by rottmann** [comment]
You can define as much as you want, but each block kann have only one define.
Spaces/special chars in Names are not allowed.
