### ISSUE TITLE
 Error 0:  undefined

### ISSUE THREAD

**Issue by YeDongaidiiqu** [apidoc/apidoc#740]
when  the api response 400 ,the html is dispaly  Error 0:  undefined
the api response is below
`
http status 400
{
         code:1,
         msg:"params error" 
}
`
![qq 20180815095734](https://user-images.githubusercontent.com/25131877/44127820-b834eff4-a071-11e8-9354-75727037b9fd.png)
![qq 20180815095754](https://user-images.githubusercontent.com/25131877/44127821-b889f044-a071-11e8-9a99-c9f153654e73.png)
![qq 20180815100225](https://user-images.githubusercontent.com/25131877/44127922-5d38f130-a072-11e8-8a67-d19a514e908c.png)

**Comment by NicolasCARPi** [comment]
This behavior seems no longer present. Please try the latest version.
