### ISSUE TITLE
Api auto numering

### ISSUE THREAD

**Issue by vishnu-220** [apidoc/apidoc#743]
**Please add some configurable feature (like 1-100,a-z,A-Z,i-x) for auto numbering the api's.It is really hard to manually number them each time i change something.**

**Comment by rottmann** [comment]
apiDoc did not know what you want to increment, major, minor, patch,.... ?

You can write a little helper script that runs before you deploy you docs.
Example increment the minor version:

```js
const semver = require('semver')
const fs = require('fs')

let apiProjectJson = require('./api_project.json')
apiProjectJson.version = semver.inc(apiProjectJson.version, 'minor')

fs.writeFileSync('./api_project.json', JSON.stringify(apiProjectJson, null, 2), 'utf8')
```
