### ISSUE TITLE
warn: parser plugin 'apiprivate' not found in block: 1

### ISSUE THREAD

**Issue by jason-gao** [apidoc/apidoc#744]
I upgrade version to 0.17.5,but when I using @apiPrivate in doc, then has an error:warn: parser plugin 'apiprivate' not found in block: 1,why? when I upgraded, origin sort sames not work,why?

**Comment by mbush92** [comment]
I'm having the same issue, do not see a api_private.js file in the parser folder.  Also, noticed that there is not a parser file for apiIgnore.

**Comment by byted** [comment]
Same here - it's in the documentation but not in the code

**Comment by SebHoremans** [comment]
Same problem. here, the documentation and the modification in [the commit](https://github.com/apidoc/apidoc/commit/87f826e003f88be3a25c38454b08350bdaafdc26) are in the release but this is not enough.
We can not use apidoc anymore because our private routes documentation is now public

**Comment by SebHoremans** [comment]
Ok found out how to use it  the doc is not correct :
By default private APIs will be ignored. To include private APIs add --private attribute to command line.
Exemple to create a full doc with private and non-private APIs : apidoc -o private-doc --private
Exemple to create a "public" doc with only non-private APIs : apidoc -o public-doc

**Comment by NicolasCARPi** [comment]
Indeed the @apiPrivate flag doesn't seem to work and there is no parser for it nor any code in the template related to it AFAIK.

**Comment by eiipaw** [comment]
**_Temporary solution:_**

If i set **@apiPrivate true**
example:

`/**`
`* @apiPrivate true`
`* @api {delete} /user/:id Delete user`
`...`

and run
`apidoc -i ./docs -o /apidoc/public/`

and after that

`apidoc -i ./docs -o /apidoc/private/ --private=true`

I still get error BUT when I open public/index.html I dont see those marked as private and I see them in private/index.html

**Comment by NicolasCARPi** [comment]
This should be fixed by https://github.com/apidoc/apidoc-core/pull/81
