### ISSUE TITLE
Duplicate content

### ISSUE THREAD

**Issue by myu** [apidoc/apidoc#745]
![20180917160356](https://user-images.githubusercontent.com/181074/45611834-77f05c80-ba93-11e8-8c61-8f9d91861567.png)
![20180917160420](https://user-images.githubusercontent.com/181074/45611838-7cb51080-ba93-11e8-81ed-362b8c9765e9.png)

**Comment by myu** [comment]
> @myu can you provide more info. How can i reproduce this issue?
when I publish to web host, and open with a domain, the content duplicate once.  It also review in offical example , also this:
http://apidocjs.com/example/

**Comment by NicolasCARPi** [comment]
Not reproducible.
