### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by 8zler** [apidoc/apidoc#746]
Hi,

Freshly using it ! 

Is it possible to make the default template responsive ?

I'm using on package.json : 

```
"apidoc": {
    "template.forceLanguage": "en",
etc....
}
```

But it doesn't force the language to english :(

Thanks in advance !

nice work btw

**Comment by NicolasCARPi** [comment]
Use:

~~~json
"template": {
    "forceLanguage": "en"
}
~~~
