### ISSUE TITLE
List already defined errors, types etc

### ISSUE THREAD

**Issue by Seluj78** [apidoc/apidoc#748]
I cannot find anywhere on the website or on the repositories the already defined `errors`, `types` etc... There is a few examples on the website, for example for the types:

```
Return type, e.g. {Boolean}, {Number}, {String}, {Object}, {String[]} (array of strings), ... 
```
But i cannot find all the options possible.

**Comment by RafaelGuo** [comment]
I think you can define your return type freely.

**Comment by NicolasCARPi** [comment]
None are hardcoded, it's free use.

**Comment by Seluj78** [comment]
Thanks for the late reply ! 😄  I will keep that in mind in the future
