### ISSUE TITLE
About version compare mark

### ISSUE THREAD

**Issue by iuShu** [apidoc/apidoc#753]
For example:
1. Initialize apidoc with @apiVerion 1.0.0 and contains 10 methods
2. Modified 3 methods and then change version to @apiVersion 1.0.1
3. Current version select 1.0.1 and click "Compare all with predecessor" and mark 3 modified methods 
    with green bar.
4. Keep developing and modify other 2 methods and change version to @apiVersion 1.0.2 
5. Now current version select 1.0.2, as i click "Compare all with predecessor", it will mark 5 modified 
    methods (3 from 1.0.1 and 2 from 1.0.2) with green bar  

What i need is only show me the diff between 1.0.1 and 1.0.2, instead of 1.0.0 to 1.0.2.
Does it available in apidoc ?

**Comment by nivance** [comment]
I seem to have the same problem， how to solve it ?

![apidoc](https://user-images.githubusercontent.com/3291404/51972594-b7ee3400-24b6-11e9-9993-0eba92efa8d2.jpg)
