### ISSUE TITLE
Dynamic Variables in Comment Block

### ISSUE THREAD

**Issue by orcunkobal** [apidoc/apidoc#758]
Hi all,

Is there a way to use the dynamic variable in the comment block?

For example;

I want to define a variable in apidoc.js file, then I want to use in the comment block. Is it possible?

**Comment by rottmann** [comment]
Not with apidoc.

You can use tools like `grunt` with `grunt-replace` to copy your docs to a temp-folder, replace your vars and let apidoc generate the doc from the temp-folder.
