### ISSUE TITLE
install gives error (asyncWrite and pna.nextTick is not a function)

### ISSUE THREAD

**Issue by et4891** [apidoc/apidoc#762]
when I am running the install, error happens

`sudo npm install apidoc -g`

> npm ERR! asyncWrite is not a function
> npm ERR! pna.nextTick is not a function
>

**Comment by manishsaraan** [comment]
can you provide your node version.
I can successfully install for
node version: 8.11.1
npm version: 5.6.0
![img](https://user-images.githubusercontent.com/19797340/48392142-00a41580-e730-11e8-9ef3-f72ff6631c4e.png)

**Comment by et4891** [comment]
sryz for the late reply
here's a screenshot
![selection_001](https://user-images.githubusercontent.com/2792333/48511935-fc99f580-e80c-11e8-8417-6bd2892f2445.png)

**Comment by et4891** [comment]
@manishsaraan just wondering if there's any update about this?

**Comment by cworth33** [comment]
Having similar issues on Windows 10 with clean install of node js
Node 8.15.1
NPM 6.4.1

**Comment by ravikantmaurya** [comment]
I'm havinng the similar issue on Windows 7.

Node Version 8.15.1
NPM Version 6.4.1

Even the create-react-app package is not installing via npm, i have tried it using npx but getting the same error. 
![Capture](https://user-images.githubusercontent.com/29114028/55815452-01d64480-5b0e-11e9-87a1-2ffa531c4f94.PNG)

**Comment by NicolasCARPi** [comment]
Please try again with latest node version.
