### ISSUE TITLE
documentation for "send a sample request" interface?

### ISSUE THREAD

**Issue by chovy** [apidoc/apidoc#766]
I don't see this feature documented anywhere, I would like to be able to send sample requests from the interface, is that possible?

I've seen other implementations do this, but I don't see the feature documented anywhere, how do I enable it?

**Comment by chovy** [comment]
https://www.dropbox.com/s/8jo36qlrx7sfawu/json1.mov?dl=0

**Comment by chovy** [comment]
<img width="417" alt="screenshot 2018-11-27 11 58 42" src="https://user-images.githubusercontent.com/27381/49108076-18a18c00-f23c-11e8-9139-d5c3b5c0f066.png">

This is a json body payload, notice how its json sent, not key=val pairs.

**Comment by NicolasCARPi** [comment]
Could https://github.com/apidoc/apidoc/pull/514 fix this issue you're having?
