### ISSUE TITLE
Routes of laravel

### ISSUE THREAD

**Issue by justcoding8** [apidoc/apidoc#768]
Why can i only able to see documentation of 7 routes even though i have 11 routes in master container?
I have put this at starting of every route:
```
/**
 * @apiGroup           Master
 * @apiName            api name
 *
 * @api                {DELETE} /v1/api 
 * @apiDescription     api description
 *
 * @apiVersion         1.0.0
 * @apiPermission      auth
 *
 * @apiParam           {String}  api/{id} Delete service order roles type by using id
 *
 * @apiSuccessExample  {json}  Success-Response:
 * HTTP/1.1 200 OK
```
and then i run `apidoc -i app/Containers/Master/ -o docs` this command. But the documentation was generated for only 7 routes even though I have put everything similar in all 11 routes.

**Comment by NicolasCARPi** [comment]
Please reopen issue if this behavior is still present with latest code from master.
