### ISSUE TITLE
I set the url in apidoc.json,but i don't want use it in an api.How can i do ?

### ISSUE THREAD

**Issue by xulayen** [apidoc/apidoc#771]
apidoc.json
``` js

{
...
    "url": "http://10.20.26.19:8011/api",
...
}

```

An api not need url pre
![image](https://user-images.githubusercontent.com/15044564/50672290-2a800700-1012-11e9-900b-c275e9dd3047.png)

**Comment by NicolasCARPi** [comment]
Please try latest version from master.
