### ISSUE TITLE
i do like this,but it has error

### ISSUE THREAD

**Issue by smilexlong** [apidoc/apidoc#772]
apidoc.json
{
  "name": "测试",
  "description": "API文档测试",
  "title": "API文档测试",
  "url": "http://****/v1",
  "template": {
    "forceLanguage": "zh-cn"
  }
}

'apidoc -i controllers -o apidoc ' this is work  ,but open zhe 'index.html',it is error like 
![qq 20190110105624](https://user-images.githubusercontent.com/19772709/50943320-e637af80-14c6-11e9-9da0-cd2528bb31c0.png)

**Comment by yunlongz** [comment]
I have a same problem

**Comment by NicolasCARPi** [comment]
Use `zh_cn`.
