### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by gemal** [apidoc/apidoc#776]
Any chance of a new release with all the latest changes in?

**Comment by okonon** [comment]
Also interested in this. I has been a while

**Comment by NicolasCARPi** [comment]
I'm afraid the maintainer is not very interested in this project anymore (which is something that happens as life goes on!).

**Comment by gemal** [comment]
Perhaps mark the project as "available". Perhaps someone has the time to step up as a new maintainer?

**Comment by NicolasCARPi** [comment]
@gemal I sent an email to the info@apidoc.com address proposing my help as a maintainer. Let's see the answer. It would be a shame to see this project abandoned...

**Comment by NicolasCARPi** [comment]
@manishsaraan I'm not even talking about working on new features, but just the maintainance at the moment: issue triage/closing and PR review (26 are waiting). Even if this project goes into "maintenance only mode/only bugfixes", it's fine, I just don't want to see it abandoned where the only person with commit rights is gone in the wind. I'll start going over the issues and such, and maybe later request contributor access to the repo so I can actually close/merge stuff myself :)

**Comment by rottmann** [comment]
The maintainer is interested, but he has no time ;)

I can give you access just like I've given access to 10 people before, but they've never really done anything to the project, or quickly lost interest again as soon as they see that such a project is work.

You can send me an email to info@apidocjs.com.

**Comment by NicolasCARPi** [comment]
@rottmann This is something I did already for a dying library : https://github.com/NicolasCARPi/jquery_jeditable/ There was HUNDREDS of PRs and issues, and I went through them all and I'm still maintaining the library as of today.

> quickly lost interest again as soon as they see that such a project is work

Of course I can't promise anything, but I'm pretty sure I'll review all issues and PR (given enough time) and help with issue triage/labeling. I know it's work, and I wish to do this for 3 reasons:

1. To help this great project that I use in my app
2. To learn along the way
3. Because I get dopamine in my brain when I close an issue and it's addictive :p 


> You can send me an email to info@apidocjs.com.

This was done an hour ago ;)



~Nico

**Comment by NicolasCARPi** [comment]
@rottmann Thank you very much for giving me access. I'll do my best. Please let me know if I'm doing something wrong :)

**Comment by rottmann** [comment]
@NicolasCARPi i give you write access. Your email before goes to the wrong address, to some chinese.

**Comment by NicolasCARPi** [comment]
Well, I did send it to info@apidocjs.com!

**Comment by NicolasCARPi** [comment]
Now to get back to this issue:

> Any chance of a new release with all the latest changes in?

Yes, as soon as all the current PRs and most issues have been reviewed, a new version will be released!

**Comment by danger89** [comment]
W00t! Well done @NicolasCARPi  I buy you a free beer. Free as in free as in freedom.

**Comment by antoinezanardi** [comment]
Thanks a lot @NicolasCARPi  for keeping up this project !  I'm sure you'll do your best. 🦾

**Comment by NicolasCARPi** [comment]
@rottmann I have tagged version 0.18.0. Please do "npm publish" whenever you have time (the sooner the better of course :p).

Of course, things are not perfect and issues remain, but there is no way to address ALL the issues at once, and I feel it's better to release often. At least now the number of open issues is halved and only 2 PRs are open \o/

**Comment by rottmann** [comment]
Thanks Nicolas! New version is up.

**Comment by NicolasCARPi** [comment]
Great! :D

**Comment by danger89** [comment]
Yup its final! Thx!
