### ISSUE TITLE
Error excludeFilter

### ISSUE THREAD

**Issue by cognativo** [apidoc/apidoc#778]
Good afternoon.

When I execute command  node apidoc -i myapp/ -o apidoc/ -t mytemplate/ is occured error below:

{"Path":"MYPATH","level":"error","message":"No files found."}.

I'm execute on debug mode and identified an error in the command: "options.excludedFilters".

Tks

**Comment by NicolasCARPi** [comment]
Please leave a comment if issue is still present.

**Comment by Mrkezii** [comment]
I have the exact same issue and i have a `apidoc.json` config file

**Comment by NicolasCARPi** [comment]
@Mrkezii what version are you using? Can you try with the latest from master?

What is the debug output?
