### ISSUE TITLE
string interpolation using python

### ISSUE THREAD

**Issue by praveen-kalpavruksh** [apidoc/apidoc#780]
I want to achieve something below, is it possible?

import abc
doc = abc.__doc__

```
"""@api {post} /models/:model_id Create and configure a model--single model
     @apiName PostModels
     @apiGroup Models
     @apiVersion 0.2.0
     @apiDescription {}
""".format(abc)
```

Is something like this doable? Can I create custom `apiDoc-params`?

**Comment by praveen-kalpavruksh** [comment]
I know that in comment part we can't do string interpolation just wanted to know if dynamic creation of doc part is possible via `_apidoc.py`  or something else.

**Comment by NicolasCARPi** [comment]
Wrong repo? Is this what you are using? https://github.com/SolutionsCloud/apidoc
