### ISSUE TITLE
Problem in apiSuccess

### ISSUE THREAD

**Issue by manikandanselva** [apidoc/apidoc#785]
Hi 

How to use the same keyword second time in API success.

includes : 
    type : category
    type : seo_content 

 * @apiSuccess (Response) {String}  **included.type** Type of the response JSON object   
 * @apiSuccess (Response) {String}  included.id Unique ID of the response JSON object   
 * @apiSuccess (Response) {Object}  included.relationships Related data to the response   
 * 
 * @apiSuccess (Response) {Object[]}  included.relationships.data The data”  
 * 
 * 
 * @apiSuccess (Response) {String}  **included.type** Type of the response JSON seo
 * @apiSuccess (Response) {String}  included.id This is an internal unique ID for a seo_content

![image](https://user-images.githubusercontent.com/21096619/57772764-f2ad6c80-7733-11e9-8a90-3fb4c6ab01e8.png)

**Comment by NicolasCARPi** [comment]
Why would you want to use the same keyword multiple times?
