### ISSUE TITLE
@apiName @apiGroup was Right in source code,But in html was wrong

### ISSUE THREAD

**Issue by byMoWen** [apidoc/apidoc#790]
my source code was right  @apiName   A  and @apiGroup  B
when i  use "apidoc -i src/ -o apidoc/" to build it
@apiName was @apiGroup in html
just:
      group1234
      group1234 - addOne
was it right ?
I think it should be like this in html:
      group1234
      apiOne - addOne

**Comment by SenixCoder** [comment]
Same qusetion，if you have answer, please let me know

**Comment by emauro** [comment]
I checked the template and it uses "title" after APIGroup. But "title" is empty in the generated JSON. I think the template should be changed to use "name" instead of "title". Line 106 of "index.html".

**Comment by NicolasCARPi** [comment]
This bug has been fixed!
