### ISSUE TITLE
Is there any to know where is the warning from?

### ISSUE THREAD

**Issue by MukuroSama** [apidoc/apidoc#791]
Only tell me there are some warnings but don't say which code you scanned that find error?
And the warning messages are meaningless！

> {"message":"parser plugin 'see' not found in block: 0","level":"warn"}

WTF!
You scanned a whole project, and then just say 'there are some problems'.How can developer get to know WHERE! WRONG!
I have tried --debug and --verbose,nothing meaningful got.

**Comment by kuangyanit** [comment]
Maybe you can clean the output files and try it again

**Comment by NicolasCARPi** [comment]
The error will now show the filename.
