### ISSUE TITLE
Error loading site - handlebars/diffMatchPath problem

### ISSUE THREAD

**Issue by mickwhiffin** [apidoc/apidoc#792]
I've just tried to refresh my api docs using your tool but the newly created apidoc site won't load. The error in the console is below.

![apidocs-bug-handlebars](https://user-images.githubusercontent.com/3450967/61479318-6e9c7e80-a948-11e9-88fc-9c7ce4f6937a.png)

Is this a dependency issue that i need to address or is it a known issue on your side. Please help!

**Comment by NicolasCARPi** [comment]
Hello,

Please reopen issue if the problem persists with the latest version from master.
