### ISSUE TITLE
one question about @apiGroup

### ISSUE THREAD

**Issue by steveGuRen** [apidoc/apidoc#794]
I have writted a examples like 
/**
* @apiGroup 工资条
*/

but when I get the  html doc , “工资条” is show as "___"，
why?

**Comment by steveGuRen** [comment]
But when I change the Chinese String "工资条" to "Groupsend", it can work well.is it possible the annnotion can't well support Chinese?

**Comment by cs12110** [comment]
Hi,look at this: `https://github.com/apidoc/apidoc/issues/749`

I got the same problem too, it's so annoying.

**Comment by multinucliated** [comment]
@steveGuRen  I'm also getting the underscore when I'm providing in my python file 

`@apiGroup Dynamic Benchmarking` -> Dynamic__Benchmarking

**Comment by NicolasCARPi** [comment]
Hello,

Until UTF-8 is fully supported, you cannot add CJK characters.

ISSUE NEEDS CLOSING
