### ISSUE TITLE
Menu ordering numeric

### ISSUE THREAD

**Issue by Bundara123** [apidoc/apidoc#796]
I'm using @apiGroup Number order menu, but the resulting output to order number.
Output like example:

-1. a 
-10. c
-2.b
But's I wanna get a result like below: 
-1. a
-2.b
-10.c

I propose the order number is better?

**Comment by NicolasCARPi** [comment]
That's an old problem with computers and number ordering. Is it possible for you to use 01, 02, 10 instead?

**Comment by ATLANT1S** [comment]
You can use apidoc.json for this. Just add "order" field and use it like array of apiGroup and apiName values.

Example:

> 
> {
>     "name": "my best api",
>     "version": "0.2.0",
>     "description": "for fun",
>     "title": "Documentation API",
>     "url": "http://localhost:8000",
>     "sampleUrl": "http://localhost:8000",
>     "template": {
>         "withCompare": false,
>         "withGenerator": true
>     },
>     "order": [
>         "Authorization", // apiGroup
>         "authByLogin", // apiName
>         "authByOauth",  // apiName
>         "authBySms", // apiName
>         "authByRefreshToken", // apiName
>         "Payments",  // apiGroup
>         "paymentHistory", // apiName
>         "paymentSettings", // apiName
>     ]
> }

**Comment by NicolasCARPi** [comment]
Thanks @ATLANT1S didn't know this existed! :)
