### ISSUE TITLE
@apiParam type array object

### ISSUE THREAD

**Issue by Bundara123** [apidoc/apidoc#797]
I read the APIDoc documents and see the result of the output array object, but I wanna another result like this:

example: 
- @apiParam {Object} timesheets Timesheet
- @apiParam {String} `timesheets.*.name` Name

When i generate to get the resulting key like below:
`timesheets.*.name`

I got the problem result `timesheets` and some end of the key in the description `*.name`. if can help me and suggest to do another.

**Comment by NicolasCARPi** [comment]
Remove the asterix.
