### ISSUE TITLE
Unwanted JSON output in CLI

### ISSUE THREAD

**Issue by OsoianMarcel** [apidoc/apidoc#799]
Hi,

After upgrading the library to latest version (0.17.7), in CLI output appers a JSON line.

When I run the command:
```apidoc -i src -o public/docs```
The CLI output is:
```
{"message":"Done.","level":"info"}
Done in 7.73s.
```
Why do we need this JSON line in CLI?

P.S. Thank you for this great library.

**Comment by NicolasCARPi** [comment]
Hello,

That's a good question!

ISSUE NEEDS QUESTION LABEL

**Comment by NicolasCARPi** [comment]
Probably because when it's not "info" level, a whole bunch of other stuff is displayed and it's nice to have it in json for further parsing.

**Comment by jilvin** [comment]
@NicolasCARPi Is there some option to enable this reporting only for errors and such?

**Comment by OsoianMarcel** [comment]
@NicolasCARPi In most of cases, this instrument is used in CLI, so in my opinion by default we do not need this JSON. I am sure that that JSON may be useful in some cases, but not in default / CLI mode.

**Comment by NicolasCARPi** [comment]
ok I'll reopen and see if that can be removed and hidden behind a switch.

**Comment by NicolasCARPi** [comment]
I have hidden this message behind the verbose flag.
