### ISSUE TITLE
Version-specific markdown sections (non-"@api")

### ISSUE THREAD

**Issue by natematykiewicz** [apidoc/apidoc#80]
Just like how you can add a header and footer and have them appear in the menu on the left, I found that it would be really helpful if it were possible to create similar sections that were version-specific.

In my case, my API requires a custom Accept header to specify the API version. I documented this in the header.md file and it looks great. My API is only in v1.0.0 right now, but it got me thinking. If we need to change this header in the future, I wouldn't be able to properly document it.

If I were able to say something like this, it would be really helpful:
/**
*@apiVersion 1.0.0
*@apiMarkdownSection {Menu Link Title} Multi-line markdown text
*/

In my mind, a section like this would be useful for describing some global part of the API, for that version, or even overview type of stuff. Support for multiple markdown sections would also be good.

**Comment by saritasa** [comment]
any news on this one?

**Comment by YouYII** [comment]
How to create some custom page in document and menu.
