### ISSUE TITLE
Question: Do you have any suggestion how can we import apidoc output to gitbook

### ISSUE THREAD

**Issue by tugan** [apidoc/apidoc#800]
Hello

first of all, this is not a bug or issue just a question 

we use the apidoc for main API documentation and also we use gitbook for documentation. 

quesiton how can we integrate apidoc result with gitbook 

thanks in advance for your support 
tugan

**Comment by NicolasCARPi** [comment]
ISSUE NEEDS QUESTION LABEL

**Comment by NicolasCARPi** [comment]
Hello,

Gitbook is a hosted application, what kind of integration are you looking for?
