### ISSUE TITLE
Bundle apidoc file into single html file

### ISSUE THREAD

**Issue by tboulis** [apidoc/apidoc#801]
Hello guys, I search in the issues and didn't find something similar. Is there a way to serve the apidoc as a single html file and not as a directory? I need this in order to make the apidoc page password protected and I want to serve it with express. Any ideas?

**Comment by NicolasCARPi** [comment]
ISSUE NEED QUESTION LABEL

**Comment by NicolasCARPi** [comment]
Hello,

There is already a single index.html file. You would need to add the javascript in the html file along with the CSS.

Note that you can password protect a directory!

But this is outside the scope of this project so I'm closing this issue.
