### ISSUE TITLE
Not support status code 204  on Test

### ISSUE THREAD

**Issue by phoenixsky** [apidoc/apidoc#811]
# Describe the bug

I use express in nodejs

if respone status is 200 
```
res.status(200).json('foo');
```
![image](https://user-images.githubusercontent.com/6359214/68924840-9b5c8780-07bc-11ea-9eb7-72879285f90e.png)

if response status is 204
```
res.status(204).json('foo');
```
![image](https://user-images.githubusercontent.com/6359214/68924550-0fe2f680-07bc-11ea-863b-e70e82fea640.png)

it aways like this . like not response

# Information

- Version of apidoc:  apidoc@0.18.0
- Operating system (e.g. GNU+Linux/MacOS/Windows): mac 10.15.1
- Browser (e.g. firefox, chrome): chrome 78.0.3904.87

**Comment by NicolasCARPi** [comment]
A 204 status is for "No content", so it makes sense to have no content, no?

**Comment by phoenixsky** [comment]
oooh ,
I think I got it.

`empty on responese textfield`  give rise to misunderstanding that the req have not been sent
