### ISSUE TITLE
Header field is never replaced by user value, only send default value

### ISSUE THREAD

**Issue by Seebomega** [apidoc/apidoc#813]
# Describe the bug

> 0.18

Hello looks like this commit cause a bug where now only default value is passed to the query instead of the real value.

example i use authorization token

i put in example token123456qwerty
i replace the field with my real token
in the network logs (f12) default value is send in the header instead of the real one

looks like it s caused by this commit 

https://github.com/apidoc/apidoc/commit/2c4ec0a00d99f5764477116a1ff1653bc0146194

Looks like this value is always default and not bind to user input

# Steps to reproduce
Add a header field with a default value
Go in the UI place another value
Look in the network defaul value is send in the header no matter what 

# Information

- Version of apidoc: >0.18
- Operating system (e.g. GNU+Linux/MacOS/Windows): GNU+Linux / windows
- Browser (e.g. firefox, chrome): Firefox, Vivaldi(chrome)

**Comment by NicolasCARPi** [comment]
Hello,

Yes I can reproduce this bug. Removing [those three lines](https://github.com/apidoc/apidoc/blob/master/template/utils/send_sample_request.js#L58-L60) fixes this issue.
