### ISSUE TITLE
Add color for the required keys in the APIspec.

### ISSUE THREAD

**Issue by srikanthbhamidipalli** [apidoc/apidoc#814]
# Feature request
Could you suggest me any way to apply some styles for the required keys?
Its badly needed for me.

I literally want this type or even with better styles which should display uniquely.
![Selection_001](https://user-images.githubusercontent.com/34590608/69476715-65925100-0e03-11ea-94cc-3d4fa1e41166.png)

Thank You Very Much

**Comment by NicolasCARPi** [comment]
Hello,

You might want to look into `template/css/style.css`. It's not clear where you want the style applide from your message.

**Comment by srikanthbhamidipalli** [comment]
> Hello,
> 
> You might want to look into `template/css/style.css`. It's not clear where you want the style applied from your message.

**Comment by srikanthbhamidipalli** [comment]
> # Feature request
> Could you suggest me any way to apply some styles for the required keys?
> Its badly needed for me.
> 
> I literally want this type or even with better styles which should display uniquely.
> ![Selection_001](https://user-images.githubusercontent.com/34590608/69476715-65925100-0e03-11ea-94cc-3d4fa1e41166.png)
> 
> Thank You Very Much

**Comment by srikanthbhamidipalli** [comment]
> Hello,
> 
> You might want to look into `template/css/style.css`. It's not clear where you want the style applied from your message.

I’m generating the doc which will helpful for frontend developers. I want to show them json object required params with highlighted colour.
As i mention that json object pic above.
