### ISSUE TITLE
@apiSampleRequest does not join the URL with the endpoint

### ISSUE THREAD

**Issue by irinabatiri** [apidoc/apidoc#817]
Hello, 
I am a new user and I am trying to use @apiSampleRequest for a Django REST Framework API, and I am following the last example from the documentation (where the sampleURL is not set in configuration - because anytime I am trying to set it to my URL, it just overwrites it back to "false" - no idea why).

I expect to get the result specified in the documentation: the URL to be joined to the endpoint, but when I open the html, I still see the URL specified in @apiSampleRequest only - it does not add the endpoint to it. 

Here is my config:
~~~json
{
  "name": "NewspaperAPI",

  "version": "0.1.0",

  "description": "apiDoc for newspaperAPI",

  "title": "NewspaperAPIDocs",

  "url": "http://localhost:8000/api/v1/",

  "sampleUrl": false,

  "defaultVersion": "0.0.0",

  "apidoc": "0.3.0",

  "generator": {

    "name": "apidoc",

    "time": "2019-11-26T09:55:00.306Z",

    "url": "http://apidocjs.com",

    "version": "0.18.0"

  }

}
~~~

And here is my doc:

~~~python
class ArticleList(generics.ListAPIView):

    """

    @api {get}    articles/                     Retrieve all articles

    @apiSampleRequest http://localhost:8000/api/v1/

    @apiName GetArticles

    @apiGroup Articles

    @apiPermission Authenticated user
~~~

Questions:
1) What can I do so that the endpoint joins itself to the URL and when I access the HTML the line "Send a Sample Request" presents the correct address.
2) Even if I hardcode the entire address into the @apiSampleRequest, I get error:0. I suppose the problem lies in the fact that I need to pass in authorization token, but I could not find any info on the apidocjs website about how to do that. 
3) Could you guide me - why is the sampleURL turning back to false on its own?

Thank you!

# Information

- Version of apidoc: 0.18.0
- Operating system: Windows
- Browser: chrome

**Comment by NicolasCARPi** [comment]
Try to remove the @apiSampleRequest line.
