### ISSUE TITLE
jsonapi apidoc--apidoc

### ISSUE THREAD

**Issue by rengan76** [apidoc/apidoc#824]
json:api apidoc--apidoc
is there anyway to post data with **field image** and path filename
{
	"data": {
	    "type": "apidoc--apidoc",
	    "attributes": {
	      "status": true,
	      "name": "New API Doc",
	      "description": {
	        "value": "<p>Lorem ipsum...</p>",
	        "format": "full_html"
	      },
	      "spec_file_source": "url",
	      "file_link": {
	        "uri": "http://other.local/spec.yaml"
	      }
	    }
	}
}

**Comment by NicolasCARPi** [comment]
Wrong repo it seems.
