### ISSUE TITLE
version repeat problem

### ISSUE THREAD

**Issue by cappuccino5** [apidoc/apidoc#830]
# Describe the bug

# Steps to reproduce

# Information

- Version of apidoc:
- Operating system (e.g. GNU+Linux/MacOS/Windows):
- Browser (e.g. firefox, chrome):

![image](https://user-images.githubusercontent.com/40583480/71659049-0a983600-2d81-11ea-82a0-7d857fe41771.png)

**Comment by cappuccino5** [comment]
![微信图片_20200102165947](https://user-images.githubusercontent.com/40583480/71659178-94480380-2d81-11ea-91b3-18b9ee8be2f1.png)

**Comment by NicolasCARPi** [comment]
Hello,

Please provide the code you are using.

**Comment by leslieSie** [comment]
@NicolasCARPi can i ask you some question,what can you do to deal this question?

**Comment by NicolasCARPi** [comment]
@leslieSie I am sorry, I don't understand your request.
