### ISSUE TITLE
@apiPrivate throws "Empty parser result." error

### ISSUE THREAD

**Issue by yagyesha** [apidoc/apidoc#831]
After updating to the latest version of apidoc (i.e. 0.19.1), building documentation fails where @apiPrivate tag is used. The error thrown is below:
```
{
	"File": "somefilename.ts",
	"Block": 17,
	"Element": "@apiPrivate",
	"Source": "@apiPrivate",
	"level": "error",
	"message": "Empty parser result."
}`
```
However, if i pass a value with @apiPrivate param then the error goes away.

For example, below fails:
```
/**
 * @api {get} /user/:id
 * @apiPrivate
 */
```
But below works:
```
/**
 * @api {get} /user/:id
 * @apiPrivate  test
 */
```
Note, the value 'test'.

Has anything changed around the usage of @apiPrivate ?

**Comment by NicolasCARPi** [comment]
See https://github.com/apidoc/apidoc-core/pull/93

Will be merged asap.
