### ISSUE TITLE
Add a --watch flag to refresh the api upon file change

### ISSUE THREAD

**Issue by PLQin** [apidoc/apidoc#833]
# Feature request

Can I update the apidoc while editing the API ?

It's like a hot update

**Comment by NicolasCARPi** [comment]
I'm having trouble understanding your request. What do you mean?

**Comment by omargho** [comment]
@PLQin you can use [nodemon](https://github.com/remy/nodemon) to watch file changes and execute a specific command whenever a file changes.
example `nodemon --exec "apidoc ... "` 
you can check this [section](https://github.com/remy/nodemon#running-non-node-scripts) for more info

@NicolasCARPi i think it could be a good feature to use nodemon as a [module](https://github.com/remy/nodemon/blob/master/doc/requireable.md) and add a tag to apidoc something like `apidoc --watch ... `

**Comment by NicolasCARPi** [comment]
@omargho Ok I understand the request now. What you propose sounds like a good idea!

**Comment by neelbhanushali** [comment]
when will this pr be merged?
