### ISSUE TITLE
Add koa2(express) middleware support

### ISSUE THREAD

**Issue by alex-zhang** [apidoc/apidoc#834]
# Add koa2(express) middleware support

hi, i decide to write a web framework  base on typescript  with decorator.
i have already write a route decorator  like `GTE(/api/users)`,  i don't want write the api-doc comments twice.

**Comment by NicolasCARPi** [comment]
Hello,

That's out of scope of this project. It is very unlikely that someone will work on it for you, so I'm closing this issue.
