### ISSUE TITLE
Support apidoc.js (in addition to apidoc.json)

### ISSUE THREAD

**Issue by thernstig** [apidoc/apidoc#838]
# Feature request
Add support for apidoc.js that exports an object, similar to how other projects supports both .json and .js. The reason is that for example I somehow programatically want to update the version field and get it from an external VERSION file. This file can be used by many tools such as CI/CD, other docs etc. to keep one location for the version of some software.

Problem with this is that it is JavaScript specific and apidoc supports many languages.

If this is a bad idea, an alternate approach would be to have a versionPath that points to a file containing just the version number.

**Comment by NicolasCARPi** [comment]
Hello,

I'm gonna be very honest with you: unless you work on it and propose a PR there is very little chance for this to happen.

**Comment by thernstig** [comment]
Honesty is good. Let's keep it for some time to see if other weigh in.
