### ISSUE TITLE
Does it support multiple languages?

### ISSUE THREAD

**Issue by yingzi20** [apidoc/apidoc#842]
Is it support multiple languages?

**Comment by NicolasCARPi** [comment]
Yes, in apidoc.json you can use forceLanguage. See Template specific settings on this page: https://apidocjs.com/#examples (ctrl+f forceLanguage)

**Comment by yingzi20** [comment]
@NicolasCARPi 
I mean I want to generate multi-language documents, such as English and Chinese, The user can switch languages, Does it support it?

**Comment by NicolasCARPi** [comment]
No.
