### ISSUE TITLE
Specify dynamic url/sampleUrl while generating apidoc for different environment

### ISSUE THREAD

**Issue by abhivishwebdunia** [apidoc/apidoc#844]
# Feature request
Hello ,
There should be feature to specify dynamic url or sampleUrl according to the application environment either in cli or somewhere else.So we will be able to create apidoc as per our application environment

**Comment by NicolasCARPi** [comment]
Before this is implemented, you can dynamically generate the config file in a bash script before calling apidoc ;)

**Comment by javajoe1** [comment]
I commented on https://github.com/apidoc/apidoc/issues/719 before seeing this, but I believe it is the same concern.
