### ISSUE TITLE
Kotlin specally support

### ISSUE THREAD

**Issue by lizhongyue248** [apidoc/apidoc#845]
# Feature request

In kotlin , use `[firstname]`, It will find the var `firstname`.

```kotlin
/*
 * @api {get} /user/:id Request User information
 * @apiName GetUser
 * @apiGroup User
 *
 * @apiParam {Number} id User's unique ID.
 *
 * @apiSuccess {String} [firstname] Firstname of the User.
 * @apiSuccess {String} [lastname]  Lastname of the User
 */
```
`[firstname]` and `[lastname]` give me a warning: `Cannot resolve symbol 'firstname'.`

Can i have another use `[firstname]` ?

Or Kotlin specally support? Such as `\[firstname]`.

**Comment by NicolasCARPi** [comment]
Indeed you cannot use some characters, as the parser will choke on them.

**Comment by lizhongyue248** [comment]
Now i use `[firstname ]` instead
