### ISSUE TITLE
New template

### ISSUE THREAD

**Issue by omargho** [apidoc/apidoc#847]
I'm planning to create a new template inspired from [slate](https://github.com/slatedocs/slate) and using apidoc-core and i think i will start it from scratch and take some parts from apidoc to progress rapidly.
should i create a seperate project, or seperate repo in apidoc's group, or new branch on apidoc ?

**Comment by NicolasCARPi** [comment]
If you plan to use apidoc-core and code from apidoc, I'd say another template that can be selected from the config file would be best. So another branch on apidoc that will get merged in master once it's stable and works well.

**Comment by omargho** [comment]
some of the modification will include some changes of the structure of the generated JSON object in order to simplify the work on the template and also to generate an HTML that include all elements of the docs to have a good SEO , because slate is used generally to write the public API documentation of enterprises so the documentation should be easily referenced.

**Comment by omargho** [comment]
@NicolasCARPi do you thing it's ok to do this kind of changes because i think it could considered as breaking changes, or should i create another project like [apidoc-swagger](https://github.com/fsbahman/apidoc-swagger) ?

**Comment by NicolasCARPi** [comment]
Creating another project will let you have the most freedom ;)

**Comment by mikebarkmin** [comment]
I have created this template, which might be something you are trying to archive. Maybe it is helpful to you. https://gitlab.com/openpatch/apidoc-template
