### ISSUE TITLE
Issue with @apiParam arrays auto append [] to the key

### ISSUE THREAD

**Issue by jackyzq** [apidoc/apidoc#848]
Hi, just updated my testing enivronment to the newest apidoc 0.20.0

I have an apiParam like so:
`@apiParam {String[]} sender_password_array
`

When I use the sample request in the generated document and input
`["abc","xyz"]
`

my api received a request json like so:
```
{
  'sender_password_array[]': ['abc','xyz']
}

```
previous version works as expected:
```
{
  'sender_password_array": ['abc','xyz']
}
```

Edit: it works with parameter: body/json, but doesn't work with parameter: ajax-auto

**Comment by NicolasCARPi** [comment]
I think it's fixed now.
