### ISSUE TITLE
loading style error

### ISSUE THREAD

**Issue by Ricuzy** [apidoc/apidoc#849]
When the page was loading, it shows like this
![image](https://user-images.githubusercontent.com/36161391/74496446-ac30ac80-4f15-11ea-9e1f-73bc34721e1d.png)

- my apidoc version is 0.20.0
- my chrome version is 79.0.3945.130(Mac)
- my screen width is over 1280px

Then i try other browsers, it shows error too.

When i update the style of css/style.css.

`body { max-width: 1280px; position relative; }`

It works fine, i guess may browser update it's parsing rules.

I hope you guys can fix the problem.

**Comment by NicolasCARPi** [comment]
Hello,

Thank you for reporting this issue. It is a bit surprising that only you get this error! Can you try with a fresh chrome profile? To make sure it's not some extension/customization of your browser causing this issue.

**Comment by AlexNeises** [comment]
This has actually been resolved in #846 and should make it into the next release.

**Comment by NicolasCARPi** [comment]
Released!

**Comment by Ricuzy** [comment]
Thanks for your response.

**Comment by oze4** [comment]
> Released!

@NicolasCARPi  thank you for the quick resolution as I am also encountering this issue.  However, I have noticed `npm` is still v0.20.0 and not v0.20.1.  Any way we can get that updated, too?

Thanks for the awesome tool - it's amazing!

**Comment by NicolasCARPi** [comment]
@oze4 I don't have access to the npm repo, but @rottmann is generally fast to push a release once I've pinged him ;)

**Comment by oze4** [comment]
> @oze4 I don't have access to the npm repo, but @rottmann is generally fast to push a release once I've pinged him ;)

@NicolasCARPi  @rottmann any idea when v0.21.0 will be pushed to `npm`?

**Comment by rottmann** [comment]
@oze4 Sorry, i missed the publish call. New version is up.
