### ISSUE TITLE
Configure Sidenav width

### ISSUE THREAD

**Issue by tsndr** [apidoc/apidoc#851]
I'd really like to have the option to configure the witdth of the sidenav or even better make it change it's width depending on the viewport.

But right now it's too narrow for me, most of my labels break into two lines.

**Comment by NicolasCARPi** [comment]
I agree that hardcoding width in pixels in the css is not the right way to go. We're loading bootstrap, we should take advantage of that.

**Comment by NicolasCARPi** [comment]
I've pushed a commit in that direction.
