### ISSUE TITLE
Special Characters in @apiGroup Breaks Javascript

### ISSUE THREAD

**Issue by EchelonEric** [apidoc/apidoc#852]
# Describe the bug
Using special characters in apiGroup field breaks Javascript, especially @apiSampleRequest 

# Steps to reproduce

Add a special character in apiGroup such as a slash /.
apiGroup Some Group / Some Name

Add an @apiSampleRequest url and generate your docs.  Go to the browser and try to submit the sample request form. It refreshes the whole page and also Chrome Developer Console shows errors such as:

> Error: Syntax error, unrecognized expression: #api-Some_Group_/_Some_Name
>     at Function.se.error (jquery.min.js?v=1581968830387:2)
>     at se.tokenize (jquery.min.js?v=1581968830387:2)
>     at se.select (jquery.min.js?v=1581968830387:2)
>     at Function.se [as find] (jquery.min.js?v=1581968830387:2)
>     at k.fn.init.find (jquery.min.js?v=1581968830387:2)
>     at new k.fn.init (jquery.min.js?v=1581968830387:2)
>     at k (jquery.min.js?v=1581968830387:2)
>     at HTMLAnchorElement.<anonymous> (bootstrap.min.js?v=1581968830387:6)
>     at jquery.min.js?v=1581968830387:2
>     at Function.map (jquery.min.js?v=1581968830387:2)

Removing the forward slash in apiGroup removes this error.

# Information

- Version of apidoc:
apidoc-generator version: 0.20.0"
apidoc-core version: 0.11.0
apidoc-spec version: 0.3.0

- Operating system Mac OS / Linux
- Browser Chrome

**Comment by NicolasCARPi** [comment]
Yes, there are "forbidden" characters. Not sure where in the code that would happen though...

**Comment by evgen-dev** [comment]
The use of Cyrillic characters also leads to a similar behavior:
`require.min.js:19 Error: Syntax error, unrecognized expression: #api-%D0%A2%D0%BE%D0%B2%D0%B0%D1%80%D1%8B-Delete
    at Function.se.error (jquery.min.js?v=1583306025802:2)
    at se.tokenize (jquery.min.js?v=1583306025802:2)
    at se.select (jquery.min.js?v=1583306025802:2)
    at Function.se [as find] (jquery.min.js?v=1583306025802:2)
    at k.fn.init.find (jquery.min.js?v=1583306025802:2)
    at new k.fn.init (jquery.min.js?v=1583306025802:2)
    at k (jquery.min.js?v=1583306025802:2)
    at main.js:402
    at Object.execCb (require.min.js:30)
    at ea.check (require.min.js:18)`

**Comment by wilon** [comment]
+1
Hope to solve it soon.

**Comment by NicolasCARPi** [comment]
PRs are welcome ;)
