### ISSUE TITLE
Convert To Swagger

### ISSUE THREAD

**Issue by scriptsure** [apidoc/apidoc#853]
does anyone have any experience converting apidoc to swagger? I want o have both documentation sets. The npm packages i see out there dont work...

**Comment by NicolasCARPi** [comment]
Unfortunately, the packages for apidoc <-> swagger are not maintained. But if you fork one and make it work I'll put your fork in the readme!

**Comment by amanoooo** [comment]
I write an [apidoc-swagger-3](https://github.com/amanoooo/apidoc-swagger-3),

- support separated path parameters from query/body
- support apiHeader
- support convert example to swagger schema

**Comment by NicolasCARPi** [comment]
@amanoooo https://github.com/apidoc/apidoc/commit/a7a3b7b0c93c2f58f4d5f3085e7e4f16f7b2f9ba
