### ISSUE TITLE
nav-tabs not active correctly

### ISSUE THREAD

**Issue by force1585** [apidoc/apidoc#856]
# Describe the bug

can't switch nav-tabs. 
error messages below:
require.min.js:19 Error: Syntax error, unrecognized expression: #api-Messages-Create_or_reply_a_message/file

jquery.min.js?v=1582703751917:2 Uncaught (in promise) Error: Syntax error, unrecognized expression: #api-Messages-Create_or_reply_a_message/file

# issue caused by

generated files :
api_data.js and api_data.json -  line 923

Create_or_reply_a_message/file -> Create_or_reply_a_message_file
may fix the issue

# Information

Version of apidoc:
apidoc-generator version: 0.20.0"
apidoc-core version: 0.11.0
apidoc-spec version: 0.3.0

Operating system Mac OS / Linux

Browser Chrome

**Comment by NicolasCARPi** [comment]
Could you provide some code to reproduce the issue please?
