### ISSUE TITLE
Sidebar filter not working

### ISSUE THREAD

**Issue by sureshdmavericks** [apidoc/apidoc#857]
Hi, 
The sidebar filter not working after docs generate. Can anyone help

**Comment by NicolasCARPi** [comment]
Which version of apidoc are you using? Which browser? Add screenshots.

**Comment by sureshdmavericks** [comment]
Hi @NicolasCARPi , I'm using 
{"message":"apidoc-generator name: apidoc","level":"verbose"}
{"message":"apidoc-generator version: 0.17.7","level":"verbose"}
{"message":"apidoc-core version: 0.8.3","level":"verbose"}
{"message":"apidoc-spec version: 0.3.0","level":"verbose"}

**Comment by NicolasCARPi** [comment]
Please use latest versions.
