### ISSUE TITLE
Vulernability - Update dependancy

### ISSUE THREAD

**Issue by hcleldaddonio** [apidoc/apidoc#858]
# Describe the bug
/template/vendor/handlebars.min.js
in handlebarsjs versions lower then 4.5.3 there is a vulnerability.
The handlebarjs version you are using is 4.0.5 according to the last time you committed it :)

Solution - update to handlebar js in version at least 4.5.3.

**Comment by NicolasCARPi** [comment]
Hello,

Thank you for reporting this. This is what happens when dependencies are not in a lockfile (so github can't warn the repo owner)...

I will try and see if it can be updated without breaking everything. Changelog: https://github.com/wycats/handlebars.js/blob/master/release-notes.md
