### ISSUE TITLE
Make it easy to add custom plugins

### ISSUE THREAD

**Issue by ollydixon** [apidoc/apidoc#861]
I'm trying to copy https://github.com/bangbang93/apidoc-plugin-ts

It works nice but it doesn't spit out JSON for API success example only individual lines.

But for the life of me, I cannot figure out where it starts? What is init(app)? How can I create my own plugin within my own source?

**Comment by NicolasCARPi** [comment]
Hello,

I am sorry I have troubles understanding your issue.

> What is init(app)?

What are you talking about?

> How can I create my own plugin within my own source?

Can you please reformulate?

**Comment by ollydixon** [comment]
I'm trying to create a plugin that reads the TypeScript interface and spits it out as JSON for API response examples and success examples. I've almost completed it here https://github.com/ollydixon/apidoc-plugin-ts

This plugin already reads the interface in Typescript and adds the lines. (forked from another project)

My only confusion is how the library apidocs-core reads plugins, but now I see it scans the directories (node modules) for "apidocs-plugin" string. Maybe put that in the docs and how to make your own plugins easier?

**Comment by NicolasCARPi** [comment]
Yes documentation is severely lacking for that. Because you're going through the process, maybe you could propose a PR on apidoc-core repository? I'm not sure if this would go in the README or in the wiki...

Closing this issue as it seems you found what you were looking for.

**Comment by ollydixon** [comment]
@NicolasCARPi yes it's forked, I will update the README. Ok, I will look into making a PR for that :-)
