### ISSUE TITLE
Require Error when using with GitHub pages

### ISSUE THREAD

**Issue by flexwie** [apidoc/apidoc#863]
# Describe the bug
When deploying to GitHub Pages there are several errors regarding the included js scripts in the vendor folder

```
Error: Script error for "api_data.js"
http://requirejs.org/docs/errors.html#scripterror
```
# Steps to reproduce

- Generate docs
- Save in repo
- Point GitHub Pages to /docs folder
- Visit site and check console

# Information

- Version of apidoc: latest
- Operating system (e.g. GNU+Linux/MacOS/Windows): Windows i guess
- Browser (e.g. firefox, chrome): Firefox

**Comment by NicolasCARPi** [comment]
Can't you see the same errors locally? `api_data.js` is a generated file. I don't think it's an issue if you get errors about this file in the console (AFAIK).

**Comment by flexwie** [comment]
Seems to be working fine now (out of the blue)... Maybe the GitHub Pages deployment just needs some time
