### ISSUE TITLE
Support set sampleUrl multi version

### ISSUE THREAD

**Issue by lee149205** [apidoc/apidoc#865]
# Feature request

_ I think we should allow set "sampleUrl" for each version 1.0.0, 2.0.0,...
_ I think we should show|hide input correct for each version
     Example: 
              + version 1.0.0 have 4 input (client_id, client_secret, email, password)
              + version 2.0.0 have 2 input (client_id, client_secret)
          ---> so, i think when switch to version 2.0.0 --> we only should show 2 input instead of 4 input

<img width="1363" alt="Screen Shot 2020-04-22 at 2 16 54 PM" src="https://user-images.githubusercontent.com/11714006/79952031-f4cf8d80-84a3-11ea-924b-9bf548affd8a.png">

thank you

**Comment by NicolasCARPi** [comment]
Thank you for your suggestion, at the moment we need to focus on other aspects (like fixing bugs) so this feature won't be implemented.
