### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by AkshayIyer12** [apidoc/apidoc#870]
# Describe the bug

**I suspect it's a possible memory leak issue.**

Whenever I run the my rest-doc-generation script.
https://paste.rs/Nry.sh

apidoc -f $CUR_DIR/$filename -o $FULL_REST_API_DOC_DIR/${filename%.*}
The above line throws an out of memory error.

Please see the full error [APIDOC_ERROR_LINK](https://paste.rs/z6r)
# Steps to reproduce

- Run ~/.npm-global/bin/apidoc -f vd_workflow_management.js -o /tmp/vd_workflow_management 2>&1
- You see the following error: https://paste.rs/kMZ
- HTOP overview of the same: [vd_workflow_management](https://user-images.githubusercontent.com/5500080/80469342-0dd1b600-895e-11ea-8a18-d432bdb9a78e.png)
- The file for which apidoc bails out:
[vd_workflow_management.js.gz](https://github.com/apidoc/apidoc/files/4544575/vd_workflow_management.js.gz)
Please use ```gzip -d vd_workflow_management.js.gz``` to unzip and run apidoc.
The unzipped file size is 133MB.

# Information

- Version of apidoc: 0.22
```
akshay@akshay-ThinkPad-T470:~/.npm-global/bin$ ./apidoc -v
{"message":"Please create an apidoc.json configuration file.","level":"warn"}
{"message":"apidoc-generator name: apidoc","level":"verbose"}
{"message":"apidoc-generator version: 0.22.0","level":"verbose"}
{"message":"apidoc-core version: 0.11.1","level":"verbose"}
{"message":"apidoc-spec version: 0.3.0","level":"verbose"}
{"message":"run parser","level":"verbose"}
{"Path":"/home/akshay/.npm-global","level":"error","message":"No files found."}
```

- Operating system (e.g. GNU+Linux/MacOS/Windows):  Linux
https://paste.rs/DdE
- Browser (e.g. firefox, chrome):Not Applicable

**Comment by rottmann** [comment]
Wow, huge file. One more thing for todo-list: change api-doc for streamed processing for larger files and split output to chunks for browser output.

Workaround, increase heap size:

`NODE_OPTIONS="--max-old-space-size=8192" ~/.npm-global/bin/apidoc -f vd_workflow_management.js -o /tmp/vd_workflow_management 2>&1`

**Comment by AkshayIyer12** [comment]
Hi @rottmann ,

For my teammate, it failed with a more bigger file size.
It was around 150MB.

**Comment by AkshayIyer12** [comment]
I have around 8GB of RAM and 12.5GB of Swap memory. By default my system consumes around 1GB of RAM and with firefox running it adds to about another 500MB-700MB. 

Apidoc is making my system consume too much resources. I see extra 5-5.5GB of RAM usage and my swap memory being used to around 3.58-4GB and also it is using all of my 4 CPUs as I see most of my CPU being on 100% whenever apidoc is run. I assume it's multi-threaded/process application but are you guys doing any heavy computation.

**Comment by NicolasCARPi** [comment]
>  but are you guys doing any heavy computation.

Yes we're mining cryptocoins every time apidoc is ran but we hoped that nobody would notice...! :p 

Now to be serious, your file is HUGE, I'm not sure anyone would have guessed during the development of this library that it was going to be used as such. The next step would be to use a profiler and see which function is taking a lot of CPU/memory and start from here.

**Comment by NicolasCARPi** [comment]
Out of scope for free support.
