### ISSUE TITLE
Add declaration file

### ISSUE THREAD

**Issue by rigwild** [apidoc/apidoc#875]
Hi,
It could be nice to have a typescript declaration file.

I made one, did I miss any options ?

```ts
// index.d.ts

declare module 'apidoc' {
  // See https://github.com/apidoc/apidoc/blob/42aa8ace8f6604267b0d37d4c413628ef53aca92/lib/index.js#L10-L26
  export interface DocOptions {
    dest?: string
    template?: string
    templateSingleFile?: string
    debug?: boolean
    single?: boolean
    silent?: boolean
    verbose?: boolean
    simulate?: boolean
    parse?: boolean
    colorize?: boolean
    markdown?: boolean
    config?: string
    apiprivate?: boolean
    encoding?: string
  }

  function createDoc(options: DocOptions): boolean | { data: Record<string, any>; project: Record<string, any> }

  export default createDoc
}
```

If you are ok with this, I can do a PR.

**Comment by NicolasCARPi** [comment]
Hello,

I just merged #874. Adding a .ts file should be easier now ;)

Waiting for your PR!

**Comment by rigwild** [comment]
> I just merged #874. Adding a .ts file should be easier now ;)

I'm not sure what you mean ? Is the definition I provided enough, or I missed someting ? 🤔

**Comment by NicolasCARPi** [comment]
Sorry I just didn't understand at all what you said. I was thinking of a CONFIG file in .ts.... (it's nearly 3am in my timezone :p)

Yes I see now what you want. Is there a way to test the validity of this file? So that if something changes a test will break?

**Comment by rigwild** [comment]
> (it's nearly 3am in my timezone :p)
Moi aussi 🤯

> Yes I see now what you want. Is there a way to test the validity of this file? So that if something changes a test will break?
We can make a small TypeScript file which get compiled during tests. But I don't think it's very useful as the exposed API is minimal.

**Comment by NicolasCARPi** [comment]
Wouldn't this file have a better home here? https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by rigwild** [comment]
Surely. Will do the PR there then 😉 I will tag you in it when opened.

**Comment by NicolasCARPi** [comment]
Yes, and then when it exists we can add it in the doc here.

**Comment by rigwild** [comment]
Types are published, see [@types/apidoc](https://www.npmjs.com/package/@types/apidoc) :)
I will let you do the README edit as I don't know how you would prefer to show it.

**Comment by NicolasCARPi** [comment]
> as I don't know how you would prefer to show it.

You think I know?? :p I guess a paragraph at the end about it will be good.

**Comment by hoonga** [comment]
@rigwild Looking at `bin/apidoc` I found these options
``` javascript
var options = {
    excludeFilters: ['apidoc\\.config\\.js$'].concat(argv.excludeFilters.length ? argv.excludeFilters : []),
    includeFilters: argv.fileFilters.length ? argv.fileFilters : ['.*\\.(clj|cls|coffee|cpp|cs|dart|erl|exs?|go|groovy|ino?|java|js|jsx|kt|litcoffee|lua|mjs|p|php?|pl|pm|py|rb|scala|ts|vue)$'],
    src           : argv.input.length ? argv.input : ['./'],
    dest          : argv.output,
    template      : argv.template,
    config        : argv.config,
    apiprivate    : argv.private,
    verbose       : argv.verbose,
    single        : argv.single,
    debug         : argv.debug,
    parse         : argv.parse,
    colorize      : argv.color,
    filters       : transformToObject(argv.parseFilters),
    languages     : transformToObject(argv.parseLanguages),
    parsers       : transformToObject(argv.parseParsers),
    workers       : transformToObject(argv.parseWorkers),
    silent        : argv.silent,
    simulate      : argv.simulate,
    markdown      : argv.markdown,
    lineEnding    : argv.lineEnding,
    encoding      : argv.encoding,
    copyDefinitions: !argv.definitions,
    filterBy      : argv.filterBy,
};
```
I guess we can add these too?

**Comment by rigwild** [comment]
You are right. I missed those. Can you do the PR to edit the types and the test ? https://github.com/DefinitelyTyped/DefinitelyTyped/tree/492b0ea5909f53629c99d8d35d68b45ba948ed67/types/apidoc

**Comment by hoonga** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46385

I made the PR
