### ISSUE TITLE
APIs do not load documentation when withCompare set to false

### ISSUE THREAD

**Issue by wouthoekstra** [apidoc/apidoc#879]
# Describe the bug
Only the titles of the APIs load, nothing of the actual docs. The console logs the following error, so I guess it has something to do with SemVer:

```
semver.min.js?v=1588867787213:1 Uncaught (in promise) TypeError: Invalid Version: undefined
    at new K (semver.min.js?v=1588867787213:1)
    at K.compare (semver.min.js?v=1588867787213:1)
    at ir (semver.min.js?v=1588867787213:1)
    at Object.vr [as lte] (semver.min.js?v=1588867787213:1)
    at HTMLElement.<anonymous> (main.js:561)
    at Function.each (jquery.min.js?v=1588867787213:2)
    at k.fn.init.each (jquery.min.js?v=1588867787213:2)
    at setMainVersion (main.js:556)
    at init (main.js:586)
    at Object.active (main.js:61)
```

# Steps to reproduce
* All the APIs are documented with @apiVersion 2.0.0
* withCompare is set to false. _If set to true, the docs do work._

# Information

- Version of apidoc: 0.22.1 _(but also tried to downgrade to 0.18.0, which uses an older SemVer)_
- Operating system (e.g. GNU+Linux/MacOS/Windows): Linux for generating. Windows for testing.
- Browser (e.g. firefox, chrome): Chrome / Brave / Edge
- Too make life a little easier: the broken docs are in the attachment.
[broken_docs.zip](https://github.com/apidoc/apidoc/files/4594277/broken_docs.zip)
- The configuration from package.json: _(slightly modified to not clutter this issue)_
"apidoc": {
    "name": "Our name",
    "title": "Our title",
    "version": "2.0.0",
    "description": "lorem ipsum",
    "url": "url to our domain",
    "template": {
      "forceLanguage": "en",
      "withGenerator": false,
      "withCompare": false
    },
    "order": [
      _...(list of all the APIs here)_
    ],
    "header": {
      "title": "General",
      "filename": "header.md"
    }
  }

**Comment by wouthoekstra** [comment]
Sorry, I see literally the last issue before mine reports the same thing: https://github.com/apidoc/apidoc/issues/878

I did not notice, because at first I did not know the issue was with withCompare. I'll leave my issue open, because I think it might have some additional info to resolve the bug.

**Comment by rafaelgssa** [comment]
It's not SemVer, the version is retrieved from the HTML, but the HTML containing the version isn't inserted with the option set to false. I'll make a PR soon.
