### ISSUE TITLE
--watch is not work

### ISSUE THREAD

**Issue by liyoy** [apidoc/apidoc#883]
# Describe the bug
package.json 
"getapi": "apidoc -i routers/ -o public/apidoc --watch"
npm run getapi 
`
families@0.1.0 getapi D:\projects\myproject\service
apidoc -i routers/ -o public/apidoc --watch

Watching mode is Activated
Listening for changes...

Process finished with exit code 0
`
# Steps to reproduce

# Information

- Version of apidoc: 0.22.1 
-version of node 12.16.1
- Operating system (e.g. GNU+Linux/MacOS/Windows): windows
- Browser (e.g. firefox, chrome): chrome

**Comment by NicolasCARPi** [comment]
I think it just cannot work on Windows because it's not possible to query the filesystem to see changes.

Try it on a REAL OS.
