### ISSUE TITLE
Api doc webpage not loading with big api_data.js file

### ISSUE THREAD

**Issue by AmirDadi** [apidoc/apidoc#884]
# Describe the bug

I have a big project and the api doc web page is available for the customers, currently the size of generated api_data.js file is more than 10 MB. The web page stucks on loading whenever loading the api_data file takes more than 15 secs to be downloaded. 
In the web console this error is printed.
"Error: Load timeout for modules: api_data.js 
http://requirejs.org/docs/errors.html#timeout"

**Comment by NicolasCARPi** [comment]
So the issue is with requirejs, right? Is there a config option to increase timeout?

**Comment by AmirDadi** [comment]
Yes, requirejs timeout default is 7 secs and can be set to more or 0 to set infinite. 
Here is the document: 

> https://requirejs.org/docs/api.html#config-waitSeconds

Also it's discussed here: 

> https://stackoverflow.com/questions/14511036/how-to-change-module-timeout-in-require-js

Another solution to change the flow of the index and load the api_data.js file using an ajax request instead of requiring the file. But I think it's more complicated.

**Comment by NicolasCARPi** [comment]
Timeout increased to 150 seconds.
