### ISSUE TITLE
the message when building doc failed is so simple and less, can not find the real position in the file 

### ISSUE THREAD

**Issue by owen-carter** [apidoc/apidoc#892]
# Feature request

## WHEN
`
 TERM>apidoc -i web_service -o ./pub -v --debug --watch
{"message":"found @apiUse in block: 9","level":"debug"}
{"File":"web_service/handler/handler_self_server.py","Block":10,"Element":"@apiUse","Source":"@apiUse Pagination\n","level":"error","message":"Only one definition or usage is allowed in the same block."}
`

## Question
when i wrote wrong doc, i find the error message is 
- Block":10
- "message":"Only one definition or usage is allowed in the same block."

**but where is the  block 10, when i wrote a huge file?**

**Comment by NicolasCARPi** [comment]
Open the file, search for `@apiUse`, look for somewhere where it 's duplicated. I agree that a line number would be better if provided...
