### ISSUE TITLE
0.22.1 and above break offline documentation

### ISSUE THREAD

**Issue by SecretAgentKen** [apidoc/apidoc#893]
# Describe the bug
The bugfix done as part of 0.22.1 breaks offline documentation. The `init` function now only gets called once `WebFont.load` is successful. If it fails, `init` is never called and you are stuck with the loading spinner. 

This can be fixed by adding an `inactive` section to WebFont.load with the same `init` call as the `active` section. 

# Steps to reproduce

Run apidoc as usual using 0.22.0 and 0.22.1 in different directories for each version. Disconnect from the network (no wifi or cable connection) and load each in the browser. In 0.22.0, the loading spinner will disappear and you will see your documentation (with a console error regarding not being able to load Google fonts). In 0.22.1 you will see the same console error, but the loading spinner will never go away.

# Information

- Tested with 0.22.0, 0.22.1, and 0.23.0.
- Tested in Firefox and Chromium.

**Comment by NicolasCARPi** [comment]
Hello,

Thank you for the report. Could you make a PR?

**Comment by SecretAgentKen** [comment]
I can this evening. I figured I'd post the bug in case someone can get to
it sooner since it's a two-liner.

**Comment by zedd3v** [comment]
I still get this (latest version)

**Comment by SecretAgentKen** [comment]
> I still get this (latest version)

The fix is in the dev branch, it isn't in a tagged release yet.

**Comment by NicolasCARPi** [comment]
ping me again if I don't make a release in the next few days.

**Comment by coooliang** [comment]
I still get this (latest version)
