### ISSUE TITLE
Group cannot be located using Chinese page refresh

### ISSUE THREAD

**Issue by lyrstar** [apidoc/apidoc#895]
I found that when the group uses Chinese, When the page refreshes, Unable to relocate to target location.
It is recommended to modify the default template "main.js" file, on line 617, revised as:
`var id = decodeURI(window.location.hash);`

**Comment by lyrstar** [comment]
Correct it. It's line 619

**Comment by NicolasCARPi** [comment]
Made a PR for that, can you confirm that this change is enough to fix the issue?

**Comment by lyrstar** [comment]
thank! I think so.
