### ISSUE TITLE
Using `#` in property name is not supported

### ISSUE THREAD

**Issue by GentileFulvio** [apidoc/apidoc#899]
# Describe the bug

So I have an api that returns a property that starts with a `#` but generating the docs always fails with the following error: 

```
{"message":"Please create an apidoc.json or apidoc.config.js configuration file or add an 'apidoc' key to your package.json.","level":"warn"}
{"File":"src/lib/controllers","Block":1,"Element":"@apiParam","Source":"@apiParam (body)\t\t\t{String}\t[#issueDate]\tTest description"}
```
Create an apiDoc with something like

```
 * @apiParam	(body)	{String}	[#test]	Test property
```

I can't get this working

# Information

- Version of apidoc: 0.24.0 (tried others as well)
- Operating system (e.g. GNU+Linux):

**Comment by NicolasCARPi** [comment]
Yes only alpha-numeric characters are supported. See https://github.com/apidoc/apidoc-core/issues/3 https://github.com/apidoc/apidoc-core/issues/64 and https://github.com/apidoc/apidoc-core/issues/66

Patches are welcome.

**Comment by GentileFulvio** [comment]
> Yes only alpha-numeric characters are supported. See [apidoc/apidoc-core#3](https://github.com/apidoc/apidoc-core/issues/3) [apidoc/apidoc-core#64](https://github.com/apidoc/apidoc-core/issues/64) and [apidoc/apidoc-core#66](https://github.com/apidoc/apidoc-core/issues/66)
> 
> Patches are welcome.

Forked + cloned the repo but can't run tests because of the following linting error.
`lib/parsers/api_private.js: line 1, col 16, 'content' is defined but never used.`
Am I doing something wrong or is this an actual issue that slipped through ?

**Comment by GentileFulvio** [comment]
After fixing the linting I get a failing test.
Note that I am working in the `apidoc/apidoc-core` repo atm.
![image](https://user-images.githubusercontent.com/17174077/89222091-b3876780-d5d4-11ea-8ce3-8f933fe6f34c.png)
