### ISSUE TITLE
Page won't show

### ISSUE THREAD

**Issue by SharifPoetra** [apidoc/apidoc#901]
# Describe the bug
After updating to `0.24.9`, the web won't shown, See [here](https://emilia-api.xyz/).

# Steps to reproduce
I don't know how to reproduce this, it's just happen after upgrading the version.

# Information

- Version of apidoc: 0.24.0
- Operating system: Ubuntu 18.04 LTS amd64
- Browser: Firefox, Chrome

**Comment by NicolasCARPi** [comment]
It's working fine for me on Firefox, but shows a blank page on Chromium.

The problem lies with your CSP: 

![2020-08-08-165621_1148x186_scrot](https://user-images.githubusercontent.com/3043706/89713471-2196aa80-d998-11ea-9075-86d2052bcc56.png)

**Comment by SharifPoetra** [comment]
Now it's fixed by adding `add_header Content-Security-Policy "script-src 'self' 'unsafe-eval'";` to my nginx configuration, My bad because not debugging it first, Sorry for wasting your time. and Thanks!
