### ISSUE TITLE
--watch does not work

### ISSUE THREAD

**Issue by dstampfer** [apidoc/apidoc#903]
# Describe the bug

I run --watch, but nothing happens.

# Steps to reproduce

$...:/tmp/example$ apidoc --watch -i src/  -o out
Watching mode is Activated
Listening for changes...
$
<process terminates immediately>

I would expect that the process stays running and updates the documentation once I do changes.

# Information

- Version of apidoc: latest with npm install: 0.24.0
- Operating system (e.g. GNU+Linux/MacOS/Windows): Ubuntu 16.04
- Browser (e.g. firefox, chrome): not relevant

**Comment by NicolasCARPi** [comment]
Can you run it with `-v` flag?

**Comment by dstampfer** [comment]
thanks for looking at this.

$ apidoc -i src/  -o out --watch -v
Watching mode is Activated
Listening for changes...
{"message":"apidoc-generator name: apidoc","level":"verbose"}
{"message":"apidoc-generator version: 0.24.0","level":"verbose"}
{"message":"apidoc-core version: 0.11.1","level":"verbose"}
{"message":"apidoc-spec version: 0.3.0","level":"verbose"}
{"message":"run parser","level":"verbose"}
{"message":"parse file: src/_apidoc.js","level":"verbose"}
{"message":"parse file: src/example.js","level":"verbose"}
{"message":"run worker","level":"verbose"}
{"message":"worker preProcess: apierrorstructure","level":"verbose"}
{"message":"worker preProcess: apierrortitle","level":"verbose"}
{"message":"worker preProcess: apigroup","level":"verbose"}
{"message":"worker preProcess: apiheaderstructure","level":"verbose"}
{"message":"worker preProcess: apiheadertitle","level":"verbose"}
{"message":"worker preProcess: apiparamtitle","level":"verbose"}
{"message":"worker preProcess: apipermission","level":"verbose"}
{"message":"worker preProcess: apistructure","level":"verbose"}
{"message":"worker preProcess: apisuccessstructure","level":"verbose"}
{"message":"worker preProcess: apisuccesstitle","level":"verbose"}
{"message":"worker preProcess: apiuse","level":"verbose"}
{"message":"worker postProcess: apierrorstructure","level":"verbose"}
{"message":"worker postProcess: apierrortitle","level":"verbose"}
{"message":"worker postProcess: apigroup","level":"verbose"}
{"message":"worker postProcess: apiheaderstructure","level":"verbose"}
{"message":"worker postProcess: apiheadertitle","level":"verbose"}
{"message":"worker postProcess: apiname","level":"verbose"}
{"message":"worker postProcess: apiparamtitle","level":"verbose"}
{"message":"worker postProcess: apipermission","level":"verbose"}
{"message":"worker postProcess: apisamplerequest","level":"verbose"}
{"message":"worker postProcess: apistructure","level":"verbose"}
{"message":"worker postProcess: apisuccessstructure","level":"verbose"}
{"message":"worker postProcess: apisuccesstitle","level":"verbose"}
{"message":"worker postProcess: apiuse","level":"verbose"}
{"message":"run filter","level":"verbose"}
{"message":"filter postFilter: apierror","level":"verbose"}
{"message":"filter postFilter: apiheader","level":"verbose"}
{"message":"filter postFilter: apiparam","level":"verbose"}
{"message":"filter postFilter: apisuccess","level":"verbose"}
{"message":"create dir: out/","level":"verbose"}
{"message":"copy template /home/ds/bin/node-v12.16.1-linux-x64/lib/node_modules/apidoc/template/ to: out/","level":"verbose"}
{"message":"write json file: out/api_data.json","level":"verbose"}
{"message":"write js file: out/api_data.js","level":"verbose"}
{"message":"write json file: out/api_project.json","level":"verbose"}
{"message":"write js file: out/api_project.js","level":"verbose"}
{"message":"write json file: out/api_definitions.json","level":"verbose"}
{"message":"write js file: out/api_definitions.js","level":"verbose"}
{"message":"Done.","level":"info"}
$

**Comment by NicolasCARPi** [comment]
Can you make sure that node_modules are up to date? (`npm i`)

**Comment by dstampfer** [comment]
yes, it is. It was a fresh demo-project. I updated it today, too. same behavior.

**Comment by NicolasCARPi** [comment]
Sorry but I have no idea why this is happenning. Might be a bug in the [nodemon](https://github.com/remy/nodemon) library used. You'll want to have a reproducible setup.

**Comment by xuwenkeke** [comment]
I always run --watch, but nothing to rebuilding.

**Comment by NicolasCARPi** [comment]
Closing as not reproducible.

**Comment by nicedouble** [comment]
face the same problem,--watch will not auto refresh output,to update the project,i need run the command again.
----
apidoc -i ./api -o ./apidoc -t ./template --watch
Watching mode is Activated
Listening for changes...
----
npm 7.3.0
apidoc 0.29.0
win10 64bit

**Comment by NicolasCARPi** [comment]
@nicedouble maybe update your apidoc version?

**Comment by bmqy** [comment]
> 
The latest version 0.52.0 is still invalid...

```
Watch mode enabled
Listening for changes on input files...
verbose: apidoc-generator name: apidoc
verbose: apidoc-generator version: 0.52.0
verbose: apidoc version: 0.52.0
verbose: apidoc-spec version: 0.3.0
verbose: run parser
verbose: parse file: src\main\webapp\app\api\index.jsp
verbose: run worker
verbose: worker preProcess: apierrorstructure
verbose: worker preProcess: apierrortitle
verbose: worker preProcess: apigroup
verbose: worker preProcess: apiheaderstructure
verbose: worker preProcess: apiheadertitle
verbose: worker preProcess: apiparamtitle
verbose: worker preProcess: apipermission
verbose: worker preProcess: apistructure
verbose: worker preProcess: apisuccessstructure
verbose: worker preProcess: apisuccesstitle
verbose: worker preProcess: apiuse
verbose: worker postProcess: apierrorstructure
verbose: worker postProcess: apierrortitle
verbose: worker postProcess: apigroup
verbose: worker postProcess: apiheaderstructure
verbose: worker postProcess: apiheadertitle
verbose: worker postProcess: apiname
verbose: worker postProcess: apiparamtitle
verbose: worker postProcess: apipermission
verbose: worker postProcess: apisamplerequest
verbose: worker postProcess: apistructure
verbose: worker postProcess: apisuccessstructure
verbose: worker postProcess: apisuccesstitle
verbose: worker postProcess: apiuse
verbose: run filter
verbose: filter postFilter: apierror
verbose: filter postFilter: apiheader
verbose: filter postFilter: apiparam
verbose: filter postFilter: apisuccess
verbose: Writing files...
verbose: Copying template index.html to: src\doc\
verbose: Copying fonts to: D:\workspace\ibicn\2022\time.ibicn.com\src\doc\assets
verbose: Copying bootstrap css to: D:\workspace\ibicn\2022\time.ibicn.com\src\doc\assets
verbose: Copying prism css to: D:\workspace\ibicn\2022\time.ibicn.com\src\doc\assets
verbose: Copying main css to: D:\workspace\ibicn\2022\time.ibicn.com\src\doc\assets
verbose: Running webpack bundler
verbose: All done :)
```

**Comment by NicolasCARPi** [comment]
What system, what node version?

**Comment by bmqy** [comment]
> What system, what node version?

system: windows11 21H2
node: v16.14.0

**Comment by NicolasCARPi** [comment]
I have strictly no interest fixing bugs related to the use of the Microsoft Windows operating system. Try this: https://github.com/remy/nodemon/blob/master/faq.md#windows-nodemon-keeps-restarting-without-changes.

**Comment by eJayYoung** [comment]
The same problem, --watch not auto refresh output 

system:  Darwin Kernel Version 20.6.0
node: v16.15.0
apidoc: 0.52.0
