### ISSUE TITLE
can not find header.md in crontab job

### ISSUE THREAD

**Issue by uasunshine** [apidoc/apidoc#904]
# Describe the bug

i am trying to use crontab to update doc automatically
but it always a erros like {"message":"Can not read: header.md.","level":"error"}
# Steps to reproduce

my heaerd.md and apidoc.json are in a same directory which is project root path /www/project/
my crontab command is like this:   */1 * * * * apidoc -i /www/project/controller -o /www/project/public/apidoc
apidoc.json
{ "header": {"title": "title", "filename": "header.md" }}
# Information

- Version of apidoc: latest
- Operating system (e.g. GNU+Linux/MacOS/Windows): ubuntu 18.04
- Browser (e.g. firefox, chrome): -

**Comment by NicolasCARPi** [comment]
cd into the directory first.

**Comment by uasunshine** [comment]
> cd into the directory first.

hi, i have change crontab command like this: */1 * * * * cd /www/project/ && apidoc -i /www/project/controller -o /www/project/public/apidoc

but still not work for me... 

the crontab log shows like down below:
-- Aug 20 09:06:01 mylocal CRON[9814]: (myusername) CMD (cd /www/project/&&apidoc -c /www/project/apidoc.json -i /www/project/controller/ -o /www/project/public/apidoc)

**Comment by NicolasCARPi** [comment]
I just tried it, it works as expected. Can you try and remove the `-c` flag?

**Comment by uasunshine** [comment]
Thanks for your help...it's done
