### ISSUE TITLE
change color theme

### ISSUE THREAD

**Issue by SantetAlami** [apidoc/apidoc#907]
# Feature request

hex color in apidoc.json

```json
{
  "name": "AcmeCorp Api documentation",
  "version": "0.3.0",
  "description": "Documentation for the REST api access provided at AcmeCorp",
  "title": "Custom apiDoc browser title",
  "url" : "https://api.example.com",
  "sampleUrl": "https://apidoc.free.beeceptor.com",
  "header": {
    "title": "Introduction",
    "filename": "header.md"
  },
  "footer": {
    "title": "Best practices",
    "filename": "footer.md"
  },
  "template": {
    "withCompare": true,
    "withGenerator": true,
    "aloneDisplay": false,
    "theme-color": "#fcba03" //new
  }
}
```

**Comment by shankiflang** [comment]
I think this idea is cool because I can't look at white sites anymore! For example with a dark theme

**Comment by rottmann** [comment]
You need to change more than one color, so you better copy apidoc template and modify the template css-file.
then you can use your template with `apidoc -t my-template/`

To add a dark theme direct into apidoc there is more todo: Need the css file, the path in apidoc.json e.g. `template/cssFile`: `dark.css`. A modified template and generator to switch between default or the theme defined with `template/cssFile`.
PR is welcome.

**Comment by NicolasCARPi** [comment]
I've reworked the css, should be easier on the eyes at night now ^^ => https://apidocjs.com/example/

**Comment by ditinexDevelopers** [comment]
@NicolasCARPi how to install your example ? I have installed the latest version of apidoc and I am still seeing the white text

**Comment by mjy78** [comment]
One approach to change theme colour is to override the CSS primary variable in a style tag through a header markdown file.

Add to apidocjs config...

```  
"header": {
    "filename": "custom-header.md"
}
```

Then in the custom header markdown file add the style tag...

```
<style>
  :root {
    --primary: #FF5733; /* Primary theme color override */
  }
</style>
```
