### ISSUE TITLE
@apiName must not contain spaces

### ISSUE THREAD

**Issue by ghost** [apidoc/apidoc#908]
When you put spaces in the @apiName, the api documentation is gerated without any warnings or errors.
But the documentation itself presents a strange grayed color instead of the classic black background in the example areas. And also, the documentation is completly unresponsive when trying to send request examples or interact with tabs within the document.

So this:

~~~javascript
* @apiExample {JSON} Sample Request:
 * {
 *     "Token" : "fc9edd42-cb33-4f4d-b2c6-01f051ae879a",
 *     "IdInstallation" : 0,
 *     "Type" : 1,
 *     "Json" : {
 *         "New Batch" : 1
 *     }
 * }
~~~

would be displayed with a gray background

- Operating system Windows 10;
- Browser : chrome;

**Comment by NicolasCARPi** [comment]
Can't reproduce. Please provide screenshots and reproducible code.

**Comment by h496336011** [comment]
I have reappear this issue .
After the @apiName  , the text has include the symbols such as {} or / ...
For example:
@apiName getUser/{id}
Then the backGround color will turn to grey
