### ISSUE TITLE
Response Parameters as JSON

### ISSUE THREAD

**Issue by shahidkarimi** [apidoc/apidoc#910]
# Feature request

Well the @apiParam thing is ok usually. But systems today accept json payload. So in case of json payload instead of @apiParams we can do something like

@apiParamsJson json-payload:
```
{
 "id": 420,
 "resources": [
  { 
   "name": "Hltad wala"
  }
 ]
}
```

**Comment by rottmann** [comment]
You can define Objects (JSON) with apiParam

```
@apiParam {Object} MyObject Some Description.
@apiParam {String} MyObject.field1 A Field.
@apiParam {String} MyObject.field2 Another Field.
```
