### ISSUE TITLE
Block of text

### ISSUE THREAD

**Issue by lucasltavares** [apidoc/apidoc#911]
Hello, thanks for this awesome doc generator.

Is it possible that we have blocks of just text and descriptions of something? Like this one: https://www.promoter.ninja/apidocs/#api-Webhooks-Webhooks in the section "Webhooks" and "Web snippet" there's no http method just text. How can I do this since i didn't find anything related to this in the documentation? Thanks.

**Comment by NicolasCARPi** [comment]
You can use the header and footer markdown files, and apiDescription.
