### ISSUE TITLE
override url parameter

### ISSUE THREAD

**Issue by danidev** [apidoc/apidoc#912]
Hello,

is it possible to override the parameter *url* specified in apidoc.json for a single endpoint?

I mean: if I specify on apidoc.json:
```
"url":"myapi.com"
```
when I define an api endpoint like:
```
@api {post} /api/endpoint Endpoint
```
on the documentation the path of the request looks like:
```
myapi.com/api/endpoint
```
I must write documentation for endpoints outside this base url (for instance the oauth endpoints on a resource server) and I cannot find a way to override this base url.
I didn't found anything on the apidoc documentation, am I missing something? 
Is it feasible with a work-around?

Thanks!
Daniele

**Comment by NicolasCARPi** [comment]
I don't think it's feasible, as the endpoint is a globally defined var that doesn't change.

We would need a `@apiBaseUrl` param to be able to override that.
