### ISSUE TITLE
Command line input *

### ISSUE THREAD

**Issue by DEF4ULT-OP** [apidoc/apidoc#913]
# Describe the bug

It didn't creates output when I do 
apidoc -i * -o Docs

# Steps to reproduce
$ apidoc -i *  -o Docs

# Information

- Version of apidoc: latest
- Operating system (e.g. GNU+Linux/MacOS/Windows): Linux
- Browser (e.g. firefox, chrome):

**Comment by NicolasCARPi** [comment]
That's because `-i` expects a folder path.

**Comment by DEF4ULT-OP** [comment]
Yea got it .
Just have to remove -i for current directory
