### ISSUE TITLE
Take Sample URL from Base URL

### ISSUE THREAD

**Issue by thealphadollar** [apidoc/apidoc#914]
# Feature request

Currently, the apidoc hosted asks for an explicit sample URL which needs to be set in the configuration file or when defining the documentation itself for the endpoints.

I propose that, if none of the above is specified, the sample URL should default to the base URL where the docs are being served. 

For example, if I open docs on `http://0.0.0.0:5000/apidocs` then the sample URL should be `http://0.0.0.0:5000/ENDPOINT` in the case where the sample URL has not been defined explicitly.

## Benefits

This would solve the issue of testing API changes when working locally or on multiple environments where it is required to send requests to the hosting URL and not to a specified test bed.

PS. I'm willing to contribute towards the feature if we decide to include this.

**Comment by NicolasCARPi** [comment]
Hello @thealphadollar,

What you propose sounds like a good idea. Now waiting on your PR ;p

Cheers,
~Nico

**Comment by thealphadollar** [comment]
Hey Nicolas, thanks for the go-ahead. Is there any information that you can make available to me, as you have more understanding of the structure of the code, that will help me deliver faster? This may include the areas where changes might be required, maybe a change would be required in https://github.com/apidoc/apidoc-core or anything that you seem suitable as a guide for the issue.

**Comment by NicolasCARPi** [comment]
I believe I would start [here](https://github.com/apidoc/apidoc/blob/master/template/main.js#L105) and add something like:

~~~javascript
if (!apiProject.url) {
   // grab url from where we are hosted and use that
}
~~~
