### ISSUE TITLE
Image on footer.md doesn't work

### ISSUE THREAD

**Issue by mtacnet** [apidoc/apidoc#917]
# Describe the bug

When i add an image on footer.md file that doesn't work. 

I use this markdown notation for add my image: `![Logo](./images/myLogo.png)`

Obviously, where the file `footer.md` is located i have a folder named `images` and `myLogo.png`  file is present. 

When I use the markdown preview with VSCode my image is well displayed but when i launch `index.html` file my image does not appear (but the title `Logo` is present). 

# Steps to reproduce

- Create folder named "images" where your `footer.md` file is located
- Add an image on standard format (for exemple: `.png` or `.jpeg`) 
- Name your image with the correct extension, for a `.png` file you can choose: `myLogo.png`
- Finally, add this on `footer.md` file: `![Logo](./images/myLogo.png)`
- Generate your documentation and launch `index.html` file

# Information

- Version of apidoc: apidoc@0.25.0 with apidoc-core@0.12.0
- Operating system (e.g. GNU+Linux/MacOS/Windows):  macOS Catalina Version 10.15.7 (19H2)
- Browser (e.g. firefox, chrome): Google Chrome Version 86.0.4240.111 (Build officiel) (x86_64)
![Markdown_Preview_VSCode](https://user-images.githubusercontent.com/22075833/97019834-14c63380-1551-11eb-8019-98ed9ef5ab47.png)
![index_HTML](https://user-images.githubusercontent.com/22075833/97018359-5950cf80-154f-11eb-978f-b58896f6ac1b.png)

**Comment by NicolasCARPi** [comment]
It can only work if your `images` folder is where the `index.html` file is.

Try this:

Add the `--single` option so you only have one index.html file to move around. Copy this html file in the same directory as `images` (or the other way around), et voilà !

**Comment by mtacnet** [comment]
Ok, perfect, it works, thanks for your help ! :)
