### ISSUE TITLE
if have the same fieldname in sub layer, the iterant field was not displayed

### ISSUE THREAD

**Issue by jason-jiangjs** [apidoc/apidoc#919]
# Describe the bug

apidoc 0.25.0

if have the same fieldname in sub layer, the iterant field was not displayed
# Steps to reproduce
![image](https://user-images.githubusercontent.com/35398337/98194629-ca828080-1f5a-11eb-86d5-0a004c01f9b0.png)
![image](https://user-images.githubusercontent.com/35398337/98194733-00276980-1f5b-11eb-997a-2ff7656db807.png)

# Information

- Version of apidoc:
- Operating system (e.g. GNU+Linux/MacOS/Windows):
- Browser (e.g. firefox, chrome):

**Comment by NicolasCARPi** [comment]
Why would you have the same field several times??

**Comment by tommy87** [comment]
I think what you want ist writing 
WantMergeIdList.warrantId instead of just .warrantId

Writing It this way you can assign IT to a conrete Patent object

**Comment by NicolasCARPi** [comment]
You can try the current `dev` branch: `npm i -g apidoc/apidoc#dev`. See also #999.
