### ISSUE TITLE
Tabs not working

### ISSUE THREAD

**Issue by bornagainraj7** [apidoc/apidoc#920]
# Describe the bug

Whenever we are using multiple Error for an API and the result is in Tabs in Error Section of API the, now by default the first tab is selected but if you select the 2nd or 3rd tab it doesn't opens

/**
 * @apiDefine ServerError
 *
 * @apiError ServerError 500 This error occurs when server rans into an unknown error.
 *
 * @apiErrorExample { json } Error-Response:
 * {
 *  "error": true,
 *  "message": "Server Error Occurred",
 *  "status": 500,
 *  "data": null
 * }
 */

 * @apiError  AlreadyInUse  This error occurs when you try to
 * signup with already existing mobile number or email id.
 *
 * @apiErrorExample Error-Response:
 * {
 *  "error": true,
 *  "message": "Please use different email or mobile number",
 *  "status": 403,
 *  "data": null
 * }
 *
 * @apiUse  ServerError

# Information

- Version of apidoc: 0.25.0
- Operating system (e.g. GNU+Linux/MacOS/Windows): Windows
- Browser (e.g. firefox, chrome): Chrome/Brave/Firefox/Vivaldi

**Comment by tommy87** [comment]
I dont understand the problem. Could you explain it more detailed? And also i dont see the tabs, maybe you can give me some hints

**Comment by NicolasCARPi** [comment]
You can provide screenshots, too.

**Comment by bornagainraj7** [comment]
![screenshot-localhost_3500-2020 11 17-14_51_42](https://user-images.githubusercontent.com/43012371/99371116-7ffeed80-28e4-11eb-9e98-4644eb9d14ce.png)


As in the screenshot, the error tabs doesn't work 



But since I added @apiName SomeName it started working

**Comment by NicolasCARPi** [comment]
> But since I added @apiName SomeName it started working

And since @apiName should always be used, as per the doc. We can close this.
