### ISSUE TITLE
White boxes if apiName ends in .

### ISSUE THREAD

**Issue by gemal** [apidoc/apidoc#921]
I'm getting white boxes if the `@apiName` ends in a period like `@apiName GetUser.`

![image](https://user-images.githubusercontent.com/69105/99404964-7bd6ce00-28ec-11eb-99b8-90b507003211.png)

very easy to reproduce:
Try to generate apidoc for the following php file:

```
<?php
/**
 * @api {get} /user/:id Request User information
 * @apiName GetUser.
 * @apiGroup User
 *
 * @apiParam {Number} id Users unique ID.
 *
 * @apiSuccess {String} firstname Firstname of the User.
 * @apiSuccess {String} lastname  Lastname of the User.
 */
```

I think it's related to prism.js or something. Anyways super weird

Using apidoc-0.25.0

If I remove the `.` from the `apiName` I get:

![image](https://user-images.githubusercontent.com/69105/99405195-c6f0e100-28ec-11eb-8dc1-4ba4f4c2663c.png)

which looks correct

**Comment by NicolasCARPi** [comment]
Ok, thanks for the report. Don't use `.` in `@apiName` then ;p
