### ISSUE TITLE
style.css Unexpected shorthand "padding" after "padding-bottom"

### ISSUE THREAD

**Issue by seetoml** [apidoc/apidoc#923]
# Describe the bug
When going through SonarQube, it produce critical issues - Unexpected shorthand "padding" after "padding-bottom"

# Steps to reproduce

At line 70 under section h1 and line 162 under apidoc h1

section h1 {
--
  |   |   | font-family: "Source Sans Pro", sans-serif;
  |   |   | font-weight: 700;
  |   |   | font-size: 32px;
  |   |   | line-height: 40px;
  |   |   | padding-bottom: 14px;
  |   |   | margin: 0 0 20px 0;
  |   |   | padding: 0;
}

#apidoc h1 {
--
  |   |   | font-family: "Source Sans Pro", sans-serif;
  |   |   | font-weight: 700;
  |   |   | font-size: 32px;
  |   |   | line-height: 40px;
  |   |   | padding-bottom: 14px;
  |   |   | margin: 0 0 20px 0;
  |   |   | padding: 0;

}

# Information

- Version of apidoc: 0.25.0
- Operating system (e.g. GNU+Linux/MacOS/Windows): Windows
- Browser (e.g. firefox, chrome): MS Edge

**Comment by NicolasCARPi** [comment]
Hello,

Thank you for the report, the code has been modified.
