### ISSUE TITLE
Unable to initialize document without network

### ISSUE THREAD

**Issue by coooliang** [apidoc/apidoc#924]
# Describe the bug
I am using the latest version of apidoc, and when I access the generated document without a network, it cannot be properly initialized
I found that **webfontloader.js** has CSS to introduce this path (https://fonts.googleapis.com/css)

# Information

- Version of apidoc: 0.25.0
- Operating system (e.g. GNU+Linux/MacOS/Windows):MacOS
- Browser (e.g. firefox, chrome):chrome

**Comment by NicolasCARPi** [comment]
Indeed.
