### ISSUE TITLE
Multiple metods ?

### ISSUE THREAD

**Issue by omidgfx** [apidoc/apidoc#927]
How can I have multiple `method`s in my api?

I already tried:
```php
/**
* @api {get|post} ...
**/
```
----
```php
/**
* @api {get,post} ...
**/
```
----
```php
/**
* @api {get} {post} ...
**/
```
----
```php
/**
* @api {get}|{post} ...
**/
```
----
```php
/**
* @api {get},{post} ...
**/
```
----

But none of above approaches works for me !

What can I do ?

**Comment by NicolasCARPi** [comment]
Create a block for each method. There is no support for multiple methods.

**Comment by omidgfx** [comment]
Is it so complicated to have multiple method tags? 👎

**Comment by rottmann** [comment]
Why should 2 different request methods with the exact same behavior exists? 👀

**Comment by NicolasCARPi** [comment]
> Is it so complicated to have multiple method tags? -1

This behavior will not be tolerated. If you're unhappy with the **FREE** software apidoc, feel free to implement your own solution, or propose a patch.

**Comment by omidgfx** [comment]
> 
> 
> > Is it so complicated to have multiple method tags? -1
> 
> This behavior will not be tolerated. If you're unhappy with the **FREE** software apidoc, feel free to implement your own solution, or propose a patch.

I didn't mean what you saying! I was just asking a question and really like this module. that's it.
Thanks for responding and yeah maybe I'll make a patch for my solution

**Comment by omidgfx** [comment]
> 
> 
> Why should 2 different request methods with the exact same behavior exists? 👀

In some case you want to use put & patch for updating something and you giving your user an extra option and I do know it worth nothing by the way. I was just wondering! it's not too important :-)
