### ISSUE TITLE
@apiSuccess with image response

### ISSUE THREAD

**Issue by erakis** [apidoc/apidoc#928]
# Describe the bug

Hi,

I have a route which returned an http image. Like this one

https://ui-avatars.com/api/?name=John+Doe

How should I describe the @apiSuccess. There is not a json response so 

 - I don't know the response type except by looking at the `content-type`.
 - I don't know the `field` name too as I'm receiving an image data as binary or base 64.

# Steps to reproduce

N/A

# Information

- Version of apidoc: 0.25.0
- Operating system (e.g. GNU+Linux/MacOS/Windows): Windows
- Browser (e.g. firefox, chrome): Chrome

**Comment by NicolasCARPi** [comment]
Maybe `@apiSuccess (200) {Binary} null base64-encoded png image` ?

**Comment by purell** [comment]
> `@apiSuccess (200) {Binary} null base64-encoded png image` ?

It makes sense. Thank you. 

It would have been cool to have an example similar to the documentation.
