### ISSUE TITLE
@apiBody Not Working

### ISSUE THREAD

**Issue by arejay73** [apidoc/apidoc#935]
# Bug Description
I tried to create a block that uses the @apiBody parameter.  I get the error:
```
{"message":"parser plugin 'apibody' not found in block: 0 in file: server/services/v1/auth/auth.js","level":"warn"}
```
# Steps to reproduce
```
/**
 * 
 * @api {post} /auth/register Register a new user
 * @apiName Register
 * @apiGroup USER
 * @apiVersion  1.0.0
 * 
 *  @apiBody {String} {"username": "TheUserName"}
 * /
```
# Information

- Version of apidoc: apidoc@0.26.0
- Operating system (e.g. GNU+Linux/MacOS/Windows): MacOS 11.2
- Browser (e.g. firefox, chrome): Safari

**Comment by NicolasCARPi** [comment]
That's because it's not merged in master/released yet.
