### ISSUE TITLE
Duplicated entries and contents when aloneDisplay is true

### ISSUE THREAD

**Issue by nianxy** [apidoc/apidoc#938]
# Describe the bug
I have a project with multiple version documents, the apidoc works well when `aloneDisplay` is false, but when I set `aloneDisplay` to `true`, the document page displays duplicate entries for each version of the API, and the contents of all versions are shown in one page. 

Here is the snapshot (Sorry for blurring some sensitive areas, but you can see the duplicate entries and contents obviously): 
![image](https://user-images.githubusercontent.com/26179440/107318788-84e4cf00-6ad8-11eb-9c49-60eb84c45793.png)

- Version of apidoc: 0.26.0
- Operating system (e.g. GNU+Linux/MacOS/Windows): Ubuntu 20
- Browser (e.g. firefox, chrome): Chrome

**Comment by NicolasCARPi** [comment]
Hello,

Thanks for reporting this bug.
