### ISSUE TITLE
Specify --private=false will not exclude private APIs

### ISSUE THREAD

**Issue by chw2054** [apidoc/apidoc#942]
# Describe the bug

Hi,

I follow the document, please see [@apiPrivate](https://apidocjs.com/#param-api-private)

The following command will not build the doc for public API:

```bash 
apidoc --private false
````

Please update the [doc](https://github.com/apidoc/apidocjs.com/blob/gh-pages/index.html#L1648):

```
Command line usage to include private APIs: --private [true]
```

# Information

- Version of apidoc: 0.26.0
- Operating system: Linux
- Browser: Chrome

**Comment by NicolasCARPi** [comment]
It is working fine now (in `dev` branch at least).

**Comment by jwerre** [comment]
I'm having this issue as well where using `--private false` is equivalent to `--private true`.  Perhaps you could do a little more type checking here:

https://github.com/apidoc/apidoc/blob/3d3025e7c96adf0d5926cfd7388dbbec5b900fbd/bin/apidoc#L116

**Comment by NicolasCARPi** [comment]
@jwerre care to propose a PR?

**Comment by jwerre** [comment]
I upgraded commander to v9 and unfortunately that didn't solve the issue. I don't think there is a great way to fix this other than create a pull request for commander.js or switch to something like [minimist](https://github.com/substack/minimist) where you have a bit more control.

**Comment by NicolasCARPi** [comment]
I'm surprised that commander.js with its 13 millions users cannot handle bool flags correctly. I would like to stick with commander.js, so if you can look into solving this while keeping the same lib it would be great. I currently don't have the bandwidth to look into it myself.

**Comment by jwerre** [comment]
> if you can look into solving this while keeping the same lib it would be great

ok, I'll see if I can get some clarification on this.

**Comment by jwerre** [comment]
https://github.com/tj/commander.js/issues/1759

**Comment by jwerre** [comment]
I got some feedback form the maintainer of commander.js and it seems to make sense. 

https://github.com/tj/commander.js/issues/1759#issuecomment-1163591506

Perhaps this isn't an issue worth addressing.

**Comment by nolimitdev** [comment]
Issue still alive. Adding two scripts with `--private true` and `--private false` causes identical result. So doc should be changed - notice that false should not be used just true.
