### ISSUE TITLE
how to change the output index file extension from html to other extension like gsp or php etc

### ISSUE THREAD

**Issue by mukeshsalaria01** [apidoc/apidoc#943]
# Feature request

When we are making the output of the current index.html file, it's generating an index.html file in the doc folder. I want to change the extension to other extensions like PHP or GSP. Is it possible to do?

If yes how I can do that.

thanks!

**Comment by NicolasCARPi** [comment]
The extension is .html because it's an html file. If you wish to change it just make a simple script that moves the output file to the desired extension.

**Comment by mukeshsalaria01** [comment]
@NicolasCARPi But do you mean by making a simple script.
Here is what I tried.
1. I tried to make index.html to index.gsp it didn't work.
2. I tried to rename the output file from index.html to index.gsp. It also didn't work.

Can you let me know if I'm missing anything?

**Comment by NicolasCARPi** [comment]
I mean this:

~~~bash
#!/usr/bin/env bash
apidoc -i src -o doc
mv doc/index.html doc/index.gsp
~~~

(what the hell is a .gsp??)

And what do you mean "it didn't work"? Renaming a file is not rocket science.

**Comment by mukeshsalaria01** [comment]
@NicolasCARPi That you suggested I have already tried. I thought there is something else from the configuration I have to do.
Thanks though.
