### ISSUE TITLE
Runtime error in single page template (Missing helper: "if_neq", Handlebars.js) in #dev branch

### ISSUE THREAD

**Issue by Ashlanfox** [apidoc/apidoc#944]
# Describe the bug
I ran the doc generation using --single argument, with apidoc 0.26.0 dev branch and apidoc-core 0.14.0.
When rendering the HTML page the console outputs an error `Missing helper: "if_neq"` and won't show more than the header content.

# Steps to reproduce
See above.

# Information
I fixed the issue by changing every `if_neq` to `unless`. It seems like Handlebars.js does not have the `if_neq`: https://handlebarsjs.com/guide/builtin-helpers.html#unless.

- Version of apidoc: 0.26.0 (dev branch)
- Operating system (e.g. GNU+Linux/MacOS/Windows): Windows
- Browser (e.g. firefox, chrome): Chrome

**Comment by Ashlanfox** [comment]
Also, I don't really know why the success article would be above the query/body article. This is confusing for the reader. I know this doesn't belong here but I felt like it didn't need a specific issue.

`{{subTemplate "article-param-block" params=article.success _hasType=_hasTypeInSuccessFields section="success"
{{subTemplate "article-query-block" params=article.query _hasType=_hasTypeInParameterFields section="query"}}
    {{subTemplate "article-body-block" params=article.body _hasType=_hasTypeInParameterFields section="body"}}`

**Comment by NicolasCARPi** [comment]
Hello, thanks for reporting this issue. Would you mind creating a PR?

**Comment by Ashlanfox** [comment]
> Hello, thanks for reporting this issue. Would you mind creating a PR?

Haven't done that before, excuse me if it is a bit bumpy: https://github.com/apidoc/apidoc/pull/945

**Comment by seyfer** [comment]
I still have this issue in the latest version with `if_neq `

**Comment by NicolasCARPi** [comment]
I just tried with a fresh git clone, it works fine. git clone, npm i, npm run build-example, all good.
