### ISSUE TITLE
Custom variables not working with Headers

### ISSUE THREAD

**Issue by neeleshguptagate6** [apidoc/apidoc#946]
# Describe the bug

We are trying to use custom variables with the header but it's not working. When we submit the request then payload and request header parameters goes blank. Please help how we can make requests with custom header variables.
Thanks in advance!

# Steps to reproduce
Pass custom variables with the header like apikey, sessionId etc.

# Information

- Version of apidoc: 0.26.0
- Operating system (e.g. GNU+Linux/MacOS/Windows): Linux & Windows
- Browser (e.g. firefox, chrome): Chrome & Firefox

**Comment by NicolasCARPi** [comment]
Please provide reproducible code.

**Comment by neeleshguptagate6** [comment]
@NicolasCARPi 

Here is the sample code that we are using to pass custom variables (like apikey, sessionId) on header params,

/**
* @api {post} /user/logout/ user logout
* @apiVersion 0.3.0
* @apiName postUserLogout
* @apiGroup User
* @apiPermission none
* @apiSampleRequest /user/logout
* @apiDescription Used to unset user sesstion
*
* @apiHeader (Auth) {String} Authorization Basic Access Authentication token.
* @apiHeader (Auth) {String} [Accept=application/json]
* **@apiHeader (Auth) {String} apikey**
* **@apiHeader (Auth) {String} sessionId**
*
* @apiParam {Number} _id Mandatory User unique id.
*
* @apiSuccess {String} status success.
* @apiSuccess {Number} code 200
*
*
*/

Please check and revert us ASAP because it's very critical for us.

Thanks in advance!

**Comment by NicolasCARPi** [comment]
If it was working in a previous version I would recommend sticking with that version. Or proposing a PR to fix the bug. I currently don't have the time nor will to fix it for you for free.

> Please check and revert us ASAP because it's very critical for us.

I think you misunderstood the licence of this free and open-source project: 

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.

@rottmann is currently working on a total rewrite of this software. We might be able to provide PRO Support in the future, but for now it is not the case.

**Comment by NicolasCARPi** [comment]
You can try the current `dev` branch: `npm i -g apidoc/apidoc#dev`
