### ISSUE TITLE
@apiSampleRequest off not working

### ISSUE THREAD

**Issue by mchampaneri** [apidoc/apidoc#947]
# Describe the bug
version: 0.22.2
Even after applying ```@apiSampleRequest off``` . It's putting sample request in docs.

# Information
- Operating system : MacOS 
![Screenshot 2021-03-02 at 4 45 29 PM](https://user-images.githubusercontent.com/13694774/109640655-c1a36380-7b76-11eb-829b-dca52a91c823.png)

**Comment by ebadilla10** [comment]
Same here, this is mi apidoc.json
{
  "name": "Backend APIs Tool",
  "version": "0.1.0",
  "description": "These are all the available backend APIs created for Tool",
  "url" : "http://something.net:8070/api/test"
}

So, based on documentation due to I don't have any "sampleUrl" in this doc, it shouldn't be showed.

**Comment by NicolasCARPi** [comment]
> version: 0.22.2

Please update to latest version.

**Comment by ebadilla10** [comment]
I have 0.26.0 and it's still not working as expected.

**Comment by Jarod-Xie** [comment]
I'm using 0.27.0 and it's not working either

**Comment by blairjanis** [comment]
Same here.  Latest version 0.27.0

**Comment by btav** [comment]
@blairjanis I am experiencing the exact same issue. I found a slightly less _**hacky**_ way to resolve it. By adding `"sampleUrl": null` inside the `apidoc.json` config file.

**Comment by bene-we** [comment]
I'm on apidoc version `0.27.1` right now. I had to set the `sampleUrl` property in `apidoc.json` to any value (doesn't matter if `true` or any other string) as mentioned by @SeoungJinKim:

```json
{
    "name": "API",
    "version": "0.0.1",
    "description": "API Documentation",
    "url" : "http://localhost:8080",
    "sampleUrl": "http://localhost:8080"
  }
```
Please note that I have to set `@apiSampleRequest off` to every route definition where the "sample request" section should not be visible.

**Comment by NicolasCARPi** [comment]
Fixed in dev branch.
