### ISSUE TITLE
change color of checkbox

### ISSUE THREAD

**Issue by paulovich10** [apidoc/apidoc#948]
# Feature request

I'm trying. to change de color of the checkbox checked but there's no way to do it. 

`      {{#if article.header}}
        {{#if article.header.fields}}
          <h3>{{__ "Headers"}}</h3>
          {{#each article.header.fields}}
            <h4><input type="checkbox" data-sample-request-header-group-id="sample-request-header-{{@index}}" name="{{../id}}-sample-request-header" value="{{@index}}" class="sample-request-header sample-request-switch" checked />{{__ @key}}</h4>
            <div class="{{../id}}-sample-request-header-fields envelop-label">
              {{#each this}}
              <div class="form-group">
                <label  class="col-md-3 control-label" for="sample-request-header-field-{{field}}">{{field}}</label>
                <div class="input-group">
                  <input type="text" placeholder="{{field}}" value="{{defaultValue}}" id="sample-request-header-field-{{field}}" class="form-control sample-request-header" data-sample-request-header-name="{{field}}" data-sample-request-header-group="sample-request-header-{{@../index}}">
                  <span class="input-group-addon">{{{type}}}</span>
                </div>
              </div>
              {{/each}}
            </div>
          {{/each}}
        {{/if}}
      {{/if}}`
I'm trying this but it's not working. I picked the color with google  color picker extension try to find it to find where is styling it, to change it but it doesn't exist. 

` .sample-request-header:checked  .enevelop-label .form-group .control-label::before {
    background: red !important;
    box-shadow:0 0 3px red ;
}
`

also this:

`input[type="checkbox"]:checked{
    background-color: #ff3d46 !important;
}`

but it won't work. Thanks for your help

**Comment by rottmann** [comment]
Not an apidoc-Problem, a CSS-Problem.
Background color of a checkbox can not be changed directly.
See: https://stackoverflow.com/questions/34388696/how-to-change-the-background-color-on-a-input-checkbox-with-css
