### ISSUE TITLE
Menu hide on mobile

### ISSUE THREAD

**Issue by Vincent-Projects** [apidoc/apidoc#949]
# Feature request

ApiDoc is a great way of creating docs easily but when i go through the doc on mobile ( IOS 14, Iphone 11 ) The menu with links takes ~70%. So it would have been great if there were a button to hide the menu on mobile

**Comment by NicolasCARPi** [comment]
With the changes I made in `merge` branch, the left menu is now responsive instead of having a fixed width, but this will need further improvements like having a burger menu for small screens. Work is ongoing, first upgrade bootstrap....
