### ISSUE TITLE
hide request form

### ISSUE THREAD

**Issue by cchetan1993** [apidoc/apidoc#954]
I am trying to hide the request from and parameters 
i am using @apiSampleRequest off but no success.

regards

**Comment by SeoungJinKim** [comment]
https://github.com/apidoc/apidoc/issues/947#issuecomment-810089461
here is my answer
I hope you solve the problem

**Comment by olignyf** [comment]
Is apidoc missing documentation on itself?

**Comment by SeoungJinKim** [comment]
I'm not sure. But, I solved the problem by analyzing the code myself.

> Is apidoc missing documentation on itself?

**Comment by NicolasCARPi** [comment]
Fixed now in dev branch.
