### ISSUE TITLE
When the api route length < 4, the sample request url is error.

### ISSUE THREAD

**Issue by wilon** [apidoc/apidoc#956]
# Describe the bug

When the api route length < 4, the sample request url is error.

# Steps to reproduce

```bash
git clone https://github.com/apidoc/apidoc.git
cd example
# edit example.js line 2 to:  * @api {get} /uu Read data of a User
apidoc -i . -o doc
# then brower ./doc/index.html
```
The sample request url is error.
![image](https://user-images.githubusercontent.com/7512755/114143155-5e130f80-9946-11eb-93fe-f1783d106599.png)

# Information

- Version of apidoc: latest
- Operating system (e.g. GNU+Linux/MacOS/Windows): win
- Browser (e.g. firefox, chrome): chrome

**Comment by NicolasCARPi** [comment]
I think you need to have a complete url in there.
