### ISSUE TITLE
RAW Json body for request

### ISSUE THREAD

**Issue by alanapplyby** [apidoc/apidoc#957]
The API which I am producing documentation for has a get token end-point. The requirement is to call the url with an email and password as a raw JSON in the header. In postman I set body -> raw:

```
{
    "email": "foo@bar.com",
    "password": "mypassword"
}
```

I am declaring this as:

* @apiHeader {String} Accept='application/json'
* @apiHeader {String} Content-Type='application/json'
* @apiParam {String} [auth]

In my generated docs, I am trying to make a request under: Send a Sample Request

Under parameters I have selected body/json as the parameter, and added the json email/password as above. Then when I make the request the user does not authenticate - same behaviour and end-point in postman works.

I guess that the body is not being sent in the correct format which should be raw.

- Version of apidoc:
apidoc-0.27.0
- Operating system (e.g. GNU+Linux/MacOS/Windows):
Win10
- Browser (e.g. firefox, chrome):
Chrome

**Comment by NicolasCARPi** [comment]
Did you inspect the sent request?

**Comment by alanapplyby** [comment]
I apologies this was an error on my part, I was using a GET instead of a POST hence the problem I reported. I'll close the ticekt.
