### ISSUE TITLE
@apiBody and @apiQuery are not rendering.

### ISSUE THREAD

**Issue by Abdelrhman-Hosny** [apidoc/apidoc#958]
## Bug Description

I am trying to write a Query and Body parameters for my apiDoc, however both @apiBody and @apiQuery don't show up in the `index.html` file when opened in the browser.

I ran apiDoc and generated the documentation, and the rest of the stuff works fine. only those two don't show up.

# Steps to reproduce

```
/**
 * 
 * @api {POST} /auth/signUp signUp
 * @apiGroup auth
 * @apiVersion  0.1.0
 * 
 * 
 * @apiQuery {Number} id Users unique ID.
 * 
 * @apiBody {Number} id Users unique ID.
 * 
 */
```
- Version of apidoc: 0.27.1
- Operating system : Ubuntu 20.04
- Browser : Brave, firefox

**Comment by Abdelrhman-Hosny** [comment]
There is a work around for this, you can write this instead

```
..
..
..
@apiParam (Query) {Number} id Users unique ID. // instead of @apiQuery ...

@apiParam (Body) {Number} id Users unique ID. // instead of @apiBody ...

```
This is not written on the page apidocjs.com unlike `@apiQuery {Number} id Users unique ID.` which is specified on the website. so, I'm not sure if this is the intended way to write these.

**Comment by anhkhoi** [comment]
Same issue with me. @apiBody is not working. Btw, thanks @Abdelrhman-Hosny for your work around.

**Comment by Rukeith** [comment]
This issue is duplicate with my issue #952

**Comment by SWheeler17** [comment]
The latest version is 0.28.1 according to npm (@Abdelrhman-Hosny you were on 0.27.1, when this issue was created). Please update apidoc and try again. If you are still having issues after updating, please let me know since the documentation generation seems to work for me.

**Comment by MiguelVis** [comment]
Hi all,

I'm facing the same issue, `@apiBody` params are now shown on the generated documentation.

I'm using the last apidoc version 0.29.0 and the default template.

One thing I don't understand is this line in the template file `index.html` (marked as bold):

```
{{subTemplate "article-param-block" params=article.body _hasType=**_hasTypeInSuccessFields** section="body"}}
```

But if I change it to `_hasTypeInParameterFields` nothing changes.

**Comment by MiguelVis** [comment]
Ok I have found the issue.

In the file `template/index.html` the line no. 183 has to be modified from:

```
{{subTemplate "article-param-block" params=article.body _hasType=_hasTypeInSuccessFields section="body"}}
```

to:

```
{{subTemplate "article-body-block" params=article.body _hasType=_hasTypeInParameterFields section="body"}}
```

I will do a PR asap.

PS: The template does nothing about `@apiBody` optional parameters. I'll try to solve this too.

**Comment by NicolasCARPi** [comment]
Yep, many bugs to solve, help is welcome ;)

**Comment by MiguelVis** [comment]
Hi all,

I think this issue is now solved and could be closed.
