### ISSUE TITLE
Getting "No files found" error

### ISSUE THREAD

**Issue by AldoErco** [apidoc/apidoc#959]
# Describe the bug
Tried to reinstall with
```
sudo npm uninstall -g apidoc
sudo npm install -g apidoc
```
I have in a single folder just 2 files:
* apidoc.json
* api_module_apionly.py (I removed all the code and left only the APIDOCs comments, the same result if I leave the python code in plase

From inside that folder, I run the statement:
`apidoc --input api_module_apionly.py --config apidoc.json --single`

I get the error
`{"Path":"<path to my folder>","level":"error","message":"No files found."}`

The same I get with all the CLI commands variants like
* using full file paths in `--input` and `--config` parameter
* not using `--single` parameter
* running the statement in a `sudo` command

# Steps to reproduce
* I attach files to reproduce
[files.zip](https://github.com/apidoc/apidoc/files/6409294/files.zip)

* Unzip all files in a folder
* Run `apidoc --input api_module_apionly.py --config apidoc.json --single`

# Information

- Version of apidoc:
{"message":"apidoc-generator name: apidoc","level":"verbose"}
{"message":"apidoc-generator version: 0.27.1","level":"verbose"}
{"message":"apidoc-core version: 0.15.0","level":"verbose"}
{"message":"apidoc-spec version: 0.3.0","level":"verbose"}

Running under Linux (inux ubuntu 5.8.0-49-generic #55~20.04.1-Ubuntu SMP Fri Mar 26 01:01:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux)

**Comment by NicolasCARPi** [comment]
Input must be a folder, not a file.

Also don't use sudo for npm install.
