### ISSUE TITLE
Command can't output any result in my folder. 

### ISSUE THREAD

**Issue by imvkmark** [apidoc/apidoc#964]
# I cant has expect result in my folder.

directory structure below here
```
directory : /Users/duoli/Documents/workbench/d.hub-cn/web
├── modules
│   ├── app
│   │   ├── src
│   │   │   ├── http
│   │   │   │   ├── request
│   │   │   │   │   ├── Controller.php
│   │   │   │   │   ├── api
│   │   │   │   │   │   └── web
│   │   │   │   │   │     ├── FinanceController.php
│   │   │   │   │   │     ├── StoreController.php
│   │   │   │   │   │     ├── UploadController.php
│   │   │   │   │   │     └── UserController.php
```

# The command and result is 
```
apidoc -i /Users/duoli/Documents/workbench/d.hub-cn/web  -o /Users/duoli/Documents/workbench/d.hub-cn/web/public/docs/web  -f "modules/.*/src/http/request/api.*/web/.*\.php$" -f "vendor/poppy/.*/src/Http/Request/Api.*/Web/.*\.php$"
{"Path":"/Users/duoli/Documents/workbench/d.hub-cn","level":"error","message":"No files found."}
```

# Information

Version of apidoc:

```
{"message":"apidoc-generator name: apidoc","level":"verbose"}
{"message":"apidoc-generator version: 0.27.1","level":"verbose"}
{"message":"apidoc-core version: 0.15.0","level":"verbose"}
{"message":"apidoc-spec version: 0.3.0","level":"verbose"}
```

- Operating system (e.g. GNU+Linux/MacOS/Windows): Mac OS 11.3.1
- Node version : 14.16.1 (Latest LTS)
- Browser (e.g. firefox, chrome):

**Comment by NicolasCARPi** [comment]
Did you try without the `-f` flag as a first step? Then add more filters little by little.

**Comment by imvkmark** [comment]
I copied specied files to other directory with same params can generate api files. 
![image](https://user-images.githubusercontent.com/150127/117966850-f726b300-b356-11eb-861f-78a952949847.png)
So I rename the origin file to other name. and re clone from git repo. it can works.
but the renamed directory still can't generate. 
it's so strange.
