### ISSUE TITLE
API version in the URL

### ISSUE THREAD

**Issue by andrejserafim** [apidoc/apidoc#965]
Similar issue: https://github.com/apidoc/apidoc/issues/392, but quite old and the example there doesn't work any more.

We would like like to put API versions in the URL - `GET /v1.0.0/foo`

What's the best way to reflect this in the apidoc document?

The hack I have atm: 

```
@api {get} /v:version/foo
@apiVersion 3.0.1
@apiSampleRequest /v3.0.1/foo
@apiParam (URL) {String} version=3.0.1 API Version
```

Note that if I hardcode the version in the `@api` I don't seem to get diffs as apidoc treats those as independent APIs, even in apiName and apiGroup are set to the same.

**Comment by NicolasCARPi** [comment]
I believe this is unsupported.
