### ISSUE TITLE
Invalid nesting in apiSuccess since Version 0.27.0

### ISSUE THREAD

**Issue by a-tonchev** [apidoc/apidoc#968]
Following code:

```
       ...
       * @apiSuccess (200) {Boolean} ok True when success
       * @apiSuccess (200) {Object} data Response data, that includes returned values
       * @apiSuccess (200) {Object} data.fileType File Type and Extension.
       * @apiSuccess (200) {String} data.fileType.ext Detected Image Extension from file type.
       * @apiSuccess (200) {String} data.fileType.mime Detected Image Mime Type from file type.
       * @apiSuccess (200) {Buffer} data.imageBuffer Image Buffer.
       * @apiSuccess (200) {String} data.extension Image Extension from URL.
       ...
```
      
      is causing invalid nesting:

![image](https://user-images.githubusercontent.com/54528540/118636739-b0650d00-b7dd-11eb-80d7-e8733cdd1938.png)

I just tried it with 0.26.0 - it works just fine.

**Comment by a-tonchev** [comment]
This is the correct one, that I get in 0.26.0:

![image](https://user-images.githubusercontent.com/54528540/118637352-5dd82080-b7de-11eb-8da7-8675b40315b4.png)

**Comment by wecomgroups** [comment]
git checkout bf56f2ff872850560423f6e0ea215c5905787db7

**Comment by wecomgroups** [comment]
Rolling back version to 26 can solve the problem.
git checkout bf56f2ff872850560423f6e0ea215c5905787db7

**Comment by NicolasCARPi** [comment]
Does it seem reasonable to all if I just remove the sorting function and let the order in which it was parsed be the one in the output doc? The code is not working anyway and seems hard to fix. Also, I _love_ removing code ^^

**Comment by singla96** [comment]
@NicolasCARPi this will be helpful. also ay new params can just b added at last of documentation, instead of comparing various versions.
