### ISSUE TITLE
Apidocs not loading on browser

### ISSUE THREAD

**Issue by Facj** [apidoc/apidoc#973]
# Describe the bug
I am able to generate the docs correctly but I cannot see them in the browser. Are they incorrectly router?

# Steps to reproduce
I have created a minimal example of my API server. Here, I include the basic files.
Structure:
![imagen](https://user-images.githubusercontent.com/5441615/122784555-db49f180-d2b2-11eb-8579-7f081afab94d.png)

index.js:
```
const routes = require('./routes');
const express = require('express')
var http = require('http')
const path = require("path");
const app = express();

var httpServer = http.createServer(app)
httpServer.listen(9443, () => {
  console.log('HTTPS running on http://localhost:9443')
})

// Load routes
routes(app)

//Publish API documentation
app.use("/", express.static(path.join(__dirname, "./apidoc/public")))
```

package.json:

```
{
  "name": "basic-api-example",
  "version": "1.0.0",
  "description": "",
  "main": "src/index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node src/index.js",
    "docs": "apidoc -i src/ -o apidoc/public/api/ -t apiDoc/templateDoc/ -v"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "apidoc": "^0.28.1",
    "express": "^4.17.1"
  }
}
```
apidoc.json:

```
{
  "name": "basic-api-example",
  "version": "0.0.0",
  "description": "Basic example for apidocs",
  "title": "basic-api-example",
  "url" : "/api",
  "forceLanguage": "en",
  "template" : {
    "withCompare" : false
  }
}
```

I am able to create the docs using `npm run docs`. 
I run the server with `npm run`. Then, I expected to find the docs on http://localhost:9443/api. However, what the browser shows is: `Cannot GET /api`.

# Information

- Version of apidoc: 0.28.1
- Operating system (e.g. GNU+Linux/MacOS/Windows): Windows 10
- Browser: Tested on Firefox and Chrome

**Comment by NicolasCARPi** [comment]
Can you open the index.html file manually with your browser? If yes then your issue is with your app and doesn't concern this project.

**Comment by Facj** [comment]
Yes, I can open the index.html file manually.
Ok, thanks for the insight.
