### ISSUE TITLE
Deeply nested apiParams not shown in HTML output

### ISSUE THREAD

**Issue by aheadware** [apidoc/apidoc#975]
# Description

Maybe I am doing something wrong - but it seems that deeply nested apiParams are not shown in the generated HTML.

**Example**

`* @apiParam {Object}   person`
`* @apiParam {String}   person[name]`
`* @apiParam {Number}   person[age]`
`* @apiParam {Object}   person[address]`
`* @apiParam {String}   person[address[street]]`
`* @apiParam {String}   person[address[city]]`

**Result**

![apijsdoc-issue](https://user-images.githubusercontent.com/26056342/123963562-e091f500-d9b2-11eb-975f-5c0465b3d6b0.PNG)

**Expected**

address.street and address.city is listed below person.address object.

**Comment by NicolasCARPi** [comment]
Hello,

It works if you use:

~~~javascript
* @apiParam {Object} person
* @apiParam {String} person.name
* @apiParam {Number} person.age
* @apiParam {Object} person.address
* @apiParam {String} person.address.street
* @apiParam {String} person.address.city
~~~

**Comment by aheadware** [comment]
Hello, 

Thanks for your reply. 

I can confirm. This works!
