### ISSUE TITLE
Strange HTML output with properties of array objects

### ISSUE THREAD

**Issue by aheadware** [apidoc/apidoc#976]
# Description

Invalid HTML output when defining Object-Arrays properties as apiParams. 
Tried with 0.26, 0.27 and 0.28.

# Example

`* @apiParam {Object} person`
`* @apiParam {String} person.name`
`* @apiParam {Number} person.age`
`* @apiParam {Object[]} addresses`
`* @apiParam {String} addresses.street`
`* @apiParam {String} addresses.city`

# Result

![apijsdoc-issue2](https://user-images.githubusercontent.com/26056342/123996220-6459da80-d9cf-11eb-9121-4f3cbd06035f.PNG)

# Expected

The `street `and `city `property is listed under "`addresses`" property.

**Comment by NicolasCARPi** [comment]
You need to have your person be an `Object[]`.

**Comment by aheadware** [comment]
Thanks again for the quick reply. I can confirm that the result look better now.

However, now the parameter lists accepts an array of person objects and an array of address objects.

Why is a possible structure like

`{ "person" : { "name" : "", "age": 0 }, "addresses" : [ { "street" : "street one", "city" : "city one" } ] }`

not possible?

**Comment by NicolasCARPi** [comment]
No, AFAIK.
