### ISSUE TITLE
Forever Loading screen!!!

### ISSUE THREAD

**Issue by prashant93** [apidoc/apidoc#981]
I am seeing a permanent 'loading' symbol when requesting the apidoc index.html.
Using node version : 12.22.1 
apidoc version :   "apidoc": "^0.28.1",
Previously it was working but suddenly stopped.
using local url : file:///D:/Project/Git/testapi/apidoc/index.html , it is working fine
but on serving it is failing with forever loading screen.

 "apidoc": {
        "name": "Test API",
        "title": "Test API",
        "description": "TheTest API",
        "version": "1.0.0",
    },

![APidoc-loading](https://user-images.githubusercontent.com/4151470/126289000-4e62746b-bca2-478e-811c-9f80c21c800b.png)

**Comment by NicolasCARPi** [comment]
As the error states, you have a restrictive CSP.

**Comment by prashant93** [comment]
Yes but it is while generating apidoc and handlebar
