### ISSUE TITLE
Nested Boolean Params are not rendering properly and default booleans are not working

### ISSUE THREAD

**Issue by yashwanth-Thota** [apidoc/apidoc#982]
I have a use case where, I need to send set of flags in a JSON body as below
```
{
flags:{
"flag1":false,
"flag2":true
}
}
```

And in apiDoc definition I gave the body field as below
```
* @apiBody {Boolean} flags[flag1]    Optional flag1.
 * @apiBody {Boolean} flags[flag2]   Optional flag2.
```

But out request body rendered in doc is as below
```
{
    "flags[flag1": null,
    "flags[flag2": null,
}
```
I am on tight deadlines. Fastest workaround or solutions are appreciated.
Thanks in advance.

**Comment by NicolasCARPi** [comment]
I can confirm the bug.

**Comment by NicolasCARPi** [comment]
You can try the current `dev` branch. See also #999 for breaking changes on how to define your json params. See also example if needed (the Create user example).
