### ISSUE TITLE
"Send a Sample Request" now appears at the bottom of each endpoint and `@apiSampleRequest off` doesn't work

### ISSUE THREAD

**Issue by funandgame** [apidoc/apidoc#984]
# Describe the bug

I started having the sample request forms appearing in my apidoc output, now there is a "Send a Sample Request" at the bottom of each endpoint and `@apiSampleRequest off` doesn't seem to work. Also there seems to be no way to print apidoc version: `apidoc -v` would be nice or the `apidoc --help` to be printing the version number?

Currently I need to use this to check the globally installed apidoc version

```
$ npm list -g | grep apidoc
+-- apidoc@0.28.1
| +-- apidoc-core@0.15.0
```

# Workaround 

I have to use the workaround/hack with these two things at once:
`"sampleUrl": true` in apidoc.json
`@apiSampleRequest off` on each endpoint

# Information

- Version of apidoc: 0.28.1
- Operating system (e.g. GNU+Linux/MacOS/Windows): Linux

**Comment by NicolasCARPi** [comment]
IIRC you need to use `sampleUrl: null` until this bug is fixed.

**Comment by NicolasCARPi** [comment]
You can try the current `dev` branch.

**Comment by cnwangjie** [comment]
Same in 0.29

And @apiBody disappeared also.

**Comment by NicolasCARPi** [comment]
@cnwangjie please try the code from master of dev branch.
