### ISSUE TITLE
Object type of success always show in first

### ISSUE THREAD

**Issue by jobinli** [apidoc/apidoc#995]
# Describe the bug
if the success param has an object type。it always show in the first of param list.

# Steps to reproduce
for example, i defined an api like 
```php
    /**
     * 上传文件到临时目录
     * @api {post} /api/upload 上传文件到临时目录
     * @apiName upload
     * @apiParam {String} token 登录后获取的token
     * @apiParam {Object} file 上传的文件
     * @apiParam {Array} files 上传的文件数组，优先级比file高
     * @apiParam {String} [upload_type] 上传类型，默认img
     * @apiSuccess {Number} code 响应码，200
     * @apiSuccess {String} msg 响应信息
     * @apiSuccess {Object} data 响应数据
     * @apiSuccess {Object} data.file 上传后的文件描述对象
     * @apiSuccess {String} data.file.path 文件路径，用于表单提交
     * @apiSuccess {String} data.file.url 文件地址，用于预览
     * @apiSuccess {Object} data.files 上传后的文件描述对象
     * @apiSuccess {String} data.files.name 文件名称
     * @apiSuccess {String} data.files.path 文件路径，用于表单提交
     * @apiSuccess {String} data.files.url 文件地址，用于预览
     * @apiSuccess {String} data.files.error 错误信息
     */
```
it **always** show the first of **Object** type in first of the success param
![image](https://user-images.githubusercontent.com/59111601/132305047-3c45bfd8-efae-4a51-8039-4abfcc67ec9c.png)

# Information

- Version of apidoc: 0.29.0
- Operating system (e.g. GNU+Linux/MacOS/Windows): Ubantu18.04(wsl2)
- Browser (e.g. firefox, chrome): edge

**Comment by jobinli** [comment]
i tried some version of apidoc, found this happening since **0.24.0**

**Comment by NicolasCARPi** [comment]
Hello,

I'm currently in the process of basically rewriting this entire project. Can you try with the version from the `master` branch please?

**Comment by jobinli** [comment]
Hello, i try to clone the project and run by docker. This problem still happening.

**Comment by NicolasCARPi** [comment]
That's because the Docker image is taking the project from npm. Use directly `bin/apidoc` after `npm i` in the repo.

**Comment by jobinli** [comment]
Ok, it work well.

![image](https://user-images.githubusercontent.com/59111601/132329616-a7f29b1c-87cc-46d6-8a16-d5873b138823.png)

**Comment by NicolasCARPi** [comment]
Great!
