### ISSUE TITLE
{"message":"parser plugin 'apibody' not found in block: 2 in file: app/routers.js","level":"warn"}

### ISSUE THREAD

**Issue by DungVA1** [apidoc/apidoc#996]
# Information

- Version of apidoc: 0.23.0
- Operating system (e.g. GNU+Linux/MacOS/Windows): MacOS 11.5.2
- NodeJS version: 14.17.3

When I include @apiBody {Number} age
and run script to generate api document. It return an error: 
{"message":"parser plugin 'apibody' not found in block: 2 in file: app/routers.js","level":"warn"}

**Comment by NicolasCARPi** [comment]
Hello, can you try the latest version from `master` branch please? Or at least 0.29.0.
