### ISSUE TITLE
Field sorting order error when using multiple apiUse

### ISSUE THREAD

**Issue by swlws** [apidoc/apidoc#998]
# Describe the bug
when use two define code, the result order not right

the definde code:
/**
 * @apiDefine HttpResponse
 *
 * @apiSuccess {Number} r0 code
 * @apiSuccess {String} r1 description
 */

/**
 * @apiDefine Row
 *
 * @apiSuccess {Object} res 
 * @apiSuccess {Name} res.name 
 */

And use them:
/**
 * @apiUse HttpResponse
 * @apiUse Row
 */

# Information

- Version of apidoc: 0.29.0
- Operating system (e.g. GNU+Linux/MacOS/Windows): MacOS
- Browser (e.g. firefox, chrome): chrome

**Comment by NicolasCARPi** [comment]
Hello, I'm currently in the process of rewriting the whole project. Check back again in a few days once my branch is merged. A lot of things changed. And this kind of bug will hopfully be fixed. Check also with the current master version.

**Comment by NicolasCARPi** [comment]
You can try the current `dev` branch.
